### ISSUE TITLE
is it possible to set font color of just some text of  cell insted of the total cell?

### ISSUE THREAD

**Issue by sytan** [360EntSecGroup-Skylar/excelize#100]

**Comment by xuri** [comment]
I close this and merge it into the issue #127 is still discussing this problem.

**Comment by xuri** [comment]
Hi @sytan, sorry for my late reply. I have added rich text support for this lib, now you set cell with rich text by the [`SetCellRichText`](https://github.com/360EntSecGroup-Skylar/excelize/blob/66d0272f6af59b5f0c97a304379a795420a43e8b/cell.go#L460) function.
