### ISSUE TITLE
GetCellValue doesn't work correctly if the sheet name is not the default

### ISSUE THREAD

**Issue by nywleswoey** [360EntSecGroup-Skylar/excelize#102]
It seems like this method is not able to retrieve the value of a cell if the sheet name has been changed.
e.g xlsx.GetCellValue("Sheet1", "A1") will work while xlsx.GetCellValue("Config", "A1") doesn't.

**Comment by xuri** [comment]
Please reference issue #25, #51, #101 and [godoc](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.GetCellValue). Use `sheet`+index instead of sheet name (`Config`).

**Comment by nywleswoey** [comment]
Ok. Using the sheet+index works.
