### ISSUE TITLE
very slow when write 10000 rows with cells have hyperlink and style.

### ISSUE THREAD

**Issue by FU100** [360EntSecGroup-Skylar/excelize#106]
xlsx := excelize.NewFile()

	xlsx.SetColWidth("Sheet1", "A", "A", 15)

	for i := 0; i < 10000; i++ {
		var msec1 = time.Now().UnixNano() / 1000 / 1000

		rowIdx := i + 2
		xlsx.SetRowHeight("Sheet1", rowIdx, 15)
		rowNum := strconv.FormatInt(int64(rowIdx), 10)

		xlsx.SetCellValue("Sheet1", "M"+rowNum, "link1")
		xlsx.SetCellHyperLink("Sheet1", "M"+rowNum, "./data/201708151534444.jpg", "External")
		xlsx.SetCellValue("Sheet1", "N"+rowNum, "link2")
		xlsx.SetCellHyperLink("Sheet1", "N"+rowNum, "./data/201708151534445.jpg", "External")

		style, _ := xlsx.NewStyle(`{"font":{"bold":true,"italic":true,"family":"Berlin Sans FB Demi","size":10,"color":"blue","underline":"single"}}`)
		xlsx.SetCellStyle("Sheet1", "M"+rowNum, "M"+rowNum, style)
		xlsx.SetCellStyle("Sheet1", "N"+rowNum, "N"+rowNum, style)

		var msec2 = time.Now().UnixNano() / 1000 / 1000

		glog.Infoln("row = ", rowIdx, ", msecs = ", msec2 - msec1)
	}

Output

I0815 10:13:31.513288    2819 excelfile.go:35] row =  2 , msecs =  1ms
...
I0815 10:14:14.555693    2819 excelfile.go:35] row =  1000 , msecs =  84ms
...
I0815 10:16:21.934837    2819 excelfile.go:35] row =  2000 , msecs =  181ms
...
I0815 10:19:48.245594    2819 excelfile.go:35] row =  3000 , msecs =  252ms
...

**Comment by xuri** [comment]
Thanks for your issue. Reference #60 and #105,  if the number of cells is large and all styles of the cell are same, we can set style with range in a batch instead of set the cell style one by one.

**Comment by xuri** [comment]
Relationship XML files that storage hyperlink can be optimized by reducing serialization and deserialization times to improve performance.

**Comment by cescoferraro** [comment]
@FU100  Changing my codebase like the below snippet really tuned my endpoint performance
```go
style, _ := xlsx.NewStyle(`{"font":{"bold":true,"italic":true,"family":"Berlin Sans FB Demi","size":10,"color":"blue","underline":"single"}}`)
xlsx.SetCellStyle("Sheet1", "M1", "M10000", style)
xlsx.SetCellStyle("Sheet1", "N1", "N10000", style)
for i := 0; i < 10000; i++ {
	var msec1 = time.Now().UnixNano() / 1000 / 1000
	rowIdx := i + 2
	xlsx.SetRowHeight("Sheet1", rowIdx, 15)
    xlsx.SetCellHyperLink("Sheet1", "M"+rowNumber, "./data/201708151534444.jpg", "External")
    xlsx.SetCellHyperLink("Sheet1", "N"+ rowNumber, "./data/201708151534445.jpg", "External")
	rowNum := strconv.FormatInt(int64(rowIdx), 10)
	xlsx.SetCellValue("Sheet1", "M"+rowNum, "link1")
	xlsx.SetCellValue("Sheet1", "N"+rowNum, "link2")
	var msec2 = time.Now().UnixNano() / 1000 / 1000
	glog.Infoln("row = ", rowIdx, ", msecs = ", msec2 - msec1)
}
```

**Comment by jorgeb12** [comment]
Is there any other solution? Seems like SetCellHyperLink is very slow in a loop of 10k. It takes between 1 and 2 minutes. Without that function it only takes 10 seconds.

**Comment by xuri** [comment]
I have optimized the performance of add hyperlink, adding 10000 comments takes less than 1 second now.
