### ISSUE TITLE
How to upload excel file to database by read header column name

### ISSUE THREAD

**Issue by baskara8** [360EntSecGroup-Skylar/excelize#110]
How to upload excel file to database by read header column name/first row as index

**Comment by baskara8** [comment]
Now, my problem is when I import data form excel sheet to the database in particular format. Like,

Table name:-Mytable

id | name | surname | email | date |

and the excel file I am using to import have a same format. But a format can change Like,

id | surname | name | date | email |

how can I map the columns from excel file to the database table so that correct data should enter into the data table.

**Comment by xuri** [comment]
Thanks for you issue. If the column name is fixed, just the order is not the same as in the database, you can specify the column coordinates. This library doesn't provide the function to change the result set currently.

**Comment by baskara8** [comment]
Yes column name is same with database, how to specify column coordinates with column name not using number?

**Comment by xuri** [comment]
I don't quite understand why cant use the alphabet to determine the column coordinates?

**Comment by baskara8** [comment]
So is it possible to upload 
`for _, sheet := range xlFile.Sheets {
    	for a, _  := range sheet.Rows {
    	if a>0{
var profile_refid 		      	= sheet.Cell(a,0).Value -> sheet.Cell(a,profile_refid).Value
var profile_extid           	       = sheet.Cell(a,1).Value -> sheet.Cell(a,profile_extid).Value
var profile_salutation             = sheet.Cell(a,2).Value -> sheet.Cell(a,profile_salutation).Value
var profile_name      	      = sheet.Cell(a,3).Value -> sheet.Cell(a,profile_name).Value
}
}
}`
because my column name excel below
![image](https://user-images.githubusercontent.com/1335828/29769292-fca85ba8-8c13-11e7-87d2-9af7103f707c.png)

**Comment by xuri** [comment]
Do you mean's that insert rows into database? If so, this lib can help you read from Excel only, the other work is your biz logic and that doesn't fall within the scope of this lib. You can prepare generate a SQL from cell value like this: 

```
var values string 
for idx, row := range rows {
    // Skip table header
    if i == 0 {
        continue 
    }
    // For example if the column order of database tabe is
    // profile_refid, profile_salutation, profile_extid, profile_name: 
    values += fmt.Sprintf("(%s, %s, %s, %s), ", row[0], row[2], row[1], row[3])
}
sql := fmt.Sprintf("INSERT INTO your_tabe VALUES %s ;", strings.TrimSuffix(values, ","))
// ...
```

**Comment by baskara8** [comment]
But field in my table like this
profile_salutation,profile_name,profile_refid,profile_extid, so not equal position with excel column

**Comment by xuri** [comment]
Adjust the order of the binding parameters like this:
```
values += fmt.Sprintf("(%s, %s, %s, %s), ", row[2], row[3], row[0], row[1])
```
or specify the order of the fields to be consistent with the table:
```
INSERT INTO your_tabe (profile_refid, profile_extid, profile_salutation, profile_name) VALUES ...
```

**Comment by baskara8** [comment]
Adjust could be automatically? identification with header table name?
Like this ->
` row[profile_refid], row[profile_extid], row[profile_salutation], row[profile_name]`

**Comment by xuri** [comment]
No, you need to handle it by yourself.

**Comment by baskara8** [comment]
Something like this?
http://www.c-sharpcorner.com/UploadFile/0c1bb2/inserting-excel-file-records-into-sql-server-database-using/

**Comment by xuri** [comment]
I have already described methods in the above, of course, you can handle it in another way by your own requirement.

**Comment by baskara8** [comment]
Yes xuri thank you, I have solved it :)
