### ISSUE TITLE
The same code can run in golang 1.8, but will crash in 1.9

### ISSUE THREAD

**Issue by Delveshal** [360EntSecGroup-Skylar/excelize#111]

**Comment by xuri** [comment]
Thanks for your issue. I have tested this lib on go1.9 darwin/amd64 and it works well. Could you provide more details?

**Comment by Delveshal** [comment]
2017/08/30 19:08:38 http: panic serving 127.0.0.1:49600: runtime error: index out of range
goroutine 16 [running]:
net/http.(*conn).serve.func1(0xc0421da280)
	D:/work/golang19/src/net/http/server.go:1697 +0xd7
panic(0x8ed7e0, 0xc0c390)
	D:/work/golang19/src/runtime/panic.go:491 +0x291
github.com/xuri/excelize.(*File).GetCellValue(0xc04238d320, 0x97b8f7, 0x6, 0xc042371008, 0x3, 0xf, 0xa3)
	D:/work/everything/goLang/package/src/github.com/xuri/excelize/cell.go:104 +0x4cd

**Comment by recallhyx** [comment]
@xuri 
I have the same problem when I use the function `GetCellValue()` ,it works when the cell value is number,but it can't work when the cell value is English or Chinese.
My go version is 1.9 too, the same code can work well at version 1.8

**Comment by recallhyx** [comment]
Thanks,
We have found the bug of go 1.9 because the font size we set is 10.5 but when we set it to 11 it works,
the `xml.Unmarshal([]byte(f.readXML("xl/sharedStrings.xml")), &sharedStrings)` should return err and check,and the err is `strconv.ParseInt: parsing "10.5": invalid syntax`

**Comment by xuri** [comment]
@recallhyx Please provide file attachments if you can.

**Comment by recallhyx** [comment]
@xuri Thanks,
the file is here:
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1269103/test.xlsx)
and the test file is:
`import (
	"testing"
	"fmt"
	"github.com/xuri/excelize"
)

func TestBug(t *testing.T){
	xlsx, err := excelize.OpenFile( "./test.xlsx")
	if err != nil {
		t.Error(err)
	}
	fmt.Println(xlsx.GetCellValue("sheet1", "A4"))
}`

**Comment by xuri** [comment]
@Delveshal, @recallhyx I have fixed this issue, please upgrade lib to the last version.
