### ISSUE TITLE
custom sheet name causes excel content blank

### ISSUE THREAD

**Issue by doggytty** [360EntSecGroup-Skylar/excelize#116]
Hi! 
When I changed the sheet name from ”sheet2“ to ”T1“ in the sample code, I found that there was no data in the generated excel, also I could not get the data using ”T1“. 
Look at the source code, in the sheet.go file setContentTypes method, the xml name has been fixed to sheet+index. So I using sheet+index when set cell value, but when I want to obtain sheetIndex, I must use "T1".
This is too inconvenient, Is there any  way to solve this question?

Thx

**Comment by xuri** [comment]
We can use the `GetSheetMap()` function to get all sheets index and name map and use "Sheet" + index to set the cell value currently. Please reference issue #25, #43, #47, #51, #89, #101 and [godoc](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.GetCellValue).

**Comment by doggytty** [comment]
o,that's very good, thank you, sir!
