### ISSUE TITLE
float64's that are NaN cause corrupt .xlsm file

### ISSUE THREAD

**Issue by sanoanalytics** [360EntSecGroup-Skylar/excelize#119]
I stumbled upon a bug. If you pass a float64 to SetCellValue() and it is NaN, it causes a corrupt .xlsm file. I simply used math.IsNaN() to check prior to SetCellValue() and that the solved problem.

**Comment by xuri** [comment]
Thanks for your issue. I have tested on xlsx and it works well. This lib not been tested with xlsm file currently.
