### ISSUE TITLE
Example doesn't work in Go 1.9

### ISSUE THREAD

**Issue by crosslogic** [360EntSecGroup-Skylar/excelize#120]
So, I've tried this:

```
func ExportarExcel(path string) error {
	file := excelize.NewFile()
	detalle := "Detalle"
	file.NewSheet(2, detalle)
	file.SetCellValue(detalle, "A1", "ID")
	file.SetActiveSheet(2)
	err := file.SaveAs(path)
	if err != nil {
		log.Fatal(err)
	}

	return nil
}
```

I get a file with the sheet created but has nothing in A1 cell. None error is returned. 

[salida.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1296206/salida.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue by use worksheet name instead of "sheet" + index, related issue #25, #43, #47, #51, #89, #101, #116 and #120. Note that the params of function `NewSheet()` also has been changed, please adjust your code like this:

```
func ExportarExcel(path string) error {
    file := excelize.NewFile()
    detalle := "Detalle"
    index := file.NewSheet(detalle)
    file.SetCellValue(detalle, "A1", "ID")
    file.SetActiveSheet(index)
    err := file.SaveAs(path)
    if err != nil {
        log.Fatal(err)
    }
    return nil
}
```

**Comment by zzc-tongji** [comment]
Oh! 
You change the API!
That's why my program doesn't work correctly!
