### ISSUE TITLE
excel打开错误

### ISSUE THREAD

**Issue by sxr5** [360EntSecGroup-Skylar/excelize#121]
英语不好。。见谅
版本1.7.3，代码用的readme实例。excel为2010
创建的excel打开报错，excel无法打开文件，因为文件格式或文件扩展名无效。请确定文件未损坏，并且文件扩展名与文件的格式匹配

**Comment by xuri** [comment]
Thanks for your issue. This library needs Go version 1.8 or later after fixed issue #32 for collecting XML all attributes. Relate issue #35, #39 and #42.

请升级到 Go 1.8 或更新版本，相关 issue 参考 #35, #39 and #42.
