### ISSUE TITLE
日期处理问题

### ISSUE THREAD

**Issue by tuyz** [360EntSecGroup-Skylar/excelize#123]
我导入的excel的日期为  2012/7/4  09:06:24 ，但是读取出啦的却是 7/4/12 09:06，格式变了，秒也没了

**Comment by xuri** [comment]
Thanks for your issue, the results consistent with the Excel application. If you wanna to read it as is, please set value as string data type.

![demo](https://user-images.githubusercontent.com/2809468/30686415-c9810308-9eea-11e7-9a37-2bc188d296fe.gif)
