### ISSUE TITLE
这个类库性能怎么样 (Working performance)

### ISSUE THREAD

**Issue by suliang** [360EntSecGroup-Skylar/excelize#124]
PHPEXCEL因为有内存泄漏的原因,所以我们准备换库
这个go语言开发的类库,  有做过压测吗
生成1W个xlsx 需要大概多久? 另外,不会发生内存泄漏吧

**Comment by xr081221097** [comment]
1. 个人使用的情况。如果对性能有极其严格要求，建议不要使用。
2. 暂时没有发生内存泄露情况。
3. 这个库的特点是对excel的一些功能上的支持比其他库要丰富的多
4. 个人认为，如果你的要求很严格，就是java的poi，这个应该是公认的各方面经得住考验的库。

**Comment by xuri** [comment]
The benchmark report of the current version of this library is shown on the [wiki page](https://github.com/360EntSecGroup-Skylar/excelize/wiki).
