### ISSUE TITLE
File.Reader (for http.ServeContent Support)

### ISSUE THREAD

**Issue by stverhae** [360EntSecGroup-Skylar/excelize#127]
Webservers which need to generate and serve excel files on-the-fly using the std golang http ServeContent now need to use an extra buffer to serve an excel file from memory.

The File.Write function accepts a writer, but often we want a reader. In the case of http.ServeContent we need a ReaderSeeker (needs to know total size etc), so you can't use an io.Pipe to connect an excelize writer to a reader (it does not support seeking).

SInce the File.Write function already makes use of an intermediate buffer, providing a function which returns a ReaderSeeker is easy, and could benefit many uses.

**Comment by xuri** [comment]
The execlize now support to get bytes.Buffer from the saved file by [`WriteToBuffer()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.WriteToBuffer), and we can get `io.Reader` like this:

```go
buf, _ := xlsx.WriteToBuffer()
strings.NewReader(buf.String())
```

another example for using with `http.ServeContent` support:

```go
package main

import (
	"net/http"
	"strings"
	"time"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":3000", nil)
}

func handler(w http.ResponseWriter, r *http.Request) {
	xlsx := excelize.NewFile()
	// Create a new sheet.
	index := xlsx.NewSheet("Sheet2")
	// Set value of a cell.
	xlsx.SetCellValue("Sheet2", "A2", "Hello world.")
	xlsx.SetCellValue("Sheet1", "B2", 100)
	// Set active sheet of the workbook.
	xlsx.SetActiveSheet(index)
	buf, _ := xlsx.WriteToBuffer()
	http.ServeContent(w, r, "test.xlsx", time.Time{}, strings.NewReader(buf.String()))
}
```
