### ISSUE TITLE
Example with different func than main

### ISSUE THREAD

**Issue by marcelloh** [360EntSecGroup-Skylar/excelize#128]
I tried searching the docs and the github sources, but I didn't find an example with more separation of functionality.

So I try to keep my main clean, and I have this:

> 
	// main snippet
	var fileName = "myfile.xlsx"
	xlsx, err := excelize.OpenFile(fileName)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	checkSheetName(xlsx, 1, "MySheetname")

and in the same file:

> 
	func checkSheetName(xlsx *File, sheetNr int, sheetName string) {
		xlsx.SetActiveSheet(1)
		sheetName := xlsx.GetSheetName(1)
		fmt.Println("Sheetname: " + sheetName)
	}

but somehow, it doesn't recognize the *File part. Can you give me (and the rest of us) a hint in how to use this, because I don't want to write one big main routine :-(

**Comment by xuri** [comment]
The parameter type of `xlsx` in the function `checkSheetName` should be `*excelize.File`, and you can also import a custom wrapped package.

**Comment by marcelloh** [comment]
Nice, thanks. Code is much more readable now
