### ISSUE TITLE
mixed values in string fields prefixes the field with a single quote

### ISSUE THREAD

**Issue by murum** [360EntSecGroup-Skylar/excelize#131]
Hi.
I'm trying to write an excel file as this:
```
xlsx.SetCellValue("Sheet1", fmt.Sprintf("M%d", i), 12345)
xlsx.SetCellValue("Sheet1", fmt.Sprintf("N%d", i), "1234N")
xlsx.SetCellValue("Sheet1", fmt.Sprintf("O%d", i), "N1234")
xlsx.SetCellValue("Sheet1", fmt.Sprintf("P%d", i), "312312")
xlsx.SetCellValue("Sheet1", fmt.Sprintf("Q%d", i), "1Christoffer")
```
When we do create CellValues as this we're getting an hidden Single Quote in the cell P because what we think is that we do send only numbers as an string. This field is taken from the Database and in somecases there are only numbers and in other cases there are mixed content with letters and numbers.

We do also have the same issue when using dates such as "2017-10-01" then we do get a hidden single quote.

Any ideas?

**Comment by xuri** [comment]
I have tested this lib on go1.9 darwin/amd64 and it works well. Could you provide more details or file attachments?

**Comment by murum** [comment]
@xuri We run this on 1.8.3 where we do see this issue. I'll try in 1.9

**Comment by xuri** [comment]
I just tested go version go1.8.3 windows/amd64 and it also works well.
