### ISSUE TITLE
Parsing for the "alt return " character. ?

### ISSUE THREAD

**Issue by joeblew99** [360EntSecGroup-Skylar/excelize#133]
I have this in a cell:

"
We need this to store valuable building materials, so do this first.
Demolish internal rear wall 
and check depth of garage. Hopefully is deep enough and door openings are wide enough.
Remove middle wall
Laminate existing main roof timbers
Demolish wall
"

This is written using the ALT return to make a carriage return within the cell.

Anyone know how to parse this ?

**Comment by xuri** [comment]
Reference issue #69, this lib not support set multiline texts for a cell currently.

**Comment by joeblew99** [comment]
@xuri 

I got it working myself:

````
if cellValue != "" {

				// Split on carriage return.
				cellSplitArray := strings.Split(cellValue, "\n")
				cellSplitNewArray := cellSplitArray

				// Loop
				for i := range cellSplitArray {
					//log.Print(fmt.Sprintf("split index (%v) Value %s ", i, cellSplitArray[i]))

					//newValue := fmt.Sprintf("%s_%s", cellSplitArray[i], "_changed")

					newValue, err := lang.Translate(cellSplitArray[i], langID)
					if err != nil {
						return err
					}

					cellSplitNewArray[i] = newValue

				}

				// rejoin array
				newValue := strings.Join(cellSplitNewArray, "\n")

				s.SetCellValue(sheetName, cellAxis, newValue)

````
