### ISSUE TITLE
How to copy a sheet to a new Excel File?

### ISSUE THREAD

**Issue by shawnye** [360EntSecGroup-Skylar/excelize#134]
I want to split one excel file into several excel files by sheet, each new file contains one sheet from original file.

I found api `func (f *File) CopySheet(from, to int) error` ,but just inside one excel file. is there any function that I can  copy a sheet to a new Excel File?

My ugly workaround: using `SaveAs()` function to make new file and reopen it and delete other sheets, and this method cause `unreadable contents` error when opening the created file.( As `DeleteSheet()` said This function will be invalid when only the one worksheet is left.  Maybe I have to create two dummy sheets)

Any suggestion?
Thank you!

**Comment by xuri** [comment]
Please reference issue #33, #41 and #99.
