### ISSUE TITLE
Adding Pie3D Chart in a Sheet with white-spaced name

### ISSUE THREAD

**Issue by vahdet** [360EntSecGroup-Skylar/excelize#138]
I am trying to generate a 3D pie chart with the code below. The xlsx file is generated, however when I try to open it via MS Office Excel 2013, it prompts an error like:

> Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
> Removed Part: Drawing shape.

But when I change the `xlsx.AddChart("Sheet 2"..)` line to `xlsx.AddChart("Sheet2"..)`, and run again; the chart is added without any problem. 
The weird thing is, I remove the space of sheet name only in `AddChart` arguments, I leave all the other _Sheet 2_ lines exactly the same (like `index  := xlsx.NewSheet("Sheet 2")` i.e. still with a space in between).

    chartedOutputPath := `path\\to\\file.xlsx`   
    categories := map[string]string{"A2": "IT", "A3": "Other", "A4": "External", "A5": "Business", "A6": "Client", "A7": "Front", "A8": "Common"}
    values := map[string]int{"B2": 205, "B3": 29, "B4": 36, "B5": 556, "B6": 71, "B7": 17, "B8": 94}
    xlsx := excelize.NewFile()
    
    index  := xlsx.NewSheet("Sheet 2")
    
    for k, v := range categories {
    	xlsx.SetCellValue("Sheet 2", k, v)
    }
    for k, v := range values {
    	xlsx.SetCellValue("Sheet 2", k, v)
    }
    
    xlsx.AddChart("Sheet 2", "E2", `{
    "type":"pie3D",
    "series":[
        {
    		"categories":"='Sheet 2'!$A$2:$A$8",
            "values":"='Sheet 2'!$B$2:$B$8"
        }
    ],
    "legend":{
        "position":"right",
        "show_legend_key":false
    },
    "title":{
        "name":"Uygulama Tipi Dağılımı"
    },
    "plotarea":{
        "show_bubble_size":true,
        "show_cat_name":false,
        "show_leader_lines":false,
        "show_percent":false,
        "show_series_name":false,
        "show_val":true
    },
    "show_blanks_as":"gap"
    }`)
    xlsx.SetActiveSheet(index)
    
    // Save xlsx file by the given path.
    err := xlsx.SaveAs(chartedOutputPath)
    if err != nil {
    	fmt.Println(err)
    }

**Comment by vahdet** [comment]
Well, apparently it is strictly obligatory to use **`Sheet#`** format no matter the sheet name is. I don't know if it is by design or a flaw.

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue.

**Comment by vahdet** [comment]
Thanks back for the marvelous library 👏
