### ISSUE TITLE
API for converting excel time to time.Time

### ISSUE THREAD

**Issue by bvwells** [360EntSecGroup-Skylar/excelize#140]
Hi,

I'm currently using the GetCellValue API to obtain dates from a spreadsheet and the date is returned in Excel's internal format. It would be great if you exposed an API which converts from Excels internal format to time.Time.

I see there is an internal API called timeFromExcelTime which seems to do the job. Perhaps it is just a case of exporting it...
Thanks
Ben

**Comment by xuri** [comment]
Variable [builtInNumFmtFunc](https://github.com/360EntSecGroup-Skylar/excelize/blob/905be463edc6d9b0ed184bdee0116217a5118c5e/styles.go#L740-L775) defined the format conversion functions map. Partial format code doesn't support currently and will return original string.

**Comment by bvwells** [comment]
Thanks, I now realise that GetCellValue is returning the internal Excel float representation of the date because the date format is not supported. 

It looks like GetCellValue to will try to return the string format which is seen in the spreadsheet which could be for example 'd-mmm-yy' or 'mm-dd-yy' ....

So perhaps my need is more to have an API to convert a string representation of a date to a time.Time...

**Comment by mlh758** [comment]
https://godoc.org/time#Parse for converting a string to `time.Time`

**Comment by rjfalconer** [comment]
> https://godoc.org/time#Parse for converting a string to `time.Time`

I don't think this can be used to convert Excel serial times though, e.g. `38719.62784` -> `Jan 2nd 2006  15:04:05`

**Comment by hexbioc** [comment]
@xuri , I have exported a function for this. Please have a look (PR #592)

**Comment by hexbioc** [comment]
@xuri , have exported an API for this: #592. Please have a look!
