### ISSUE TITLE
function AddPicture() also need  default Sheetname

### ISSUE THREAD

**Issue by kafpost** [360EntSecGroup-Skylar/excelize#142]
Hi,
Like the function SetCellValue() , AddPicture() also need to name "Sheet" + index.
Otherwise,may cause a problem which reminds that the picture was removed.

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it. Function `SetCellValue()` already require sheet name instead of `Sheet+index`.

**Comment by kafpost** [comment]
I update the library and it works.Thank you!
