### ISSUE TITLE
Could you make `getTotalRowsCols()` as public method?

### ISSUE THREAD

**Issue by shawnye** [360EntSecGroup-Skylar/excelize#144]
Could you make `getTotalRowsCols()`  in `row.go` as public method?
 
Thank you!

**Comment by xuri** [comment]
Thanks for your issue. Because function `getTotalRowsCols()` required parameter `name` is internal XML file path, and this path may be difficult to construct, if public this method, maybe not friendly to use.

**Comment by shawnye** [comment]
I did not notice that.
I think you could  provide `GetTotalRowsCols(sheetName string) (w int,h int)` using sheetName instead of internal XML file path.

**Comment by xuri** [comment]
We can count the total column and rows ourselves by rows/columns iterator or [GetRows](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2@v2.3.2#File.GetRows)/[GetCols](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2@v2.3.2#File.GetCols).
