### ISSUE TITLE
Is there anyway to read top N rows ?

### ISSUE THREAD

**Issue by shawnye** [360EntSecGroup-Skylar/excelize#146]
Suppose there is big files containing 500,000 rows , I just want to read top 1000 rows, could you provide the method  like `ReadTop(sheetName string, rows int) [][]string` , maybe you could use xml stream reading to save a lot of memory than I do with `GetRows()`.

Thanks.

**Comment by lalvarezguillen** [comment]
This would be a very interesting feature.

**Comment by kharism** [comment]
I've build a library to do that, as long as not many cells using string it can do just that. https://github.com/eaciit/hoboexcel. It stream the data directly from excel. only shared strings is being extracted and partitioned into files to save ram

**Comment by xuri** [comment]
Hi @shawnye, thanks for your issue, sorry for my late reply. I have made the function [`GetRow`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.GetRows) and [`Rows`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.Rows) read data as streaming. You can get all the data in the worksheet at once through `GetRows`, or read the data row by row using `Rows` and `Next` like this:

```go
// read top 10 rows
rows, err := f.Rows("Sheet1")
if err != nil {
    fmt.Println(err)
    return
}
for rows.Next() {
    count++
    if count > 10 {
        break
    }
    row, _ := rows.Columns()
    for _, colCell := range row {
        fmt.Print(colCell, "\t")
    }
    fmt.Println()
}
```
