### ISSUE TITLE
[Question] How can I send the xlxs file as a http response without actually creating the file?

### ISSUE THREAD

**Issue by cescoferraro** [360EntSecGroup-Skylar/excelize#148]
I want to create a GET endpoint where the user downloads the xlxs file created with excelize.
How can I achive such thing without actually creating a FS file. The below works, but its far from ideal.

```
func GenerateExcel(w http.ResponseWriter, r *http.Request) {
	xlsx := excelize.NewFile()
	xlsx.NewSheet(2, "Sheet2")
	xlsx.SetCellValue("Sheet2", "A2", "Hello world.")
	xlsx.SetCellValue("Sheet1", "B2", 100)
	xlsx.SetActiveSheet(2)
	err := xlsx.SaveAs("./Workbook.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	data, err := ioutil.ReadFile("./Workbook.xlsx")
	if err != nil {
		log.Fatal(err)
	}
	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", "attachment; filename="+"Workbook.xlsx")
	w.Header().Set("Content-Transfer-Encoding", "binary")
	w.Header().Set("Expires", "0")
	http.ServeContent(w, r, "Workbook.xlxs", time.Now(), bytes.NewReader(data))
}


```

**Comment by xuri** [comment]
Thanks for your issue. [http.ResponseWriter](https://golang.org/pkg/net/http/#ResponseWriter) implements `Write([]byte) (int, error)`, and the function [Write](https://github.com/360EntSecGroup-Skylar/excelize/blob/a4ffb4fbfc9048998345e979577dab2a81bf57ff/file.go#L61-L90) provides function to write to an io.Writer.

```
func GenerateExcel(w http.ResponseWriter, r *http.Request) {
    xlsx := excelize.NewFile()
    xlsx.NewSheet("Sheet2")
    xlsx.SetCellValue("Sheet2", "A2", "Hello world.")
    xlsx.SetCellValue("Sheet1", "B2", 100)
    xlsx.SetActiveSheet(2)
    err := xlsx.SaveAs("./Workbook.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    w.Header().Set("Content-Type", "application/octet-stream")
    w.Header().Set("Content-Disposition", "attachment; filename="+"Workbook.xlsx")
    w.Header().Set("Content-Transfer-Encoding", "binary")
    w.Header().Set("Expires", "0")
    xlsx.Write(w)
}
```

**Comment by cescoferraro** [comment]
@xuri Thanks! I off work today. Will try this asap. Do I still need to xlxs.SaveAs?

**Comment by cescoferraro** [comment]
@xuri yeap that did it! There is no need to SaveAs, just Write(w) works

**Comment by dolmen** [comment]
@cescoferraro That would add an unnecessary dependency of `excelize` on `net/http`.

**Comment by sourabhkheterpal** [comment]
@cescoferraro :  as you mentioned in above comment, we can achieve it without calling saveAs function.

I have executed the above code after removing saveAs function. When i did HTTP request it give me Response in Binary format. 

```
func GenerateExcel(w http.ResponseWriter, r *http.Request) {
    xlsx := excelize.NewFile()
    xlsx.NewSheet("Sheet2")
    xlsx.SetCellValue("Sheet2", "A2", "Hello world.")
    xlsx.SetCellValue("Sheet1", "B2", 100)
    xlsx.SetActiveSheet(2)
  
    w.Header().Set("Content-Type", "application/octet-stream")
    w.Header().Set("Content-Disposition", "attachment; filename="+"Workbook.xlsx")
    w.Header().Set("Content-Transfer-Encoding", "binary")
    w.Header().Set("Expires", "0")
    xlsx.Write(w)
}
```

How can i save it as file with xlsx extension after making http request?

Please let me know if you need more detail.

**Comment by pulpfree** [comment]
When saving the file directly to disk with `xlsx.SaveAs("./Workbook.xlsx")` the file opens properly and all is good. However when writing to http.ResponseWriter as shown in @sourabhkheterpal's example, the file, when saved, isn't recognized and I cannot open it with an xlsx compatible application like Numbers.

Now I'm using the [github.com/awslabs/aws-lambda-go-api-proxy/handlerfunc](github.com/awslabs/aws-lambda-go-api-proxy/handlerfunc) library which uses the `base64.StdEncoding.EncodeToString` method to encode the body. Am I right in assuming this encoding is the problem?

**Comment by zsspj12** [comment]
as you mentioned @xuri , use write function return file instream, the xlsx file downloaded , opening it isn't recognized and need to repair. can you tell me the problem?

**Comment by khawerrind** [comment]
Guys any solution for it?

**Comment by xuri** [comment]
@cescoferraro, @pulpfree, @zsspj12, @khawerrind The execlize now support to get bytes.Buffer from the saved file by [`WriteToBuffer()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.WriteToBuffer), and we can get `io.Reader` like this:

```go
buf, _ := xlsx.WriteToBuffer()
strings.NewReader(buf.String())
```
Reference issue #127.

**Comment by TecLaboratory** [comment]
I am reading excel file and sending excel file to base 64 string to backend and i am not able to read in the backend. This is my code, can anyone help how to read base64 string from http server

`func ExcelImport(u FileImport, r *http.Request) (FileImportResponse, int, string) {

	valStatus, valError := drvvalidator.Check(r, nil, u, FileImport{})

	if valStatus {

		return FileImportResponse{State: "done"}, 200, "OK"
	}

	return FileImportResponse{}, http.StatusConflict, valError

}`

**Comment by vasantinnocuous** [comment]
I am reading excel file and sending base64 string to backend. I want to read base 64 string and i am not able to read from http server. Can anyone give few inputs 

 `func ExcelImport(u FileImport, r *http.Request) (FileImportResponse, int, string) {

	valStatus, valError := drvvalidator.Check(r, nil, u, FileImport{})

	if valStatus {

		return FileImportResponse{State: "done"}, 200, "OK"
	}

	return FileImportResponse{}, http.StatusConflict, valError

}`

Filehandler.go: 
`func ImportFile(w http.ResponseWriter, r *http.Request) {

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var creds importhandler.FileImport
	// Get the JSON body and decode into credentials
	err := json.NewDecoder(r.Body).Decode(&creds)
	if err != nil {
		// If the structure of the body is wrong, return an HTTP error
		rest.RespondJSON(w, http.StatusNotAcceptable, "body not parsable", nil)
		return
	}
	//database stuff here
	fileResponse, status, reserror := importhandler.ExcelImport(creds, r)

	fmt.Println(creds)
	rest.RespondJSON(w, status, reserror, fileResponse)

}`
