### ISSUE TITLE
Read cell's comments

### ISSUE THREAD

**Issue by kccleoc** [360EntSecGroup-Skylar/excelize#151]
How can I get the text of cell's comment by refer to a cell's index, for example, something like GetCellComment("sheet1","A36")
I have checked the excelize godoc and it seems we can just Add comments to cell but not Read from it.
Btw, excelize is so good and I really like it.

**Comment by xuri** [comment]
Hi @kccleoc, sorry for my late reply. [`GetComments`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.GetComments) retrieves all comments and returns a map of worksheet name to the worksheet comments.
