### ISSUE TITLE
Cannot read values after I use UpdateLinkedValue

### ISSUE THREAD

**Issue by valasek** [360EntSecGroup-Skylar/excelize#157]
Open an xlsx file, update one or more values. If excel has functions you should use UpdateLinkedValue function. But If call UpdateLinkedValue all calls using GetCellValue returns "".
When I update excel and do not use UpdateLinkedValue values are updated and I can use excelize to read data without any issues. I tested this case.

Using Open XML SDK Tools I have found differences in all sheet xmls.

Example diff from sheet xml file:
```
   <c r="F13" s="53" t="str">
    <f>
     IF(WEEKDAY($E$9)=1,$E$9,"N/A")
    </f>
    <v>
     N/A
    </v>
   </c>
```
vs
```
   <c r="F13" s="53">
    <f>
     IF(WEEKDAY($E$9)=1,$E$9,"N/A")
    </f>     
   </c>
```
or
```
   <c r="I13" s="54">
    <f>
     IF(H13="N/A", IF(WEEKDAY($E$9)=4,$E$9,"N/A"), H13+1)
    </f>
    <v>
     43040
    </v>
   </c>
```
vs 
```
   <c r="I13" s="54">
    <f>
     IF(H13="N/A", IF(WEEKDAY($E$9)=4,$E$9,"N/A"), H13+1)
    </f> 
   </c>
```
@xuri, relevant files sent via email.

**Comment by xuri** [comment]
Thanks for your issue. The function `UpdateLinkedValue` actually removes the `<v>` tags from the XML. It be used to store  the "cached results" generated by the Excel application when it is saved. After removes the `<v>` tags, it will be recalculated when the file is open again in Excel application. Recalculation requires Excel application. Excelize library doesn't implement the formula calculation engine currently (reference #65). So we will get a blank value using the function `GetCellValue` after call `UpdateLinkedValue`.

**Comment by valasek** [comment]
OK, I this case I am closing an issue as a duplicate to https://github.com/360EntSecGroup-Skylar/excelize/issues/65.

**Comment by Beilusquit90** [comment]
Big thank for answer.
