### ISSUE TITLE
GetRows() returns empty slice

### ISSUE THREAD

**Issue by crosslogic** [360EntSecGroup-Skylar/excelize#164]
I can't get to iterate rows beacause GetRows() returns an empty slice. Here's the code.

```
	xlsx, err := excelize.OpenFile(filePath)
	if err != nil {
		panic(err)
	}

	hoja := xlsx.GetSheetName(1)
	log.Printf("Reading sheet %v\n", hoja)

	rows := xlsx.GetRows(hoja)
	log.Printf("Rows length: %v\n", len(rows))
	log.Printf("Rows: %v\n", rows)
	

Output:
2017/11/28 10:22:24 Reading sheet Productos
2017/11/28 10:22:24 Rows length: 0
2017/11/28 10:22:24 Rows: []
```
I'm adding the file to recreate the situation.
[productos.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1509431/productos.xlsx)

go version go1.9 linux/amd64

Thanks!

**Comment by xuri** [comment]
I have tested that and it works well. Please try upgrade library to the last version by `go get -u github.com/xuri/excelize`

**Comment by crosslogic** [comment]
Yes you are rigtht! 
I had updated the package, but I had forgotten to update the dependency in the vendor directory.

Thanks!
