### ISSUE TITLE
After deleting the workbook, the file is damaged when the Excel file is opened, and the file can be opened after the point is repaired, but the content is less.

### ISSUE THREAD

**Issue by hwf452** [360EntSecGroup-Skylar/excelize#165]
I use this library to write dozens of Sheet, and then delete several of the Sheet.

If len (members) > 0 {

Xlsx.DeleteSheet ("Sheet1")

Xlsx.UpdateLinkedValue ()

ErrDelSheet1: = xlsx.Save ()

If errDelSheet1! = nil {{

Logs.Error (errDelSheet1)

}

Xlsx.DeleteSheet ("Sheet2")

ErrDelSheet2: = xlsx.Save ()

If errDelSheet2! = nil {{

Logs.Error (errDelSheet2)

}

}

Then open the Excel file, suggesting that some of the contents of Excel are not readable. Whether or not to repair it. I can open the file after I fix it.

If the above is not called

![180e95b0-4eea-4e29-8363-791f503e421b](https://user-images.githubusercontent.com/6705071/33549961-4133b5a0-d927-11e7-919e-fcaba889defd.png)

![2e072dbe-5b47-4bcf-a251-037c0e5e8994](https://user-images.githubusercontent.com/6705071/33550399-b5f10874-d928-11e7-8d06-180718b9a184.png)

![53434980-26a7-4e5f-a4d9-6b73e2a4cf26](https://user-images.githubusercontent.com/6705071/33550701-d7791198-d929-11e7-8d47-35d697f400d1.png)

contact me: +86 15362969113      or  QQ:273217031   or  email:hwf452@163.com

**Comment by hwf452** [comment]
if len(members) > 0 {
		xlsx.DeleteSheet("Sheet1")
		errDelSheet1 := xlsx.Save()
		if errDelSheet1 != nil {
			logs.Error(errDelSheet1)
		}
		xlsx.DeleteSheet("Sheet2")
		errDelSheet2 := xlsx.Save()
		if errDelSheet2 != nil {
			logs.Error(errDelSheet2)
		}
	}

如果这段删除Sheet的代码没有调用。文件打开正常。

**Comment by shawnye** [comment]
I've also meet this problem.

**Comment by xuri** [comment]
@hwf452 Thanks for your issue. I have fixed this issue by changing the `activeTab` tag calculation method of the workbook. Please try upgrade library to the last version by `go get -u github.com/360EntSecGroup-Skylar/excelize`.

**Comment by hwf452** [comment]
Hello, yesterday I just made the bug you quickly completed the repair, I have verified this afternoon, your efficiency is very fast. Like for you.
