### ISSUE TITLE
Using $ before first column range in formulas writes column in lowercase in xml files

### ISSUE THREAD

**Issue by gquinet** [360EntSecGroup-Skylar/excelize#166]
When i use formulas in a document, and i open it after with Excell or libreoffice, i need to do a full replace of sum to SUM for the formula to work.

Same for vlookup to replace with VLOOKUP.

In xml file, the SUM is in uppercase but when opened in libreoffice or microsof Excell it appear in lowercase.

I haven't found any way to prevent this and it might be long for huge documents to replace formulas in the whole document.

**Comment by gquinet** [comment]
For information, i'm on v1.2 of Excelize under linux mint 18.1 and go 1.8.1

**Comment by xuri** [comment]
I have tested on macOS 10.13.1 LibreOffice Version: 5.4.3.2 and Microsoft Excel Version 15.40 (171108) and uppercase formula string works well, it doesn't appear lowercase. The lowercase formula will cause any problems? Try to get formula by [`GetCellFormula()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.GetCellFormula) convert to uppercase and set cell formula again by [`SetCellFormula()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetCellFormula).

**Comment by gquinet** [comment]
My libreoffice version is 5.1.6.2, but does the same on other versions.

The strange thing is that if i look in the XML File, all seems OK, a formula writen with LibreOffice and saved as Excell format looks like the Excelize formula.

When i replace sum with SUM in LibreOffice and save, except it can now be read by Microsoft Excell 2016 on windows 10 where it couldn't before, is that all &#39; are replaced by &quote; for exemple.

I really don't undestand what does that strange thing.

May i add an example file?

**Comment by gquinet** [comment]
Ok, getting some better results on SUM  by changing '.' with '!' for area and ';' by ',' as separator. ('.' and ';' are those that appear in LibreOffice French (and SUM is converted to SOMME)).

Looking at VLOOKUP now, and changed same ';' and '.' to ',' and '!' in my go code, the generated file keep getting column letter in lowercase where Excell ibreOffice expect uppercase as you can see here : 

`<f aca="false">VLOOKUP(B2,zones!$A$4:$B$60,2,0)</f><v>France</v></c><c r="E2" s="1" t="s"><v>1084</v></c><c r="F2" s="1" t="e"><f aca="false">VLOOKUP(E2,zones!$d$4:$E$60,2,0)</f>`
The first VLOOKUP is one corrected changing a to A in formula and gives a good result.
The second one, shows Err501 because of the lowercase d.

Really close now because i got some errors in the way i wrote formulas but this lowercase problem still gives problems when reading files with Office and LibreOffice :-s

**Comment by gquinet** [comment]
Ok!! i finally got it working fine, but i think ther's still some king of issue because i had to remove all leading '$' on the first column in ranges.

`		excellFile.SetCellFormula(sheetName, "B2",
			fmt.Sprintf("VLOOKUP(%s%d,zones!$D$4:$E$60,2,0)", tools.ColNumToStr(colNum-1), rowNum))
`
is written in xml file as `VLOOKUP(A2,zones!$d$4:$E$60,2,0)` (note that D became d)


if i chang my code  to
`		excellFile.SetCellFormula(sheetName, "B2",
			fmt.Sprintf("VLOOKUP(%s%d,zones!D$4:$E$60,2,0)", tools.ColNumToStr(colNum-1), rowNum))
`
the xml file contains now `VLOOKUP(A2,zones!D$4:$E$60,2,0)` and it works very well now


This is no big deal when not manually modifying file after that, but in my case, i give the file to our accountant that add some stuff and duplicate formulas and sheets. Then the formula is broken because the leading $ (meaning not to change column when copying) no longer lock the column to it's value and D becomes E if you copy formula to the right for example.

**Comment by gquinet** [comment]
i changed the title to match the real problem ;)

**Comment by gquinet** [comment]
Last thing to get it working in Microsoft Office is i needed to open the file in LibreOffice, then save the file under Office 2007-2013 format.

The effect on the xml files composing the document is the one i noticed earlier : 

&#39; are replaced by &apos; etc.

So as a resume, leading area column letter in formulas are writen in lowercase in xml files when there is a '$' char before, AND files are writen with wrong escaping characters format for latest versions of Microsoft Office (&#39; instead of &apos; and so on).

Both issues can be solved by removing leading '$' and opening then saving the file under LibreOffice.
