### ISSUE TITLE
custom_number_format doesn't work

### ISSUE THREAD

**Issue by alexmironof** [360EntSecGroup-Skylar/excelize#167]
```
style, _ := input.NewStyle(`{"custom_number_format":"d-mmm-yy"}`)
input.SetCellStyle(inputActiveSheet, targetCol, targetCol, style)
val := input.GetCellValue(inputActiveSheet, targetCol)					
```
`val` gives me raw cell value

**Comment by xuri** [comment]
Thanks for your issue. Excelize not support to get formatted value of the cell with `custom_number_format` properties currently.

**Comment by alexmironof** [comment]
oh I see... I found it some where in doc comments and tried to use.

There is big issues  in date parsing with formats like `m/d/yy`. 

actually `go` parses year `42` as `2042` instead of `1942`, so many confussion may occur.

**Comment by bringyou** [comment]
Excuse me, but is there any plan to support such kinda usage?
