### ISSUE TITLE
Using AddTable along with SetCellStyle for the top row

### ISSUE THREAD

**Issue by vahdet** [360EntSecGroup-Skylar/excelize#173]
I have an existing xlsx file and I want to format a sheet of it as a worksheet table (i.e. I want thr sheet to have zebra-stripes). However I get no relief when trying to add it to my existing code

**My code looks like the following**

    // Open existing file
    xlsx, err := excelize.OpenFile(filePath)
    if err != nil {
    	fmt.Printf(err.Error())
    	return
    }
    
	// Add table formatting (If the following line is removed, excel is fine)
    xlsx.AddTable("SheetName", "A2", "C10", `{"table_style":"TableStyleMedium2", "show_first_column":true,"show_last_column":true,"show_row_stripes":false,"show_column_stripes":true}`)
    
    headerStyle, err := xlsx.NewStyle(`{"fill":{"type":"pattern","color":["#283593"],"pattern":1}, "font":{"bold":true,"family":"Calibri","size":9,"color":"#FFFFFF"}}`)
    if err != nil {
    	fmt.Println(err)
    }
    
	// Add header styling
    xlsx.SetCellStyle("SheetName", "A1", "C1", headerStyle)
    
    err = xlsx.Save()
    if err != nil {
    	fmt.Printf(err.Error())
    	return
    }

**Results**
The file is created but MS Excel cannot open it properly and warns that the file is broken.

**`go version`:**
```
go1.9.2 windows/amd64
```

**Excelize commit ID:**
```
46187309f4fcf317515693fcba913ae6ae3c7eb7
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```
OS: Windows 7 Enterprise Service Pack 1
Microsoft Excel™ version: 2016 Standard
```

**Comment by xuri** [comment]
Thanks for your issue. Could you provide file attachments?

**Comment by vahdet** [comment]
Sure, since attachments do not support .go file extensions, I add it as a .txt

When line 90 is commented out, the resulting excel is fine. When run as it is attached, excel cannot open it properly.

P.S: Btw, as you can see, it is a hybrid with tealeg's xlsx.

[main.txt](https://github.com/360EntSecGroup-Skylar/excelize/files/1589234/main.txt)

**Comment by xuri** [comment]
You tried to create a form in range `A2:C4`. But there an AutoFilters exists in the same range column. So this operation is attempting to change a filtered range on your worksheet and cannot be completed. To complete this operation, AutoFilters in the sheet need to be removed.

**Comment by vahdet** [comment]
Hallelujah!
Didn't notice AddTable inserts filtering by itself. Thanks a lot for making life easier and helping get rid of VisualBasic scripts 🕺
