### ISSUE TITLE
the minimal example generated XLSX file  has no data

### ISSUE THREAD

**Issue by shencan** [360EntSecGroup-Skylar/excelize#174]
**Description**

I use office 2016(mac os) Excel open the minimal example  code  generated XLSX file. but There's no data

**Steps to reproduce the issue:**
1. copy the minimal example  code 
2. run the program
```
package main

import (
    "fmt"

    "github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
    xlsx := excelize.NewFile()
    // Create a new sheet.
    index := xlsx.NewSheet("Sheet2")
    // Set value of a cell.
    xlsx.SetCellValue("Sheet2", "A2", "Hello world.")
    xlsx.SetCellValue("Sheet1", "B2", 100)
    // Set active sheet of the workbook.
    xlsx.SetActiveSheet(index)
    // Save xlsx file by the given path.
    err := xlsx.SaveAs("./Workbook.xlsx")
    if err != nil {
        fmt.Println(err)
    }
}
```

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```
shencan@MacBook:~/Goscript$ go run write_excel.go
shencan@MacBook:~/Goscript$ ls -l  Workbook.xlsx
-rw-r--r--  1 shencan  staff  5028 12 27 14:09 Workbook.xlsx
```
![image](https://user-images.githubusercontent.com/11796215/34372433-9b0d30b6-eb0f-11e7-9288-fbdf33a38c77.png)
![image](https://user-images.githubusercontent.com/11796215/34372447-bd7f4c56-eb0f-11e7-9577-7d83c9b4e4b4.png)

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
mac os  office 2016  Excel

**Comment by xuri** [comment]
Check the Go version you are using. This library needs Go version 1.8 or later. Relate issue #35, #39, #42, #84, #97 and #121.
