### ISSUE TITLE
bug in read specific xlsx data

### ISSUE THREAD

**Issue by chenwee** [360EntSecGroup-Skylar/excelize#175]
**Description**
reading error if xlsx file has the data below (tealeg is ok).

e.g. data.xlsx 
a 2 row 5 column xlsx file. where col1,2,5 in row2 is empty (write nil just to format code)

INT  INT  INT  INT  INT
nil    nil    a      b    nil

when xlsx.GetRows, it returns a len(6) row, the 6th cell is "". If all cell has value it's right, return a len(5) row.

**Comment by xuri** [comment]
Thanks for your issue. In order to ensure compatibility, excelize will auto-fill all cells according to the largest row and column, and verify the cell contents before reading or writing to the worksheet, the cell contains the empty string will be included in the completion of the range.

**Comment by chenwee** [comment]
@xuri auto-fill is ok. what make me confused is a max 5 column xlsx, return a 6 column data, with all the 6th column "".

**Comment by xuri** [comment]
I have tested and it works well, please provides file attachments if you can.

**Comment by chenwee** [comment]
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1605933/test.xlsx)
that's it

**Comment by xuri** [comment]
I have fixed it. Please try upgrade library to the last version.
