### ISSUE TITLE
Add SetCellValue time.Duration support

### ISSUE THREAD

**Issue by microo8** [360EntSecGroup-Skylar/excelize#176]
The function `SetCellValue` already supports `time.Time`, which can be then formated.

But if I have just `time.Duration` (like some diff of start and end time), I can't add it to the cell so that excel will treat it like time. I want it to be an time value with `[h]:mm:ss` format, which can be used in formulae.

- If I add only the `time.Duration` it is the textual representation (eg `5h3m33s`)
- if I add an formated output from `time.Duration` (eg `05:03:33`) , excel takes it just like an escaped string, using `SetCellDefault` also doesn't set the cell to be a time value

**Comment by xuri** [comment]
Thanks for your issue. Please try to convert time duration to the seconds, and set time format for the cell. For example: 

```
xlsx.SetCellValue("Sheet1", "B2", time.Duration(1e13).Seconds()/86400)
style, _ := xlsx.NewStyle(`{"number_format": 21}`)
xlsx.SetCellStyle("Sheet1", "B2", "B2", style)
```

You will see `02:46:40` when you open the file in Excel.

**Comment by microo8** [comment]
Thanks, this works :) but it would be great if `SetCellValue` would do it for me. Or not?

**Comment by xuri** [comment]
Because `SetCellValue ` can't determine the number format each developer's need, so I think let developers come from the definition of better.

**Comment by microo8** [comment]
But `SetCellValue` also uses the default date format `m/d/yy h:mm` for `time.Time`, so why not use `[h]:mm:ss` for `time.Duration`?

**Comment by xuri** [comment]
Thanks for your advice, I've added `time.Duration` support for the function `SetCellValue()`. note that the default number format only takes effect if no other styles are applied to the cell being set.

**Comment by microo8** [comment]
That was fast :) thanks great!
