### ISSUE TITLE
how to use zh-cn number format?

### ISSUE THREAD

**Issue by wangsongyan** [360EntSecGroup-Skylar/excelize#177]
I want to get cell value with zh-cn numberformat('28    | m"月"d"日"')
`
style, _ := xlsx.NewStyle(`{"number_format": 28, "lang": "zh-cn"}`)
xlsx.SetCellStyle("Sheet1", "A2", "A2", style)
fmt.Println(xlsx.GetCellValue("Sheet1", "A2"))
`
the cell value is '2017-12-04'，but I got '43073'.
and I want to write cell value use the same format，got '43073' too.

**Comment by xuri** [comment]
Thanks for your issue. The cell style set by function `SetCellStyle()` can be read by Excel application, but the function `GetCellValue()` only supports parsing a limited number format of the cell, if it is possible to apply a format to the cell value, it will do so, if not then the raw value of the cell will return. Variable [builtInNumFmtFunc](https://github.com/360EntSecGroup-Skylar/excelize/blob/6dc135a992f1155c581a98fca6460dad54766532/styles.go#L740-L775) defined the format conversion functions map. Partial format code doesn't support currently and will return original string. Also, reference the related issue #140.

**Comment by wangsongyan** [comment]
thanks a lot.
