### ISSUE TITLE
RemoveRow is not working

### ISSUE THREAD

**Issue by ghost** [360EntSecGroup-Skylar/excelize#178]
excelFilePath := model.GetExcelFilePath()
	file, openFileError := excelize.OpenFile(excelFilePath)
	if openFileError != nil {
		logginghelper.LogError("writeQuestionDataToExcel()::openFileError", openFileError)
		return openFileError
	}
	// sh := file.Sheet["0"]
	// rowCounter, _ := strconv.ParseInt(rowno, 10, 0)
	rowCounter, _ := strconv.Atoi(rowno)
	logginghelper.LogDebug(file.GetSheetName(1))
	file.RemoveRow(file.GetSheetName(1), 2)
	// logginghelper.LogDebug("row : ", file.GetRows(file.GetSheetName(1)))
	logginghelper.LogDebug("row : ", rowCounter+1)
	// logginghelper.LogDebug("row : ", file.GetRows(file.GetSheetName(1)))
	file.RemoveRow(file.GetSheetName(1), rowCounter+1)
	return nil
}

**Comment by xuri** [comment]
Thanks for your issue. The function `RemoveRow()` only support remove the single row and just auto handle existing hyperlinks, merged cells and auto filters currently, it may not work correctly if cells contain more complicated styles. Please provides file attachments if you can.

**Comment by vikraming** [comment]
which file..u mean excel

**Comment by vikraming** [comment]
This is the my excel Data
0 | TrueFalse | TAF | test tf edit | ["img1.jpg","img2.jpg"] | ["aA","a"] | ["aA"] | ["data","process"]
-- | -- | -- | -- | -- | -- | -- | --

**Comment by xuri** [comment]
The function `RemoveRow()` may not work on a workbook that contains pictures. If you can, please attach the .xlsx file, and provides the line number of the specific deletion.

**Comment by vikraming** [comment]
xlsx file containing pictures text only . for example image.jpg , image.png .

**Comment by vikraming** [comment]
[Book1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1614614/Book1.xlsx)

**Comment by xuri** [comment]
I have tested with the file you upload and it works well, which row do you want to remove in your case, please provide the key code if you can.

**Comment by vikraming** [comment]
func RemoveQuestionRowFromExcel(rowno string) error {
	excelFilePath := model.GetExcelFilePath()
	xlsx, _:= excelize.OpenFile(excelFilePath)
	rowCounter, _ := strconv.Atoi(rowno)
	xlsx.RemoveRow(xlsx.GetSheetName(1), rowCounter)
	return nil
}

**Comment by vikraming** [comment]
this is the my code
