### ISSUE TITLE
Image unknown format

### ISSUE THREAD

**Issue by jorgelub12** [360EntSecGroup-Skylar/excelize#179]
I'm just trying to add an image file but when I generate the excel an error shows up. (I'm just following the examples)

. There is a one.jpg file in the same directory that the .exe generated by golang.
. I used the command go build 

![image](https://user-images.githubusercontent.com/17097930/34961984-c6c6cc58-fa0f-11e7-950c-069b5fa3fe6f.png)

````
xlsx := excelize.NewFile()
	sheet := "Sheet1"

	xlsx.SetCellValue(sheet, "A2", "Picture")

	errx := xlsx.AddPicture(sheet, "A3", "https://i.imgur.com/sJUvygL.png", "")
	if errx != nil {
		fmt.Println(errx)
	}
	err := xlsx.SaveAs("./testing.xlsx")
```
`

**Comment by xuri** [comment]
Thanks for your issue, I have checked metadata of the image by [exif.regex.info/exif.cgi](http://exif.regex.info/exif.cgi), although the file extension is `.png`, but the encoding type actually is `jpeg`, so you need to import `_ "image/jpeg"`.

**Comment by jorgelub12** [comment]
I have been imported 

	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"

**Comment by xuri** [comment]
Please provides Excelize version or commit ID, Golang version you are using. I suggest that fill in the complete necessary information in the issue template when you create a new issue, that's will be saving our time.
