### ISSUE TITLE
 In the example  xlsx.GetRows("Sheet1")  Output  is []

### ISSUE THREAD

**Issue by jinjiangcc** [360EntSecGroup-Skylar/excelize#181]
cell := xlsx.GetCellValue("Sheet1", "B2")
	fmt.Println(cell)
rows := xlsx.GetRows("Sheet1")
	fmt.Println(rows)
-----------------------------------------------------------------------------
原宿迷彩外套女短款冬韩版学生加厚情侣棉衣bf宽松chic棉服女新款
[]

**Comment by xuri** [comment]
Please provides Excelize version or commit ID, Golang version you are using, and .xlsx file if you can. I suggest that fill in the complete necessary information in the issue template when you create a new issue, that's will be saving our time.

**Comment by jhinrichsen** [comment]
Running into the same error using excelize 1.4.1, Golang 1.12. Use the following test case to reproduce:


```
func TestGetRows(t *testing.T) {
        excel := excelize.NewFile()
        sheet := excel.GetSheetName(0)
        axis := "A1"
        excel.SetCellValue(sheet, axis, "666")
        rows := excel.GetRows(sheet)
        want := 1
        got := len(rows)
        if want != got {
                t.Fatalf("want %d but got %d", want, got)
        }

```

Running the test case fails, the cell is stored, but GetRows() returns 0.

```
A1 = "666"
--- FAIL: TestGetRows (0.00s)
    main_test.go:154: want 1 but got 0
FAIL

```

**Comment by xuri** [comment]
Hi @jhinrichsen, thanks for your issue. There is no worksheet with index `0`. The newly created worksheet contains a worksheet named `Sheet1` by default. You can use this name directly or get it according to the `GetSheetMap` function.
