### ISSUE TITLE
Is it possible to add a hyperlink to an image?

### ISSUE THREAD

**Issue by Eugenijus** [360EntSecGroup-Skylar/excelize#185]
I think this is FEATURE REQUEST.

**Description**

I am adding images to spreadsheet cell and want to add a hyperlink on that image.
I couldn't find a way with this library, so I add hyperlink to a cell. However, some cells have two images or more, hence adding hyperlink to a cell doesn't always produce a needed result.

Is it even possible to add a hyperlink to an image by code? I know it's possible from Excel and Calc.

Thanks for creating this library, I think that's very awesome.

**Comment by xuri** [comment]
Thanks for your issue. I have to init add a hyperlink to an image support for the function [`AddPicture()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.AddPicture).

**Comment by Eugenijus** [comment]
Thank you. However, when I create a simple spreadsheet or a spreadsheet with image + hyperlink, there is an Excel 2016 error when opening that spreadsheet:

> Excel was able to open the file by repairing or removing the unreadable content.
> Repaired Records: Worksheet properties from /xl/workbook.xml part (Workbook)

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error139200_01.xml</logFileName><summary>Errors were detected in file 'C:\...\Workbook2.xlsx'</summary><repairedRecords><repairedRecord>Repaired Records: Worksheet properties from /xl/workbook.xml part (Workbook)</repairedRecord></repairedRecords></recoveryLog>
```

There is also an extra Sheet being created "Recovered_Sheet2"

**Comment by xuri** [comment]
Please provide the file attachment if you can.

**Comment by Eugenijus** [comment]
please see attached.

**Comment by xuri** [comment]
Could you provide the origin file and code?

**Comment by Eugenijus** [comment]
Here: [excel2.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/1699063/excel2.zip)

**Comment by xuri** [comment]
Oh, when calling the `NewFile ()` function will automatically create a worksheet named `Sheet1`, so we need not call this function when only one worksheet in the workbook.

**Comment by Eugenijus** [comment]
It's working without error now. Thank you! :)
