### ISSUE TITLE
excel broken when create new file

### ISSUE THREAD

**Issue by shawnye** [360EntSecGroup-Skylar/excelize#186]
**Description**

Excel broken when create new file

**Steps to reproduce the issue:**
<pre>
xlsx := excelize.NewFile()
xlsx.NewSheet("Sheet1")
xlsx.SaveAs("test.xlsx")
</pre>

**Describe the results you received:**
Just trival process, but when open test.xlsx, excel 2013 compained: 
发现部分内容有问题，是否让我们尽量尝试修复？

**Describe the results you expected:**
excel 2013 keep quilt as do before

**Output of `go version`:**
```
go version go1.9.2 windows/amd64
```

**Excelize version or commit ID:**
```
7621927       latest commit
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
window 7 professional, excel 2013

**Comment by xuri** [comment]
Thanks for your issue. When calling the `NewFile()` function will automatically create a worksheet named `Sheet1`, so we needn't call the function `NewSheet()` when only one worksheet in the workbook. Reference issue #185.

**Comment by shawnye** [comment]
Thank you!
I did not notice the example :<
<pre>
xlsx := excelize.NewFile()
    // Create a new sheet.
    index := xlsx.NewSheet("**Sheet2**")
</pre>
