### ISSUE TITLE
Does the function "AddChart" only support microsoft office because in the AddChart example's .xlsx file , the chart is blank if open by WPS Excel but it is ok if open by microsoft office?  

### ISSUE THREAD

**Issue by lifb** [360EntSecGroup-Skylar/excelize#187]
**Description**
![default](https://user-images.githubusercontent.com/11613587/36081776-5a04d29c-0fde-11e8-8bcd-09be44117062.PNG)

**Steps to reproduce the issue:**
Does the function "AddChart" only support microsoft office?
Because when I use the AddChart example and get .xlsx file , the chart is blank if open by WPS Excel but it is ok if open by microsoft office Excel?  
**Describe the results you received:**
In the AddChart example's .xlsx file , the chart is blank if open by WPS Excel but it is ok if open by microsoft office
![default](https://user-images.githubusercontent.com/11613587/36081720-ba06c93a-0fdd-11e8-81ea-710ca324f25b.PNG)

**Describe the results you expected:**
The chart can open by WPS Excel correctly.

**Output of `go version`:**
go 1.8
```
(paste your output here)
```

**Excelize version or commit ID:**
Excelize-1.2
```
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Win7, WPS office

**Comment by xuri** [comment]
I will try to evaluate compatibility with WPS later.

**Comment by lifb** [comment]
Thank you very aery much! By the way, how soon will you commit the latest version ? May I have the your time because I‘m really in a hurry!!!

**Comment by xuri** [comment]
Just remove `=` in the formula of format string, for example, use `Sheet1!$A$30` instead of `=Sheet1!$A$30`. But WPS doesn't support all styles of charts in Microsoft Excel™. For example, the `bar3D` chart in the Microsoft Excel™ will be displayed as `bar` chart in the WPS.

**Comment by lifb** [comment]
THX too much!!!
