### ISSUE TITLE
Bar clustered

### ISSUE THREAD

**Issue by joker63** [360EntSecGroup-Skylar/excelize#190]
Hi!
How to draw a bar clustered?
![bar clustered](https://user-images.githubusercontent.com/12747633/36962831-1d5114a2-2062-11e8-95e9-24cd123302de.png)

**Comment by xuri** [comment]
Thanks for your issue, I have added clustered, stacked and 100% stacked bar and column charts support for this library. You can create bar clustered chart by add `bar` type chart.

**Comment by joker63** [comment]
It's great. Thank you! :)
