### ISSUE TITLE
Protected cell

### ISSUE THREAD

**Issue by nikencmoscow** [360EntSecGroup-Skylar/excelize#191]
Hi!

Why does the cell become protected when using SetCellStyle?

style, err := xlsx.NewStyle(`{"font":{"color":"#FF0000", "size":12}, "border":[{"type":"right","color":"#09600b","style":1}], "alignment":{"horizontal":"right"}}`)
		if err != nil {
			fmt.Println(err)
		}
		xlsx.SetCellStyle(sheetFull, cell, cell, style)

Advance thanks!

**Comment by xuri** [comment]
What's the "be protected" means? I have tested and it works well. Please provide the file attachment if you can.

**Comment by nikencmoscow** [comment]
Please, look file before and after.
Sheet 3, Cell F8.

[before.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1787549/before.xlsx)
[after.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1787550/after.xlsx)

**Comment by xuri** [comment]
I have added set protection properties support for the function `NewStyle()`. You can add `"protection":{"locked":false}` in the style format set param.

**Comment by nikencmoscow** [comment]
Thank You!)
