### ISSUE TITLE
InsertRow should return a reference to the row

### ISSUE THREAD

**Issue by cemremengu** [360EntSecGroup-Skylar/excelize#192]
As the title says, it would be great if the `InsertRow` functionality returns a reference to the row.

**Comment by xuri** [comment]
Thanks for your issue. The function `InsertRow()` and `InsertCol()` just insert a new blank row / column. Why should return a reference to the row?

**Comment by cemremengu** [comment]
I was thinking that it can be useful for making changes to that row if a reference is returned. Not really necessary. It was like that in `tealeg/xlsx` so I was expecting it but I found another way 😄 

Thank you!
