### ISSUE TITLE
GetRows loops on empty cells but with a style

### ISSUE THREAD

**Issue by Bagu3tte** [360EntSecGroup-Skylar/excelize#195]
Hello, I would like to know if there is an alternative function to `GetRows` that will only return cells with content?

Example:
![image](https://user-images.githubusercontent.com/15075205/37337432-91226d9c-26b4-11e8-9f3c-9ae9ac216fe5.png)

If I do a `len(GetRows("sheet1"))` on the sheet in example, the `len` function will return 1048576 instead of 2.

**Comment by xuri** [comment]
Thanks for your issue. Could you tell me which version of Excel that created this file? and please provides file attachments if you can. This lib will check the last XML element of worksheet inner the xlsx file when you call the function `GetRows()`, then   
 autofill the entire cell of the worksheet with the empty value.

**Comment by Bagu3tte** [comment]
I used Google Sheets and exported to .xlsx.
[example.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1818879/example.xlsx)

**Comment by rafaelmiti** [comment]
I created the PR #319 to propose a fix to this. Please review.
