### ISSUE TITLE
Memory usage keeps increasing

### ISSUE THREAD

**Issue by cemremengu** [360EntSecGroup-Skylar/excelize#197]
I am doing a lot of reports (300-400) in my program at the same time and I am limiting the concurrency to number of cpus at a time.

However, memory usage keeps increasing to insane amounts. I know there can be high memory usage but shouldn't the memory used returned back once the excel is saved?

Is there a way to release the resources used after saving? Any ideas on how to keep the memory bounded?

**Comment by cemremengu** [comment]
Here is the memory profile from a run until the process was killed
```
File: app.exe
Type: inuse_space
Time: Mar 18, 2018 at 5:36am (+03)
Showing nodes accounting for 1052630.81kB, 98.50% of 1068634.27kB total
Dropped 143 nodes (cum <= 5343.17kB)
      flat  flat%   sum%        cum   cum%
32980.33kB  3.09%  3.09% 1039679.25kB 97.29%  main.setCellCoordValue // my helper method for setting cell values
         0     0%  3.09% 926220.06kB 86.67%  github.com/360EntSecGroup-Skylar/excelize.(*File).SetCellValue
812203.03kB 76.00% 79.09% 872536.71kB 81.65%  github.com/360EntSecGroup-Skylar/excelize.completeCol
         0     0% 79.09% 861894.40kB 80.65%  github.com/360EntSecGroup-Skylar/excelize.(*File).SetCellDefault
         0     0% 79.09% 675337.30kB 63.20%  main.CreateMultiSheetXLSXFromTemplate
         0     0% 79.09% 392765.78kB 36.75%  main.CreateSingleSheetXLSX
23004.42kB  2.15% 81.24% 72471.49kB  6.78%  github.com/360EntSecGroup-Skylar/excelize.(*File).NewStyle
         0     0% 81.24% 41488.86kB  3.88%  github.com/360EntSecGroup-Skylar/excelize.(*File).SetCellStr
         0     0% 81.24% 34270.84kB  3.21%  strconv.FormatInt
         0     0% 81.24% 34270.84kB  3.21%  strconv.Itoa
34270.84kB  3.21% 84.45% 34270.84kB  3.21%  strconv.formatBits
27818.26kB  2.60% 87.05% 27818.26kB  2.60%  github.com/360EntSecGroup-Skylar/excelize.ToAlphaString
25685.18kB  2.40% 89.46% 25685.18kB  2.40%  github.com/360EntSecGroup-Skylar/excelize.setBorders
         0     0% 89.46% 23999.57kB  2.25%  database/sql.(*Rows).Next
         0     0% 89.46% 23999.57kB  2.25%  database/sql.(*Rows).Next.func1
         0     0% 89.46% 23999.57kB  2.25%  database/sql.(*Rows).nextLocked
         0     0% 89.46% 23999.57kB  2.25%  database/sql.withLock
   20.04kB 0.0019% 89.46% 23999.57kB  2.25%  github.com/go-goracle/goracle.(*rows).Next
23787.34kB  2.23% 91.68% 23787.34kB  2.23%  github.com/go-goracle/goracle._Cfunc_GoStringN
21384.62kB  2.00% 93.69% 23140.05kB  2.17%  github.com/360EntSecGroup-Skylar/excelize.completeRow
22600.14kB  2.11% 95.80% 22600.14kB  2.11%  strconv.FormatFloat
18526.35kB  1.73% 97.53% 18526.35kB  1.73%  github.com/360EntSecGroup-Skylar/excelize.setCellXfs
    4.16kB 0.00039% 97.53% 10605.77kB  0.99%  github.com/360EntSecGroup-Skylar/excelize.(*File).workSheetReader
         0     0% 97.53% 10346.08kB  0.97%  github.com/360EntSecGroup-Skylar/excelize.trimSheetName
10346.08kB  0.97% 98.50% 10346.08kB  0.97%  strings.NewReplacer
```

**Comment by kharism** [comment]
As far as i know, just because you have save the file to the hard disk does not mean the GC will release those memory to the OS. You need to check whether the xlsx objects is still being referenced by a variable. https://stackoverflow.com/questions/37382600/cannot-free-memory-once-occupied-by-bytes-buffer

**Comment by cemremengu** [comment]
@kharism Thanks for this. I guess this is the behavior I am seeing. Whatever I did (i.e. assigning nil, clearing buffer etc.), the memory won't return to OS.

**Comment by kharism** [comment]
If you only need simple export without much styling there are some libraries with streaming api such as https://github.com/eaciit/hoboexcel. Disclaimer: I wrote those code, use it as a last effort, its not tested for concurrent process

**Comment by cemremengu** [comment]
For me the problem is that although I don't do styling, I read in styled templates, fill the values and save. If it at least supports that, I could give a try.

**Comment by cemremengu** [comment]
Just tested again and can confirm that this is no longer an issue. Memory usage is way more stable than it was in the past.

**Comment by svnwell** [comment]
hello,
How do you solve this problem? I also want to reclaim memory immediately after the file is saved. @cemremengu
