### ISSUE TITLE
GetCellValue returns "" for non empty cells if cell is having a formula

### ISSUE THREAD

**Issue by valasek** [360EntSecGroup-Skylar/excelize#198]
Hi Ri Xu,

that you for your good work on this library. Using it every week.

Would like to report a possible issue with reading values. I am using the latest version of the library. OK and failing excels are shared due to sensitive nature to Ri Xu via email. In Nok excel GetCellValue returns "" in ok excel return the correct value.

**Simple test program below**
```
package main

import (
	"fmt"
	"strconv"
	"github.com/xuri/excelize"
)

func main(){
	xlsxNok, err := excelize.OpenFile("file_nok.xlsx")
	if err != nil {
		fmt.Print(err)
	}
	xlsxOk, err := excelize.OpenFile("file_ok.xlsx")
	if err != nil {
		fmt.Print(err)
	}
	fmt.Printf("file_nok.xls [M20] = '%v', [L20] = '%v\n", xlsxNok.GetCellValue("Sheet1", "M20"), xlsxNok.GetCellValue("Sheet1", "L20"))
	fmt.Printf("file_ok.xls [M20] = '%v', [L20] = '%v\n", xlsxOk.GetCellValue("Sheet1", "M20"), xlsxOk.GetCellValue("Sheet1", "L20"))
	for row := 14; row < 75; row++ {
		fmt.Printf("file_Nok.xls [M%v] = '%v'\n", row, xlsxNok.GetCellValue("Sheet1", "M"+strconv.Itoa(row)))
		fmt.Printf("file_ok.xls [M%v] = '%v'\n", row, xlsxNok.GetCellValue("Sheet1", "M"+strconv.Itoa(row)))
	}
}
```

**Output**

> file_nok.xls [M20] = '', [L20] = '0.00
> file_ok.xls [M20] = '2.00', [L20] = '0.00
> ...

**Comment by xuri** [comment]
Thanks for your issue. Excel application will autosave computed value of formula, `file_ok.xlsx` contains that computed value but `file_nok.xlsx` doesn't. We can get the same result by calling` xlsxOk.UpdateLinkedValue()` after open file. Relate issue #65.

**Comment by valasek** [comment]
Thank you. [Workaround](https://github.com/360EntSecGroup-Skylar/excelize/issues/65#issuecomment-346967778) in issue #65 updated to handle space in xlsx path.
