### ISSUE TITLE
Password protected file

### ISSUE THREAD

**Issue by hieubq90** [360EntSecGroup-Skylar/excelize#199]
I have a use case for my business scenario where I need to password protect my generated excel files before I can email them to the client.
It would be great if we can have a password protection feature in the library.
Thank you!

**Comment by xuri** [comment]
Thanks for your issue.  I have added this feature request to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki). In order to support encryption, we need to implement these [encryption standards](https://msdn.microsoft.com/en-us/library/dd910529(v=office.12).aspx) and many more. It would require a very large number of test cases would be several weeks of work involved. That's an interesting job and I will consider adding support for this feature later. I'll certainly accept that patch if somebody did that an also welcome to contribute to this project.

**Comment by xuri** [comment]
Welcome to contribution! I think `xlsxWorkbookProtection` needn't be an exportable struct. We can add a new function such as `SetPassword()` to manipulate it internally.

**Comment by mohamedainab** [comment]
Any progress on this?

**Comment by loveCatCoder** [comment]
This feature is essential.

**Comment by tsubus** [comment]
Has anyone found a way to get it working temporarily until it's officially released?

**Comment by atlasW** [comment]
two years latter....Still not implemented

**Comment by xuri** [comment]
I just initialize the decryption protection spreadsheet support, and I'll add encryption support later.

**Comment by m3ng9i** [comment]
Is there any time plan for encryption support?

**Comment by m3ng9i** [comment]
This issue is closed. May I ask is there any time plan for encryption support? The document mentioned: "The excelize just support decrypt and not support encrypt currently, the spreadsheet saved by Save and SaveAs will be without password unprotected."

**Comment by pepi1707** [comment]
Isn't this the commit that adds the encryption [01afc6e03f1d28f1806ecd1f3c6c043f6755bd01](https://github.com/360EntSecGroup-Skylar/excelize/commit/01afc6e03f1d28f1806ecd1f3c6c043f6755bd01#diff-d6845828728950151c8be8f33c63cb2194cb5e733d7cdb3b5afd5f8da0aa1ca7)? Are the docs just not updated for the thing highlighted by the person before me?

**Comment by xuri** [comment]
Hi @hieubq90, @mohamedainab, @loveCatCoder, @tsubus, @atlasW, @m3ng9i. Sorry for my late reply. I have just initialized the workbook encryption support, and this feature will released in the next version. Please upgrade to the master branch code if you like.

**Comment by xuri** [comment]
Sorry for my late reply. I have just initialized the workbook encryption support. Please upgrade to the master branch code if you like.

**Comment by kernel-1** [comment]
Whether it can be found in readme example encryption usage?

**Comment by xuri** [comment]
Hi @kernel-1, please update and use the the master branch code for the beta, and reference [the example](https://github.com/xuri/excelize/blob/301f7bc21755cdf7c91c9acd50ddcdcf0285f779/crypt_test.go#L43-L44), specify password in the options of SaveAs function. Note that this feature still working in progress, and will be release in the next stable version.

**Comment by xuri** [comment]
Hi @kernel-1, please update and use the master branch code for the beta, and reference [the example](https://github.com/xuri/excelize/blob/301f7bc21755cdf7c91c9acd50ddcdcf0285f779/crypt_test.go#L43-L44). Specify the password in the options of the SaveAs function. Note that this feature is still a work in progress, and will be released in the next version.
