### ISSUE TITLE
Conditional formatting hides the adjacent borders

### ISSUE THREAD

**Issue by partomatl** [360EntSecGroup-Skylar/excelize#200]
**Description**

Whenever a conditional format is set on a cell and the criterion is met, then this cell "hides" the adjacent borders.

**Steps to reproduce the issue:**
1. Set a conditional format on a cell so that its criterion is met.
2. Watch how it hides the adjacent borders.

Use this code:
```go
xlsx.SetCellValue("Sheet1", "C20", 20)
style, err := xlsx.NewConditionalStyle(`{"font":{"color":"#09600B"}}`)
if err != nil {
	panic(err)
}
xlsx.SetConditionalFormat("Sheet1", "C20:C20", fmt.Sprintf(`[{"type":"cell","criteria":">","format":%d,"value":"0"}]`, style))
```

**Describe the results you received:**

The cell `C20` hides the adjacent borders.
<img width="441" alt="capture d ecran 2018-03-28 a 19 17 12" src="https://user-images.githubusercontent.com/14841318/38045307-b462c5b8-32bc-11e8-8dc8-4721dfd8ae24.png">

**Describe the results you expected:**
<img width="446" alt="capture d ecran 2018-03-28 a 19 17 08" src="https://user-images.githubusercontent.com/14841318/38045321-c33b66d0-32bc-11e8-9e2a-cfdb6d073d21.png">

**Output of `go version`:**

```
go version go1.10 darwin/amd64
```

**Excelize version or commit ID:**

```
Commit ID: 9d7b94d760126aa51485d7d864b1b98a8720017c
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
macOS High Sierra 10.13.3, Microsoft Excel 2016 for Mac 16.9

Thank you for your work!

**Comment by partomatl** [comment]
Update: same result with commit `50e396333241a2790f78966368283af58b92adcc`

**Comment by partomatl** [comment]
Update: same result with commit `2b97c3bb463b28e3d81f714ef55798621174e0a1`

**Comment by xuri** [comment]
Sorry for my so late reply, create conditional style with borders like this:

```go
style, err := f.NewConditionalStyle(`{"font":{"color":"#09600B"},"border":[{"type":"left","color":"#000000","style":1},{"type":"top","color":"#000000","style":1},{"type":"bottom","color":"#000000","style":1},{"type":"right","color":"#000000","style":1}]}`)
```

**Comment by xuri** [comment]
I have fixed it. Please try to upgrade the library with the master branch code. No longer need to specify an existing border style.
