### ISSUE TITLE
Chinese name of sheet will cause GetRows() return empty array

### ISSUE THREAD

**Issue by davyzhang** [360EntSecGroup-Skylar/excelize#201]
**Description**

Chinese name of sheet will cause GetRows() return empty array

**Steps to reproduce the issue:**
1. Create a sheet with a Chinese name like "表2"
2. GetRows("表2")
3. Won't work

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**
go version go1.9.2 darwin/amd64

**Excelize version or commit ID:**
master

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOS

**Comment by xuri** [comment]
Thanks for your issue. I have tested and it works well, please provide the file attachment if you can.

**Comment by davyzhang** [comment]
[sample.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1858412/sample.xlsx)
```go
	x, err := excelize.OpenFile("/tmp/sample.xlsx")
	log.Printf("file opened %+v", x.Path)
	if err != nil {
		panic(err)
	}
	rows := x.GetRows("表2")
```
here is the file and the code to reproduce this issue

**Comment by xuri** [comment]
I have tested and it still works well, please try upgrade library to the last version by `go get -u github.com/360EntSecGroup-Skylar/excelize`.

**Comment by xuri** [comment]
Reference issue #164

**Comment by davyzhang** [comment]
My bad, I forget to update the library for a while, thanks for your time, have a nice day!
