### ISSUE TITLE
Publicize style structs (formatFont, formatStyle and all internal structs separatly)

### ISSUE THREAD

**Issue by therox** [360EntSecGroup-Skylar/excelize#203]
I think it'll be very comfortable and will minimize errors not to generate style json by hands, but (at least) marshal it for default struct.

**Comment by xuri** [comment]
Thanks for your advice. I will make changes to assessment the APIs effect.

**Comment by mlh758** [comment]
I would also like to see this change. I had to dig into the source code to figure out what style properties to set in order to align font for example. If the struct was pubic it would have been a lot easier to figure out and it would also help prevent typos.

**Comment by trende-jp** [comment]
I also think this would be a big improvement.  There is nothing to lose by making it available and, in fact, I think it will make discovering how to interact with this library much simpler.

**Comment by trende-jp** [comment]
https://github.com/360EntSecGroup-Skylar/excelize/pull/470

**Comment by xuri** [comment]
I exported Style structs to allow create the style for cells by given JSON or structure. Ref: [9e2318c](https://github.com/360EntSecGroup-Skylar/excelize/commit/9e2318cefa4ebaa7bf6b1dbc95b30ad7a32366b1)
