### ISSUE TITLE
SetRowHeight() sets row height for next row instead of current

### ISSUE THREAD

**Issue by therox** [360EntSecGroup-Skylar/excelize#205]
```
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	xlsx := excelize.NewFile()
	sheetName := "sheet1"
	currentRow := 2
	currentLetter := "A"
	xlsx.SetCellValue(sheetName, fmt.Sprintf("%s%d", currentLetter, currentRow), "test1\ntest2\test3")
	xlsx.SetRowHeight(sheetName, currentRow, 100)
	xlsx.SaveAs("/tmp/1.xlsx")
}
```
I was thiinking this code will sets text value to "A2" cell and changes 2nd row's height. But result is like on the screenshot.

![image](https://user-images.githubusercontent.com/1963102/38126294-56f0df72-33f8-11e8-9671-f9f9a99806b8.png)

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it by make row index consistent in function `SetRowHeight()` and `GetRowHeight()`.

**Comment by therox** [comment]
Thank you for quick fix!
