### ISSUE TITLE
There is a unmerged cell in the xlsx.MergeCells.Cells

### ISSUE THREAD

**Issue by weiweiabc109** [360EntSecGroup-Skylar/excelize#206]
**Description**
when I open a excel ( exist merged cell ) I found
there is a unmerged cell in the xlsx.MergeCells.Cells

panic: runtime error: index out of range
goroutine 1 [running]:
github.com/Luxurioust/excelize.checkCellInArea(0xc0422d68f6, 0x2, 0xc0425a5750, 0x3, 0xc0422d6800)
	C:/Users/Administrator/go/src/github.com/Luxurioust/excelize/cell.go:536 +0x387
github.com/Luxurioust/excelize.(*File).mergeCellsParser(0xc0420346c0, 0xc042042640, 0x59ebd5, 0x2, 0xc042925de0, 0x4b2dae)
	C:/Users/Administrator/go/src/github.com/Luxurioust/excelize/cell.go:18 +0xc4
github.com/Luxurioust/excelize.(*File).SetCellStr(0xc0420346c0, 0x5a0f0f, 0xc, 0x59ebd5, 0x2, 0x59fa54, 0x6)
	C:/Users/Administrator/go/src/github.com/Luxurioust/excelize/cell.go:431 +0x90
github.com/Luxurioust/excelize.(*File).SetCellValue(0xc0420346c0, 0x5a0f0f, 0xc, 0x59ebd5, 0x2, 0x562500, 0x5c3aa0)
	C:/Users/Administrator/go/src/github.com/Luxurioust/excelize/cell.go:57 +0x657

**Steps to reproduce the issue:**
1.xlsx, err := excelize.OpenFile(filename)
2.xlsx.SetCellValue("Sheel1", "a5", "weiwei")
3.run it

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```
Go SDK 1.9.2
```

**Excelize version or commit ID:**

```
master
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Please provides file attachments if you can.

**Comment by weiweiabc109** [comment]
@xuri 
[user-case.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1886881/user-case.xlsx)

**Comment by xuri** [comment]
I have fixed this issue, please upgrade library to the last version.

**Comment by weiweiabc109** [comment]
@xuri 非常感谢
