### ISSUE TITLE
not a valid zip file

### ISSUE THREAD

**Issue by justdoitgo** [360EntSecGroup-Skylar/excelize#207]
wps

**Comment by xuri** [comment]
What's the version of the Go and Excelize you are using? Please provides environment details (OS, WPS version) and file attachments if you can and provide detailed information according to the issue template when creating an issue.

**Comment by vinceyoumans** [comment]
I am also getting an error when I try to load this xlsx file.
err=====================
zip: not a valid zip file


`//package PBCONVxlsx2csv03
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	//excelFileName := "EPlan_AP_LastSixMonths.xlsx"
	//excelFileName := "./EPlan_AP_LastSixMonths.xlsx"
	//excelFileName := "EPlan_SubmitRequest_LastSixMonths.xlsx"
	excelFileName := "./EPlan_SubmitRequest_LastSixMonths.xlsx"

	//xlsx, err := excelize.OpenFile("./Book1.xlsx")
	xlsx, err := excelize.OpenFile(excelFileName)
	if err != nil {
		fmt.Println("err=====================")
		fmt.Println(err)
		return
	}
	// Get value from cell by given worksheet name and axis.
	cell := xlsx.GetCellValue("Sheet1", "B2")
	fmt.Println(cell)
	// Get all the rows in the Sheet1.
	rows := xlsx.GetRows("Sheet1")
	for _, row := range rows {
		for _, colCell := range row {
			fmt.Print(colCell, "\t")
		}
		fmt.Println()
	}
}
`



/Users/vyoumans/Documents/PBeachChallenge/EPlan_AP_LastSixMonths.xlsx
[EPlan_AP_LastSixMonths.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1907806/EPlan_AP_LastSixMonths.xlsx)

EPlan_AP_LastSixMonths.xlsx
[EPlan_AP_LastSixMonths.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1907807/EPlan_AP_LastSixMonths.xlsx)

**Comment by navono** [comment]
I am also have the same problem.

Go: 1.10.2
Excelize: master
OpenFile xls file

**Comment by xuri** [comment]
@vinceyoumans Thanks for your issue. Please make sure your attachment `EPlan_AP_LastSixMonths.xlsx` can be open by Microsoft Excel™ application.

**Comment by navono** [comment]
![binary](https://user-images.githubusercontent.com/3746639/40237007-c68152c6-5ae1-11e8-9c69-1225716b11f4.PNG)

对比了下`xls`和`xlsx`文件，发现它们的文件起始的格式不一样。`zip`包的`findSignatureInBlock`会去判断前面的字符来确认文件格式。所以导致加载`xls`失败。
[1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2017055/1.xlsx)

上面`1.xlsx`是Office 2013生成的。在上传`xls`的过程中，居然也出现了下面的格式不正确的错误。
![error](https://user-images.githubusercontent.com/3746639/40237366-e0515966-5ae2-11e8-82ff-35d81872dbcc.PNG)

**Comment by calvinchankf** [comment]
@navono thanks for your info, so what is your way to workaround it?

**Comment by navono** [comment]
@calvinchankf for now, copy the content to a new `.xls` file by hand....

**Comment by calvinchankf** [comment]
Lol thanks for sharing 😂 I will request my clients to export a xlsx

**Comment by Damien9527** [comment]
I also meet this problem , I just copy the content to a new .xls or xlsx file by hand .   

need help!

**Comment by navono** [comment]
If you have a lot file .xls files, may be can write a script to transfer all files extension to .xlsx.
I haven't test the solution, just a thought.

**Comment by mahesh-sanikommu** [comment]
any fix for this issue?

**Comment by vasiliyb** [comment]
@mahesh-sanikommu convert `.xls` to `.xlsx` ... i think

**Comment by xuri** [comment]
This lib doesn't support the older binary xls format currently. I will close this issue. The issue #44 still discussing the xls format.

**Comment by iSenninha** [comment]
> @mahesh-sanikommu convert `.xls` to `.xlsx` ... i think

so sad....

**Comment by BlackCodes** [comment]
so sad...

**Comment by 1114619217** [comment]
so sad...

**Comment by MKquant** [comment]
so sad...

**Comment by cahyaramadhan** [comment]
so sad...

**Comment by XieWeiXie** [comment]
so sad...

**Comment by shikingram** [comment]
No Solution?

**Comment by xuri** [comment]
Hi @shikingram, this issue has been closed and merged into issue #44. Currently, there is no plan to add support to the legacy xls format spreadsheet.

**Comment by blusewang** [comment]
so sad...

**Comment by yasir16** [comment]
I just had this problem, 4 days ago it going well, but yesterday this issue appeared
