### ISSUE TITLE
Empty cell after hyperlink creation

### ISSUE THREAD

**Issue by OloloevReal** [360EntSecGroup-Skylar/excelize#210]
**Description**

The function xlsx.SetCellHyperLink create link without display text - the cell is empty but link is created.
It can be fixed by additionaly use xlsx.SetCellStr function

Nevertheless, it look likes as imperfection because the struct xlsxHyperlink has Display field for this purpose, but xlsx.SetCellHyperLink does not use it

```
type xlsxHyperlink struct {
	Ref      string `xml:"ref,attr"`
	Location string `xml:"location,attr,omitempty"`
	Display  string `xml:"display,attr,omitempty"`
	RID      string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}
```

**Steps to reproduce the issue:**
1. using xlsx.SetCellHyperLink

**Describe the results you received:**
```
    <hyperlinks>
        <hyperlink ref="A1" location="Sheet1!A1"></hyperlink>
    </hyperlinks>
```

**Describe the results you expected:**
If we are using MS Excel:
```
    <hyperlinks>
        <hyperlink ref="A1" location="Sheet1!A1" display="Sheet1"/>
    </hyperlinks>
```

**Output of `go version`:**

```
go version go1.10 windows/amd64
```

**Comment by xuri** [comment]
Thanks for your issue. The function `SetCellHyperLink()` doesn't support set display attribute of hyperlinks currently. We need to set cell value by function `SetCellValue()`.
