### ISSUE TITLE
Low performance with addComment

### ISSUE THREAD

**Issue by Obbi89** [360EntSecGroup-Skylar/excelize#215]
**Description**

I'm annotating an existing Excel file by adding comments to cells that contain invalid data.
While doing so I realized that adding huge amount of comments to an excel file is extremely slow.

For comparison I set the style for a cell via conditional formating (cell value != 0). This takes about 3 seconds. Adding a comment to all these fields increases runtime to 3 minutes for the same amount of cells edited.

So the question actually is. Why does adding a comment take so much time?
Is it the duplicate serialize/deserialization needed?

And I might open another issue cause the file created is shown as containing errors and needs repairs (Excel only, Libreoffice et al. say everything is ok, but comments are missing on some of the sheets. So I guess there is an issue?)

I was confused with the api tbh.
I did this, which imho is useless: (object -> json -> object -> xml)
But I couldn't find a direct approach to just hand the object in.
```go
type xlsxComment struct {
    Author string `json:"author"`
    Text   string `json:"text"`
}

errorComment := xlsxComment{
    Author: "Linter",
    Text:   strings.Join([]string{"Wow", "much error",  "such time", "many performance"}, "\n"),
}

commentSerialized, err := json.Marshal(errorComment)
xlsx.AddComment(sheetName, cellName, string(commentSerialized))
```

**Steps to reproduce the issue:**
1. Create or open file
2. Add many comments
3. Wait

**Describe the results you received:**
see description

**Describe the results you expected:**
see description

**Output of `go version`:**

```
go version go1.10.1 linux/amd64
```

**Excelize version or commit ID:**

```
2b97c3bb463b28e3d81f714ef55798621174e0a1 (at time of writing HEAD~1)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
How many comments did you add? Excelize needs to do some checks to ensure file compatibility, that will impact on performance.

**Comment by Obbi89** [comment]
Yeah guess that solved itself.

**Comment by PRwill** [comment]
> How many comments did you add? Excelize needs to do some checks to ensure file compatibility, that will impact on performance.

>I add 5k comments, I find that the cost time of every comments will increase with the comments increase.Why this happen?

**Comment by Obbi89** [comment]
As far as I understood that the issue is the constant serialization and de-serialization needed for modifying comments.
Comments are stored in a separate file and only referenced in the column-data xml-files.
So if you add a comment, you need to find a unique reference identifier and add that reference in the column data and additionally add the comment itself to the (iirc drawings) file.

Sorry it's some time ago now. I'm trying to recall this from memory. I guess yuri can tell you more about this however.

**Comment by xuri** [comment]
Hi @Obbi89, @PRwill, I have optimized the performance of add hyperlink, please upgrade the library to the last version. Reference issue #106 and #294.

**Comment by PRwill** [comment]
Hi @Obbi89 @xuri ，sry about reply so late. I limit the amount of comment to solve this problem. because when I use the latest version, it seems working as usual .
