### ISSUE TITLE
font:family appears to be ignoring my selection

### ISSUE THREAD

**Issue by michaeli99** [360EntSecGroup-Skylar/excelize#222]
I did not see anyone asking about how font:family worked.

I have this line to set my style, but my output is always in Calibri.

```go
style, err := xlsx.NewStyle(`{"alignment":{"vertical":"top","horizontal":"left"},"font":{"bold":true,"family":"Arial","size":11}}`)
```

**Describe the results you received:**
Document was generated, but the cells have a font of Calibri.

**Describe the results you expected:**
I expected document to be in Arial

**Output of `go version`:**
```
go version go1.10 windows/amd64
```

**Excelize version or commit ID:**

```
version = "1.2.0"
revision = "6d634ca320acca28a84f25888a04c0861548d5ed"
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 7, Excel 2007

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it.

**Comment by michaeli99** [comment]
Thank you!  That worked.

Will you be issuing a new release?  or should I just pin to this revision?

**Comment by xuri** [comment]
I plan to release version 1.3.0 on next week, some features are still testing. You can pin to this revision temporarily.
