### ISSUE TITLE
time.Time format error

### ISSUE THREAD

**Issue by CrazyMouse** [360EntSecGroup-Skylar/excelize#224]
style, _ := f.NewStyle(`{"number_format": 31}`)
f.SetCellStyle(sheet, axis, axis, style)

not work for date format

**Comment by CrazyMouse** [comment]
style, _ := xlsx.NewStyle(`{"custom_number_format": "yyyy-mm-dd"}`)
f.SetCellStyle(sheet, axis, axis, style)

this code is work right

**Comment by xuri** [comment]
Thanks for your issue. Use number format code 31 need to specify the lang, use `{"number_format": 31, "lang": "zh-cn"}` instead of `{"number_format": 31}`.

**Comment by CrazyMouse** [comment]
@xuri Oh, Thanks
