### ISSUE TITLE
does SetSheetRow allow to write formulas ? 

### ISSUE THREAD

**Issue by MatthiasRMS** [360EntSecGroup-Skylar/excelize#226]
Hi,

I need to add rows to an excel sheet, which might contain formulas.
I know that I can use the dedicated function to add formulas (`SetCellFormula`), but I'd like to be able to write rows by rows instead of cell by cell. 

Is this possible with SetSheetRow ?
For example, could I write this row:
{1, 2, "A1+A2", "product_name"}

Thanks

**Comment by xuri** [comment]
Sorry for late reply. The function `SetSheetRow()` unable to know the character type element in the slice be set for character or a formula.
