### ISSUE TITLE
Follow best practices for Git commit messages

### ISSUE THREAD

**Issue by dolmen** [360EntSecGroup-Skylar/excelize#230]
@xuri Could you follow the established best pratices in Git commit messages ? That would help external contributors to follow changes happening.
https://chris.beams.io/posts/git-commit/

Commit d96440edc480976e3ec48958c68e67f7a506ad32 breaks many rules:
- many unrelated changes in a single commit
- commit messge does not follow the standard format "1 summary line + 1 empty line + details"

**Comment by dolmen** [comment]
By the way, I expect that the content of `CONTRIBUTING.md` also applies to project maintainers.
https://github.com/360EntSecGroup-Skylar/excelize/blob/master/CONTRIBUTING.md#commit-messages

**Comment by xuri** [comment]
Thanks for your suggestion, I will follow best practices in the future code commit.
