### ISSUE TITLE
Use consistent tag format for versionning

### ISSUE THREAD

**Issue by dolmen** [360EntSecGroup-Skylar/excelize#231]
We have the following tags in the repo:
- `v1.0`
- `1.1`
- `v1.2`
- `1.3`

This inconsistent naming is not helpful when upgrading dependencies references from an external project.

I propose to use semver with a "v" prefix (example: "v1.3.0") as this is the direction that the Go community is taking with the VGO proposal. https://research.swtch.com/vgo-import

**Comment by xuri** [comment]
Thanks for your issue, I have updated tags versioning for the consistent format.

**Comment by dolmen** [comment]
It looks like that tag v1.0 has disappeared (and no v1.0.0 appeared)...
