### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by rmasci** [360EntSecGroup-Skylar/excelize#232]
Just wanted to give some feedback -- sorry if this is the wrong format.  I am NOT a professional programmer by any means, but I have two programs: 1. that works to query mysql in a way that is secure for my company, and now it can excelize the data directly into excel spreadsheet.  2. TCP Port Scanner that accepts a list of 1000+hosts now can excelize the data and provide a report in Excel.   Excelize is well documented and was just easy to get working. 

Thanks!!

**Comment by xuri** [comment]
You're welcome, thanks for your using excelize library.
