### ISSUE TITLE
date.go:25:36: constant 86400000000000 overflows int for compiling 386 binary. 

### ISSUE THREAD

**Issue by shenwei356** [360EntSecGroup-Skylar/excelize#239]
**Description**

A [little bug](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/date.go#L25) as title described.  It's simple to fix by change `8.64e13` to `2147483647` or `int(^uint(0) >> 1)`

**Steps to reproduce the issue:**
```
$ GOARCH=386 go build
# github.com/360EntSecGroup-Skylar/excelize
../../../360EntSecGroup-Skylar/excelize/date.go:25:36: constant 86400000000000 overflows int
```

**Output of `go version`:**

```text
go version go1.10.3 linux/amd64
```

**Excelize version or commit ID:**

```text
37c470e  
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Fedora

**Comment by shweta2202** [comment]
Any workaround for this bug ?

**Comment by liepumartins** [comment]
Simply changing 8.64e13 to int32 max value will do no good. As 8.64e13 is number of nanoseconds in one day and changing it to anything else would mess up calculation.

However this is not the only place where int64 or float64 types are used. Would this software really be 32bit compatible if we changed only this part?

**Comment by liepumartins** [comment]
I broke it, I'm fixing it. :)
Please confirm that provided patch resolves the issue.

**Comment by shenwei356** [comment]
Thank you @liepumartins , I think this issue can be closed now.
