### ISSUE TITLE
关于单元格文字样式，如一句话分成不同的颜色大小展示

### ISSUE THREAD

**Issue by storv** [360EntSecGroup-Skylar/excelize#242]
关于单元格文字样式，如一句话分成不同的颜色大小展示

我**是**测**试的**

**Comment by xuri** [comment]
Thanks for your issue, reference issue #69, #100 and #172.

**Comment by xuri** [comment]
I close this and merge it into the issue #127 is still discussing this problem.

**Comment by xuri** [comment]
Hi @storv, sorry for my late reply. I have added rich text support for this lib, now you set cell with rich text by the [`SetCellRichText`](https://github.com/360EntSecGroup-Skylar/excelize/blob/66d0272f6af59b5f0c97a304379a795420a43e8b/cell.go#L460) function.
