### ISSUE TITLE
excelize对已经存在的xlsx文件调用NewSheet()时会可能导致与打开的xlsx文件存在相同的sheetId，用Excel 2013打开时提示错误！

### ISSUE THREAD

**Issue by blueicesir** [360EntSecGroup-Skylar/excelize#249]
用excelize打开存在的 xlsx文件（里面已经存在多个worksheet时），再次使用NewSheet函数增加新的工作表是，xl\workbook.xml原数据中可能会导致存在相同的sheetId=""数值。
例如，新增ICT_DT_SRC名称的worksheet之后，发现sheetId="14"的存在两个。Excel2013打开时提示错误。虽然可以自动修复。
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x15" xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main"><fileVersion appName="xl" lastEdited="6" lowestEdited="5" rupBuild="14420"></fileVersion><workbookPr defaultThemeVersion="124226"></workbookPr><bookViews><workbookView activeTab="9" tabRatio="814" windowHeight="7785" windowWidth="19095" xWindow="-3345" yWindow="90"></workbookView></bookViews><sheets><sheet name="通服折算率" sheetId="7" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId1"></sheet><sheet name="收入-总表" sheetId="1" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId2"></sheet><sheet name="收入-销售线" sheetId="12" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId3"></sheet><sheet name="收入-家网线" sheetId="13" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId4"></sheet><sheet name="收入-集客线" sheetId="14" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId5"></sheet><sheet name="收入-营业线" sheetId="15" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId6"></sheet><sheet name="收入-互联网线" sheetId="5" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId7"></sheet><sheet name="出帐用户数" sheetId="16" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId8"></sheet><sheet name="全成本" sheetId="17" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId9" state="hidden"></sheet><sheet name="ICT_DT_SRC" sheetId="14" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId14"></sheet></sheets><calcPr calcId="152511"></calcPr></workbook>

**Comment by xuri** [comment]
Thanks for your issue. Please provide file attachments If you can.

**Comment by blueicesir** [comment]
package main

import (
	"os"
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize"
)


func main(){
	exist_xlsx:="C:\\Temp\\test.xlsx"
	xlsx,err:=excelize.OpenFile(exist_xlsx)
	if err!=nil{
		fmt.Println(err)
		os.Exit(0)
	}

	sheet_name:="新建sheet"
	index:= xlsx.NewSheet(sheet_name)
	fmt.Println(fmt.Sprintf("NEW SHEET ID=%d",index))

	sheets_info:=xlsx.GetSheetMap()
	for s := range sheets_info{
		fmt.Println(fmt.Sprintf("%d\t%s",s,sheets_info[s]))
	}


	xlsx.SetActiveSheet(index)
	for i:=1; i<=10 ;i++ {
		xlsx.SetCellValue(sheet_name,fmt.Sprintf("A%d",i),i)
	}
	xlsx.SaveAs("C:\\Temp\\test_bad.xlsx")
}

test.xlsx是用Excel 2013生成的合法文件，test_bad.xlsx是上述代码另存的文件。
test_bad.xlsx打开时报错。

sheetId="11" 出现两次。
<sheet name="新建sheet" sheetId="11" 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x15" xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main"><fileVersion appName="xl" lastEdited="6" lowestEdited="4" rupBuild="14420"></fileVersion><workbookPr defaultThemeVersion="124226" filterPrivacy="true"></workbookPr><bookViews><workbookView activeTab="8" windowHeight="8010" windowWidth="14805" xWindow="240" yWindow="105"></workbookView></bookViews><sheets><sheet name="Sheet1" sheetId="1" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId1"></sheet><sheet name="Sheet4" sheetId="4" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId2"></sheet><sheet name="Sheet5" sheetId="5" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId3"></sheet><sheet name="Sheet6" sheetId="6" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId4"></sheet><sheet name="Sheet7" sheetId="7" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId5"></sheet><sheet name="Sheet10" sheetId="10" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId6"></sheet><sheet name="Sheet12" sheetId="12" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId7"></sheet><sheet name="Sheet11" sheetId="11" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId8"></sheet><sheet name="新建sheet" sheetId="11" xmlns:relationships="http://schemas.openxmlformats.org/officeDocument/2006/relationships" relationships:id="rId11"></sheet></sheets><calcPr calcId="122211"></calcPr></workbook>


[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2200358/test.xlsx)
[test_bad.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2200360/test_bad.xlsx)

**Comment by xuri** [comment]
I have fixed this issue. Please upgrade lib to the last version.
