### ISSUE TITLE
Cannot set name to sheets

### ISSUE THREAD

**Issue by JWo1F** [360EntSecGroup-Skylar/excelize#25]
Hi! I want to use custom names for my sheets. But I can't because it need to name "Sheet" + index.
It's critical bug, I think.

https://github.com/Luxurioust/excelize/blob/master/cell.go#L14
https://github.com/Luxurioust/excelize/blob/master/sheet.go#L22
https://github.com/Luxurioust/excelize/blob/master/sheet.go#L35

**Comment by JWo1F** [comment]
@Luxurioust how to progress?

**Comment by Luxurioust** [comment]
@JWo1F Thank you very much for your suggestion, and I think this is a bug also, I will commit for this issue as soon as possible, but I really can't give an exact completion time.

**Comment by Luxurioust** [comment]
@JWo1F I have add new function `GetSheetIndex()` to provides a method to get worksheet index by name. You can also use the `GetSheetMap()` function to get all sheets index and name map. Why not add set cell value by sheet name support for function `SetCellValue()` directly or add an new export function? I think that to find the index by worksheet name will use a lot of types of inference internally it will affect performance. Please tell me if there is a better idea.

**Comment by luca-moser** [comment]
@Luxurioust there is still a bug, the sheet name **must** be modified **after** cells were written to it, otherwhise the generated excel file is invalid.

**Comment by Luxurioust** [comment]
@luca-moser Sorry, I don't understand what you mean, could you provide file attachments or some codes?
