### ISSUE TITLE
Is it possible to import specific columns only ?

### ISSUE THREAD

**Issue by hlalibe** [360EntSecGroup-Skylar/excelize#251]
Hi,

I'm working with very large excel files and i would like to read specific columns only, not all of them, is there a workaround ?

Sorry if this exists or was already requested, i searched but found nothing.

thanks

**Comment by tomcharter365** [comment]
I would like to know if this is possible as well.

**Comment by xuri** [comment]
Hi @hlalibe, @tomcharter365, sorry for my late reply. Also reference #20, #29 and #406. I'll continue to optimize and improve performance, I will consider adding a stream R/W or flush windows to decrease memory usages, and any suggestion is welcome.
