### ISSUE TITLE
The cell color how to set? Can give a simple example?

### ISSUE THREAD

**Issue by azhengyongqin** [360EntSecGroup-Skylar/excelize#254]
### The cell color how to set? Can give a simple example?

**Comment by xuri** [comment]
Thanks for your issue. Reference [godoc.org](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStyle) or [docs reference](https://xuri.me/excelize/zh-hans/cell.html#SetCellStyle):

set a solid fill for the D7 cell named Sheet1
```go
style, err := xlsx.NewStyle(`{"fill":{"type":"pattern","color":["#E0EBF5"],"pattern":1}}`)
if err != nil {
    fmt.Println(err)
}
xlsx.SetCellStyle("Sheet1", "D7", "D7", style)
```

**Comment by azhengyongqin** [comment]
Thank you very much！

**Comment by l0rda** [comment]
@xuri how to update style instead of replace?

For example i have cell with borders and i want to fill it by color.
With xlsx.NewStyle()+ xlsx.SetCellStyle() border styles are lost.

**Comment by chachora** [comment]
@l0rda have you found the solution?

**Comment by l0rda** [comment]
@chachora switched to gooxml because there is no support

**Comment by xuri** [comment]
The new function `GetStyle` has been added from version v2.8.0. You can modify or append cell style by following steps:

- Get style index by `GetCellStyle` function
- Get the style definition by `GetStyle` function
- Modify or append style based on the style definition
- Create a new style by `NewStyle` function
- Set cells style by `SetCellStyle` function
