### ISSUE TITLE
Print Area & Export To PDF

### ISSUE THREAD

**Issue by wenyuanwy** [360EntSecGroup-Skylar/excelize#255]
Hi, has this library includes the features above (set & clear print area and export to pdf format)?
Thank you.

**Comment by xuri** [comment]
Thanks for your issue. This library support to set print properties of images and charts, but no plans to support exporting with PDF format currently.

**Comment by wenyuanwy** [comment]
thanks for the info.

**Comment by Uzer007-admin** [comment]
Действительно очень много людей, которые нуждаются в возможности импорта pdf.  Excel Обладает такой возможностью, и было бы хорошо добавить и в библиотеку. Довольно тривиально и часто встречаемая задача.
