### ISSUE TITLE
different behavior between SetRowHeight & SetColWidth

### ISSUE THREAD

**Issue by lianzhao** [360EntSecGroup-Skylar/excelize#257]
**Description**
Please refer the code below

**Steps to reproduce the issue:**
```
package main

import (
	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	xlsx := excelize.NewFile()
	xlsx.SetRowHeight("SHEET1", 1, 100)
	xlsx.SetColWidth("SHEET1", "A", "A", 100)
	xlsx.SaveAs("./Book1.xlsx")
}
```

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/536786/43725508-4b57178e-99cf-11e8-96a8-3a0c10195d1a.png)

**Describe the results you expected:**
I expected it to be a 100x100 cell

**Output of `go version`:**

```text
go version go1.9.4 darwin/amd64
```

**Excelize version or commit ID:**

```text
[[projects]]
  name = "github.com/360EntSecGroup-Skylar/excelize"
  packages = ["."]
  revision = "eb62256d165607c6877ce88efbba10c119137b3d"
  version = "v1.3.0"
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
mac os 10.12.4
![image](https://user-images.githubusercontent.com/536786/43725606-956782aa-99cf-11e8-987c-8ac85a701d68.png)

**Comment by lianzhao** [comment]
Thank you for your reply.
So... How could I format a square cell on every computer? Is it impossible?

**Comment by lianzhao** [comment]
Thank you for your reply. I've tried the code below
``` go
xlsx.SetRowHeight("SHEET1", 1, 72) // got 1 inch height row
xlsx.SetColWidth("SHEET1", "A", "A", 12) // got 1 inch width column
```
May I ask why it is 12?

**Comment by xuri** [comment]
The unit of row height in Excel for Mac is equal to pixels, but it is different in Windows, it is related to the resolution of the device.
