### ISSUE TITLE
loss of the excel style after  save with The AddPicture

### ISSUE THREAD

**Issue by LianAFei** [360EntSecGroup-Skylar/excelize#258]
**Description**

**Steps to reproduce the issue:**
1.OpenFile
2.AddPicture
3.loss of the excel style
![bug](https://user-images.githubusercontent.com/24697032/43813678-4ab59546-9af9-11e8-86ba-dfd2839afbc2.png)
![result](https://user-images.githubusercontent.com/24697032/43813705-68397448-9af9-11e8-88c4-1b0d621af310.png)

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
skipping unsupported element on Workbook {http://schemas.openxmlformats.org/markup-compatibility/2006 AlternateContent}
unsupported relationship xl/worksheets/../printerSettings/printerSettings3.bin http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings
unsupported relationship xl/worksheets/../printerSettings/printerSettings2.bin http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings
unsupported relationship xl/worksheets/../printerSettings/printerSettings1.bin http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):Win10

**Comment by xuri** [comment]
Thanks for your issue. Please provide file attachments and source code If you can.

**Comment by LianAFei** [comment]
Source code 
package Test

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

type Test struct {
	Test string
}

func (obj *Test) Excel(path string) {
	xlsx, err := excelize.OpenFile("./Test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	err = xlsx.AddPicture("土方", "A20", "./timg.jpg", `{"x_scale": 0.5, "y_scale": 0.5, "hyperlink": "#Sheet2!D8", "hyperlink_type": "Location"}`)
	if err != nil {
		fmt.Println(err)
	}
	err = xlsx.SaveAs(path)
	if err != nil {
		fmt.Println(err)
	}
}

Att
[Test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2269198/Test.xlsx)
![timg](https://user-images.githubusercontent.com/24697032/43820731-a7991dbc-9b19-11e8-976d-52d10d15bf6d.jpg)
@xuri Thank you

**Comment by xuri** [comment]
I have tested that and it works well. Please try upgrade library to the last version and provides Go version you are using.

**Comment by LianAFei** [comment]
go version go1.8 windows/amd64
@xuri

**Comment by xuri** [comment]
I have tested on Windows 7 with Go 1.8 and it works well. It seems that the file loss style contains `Sheet1` and `Sheet2`, but `Test.xlsx` in your attachment only contains one sheet. Can you provide the original file as an attachment?

**Comment by LianAFei** [comment]
It seems like The AddPicture function of excelize will loss  the excel style under The SetValue function of baliance.com/gooxml/spreadsheet.Sheet "土方" is the sheet in last Test.xlsx
[Test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2279851/Test.xlsx)

**Comment by xuri** [comment]
I have tested with `Test.xlsx` and it still works well. Note that the `gooxml` is not associated with this project.
