### ISSUE TITLE
GetCellValue() supports sheet ID not only sheet name

### ISSUE THREAD

**Issue by IIInsomnia** [360EntSecGroup-Skylar/excelize#263]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. We can use the `GetSheetMap()` function to get all sheets index and name map and use `GetCellValue()` to set the cell value.

**Comment by IIInsomnia** [comment]
OK
