### ISSUE TITLE
Write text

### ISSUE THREAD

**Issue by Davidiasdesousa** [360EntSecGroup-Skylar/excelize#269]
How i can write text with break line.

**Comment by xuri** [comment]
Thanks for your issue, reference issue #69 (set multiline texts to cells support), #100 and #172. I have added this feature request to the Roadmap.

**Comment by xuri** [comment]
I close this and merge it into issue #172 is still discussing this problem.

**Comment by xuri** [comment]
Hi @Davidiasdesousa, sorry for my late reply. I have added rich text support for this lib, now you set cell with rich text by the [`SetCellRichText`](https://github.com/360EntSecGroup-Skylar/excelize/blob/66d0272f6af59b5f0c97a304379a795420a43e8b/cell.go#L460) function.
