### ISSUE TITLE
Unprotected Cell

### ISSUE THREAD

**Issue by akbarstd** [360EntSecGroup-Skylar/excelize#273]
Hello!
I just tested to protect cell like this

```
xlsx.SetCellValue("Sheet1", "B5", "Hello world.")`

style, err := xlsx.NewStyle(`{"protection":{"locked":true}}`)
if err != nil {
    fmt.Println(err)
}
xlsx.SetCellStyle("Sheet1", "B5", "B5", style)
```
But why does that cell is unprotected?
Thank you
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2426582/test.xlsx)

**Comment by akbarstd** [comment]
Hello, any updates for this issue? @xuri

**Comment by xuri** [comment]
Hi @akbarstd, thanks for your issue. I have tested with attachment and it works well. The cell `Sheet1!B5` already locked, We can validate that by right-click on `Sheet1!B5`, select Format Cells, and click on the Protection tab. "Locked" checkbox has been already checked. The cell style of `Sheet1!B5` will not be changed if users to adjust other cells in a worksheet. Reference issue #191.

**Comment by akbarstd** [comment]
I am sorry after I read the documentation, I cant found how to protect sheet. It is possible to do that with your library? @xuri thank you

**Comment by xuri** [comment]
I have added this feature request to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki).
