### ISSUE TITLE
can’t read sheetname of some xlsx file

### ISSUE THREAD

**Issue by lab37** [360EntSecGroup-Skylar/excelize#276]
这个文件，内部的表名读不出来，是不是很奇怪，因为xml在parse的时候失败了。
[临清.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2483052/default.xlsx)

All  the versions of go can‘t read the sheetname of this file。

**Comment by xuri** [comment]
@lab37 Thanks for your issue. I have fixed it.

**Comment by lab37** [comment]
Good work！Processing is very fast。But when  I tried to read this file ,another problem arises.  The func  GetRows() return wrong code。I checked this ,it like caused by the func sharedStringsReader() in the 252 line of  row.go。byte[ss] maybe the end。
按下葫芦起来瓢，还是有点小问题。

**Comment by lab37** [comment]
ps：I get another file which may cause the Memory leak. My computer got stuck when it read this file by  excelize. Though I knew  there was some useless form in this file that made it so big，I can open it correctly by office. So I think this file should be treated as a normal document，and  the  problem should be belongs to excelize.
file:

[华润菏泽.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/2486146/default.zip)

**Comment by lab37** [comment]
@xuri That explains a lot，Thank you very much.
