### ISSUE TITLE
A public review of the revision draft of Open Packaging Conventions of OOXML (ISO/IEC 29500-2) 

### ISSUE THREAD

**Issue by murata2makoto** [360EntSecGroup-Skylar/excelize#282]
Allow me to post this issue, although it is not a bug report or feature request.  I am the convenor of an ISO committe (ISO/IEC JTC1/SC34/WG4), which maintains OOXML (ISO/IEC 29500).

We are revising Open Packaging Conventions of OOXML (ISO/IEC 29500-2) very thoroughly.  The biggest motivation for this revision is to address issues around part names, references, pack URIs, base URIs, resolution of relative references, and non-ASCII characters.  We are aware that lack of clarity in the currently published ISO/IEC 29500-2 has caused interoperability problems.

We hope that this revision helps imlementations including excelize and that it does not cause any troubles.  But we are not 100% sure.

We are thus very interested in feedbacks from you.  We have a public review and an open teleconference.  More about this, see [our wiki page](https://github.com/sc34wg4/opcRevision/wiki/Public-review-of-a-working-draft-for-the-revision-of-ISO-IEC-29500-2-(Open-Packaging-Conventions)).

Thanks!

Regards,
Makoto (ISO/IEC JTC1/SC34/WG4 convenor)

**Comment by xuri** [comment]
Hi @murata2makoto, thanks for your issue. I have submitted [feedback](https://github.com/sc34wg4/opcRevision/issues/14) about ISO/IEC 29500, ECMA-376 4th §18.3.1.63
