### ISSUE TITLE
SetCellStyle() not working on date

### ISSUE THREAD

**Issue by crosslogic** [360EntSecGroup-Skylar/excelize#283]
**Description**

I'm having trouble to parse a date in file done with LibreOffice. 
Here there is the file
[XLSX file](https://drive.google.com/open?id=1W9btCsMKLSNeWGhEjuwwh1EFzpaE1AeU)

**Steps to reproduce the issue:**

```
	xl, err := excelize.OpenFile("testdata/cheques2.xlsx")
	if err != nil {
		panic(err)
	}
	hoja := "Hoja1"

	style, _ := xl.NewStyle(`{"number_format":34}`)

	xl.SetCellStyle(hoja, "a2", "a2", style)
	xl.SetCellStyle(hoja, "a3", "a3", style)
	date1 := xl.GetCellValue(hoja, "a2")
	date2 := xl.GetCellValue(hoja, "a3")
	fmt.Printf("a1: %v\na2: %v\n", date1, date2)
```

Both dates (A2 and A3) are type date. 
1. Date in cell A2 is copied from a date from an Excel file
2. Date in cell A3 was typed directly with the keyboard

**Describe the results you received:**
```
a1: 13/07/2018
a2: 43463
```
The second one is read as a number.

**Describe the results you expected:**

**Output of `go version`:**

```text
go version go1.11 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize v1.4.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
LibreOffice
Versión: 6.1.2.1
Id. de compilación: libreoffice-6.1.2.1-snap1

**Comment by xuri** [comment]
Hi @crosslogic, thanks for your issue. Please reference issue #140 & #177.
