### ISSUE TITLE
how to flush data to file partially

### ISSUE THREAD

**Issue by conquer66666** [360EntSecGroup-Skylar/excelize#284]
how to flush data to file partially

**Comment by xuri** [comment]
Hi @conquer66666, I don't understand what you mean, please describe it in detail.

**Comment by conquer66666** [comment]
I want to write 500000 records into excel, when i called SetCellValue,i found the file size not rose until i call Save method the file size changed.How can i flush the data to file when set the cell value ?

**Comment by dolmen** [comment]
Just call `Save` every time you want to flush. Else changes only happen in the process memory.

**Comment by gypsyfeng** [comment]
> Just call `Save` every time you want to flush. Else changes only happen in the process memory.

Do you mean `Save` could keep appending new rows to the same file?

**Comment by gypsyfeng** [comment]
> Hi @conquer66666, I don't understand what you mean, please describe it in detail.

I have the same problem. If the file ends up getting really big, it would take up a lot of memory. Therefore, we all want to be able to keep appending the generated xlsx rows to a file and free up the memory.

**Comment by svnwell** [comment]
> > Hi @conquer66666, I don't understand what you mean, please describe it in detail.
> 
> I have the same problem. If the file ends up getting really big, it would take up a lot of memory. Therefore, we all want to be able to keep appending the generated xlsx rows to a file and free up the memory.

me too， 我也是

**Comment by xuri** [comment]
I have added a [stream writer](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2@v2.1.0?tab=doc#File.NewStreamWriter) for generating a new worksheet with huge amounts of data.
