### ISSUE TITLE
how to set date of struct  into cell by SetCellValue(),or other way??

### ISSUE THREAD

**Issue by Crazy-Geng** [360EntSecGroup-Skylar/excelize#286]
how to set date of struct  into cell by SetCellValue(),or other way??
i dont konw how to do it...

**Comment by xuri** [comment]
What's your date of struct? Please provide more information and refer to the instructions in Godoc for [cell style settings](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStyle).

**Comment by xuri** [comment]
I'll close this issue, please provides more details and reopen this issue.
