### ISSUE TITLE
when I use the version higher v1.1.0 to generate a XLSX file, the onlyoffice will show the error "A error accurred when open the file"

### ISSUE THREAD

**Issue by yuedefeng** [360EntSecGroup-Skylar/excelize#293]
**Description**

when I use the version higher v1.1.0 to generate a XLSX file, the onlyoffice will show the error "A error accurred when open the file"

**Steps to reproduce the issue:**
1. open a xlsx template file (temp.xlsx)
2. save as a new file (data.xlsx)
3. open it by onlyoffice (web office server)

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Hi @yuedefeng, thanks for you issue. Please use the last version of the excelize and provide file attachments if you can. Note that the excelize library doesn't guarantee compatibility with OnlyOffice currently.

**Comment by yuedefeng** [comment]
When I copy the sheet , the onlyoffice will open the file failure. I don't know why?

**Comment by Ranxiu** [comment]
> 当我复制工作表时，onlyoffice将打开文件失败。我不知道为什么？

您好 你的问题解决了吗 我也遇到了和您一样的问题

**Comment by yuedefeng** [comment]
降到1.1.0 版本

**Comment by xuri** [comment]
Hi @yuedefeng, Please refer to the issue template to fill in the information, provide the code to reproduce the problem, file attachments generated by versions 1.1.0 and 1.1.0+, that will help we analyze the problem.

**Comment by xuri** [comment]
Hi @yuedefeng it seems still not have enough info on this issue, I'll close this issue, if you have any questions, please let me know, you can still leave comments on this issue.
