### ISSUE TITLE
HyperLink Bad Performance

### ISSUE THREAD

**Issue by jorgeb12** [360EntSecGroup-Skylar/excelize#294]
**Description**
I'm generating an excel file with only 3000 rows and 15 columns. Two columns have hyperlink which I set up as in docs said. The problem is that this task is taking so long (almost 9 minutes). The problem is that If I remove the hyperlinks then everything work fine (between 10 - 15 seconds). Is there anyway that I can set hyperlinks withou the name? or convert a range of rows to hyperlinks?

**Steps to reproduce the issue:**
1. Loop 3000 items.
2. Set rows values.
3. Set hyperlink row values.

**Describe the results you received:**
2 minutes of waiting for the excel file.

**Describe the results you expected:**
Less time generating the excel.

**Output of `go version`:**
go version go1.10.1 windows/amd64
```text
(paste your output here)
```

**Excelize version or commit ID:**
1.4.0

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by dayfine** [comment]
Maybe a temporary solution: would it make sense to do the everything except hyperlink first, and then generate hyperlink actually in Excel using the HYPERLINK function?
https://support.office.com/en-us/article/hyperlink-function-333c7ce6-c5ae-4164-9c47-7de9b76f577f

**Comment by jorgeb12** [comment]
Its not a good solution, since there is more than 3000 rows. I can’t just write the links manually. For now Im just writing those links as plain text

**Comment by dayfine** [comment]
you can generate the url and the name programmatically as helper columns, and then simply pass them to the HYPERLINK and fill all the rows? That probably only take a minute.

**Comment by dolmen** [comment]
So, is this issue about the performance of the [`SetCellHyperlink`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetCellHyperLink) method?

**Comment by jorgeb12** [comment]
Yes, is about the performance about that function

**Comment by xuri** [comment]
Hi @jorgeb12, sorry for my late reply. I have optimized the performance of add hyperlink, please upgrade the library to the last version.
