### ISSUE TITLE
Open the export file in Yozo office is wrong

### ISSUE THREAD

**Issue by jouyouyun** [360EntSecGroup-Skylar/excelize#298]
**Description**

**Steps to reproduce the issue:**
1. Using the example to export a xlsx file
2. Install Yozo office
3. Open the above file by Yozo

**Describe the results you received:**
Showing wrong.

**Describe the results you expected:**
Showing normally.

**Output of `go version`:**
```text
go version go1.10.2 linux/amd64
```

**Excelize version or commit ID:**

```text
507fc5307d17194203046321534244a8fe6215ed
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: deepin 15.8
Yozo office: 7.0.1491.101ZH.S1

**Comment by xuri** [comment]
Hi @jouyouyun, the excelize library doesn't guarantee compatibility with Yozo Office currently.

**Comment by jouyouyun** [comment]
I know, thanks!
