### ISSUE TITLE
Migration to go module

### ISSUE THREAD

**Issue by wcsiu** [360EntSecGroup-Skylar/excelize#305]
**Description**
Migrate excelize to go module as go 1.11 is out.

Go project using go modules right now cannot use this project as go.mod is lacking. This project is relatively easy to migrate to go module as it is not using third party library.

**Comment by wcsiu** [comment]
I have made a pull request for it.  Feel free to have a look at it. Thank you.

**Comment by xuri** [comment]
Hi @wcsiu, thanks for your PR. I have merged it.
