### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by K4N0** [360EntSecGroup-Skylar/excelize#309]
The example does not work again in 1.11.4

**Description**

undefined excelize.createfile
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Hi @K4N0, this library has been tested on go1.11.4 and works well, please provide source code if you can.
