### ISSUE TITLE
TopLeftCell

### ISSUE THREAD

**Issue by dmp73** [360EntSecGroup-Skylar/excelize#310]
I have **undefined: excelize.TopLeftCell** error message
    xlsx.SetSheetViewOptions("Sheet1", 0, excelize.SheetViewOption(excelize.TopLeftCell("A100")))

When ZoomScale working correctly
    xlsx.SetSheetViewOptions("Sheet1", 0, excelize.SheetViewOption(excelize.ZoomScale(70)))

go version go1.11.2 windows/amd64

**Comment by xuri** [comment]
Hi @dmp73, thanks for your issue. I have fixed it. Please try to upgrade the library to the last version.
