### ISSUE TITLE
[Feature Request] Get MergeCells

### ISSUE THREAD

**Issue by sairoutine** [360EntSecGroup-Skylar/excelize#312]
**Description**
Is there any way to get MergeCells as below?

If not, I will PR.

```
xlsx, err := OpenFile("./test/Book1.xlsx")
if err != nil {
	t.Error(err)
}
xlsx.MergeCell("Sheet1", "D9", "E10")

mergeCells := xlsx.GetMergeCells("Sheet1") // New Feature
for _, m := range mergeCells {
	fmt.Println(m.Start) // output: D9
	fmt.Println(m.End) // output: E10
}
```

**Comment by xuri** [comment]
Hi @sairoutine, thanks for your issue. This library doesn't support getting all merged cells from a worksheet currently. Welcome to open a pull request for that. I suggest that also return coordinate of merged cells in the function `GetMergeCells()`

**Comment by sairoutine** [comment]
@xuri
Thanks. You mean that "coordinate of merged cells" is the string value like "D4" or "E10" ?

**Comment by xuri** [comment]
Yes, the return value of the function may like this `[][]string{"D4:E10", "cell value"}`.

**Comment by sairoutine** [comment]
Understood, thanks! I will start working.
