### ISSUE TITLE
How to set up the page as landscape?

### ISSUE THREAD

**Issue by greymanking** [360EntSecGroup-Skylar/excelize#318]
I must generate xlsx files which have more than ten columns and the page should be set as landscape to hold all the columns. I searched your source and all issues to figure out how to make it but failed. I am wondering if you guys can provide a way out. Thanks.

**Comment by xuri** [comment]
Hi @greymanking, this library doesn't support to set page orientation currently. I will add this feature later.

**Comment by greymanking** [comment]
Hi @xuri, I am wondering when you could add the page orientation setup. 坐等。

**Comment by xuri** [comment]
Hi @greymanking, excelize support set page orientation now, you can set that like this:

```go
xlsx := excelize.NewFile()
err := xlsx.SetPageLayout(
	"Sheet1",
	excelize.PageLayoutOrientation(excelize.OrientationLandscape),
)
```

**Comment by greymanking** [comment]
@xuri  It just works. Thank u guys.
