### ISSUE TITLE
 "zip: not a valid zip file"Can this error define a global variable?

### ISSUE THREAD

**Issue by Sixah** [360EntSecGroup-Skylar/excelize#327]
- Hello,I have come across such a mistake recently: "zip: not a valid zip file",this error is that the excel file is not .xlsx type, it may be another type of excel change extension is .xlsx,excelize recognition can't be this type of excel.
- Can this error define a global variable?So I can catch this particular error, and I can return a particular error to the customer.The version I used v1.3.0
- Thanks very much

**Comment by dolmen** [comment]
This error is [archive/zip.ErrFormat](https://golang.org/pkg/archive/zip/#pkg-variables), so a constant already exists to catch it.

However I think that excelize should define a local error constant to catch and wrap such zip decoding issues as a more general file format issue.

**Comment by dmint007** [comment]
Is there a fix for this?
I'm also getting `zip: not a valid zip file` on **xls** files created in Excel.

**Comment by xuri** [comment]
@dmint007 This lib doesn't support the older binary xls format currently. Also reference #44.

**Comment by ddemoss222** [comment]
I pulled `ReadZipReader(*zip)` and `zip.NewReader()` out of the `excelize.OpenReader(reader, options)` function and the `zip: not a valid zip file` error does not occur with the files I was using from LibreOffice. Is it possible there is any issue with the zip library logic excelize uses with it's package?

**Comment by ddemoss222** [comment]
Can disregard the above comments. Anyone else who runs into this issue may wish to verify that they haven't read from the file prior to executing OpenReader. Or, if they read the reader prior to calling OpenReader that they reset the reader.

**Comment by prudhvirajs** [comment]
> Can disregard the above comments. **Anyone else who runs into this issue may wish to verify that they haven't read from the file prior to executing OpenReader. Or, if they read the reader prior to calling OpenReader that they reset the reader.**

@ddemoss222 can you explain this with an example please ?
