### ISSUE TITLE
You need complying with the upstream BSD  license from tealeg/xlsx

### ISSUE THREAD

**Issue by tealeg** [360EntSecGroup-Skylar/excelize#329]
Hi, I'm t he original author of tealeg/xlsx.  The BSD 3 clause license is pretty lenient, but it does require you to reproduce my copyright statement when using my code.  I know you openly state that you use some of my code, so there's no ill intent (and really I think what you've done it awesome!), but you're actually required to include my copyright statement alongside yours in the license.

**Comment by xuri** [comment]
Hi @tealeg, thanks for your proposal, I have added tealeg/xlsx copyright statement in [README](https://github.com/360EntSecGroup-Skylar/excelize#licenses) and [LICENSE](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/LICENSE) file.

**Comment by tealeg** [comment]
Thanks @xuri.

**Comment by tealeg** [comment]
Hmmm..  my copyright statement was removed again.  In this commit: https://github.com/qax-os/excelize/commit/6afc468a025984aa1b265b0228f032c5ed881a3b

Your library is *still* a derived work and you are violating the terms of the license.
