### ISSUE TITLE
TravisCI: remove support of obsolete go versions

### ISSUE THREAD

**Issue by albenik** [360EntSecGroup-Skylar/excelize#335]
According [Go Release Policy](https://golang.org/doc/devel/release.html#policy) ("Each major Go release is supported until there are two newer major releases") go1.8 is obsolete and should been removed from TravicCI config (IMHO).

If you agree, I ready to do a PR.

**Comment by dolmen** [comment]
Why ?

**Comment by albenik** [comment]
@dolmen Do you really using unsupported versions of Go in your work?
What if in future PR will break on unsupported version? Fix PR? Or change project config without asking authors? Or spend time to communicate with authors instead of simply made a PR?
I this it will be better to avoid this with very low cost.
This issue is about consistency of project with ecosystem.
Of course it can be untouched until it breaks, or TravisCI will remove support of older version. This is also a way.

**Comment by xuri** [comment]
I suggest that to keep the Travis-CI checks for old version Go.
