### ISSUE TITLE
Hello, in my project I need to run a macro and wait for it to finish, then download the document. I have scheduled the launch of the macro to change the cell, but it works for a very long time, can I use excelize to track the cell changes, or run the macro and wait for it to complete?

### ISSUE THREAD

**Issue by Jeltopuz** [360EntSecGroup-Skylar/excelize#338]
Hello, in my project I need to run a macro and wait for it to finish, then download the document. I have scheduled the launch of the macro to change the cell, but it works for a very long time, can I use excelize to track the cell changes, or run the macro and wait for it to complete?

**Comment by dolmen** [comment]
excelize doen't allow to run macros. This request is out of the scope of this project.

You can only launch Excel to run Excel macros.
