### ISSUE TITLE
Convert xls to xlsx

### ISSUE THREAD

**Issue by AngangGuo** [360EntSecGroup-Skylar/excelize#341]
Roadmap:
Object Linking and Embedding (OLE) format support (#44)

Our company has lots of system that export the old format .xls Excel file. The ole support is the last item on the roadmap list. It's difficult for the team to implement the legacy file format support.

Is it possible to just add a command to convert the xls file to xlsx file so that we can process the file using excelize?

Thanks,
Andrew

**Comment by xuri** [comment]
Thanks for your issue. I close this and merge it into issue #44 is still discussing this feature.
