### ISSUE TITLE
GetRows not getting real value of cells with formatting

### ISSUE THREAD

**Issue by tianhai82** [360EntSecGroup-Skylar/excelize#342]
**Description**

**Steps to reproduce the issue:**
1. Open file "test.xlsx"
2. Run GetRows("Sheet1")
```
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	file, err := excelize.OpenFile("test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	rows := file.GetRows("Sheet1")
	for _, row := range rows {
		fmt.Println(row)
	}
}
```
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/2806252/test.xlsx)

**Describe the results you received:**

```
[Salary Name Age Department]
[2200220 Peter 40 Finance]
```

**Describe the results you expected:**
```
[Salary Name Age Department]
[2200220.12 Peter 40 Finance]
```

**Output of `go version`:**
```text
11.1.1
```

**Excelize version or commit ID:**
```text
1.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Hi @tianhai82, since cell `A2` has a number format set, `GetRows` will return formatted value.
