### ISSUE TITLE
Ready code for new features - Deal with columns

### ISSUE THREAD

**Issue by miguelpragier** [360EntSecGroup-Skylar/excelize#344]
I made some routines to get spreadsheet columns as follows:

```golang
fmt.Println(h.NextColumn("A",0))      // Prints "B"
	fmt.Println(h.NextColumn("A",5))      // Prints "G"
	fmt.Println(h.NextColumn("Z",0))      // Prints "AA"
	fmt.Println(h.NextColumn("A",3))      // Prints "E"
	fmt.Println(h.NextColumn("AA",0))     // Prints "AB"
	fmt.Println(h.NextColumn("AA",3))     // Prints "AE"
	fmt.Println(h.NextColumn("AZ",0))     // Prints "BA"
	fmt.Println(h.NextColumn("ZZ",0))     // Prints "AAA"
	fmt.Println(h.NextColumn("XFD",0))    // Prints ""
	fmt.Println(h.NextColumn("XFD",2))    // Prints ""
	fmt.Println(h.NextColumn("XFB",0))    // Prints "XFC"
	fmt.Println(h.NextColumn("XFB",1))    // Prints "XFD"
	fmt.Println(h.NextColumn("XFB",2))    // Prints ""
	fmt.Println(h.NextColumn("XFB",3))    // Prints ""
	fmt.Println(h.NextColumn("323",0))    // Prints ""
	fmt.Println(h.NextColumn("fsdfsd",0)) // Prints ""
	fmt.Println(h.NextColumn("fsdfsd",0)) // Prints ""
	fmt.Println(h.Columns("A",5))         // Prints "[A B C D E]"
	fmt.Println(h.Columns("XFA",6))       // Prints "[XFA XFB XFC XFD]"```
```

So, I'm offering the code for the project, if the maintainer(s) understands it as useful/handy.
Please, feel free to use and adapt.
The code is available under _the unlicense_ .

Here's the code: https://github.com/miguelpragier/SpreadsheetColumnHandler/blob/master/main.go

If the maintainers do preffer, I can PR.

My only doubt is about the quantity of columns. Is it universal among spreadsheet engines/versions?

**Comment by xuri** [comment]
Hi @miguelpragier, thanks for your issue. Excelize provides a set of functions [`TitleToNumber`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#TitleToNumber) and [`ToAlphaString`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#ToAlphaString), which can be used to convert integer and Excel table columns or to get columns based on the offset. The function `NextColumn` and their functions are duplicated, so I don't recommend adding this feature.
