### ISSUE TITLE
How to delete Data Validation?

### ISSUE THREAD

**Issue by daichirata** [360EntSecGroup-Skylar/excelize#348]
Is there a way to remove all the Data Validation from the sheet?

**Comment by xuri** [comment]
Hi @daichirata, thanks for your issue. This library not support remove Data Validation currently and I have added this feature request to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki).

**Comment by daichirata** [comment]
Thank you so much for your good work!
