### ISSUE TITLE
nil Pointer Dereference with Styles (cannot recreate)

### ISSUE THREAD

**Issue by NickDubelman** [360EntSecGroup-Skylar/excelize#355]
**Description**

I've tried to recreate this issue and wasn't able to create a minimal reproduction. 

I have an app that is having a nil pointer dereference panic when calling NewStyle. The same exact code does not have the issue on a colleague's computer (we're definitely using the same 1.4.1 code). Any help is much appreciated. I've spent a few days trying various approaches (clearing my modcache, reinstalling Go, updating my Mac OS).

The error occurs in the following block (all of the below code is from styles.go):

```go
if fs.Font != nil {
	font, _ := xml.Marshal(setFont(fs))
	s.Fonts.Count++
	s.Fonts.Font = append(s.Fonts.Font, &xlsxFont{
		Font: string(font[6 : len(font)-7]),
	})
	fontID = s.Fonts.Count - 1
}
```

At the time `s.Fonts.Count++` is called, `s.Fonts` is nil, for some reason.

`s` is initialized with the following line `s := f.stylesReader()`, and I can't quite figure out why this constructor is initializing `s.Fonts` as nil for me (but not my colleagues).

I really have no idea what is causing this issue, and when I tried to create a minimal reproduction that shows NewStyle having this memory panic, I was unable to cause the panic.

**Output of `go version`:**

```text
go version go1.12 darwin/amd64
```

**Excelize version or commit ID:**

```text
1.4.1 and have also tried later commits
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Mac OSX, Gin web app, creating xlsx file

```
runtime error: invalid memory address or nil pointer dereference
/usr/local/Cellar/go/1.12/libexec/src/runtime/panic.go:82 (0x1041c70)
	panicmem: panic(memoryError)
/usr/local/Cellar/go/1.12/libexec/src/runtime/signal_unix.go:390 (0x1041a9f)
	sigpanic: panicmem()
/Users/ndubelman/Desktop/Dev/Go/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize@v1.4.2-0.20190307082615-092f16c744c4/styles.go:1898 (0x165402e)
	(*File).NewStyle: font, _ := xml.Marshal(setFont(fs))
buildAllocationSheet.go:111 (0x16e8234)
	addBuildAllocationHeaders: style1, err := excelFile.NewStyle(`{"alignment":{"horizontal":"center"},
```

**Comment by xuri** [comment]
Thanks for your issue. Please provide the code that call the NewStyle function in your app. If you are adding style to an existing file, please provide a xlsx file attachment.

**Comment by NickDubelman** [comment]
Sorry, it is company code and when I tried to recreate it with a smaller example, I was unable to get the same issue. Feel free to close this. 

I was just curious if someone might know of an obvious reason why `s.Fonts` would be initialized as nil for me but not a coworker running the same code.
