### ISSUE TITLE
如何批量写入数据

### ISSUE THREAD

**Issue by lengrongfu** [360EntSecGroup-Skylar/excelize#364]
如果遇到一个需要写入100万行的数据，如何高效的写入？

**Comment by mlh758** [comment]
What sort of limitations are you running into with a million rows? Are you running out of memory?

**Comment by lengrongfu** [comment]
写了N久都没有写进去。

**Comment by exfly** [comment]
@lengrongfu csv, if dificute to write to excel?~

**Comment by Nisus-Liu** [comment]
请问怎么遍历二维数组, 写入Excel呀, 我看api都是要指定单元格写数据, 如 "A2", "B3".

**Comment by exfly** [comment]
```go
func axis(rowN, colN int) string {
	return excelize.ToAlphaString(colN) + strconv.Itoa(rowN+1)
}
var sheet string
for rowN :=range data{
xlsx.SetCellStyle( sheet, axis(rowNum, colNum), axis(rowNum, colNum), style)
```

**Comment by han2015** [comment]
use data slice as the third parameters of `SetSheetRow`
```
for k, v := range arrs {
    f.SetSheetRow("sheet1", fmt.Sprint("A", k+1), &[]string{v.field1,v.field2,v.field3,....v.fieldN})
}
```

**Comment by haoyutc** [comment]
SetSheetRow（）只有这一种方式吗？有木有一次插入1000行、5000行、、、

**Comment by xuri** [comment]
Please using [stream writer](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.NewStreamWriter
) for generating a new worksheet with huge amounts of data.

**Comment by zmjaction** [comment]
> ```go
> ToAlphaString
> ```

ToAlphaString 在 v2.0.0 API已经删除

**Comment by xuri** [comment]
Please using [`ColumnNumberToName`](https://pkg.go.dev/github.com/xuri/excelize/v2#ColumnNumberToName) instead of [`ToAlphaString`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize#ToAlphaString).

**Comment by CarsonSlovoka** [comment]
work for `v2.6.1`

```go
package main

import (
	"fmt"
	"github.com/xuri/excelize/v2"
	"strconv"
)

func axis(rowN, colN int) string {
	colName, err := excelize.ColumnNumberToName(colN + 1)
	if err != nil {
		panic(err)
	}
	return colName + strconv.Itoa(rowN+1)
}

func Run(datas [][]string) {
	f := excelize.NewFile()
	sheetName := "ocr"
	index := f.NewSheet(sheetName)

	for rowN := range datas {
		for colNum := range datas[rowN] {
			if err := f.SetCellValue(sheetName, axis(rowN, colNum), datas[rowN][colNum]); err != nil {
				panic(err)
			}
		}
	}

	f.SetActiveSheet(index)

	if err := f.SaveAs("my.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```

**Comment by butterfly4147** [comment]
> ```go
> a usage from https://github.com/qax-os/excelize/issues/364#issuecomment-478312887
> ```

```go
//axis(1, 1) return "A1"
func axis(rowN, colN int) string {
	return excelize.ToAlphaString(colN-1) + strconv.Itoa(rowN)
}
```
