### ISSUE TITLE
不支持xls文件?

### ISSUE THREAD

**Issue by mojocn** [360EntSecGroup-Skylar/excelize#368]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by mlh758** [comment]
This does not support the older binary xls format.

If you only need read support you could try [this library](https://github.com/extrame/xls)

**Comment by xuri** [comment]
Thanks for your issue. I close this and merge it into issue #44 is still discussing this feature.
