### ISSUE TITLE
SetCellVal before using NewSheet will destroy the excel file

### ISSUE THREAD

**Issue by exfly** [360EntSecGroup-Skylar/excelize#370]
**Description**

SetCellVal before using NewSheet will destroy the excel file

**Steps to reproduce the issue:**
1. SetCellValue to a not exist sheet before NewSheet

**Describe the results you received:**

SetCellVal before using NewSheet will destroy the excel file

**Describe the results you expected:**

Create one sheet and set some value

**Output of `go version`:**

```text
go version go1.12 darwin/amd64
```

**Excelize version or commit ID:**

```text
f0244c00161ad6372ceb1ec951f3a82c741cd46a
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

latest version fo mac

microsoft excel ver: 16.9(180116)

**Comment by xuri** [comment]
Hi @exfly, thanks for your issue. I have tested based on the following code and it works well. Could you provide the code to reproduce the issue?

Create a new file

```go
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	f := excelize.NewFile()
	f.SetCellValue("Sheet2", "A2", 1)
	f.NewSheet("Sheet2")
	err := f.SaveAs("issue_370.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}
```

Open exists file

```go
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	f,  err := excelize.OpenFile("issue_370.xlsx")
	if err != nil {
		fmt.Println(err)
	}
	f.SetCellValue("Sheet3", "A2", 1)
	f.NewSheet("Sheet3")
	err = f.SaveAs("issue_370_2.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}
```

**Comment by exfly** [comment]
mac lastest version
go version:

first code destroy the file:
```go
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	f := excelize.NewFile()
	f.SetCellValue("正", "A2", "aa")
	err := f.SaveAs("issue_370.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}
```


second code is ok:
```go
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	f := excelize.NewFile()
	f.NewSheet("正")
	f.SetCellValue("正", "A2", "aa")
	err := f.SaveAs("issue_370.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}
```

it seams that, setCellvalue has some bugs
