### ISSUE TITLE
If you insert into two or more images of multiple sheets, the images will be pasted in duplicate.

### ISSUE THREAD

**Issue by GinSanaduki** [360EntSecGroup-Skylar/excelize#373]
Create a new Excel file, insert an image into one cell of one sheet, create another sheet, insert another image into one cell of another sheet, as the result, causes a event that pasted two images on both cells of both sheets.
It doesn't occur when you finish inserted an image into one cell of a sheet, or inserted images into two or more cells of the same sheet.
```golang
func main () {
    xlsx: = excelize.NewFile ()
    // Create a worksheet
    index: = xlsx.NewSheet ("Sheet2")
    // Insert image1.jpg into A2 cell of sheet 1
    // Still okay at this point
    err: = xlsx.AddPicture ("Sheet1", "A2", "./image1.jpg", "")
    if err! = nil {
        fmt.Println (err)
        return err
    }
    // Insert image2.jpg into A20 cell of sheet 2
    // If this is executed, image1.jpg is pasted A2 cells of Sheet 1 and Sheet 2 
    // and image2.jpg is pasted A20 cells of Sheet 1 and Sheet 2.
    err: = xlsx.AddPicture ("Sheet2", "A20", "./image2.jpg", "")
    if err! = nil {
        fmt.Println (err)
        return err
    }
   // Save Excel
   err: = xlsx.SaveAs ("./Book1.xlsx")
   if err! = nil {
        fmt.Println (err)
        return err
    }
    return nil
}
```

When I extracted the Excel file and saw it, the value of the name held inside of drawing1.xml was the same (Picture 1), so it is considered to be due to that.
If SaveAS is executed first and then reopened and the image is executed only after Save is executed, the stored information will disappear or it will operate normally.
Of course, there is no problem if you insert image1.jpg into one cell of one sheet, execute SaveAS, reopen it, and insert image2.jpg into another cell of another sheet.

```golang
func main () {
    xlsx: = excelize.NewFile ()
    // Create a worksheet
    index: = xlsx.NewSheet ("Sheet2")
    // Save Excel
    err: = xlsx.SaveAs ("./Book1.xlsx")
    if err! = nil {
        fmt.Println (err)
        return err
    }
    // Reopen
    xlsx, err: = excelize.OpenFile ("./Book1.xlsx")
    if err! = nil {
         fmt.Println (err)
         return err
    }
    // Insert image1.jpg into A2 cell of sheet 1
    err: = xlsx.AddPicture ("Sheet1", "A2", "./image1.jpg", "")
    if err! = nil {
        fmt.Println (err)
        return err
    }
    // Save Excel
    err: = xlsx.Save ()
    if err! = nil {
        fmt.Println (err)
        return err
    }
    // Insert image2.jpg into A20 cell of sheet 2
    err: = xlsx.AddPicture ("Sheet2", "A20", "./image2.jpg", "")
    if err! = nil {
        fmt.Println (err)
        return err
    }
    // Save Excel
    err: = xlsx.Save ()
    if err! = nil {
        fmt.Println (err)
        return err
    }
    return nil
}
```

When this is executed, Book1.xlsx is generated in which image1.jpg is inserted into only A2 cell of sheet 1 and image2.jpg is inserted into only A20 cell of sheet 2.

**Comment by xuri** [comment]
Hi @GinSanaduki, thanks for your issue. I have tested based on your code and it works well. Which version of Excelize and Go are you using?

**Comment by GinSanaduki** [comment]
> Hi @GinSanaduki, thanks for your issue. I have tested based on your code and it works well. Which version of Excelize and Go are you using?

Hi @xurl, Thanks for the reply.
The excelize library, which I downloaded March 21, 2019, is one version before the latest commit.
When I tried with 2 windows 10, the same phenomenon occurred.
go version go1.12.1 windows/amd64

**Comment by GinSanaduki** [comment]
> Hi @GinSanaduki, thanks for your issue. I have tested based on your code and it works well. Which version of Excelize and Go are you using?

Hi @xuri , thanks for the reply.
The excelize library, which I downloaded March 21, 2019, is one version before the latest commit.
When I tried with 2 windows 10, the same phenomenon occurred.
go version go1.12.1 windows/amd64
I know what to do here for the time being, so if you don't reproduce it, let me wait and see please.
Thank you for confirmation.

**Comment by nateglims** [comment]
I see something similar with comments on `69b38ddcd6`:

```go
package main

import "github.com/360EntSecGroup-Skylar/excelize"

func main() {
	xlsx := excelize.NewFile()
	xlsx.NewSheet("Sheet2")

	err := xlsx.AddComment("Sheet1", "A1", `{"author":"Me:","text":"Comment"}`)
	if err != nil {
		panic(err)
	}

	err = xlsx.AddComment("Sheet2", "A2", `{"author":"Me:","text":"Comment"}`)
	if err != nil {
		panic(err)
	}

	err = xlsx.SaveAs("./Test.xlsx")
	if err != nil {
		panic(err)
	}
}

```

Sheet1: 
![image](https://user-images.githubusercontent.com/3642427/57541034-bdf47c00-7313-11e9-9149-3df72cef3b85.png)

Sheet2:
![image](https://user-images.githubusercontent.com/3642427/57541043-c351c680-7313-11e9-8c82-6c94e4ecb635.png)

**Comment by GinSanaduki** [comment]
I did not know that the same event would occur even with the addition of comments...thank you for providing the information.

**Comment by xuri** [comment]
Hi @nateglims @GinSanaduki,  I have fixed it, but the issues of duplicate images haven't been confirmed yet.

**Comment by GinSanaduki** [comment]
Just in case, I put the reproduction file of those days.
[Book1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3168525/Book1.xlsx)

![evi01](https://user-images.githubusercontent.com/48995370/57563871-48a1ad80-73de-11e9-8813-96c5ec136091.png)

![evi02](https://user-images.githubusercontent.com/48995370/57563872-493a4400-73de-11e9-9660-aa2c3a3b5ef7.png)

**Comment by GinSanaduki** [comment]
It did not occur with modified sources.

[Book1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3168533/Book1.xlsx)
![evi04](https://user-images.githubusercontent.com/48995370/57563939-3ffda700-73df-11e9-9bd4-31160a6b957f.png)
![evi03](https://user-images.githubusercontent.com/48995370/57563940-3ffda700-73df-11e9-8e6e-02bd1dfb42ba.png)
