### ISSUE TITLE
undefined: excelize.ToAlphaString

### ISSUE THREAD

**Issue by alexaung** [360EntSecGroup-Skylar/excelize#376]
undefined: excelize.ToAlphaString in v1.4.1

[https://github.com/360EntSecGroup-Skylar/excelize/issues/66](url)

**Comment by xuri** [comment]
Hi @alexaung, thanks for your issue. [PR #356](https://github.com/360EntSecGroup-Skylar/excelize/pull/356) removes the two functions `ToAlphaString` and `TitleToNumber`, adding 4 functions [ColumnNumberToName](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#ColumnNumberToName), [CellNameToCoordinates](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#CellNameToCoordinates), [ColumnNameToNumber](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#ColumnNameToNumber) and [CoordinatesToCellName](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#CoordinatesToCellName) to replace them. All incompatible API changes will be included in next release `v2.0.0` and prompting upgrade API compatibility for the existing users.
