### ISSUE TITLE
图表横纵坐标标签颜色太浅

### ISSUE THREAD

**Issue by zarte** [360EntSecGroup-Skylar/excelize#378]
xmlCharte.go  
1192:  
LumMod: &attrValInt{Val: 15000},  
LumOff: &attrValInt{Val: 85000},  

这里透明度定义  参考https://stackoverflow.com/questions/19886180/whats-the-difference-between-lummod-lumoff-and-tint-shade-in-drawingml-colors   

luminance = (luminance/100)*(lumMod/100_000) + (lumOff/100_000) 
根据公式修改85000->15000减小

**Comment by xuri** [comment]
Thanks for your issue. I close this and merge it into the issue #229 is still discussing this feature.

**Comment by xuri** [comment]
The `AddChart` function support custom chart axis font style since v2.7.0 (also reference issue #320).
