### ISSUE TITLE
Add a function to resize the insert image to fit the cell

### ISSUE THREAD

**Issue by yoshhiide** [360EntSecGroup-Skylar/excelize#384]
**Description**
It is a proposal of the function to implement.
I want to add the function to resize and insert an image fit to the cell.
Resize to the size of a single cell or merged cell without changing the aspect ratio of the original image.

ex.) `xlsx.AddPicture("Sheet1", "A2", "./image1.jpg", `{"autofit": true}`)`
I would like to implement such a function. What do you think?

**Comment by yoshhiide** [comment]
It is an image when the image is inserted.
<img width="364" alt="autofit_image" src="https://user-images.githubusercontent.com/8830451/56018034-f10b1600-5d3b-11e9-995e-5472395bf62e.png">

**Comment by xuri** [comment]
I resolve conflicts and perform a manual merge.
