### ISSUE TITLE
老哥，删除rows时，不够干净，win下报错

### ISSUE THREAD

**Issue by ballyang** [360EntSecGroup-Skylar/excelize#387]
编辑原有excel.xlsx，某一些行有merge格时，然后 把这行remove后，save，在win下报开，会报错。linux下没报错（libre， ubuntu18）。应该是remove rows时没把style之类信息删除。

另：能否加一个功能，从某个sheet里复制某一行到另一个sheet里？

**Comment by xuri** [comment]
Hi @ballyang, please provides the version of excelize and Go you are using, and the xlsx file attachment if you can.  Also reference #372.

**Comment by ballyang** [comment]
> Hi @ballyang, please provides the version of excelize and Go you are using, and the xlsx file attachment if you can. Also reference #372.

- env:
 - go: go version go1.11.9 linux/amd64
 - ubuntu18
 - excelize: latest，已经goget最新的下来了

- go demo
`	
tmp := "./test1.xlsx"

	t1, err := excelize.OpenFile(tmp)
	if err != nil {
		log.Fatal(err)
	}

	for x := 10; x >= 5; x-- {
		t1.RemoveRow("Sheet1", x)
	}
	t1.SaveAs("./test1.save.xlsx")
`

- excel file:
 - [test1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3102569/test1.xlsx)

- 我只是把后面那几行remove掉，但在win下打开，就会报‘Excel 已完成文件级验证和修复。此工作簿的某些部分可能已被修复或丢弃’类似错误

**Comment by xuri** [comment]
Hi @ballyang, thanks for your issue, I have fixed it.
