### ISSUE TITLE
can't open with wps on android(xiaomi8)

### ISSUE THREAD

**Issue by let-s-go** [360EntSecGroup-Skylar/excelize#392]
Create a .xlsx file by using the example code, i can open it with wps on windows, but can't open it with wps on android.
I use the lastest version.

**Comment by xuri** [comment]
Hi @let-s-go, thanks for your issue. I have fixed that and tested on `Android 8.0.0, WPS Office 11.5.5.4267f970f0-cn00571`. But note that the excelize library doesn't guarantee compatibility with WPS Office currently.

**Comment by let-s-go** [comment]
thanks very much, it's all right now.
