### ISSUE TITLE
unknown import path "github.com/360EntSecGroup-Skylar/excelize/v2"

### ISSUE THREAD

**Issue by NMFR** [360EntSecGroup-Skylar/excelize#393]
**Description**

According with the [go Modules spec](https://github.com/golang/go/wiki/Modules#user-content-releasing-modules-v2-or-higher) a module with the version v2+ (`excelize v2.0.0`) should be imported as follows:

``` go
import (
  "github.com/360EntSecGroup-Skylar/excelize/v2"
)
```

But this causes the error:

```
unknown import path "github.com/360EntSecGroup-Skylar/excelize/v2": cannot find module providing package github.com/360EntSecGroup-Skylar/excelize/v2
```

**Steps to reproduce the issue:**
1. Import the dependency `"github.com/360EntSecGroup-Skylar/excelize/v2"` in a go Module enabled project.
2. Run `go build`.

**Describe the results you received:**

Error:
```
unknown import path "github.com/360EntSecGroup-Skylar/excelize/v2": cannot find module providing package github.com/360EntSecGroup-Skylar/excelize/v2
```

**Describe the results you expected:**

Build should be successful.

**Output of `go version`:**

```text
go version go1.12.2 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.0.0
```

**Comment by NMFR** [comment]
Still not fixed, i request the issue is reopened.

I believe that in order to fix this the code needs to be moved to the package `v2` and that package needs to have a `go.mod` file.

Also the current package should serve has a proxy to the classes and functions of the `v2` package.

Full description @ [go Modules spec](https://github.com/golang/go/wiki/Modules#user-content-releasing-modules-v2-or-higher).

**Steps to reproduce the issue:**
1. In a go Module enabled project run:
``` sh
go get github.com/360EntSecGroup-Skylar/excelize/v2 
```
**Describe the results you received:**

Got the following error:
``` sh
go: github.com/360EntSecGroup-Skylar/excelize/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/360EntSecGroup-Skylar/excelize" (and .../v2/go.mod does not exist) at revision v2.0.0
go: error loading module requirements
```

**Describe the results you expected:**

`go get` should be successful.

**Comment by xuri** [comment]
Hi @NMFR, please delete go mod cache `$GOPATH/pkg/mod/cache` and try again.

**Comment by NMFR** [comment]
That fixed it, i didn't realized there wasn't a new version with the fix.

Many thxs sir @xuri :)

**Comment by NMFR** [comment]
It's working but i suspect there is still a problem: `go.mod` references `v1.4.1` indirectly:

``` go
...
go 1.12

require (
	github.com/360EntSecGroup-Skylar/excelize v1.4.1 // indirect
	github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.0
	github.com/stretchr/testify v1.3.0
)
```

I suspect this is because the `package excelize` declaration on excelize .go files doesn't include the `v2`, but i might be wrong.

**Comment by toplinuxsir** [comment]
The bug still exists , Can not install v2 
go get install  github.com/360EntSecGroup-Skylar/excelize/v2
Error can not find package !

**Comment by joaowiciuk** [comment]
The bug persists!

```
go get github.com/360EntSecGroup-Skylar/excelize/v2
[...]
go: error loading module requirements
```
Also:
```
rm -rf $GOPATH/pkg/mod/cache
get github.com/360EntSecGroup-Skylar/excelize/v2
go: error loading module requirements
```

**Comment by mlh758** [comment]
I created a new project to benchmark some changes, my main.go looks like this:

```go
package main

import (
	"fmt"
	"time"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

// some code for testing stuff...
```

my go.mod looks like this:

```go
module github.com/mlh758/benchmarker

go 1.12

require (
	github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.1
	github.com/davecgh/go-spew v1.1.1 // indirect
	golang.org/x/image v0.0.0-20190802002840-cff245a6509b // indirect
)
```

and everything is building fine. Could anyone still having issues share similar information so we can try to figure out what is wrong?

**Comment by Ankitymca** [comment]
@Xuri while writing command
 **go get https://github.com/xuri/excelize**

package https:/github.com/xuri/excelize: "https://" not allowed in import path

**Comment by xuri** [comment]
Please install with command: `go get github.com/xuri/excelize/v2`

**Comment by Ankitymca** [comment]
After writing **go get github.com/xuri/excelize/v2**

I am importing in file with path  go/src/dataproceesing/Test_xls_insert.go

I am facing this error

# cd .; git clone https://github.com/xuri/excelize /home3/indiamart/public_html/dev-personalization/go/src/github.com/xuri/excelize
fatal: could not create work tree dir '/home3/indiamart/public_html/dev-personalization/go/src/github.com/xuri/excelize'.: Permission denied
package github.com/xuri/excelize/v2: exit status 128

On my dev server

**Comment by xuri** [comment]
Which Go language version are you using? Please make sure you have been enable Go modules and you can also using GOPROXY or download the source code directory.

**Comment by Ankitymca** [comment]
go version go1.9.2 linux/amd64

**Comment by xuri** [comment]
Go language support [modules](https://go.dev/blog/using-go-modules) since version 1.11, and as [README](../../excelize#installation) says, so you should be install with `go get github.com/xuri/excelize`, please also reference minimum requirements info about Excelize library #1044.
