### ISSUE TITLE
Pivot support

### ISSUE THREAD

**Issue by tvc-dps** [360EntSecGroup-Skylar/excelize#40]
Can you please add feature:
support for pivot data source edit/change
Right now I make copy of pivot, but copy make reference to the data source, so I still required to make changes in pivot data source manually 

Also it will be great to create pivot from the code, without excel application :)

Thanks in advance

**Comment by Luxurioust** [comment]
Thanks for your issue. I have made an assessment of that. I got a similar conclusion with a [Python library](https://github.com/jmcnamara/XlsxWriter/issues/50) author, that's a difficult task to do Pivot support.

**Comment by xuri** [comment]
Hi @tvc-dps, sorry for the late reply, I have already initialized support for creating pivot table. You can create a simple pivot table by the [AddPivotTable](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.AddPivotTable) function currently.
