### ISSUE TITLE
Can not install v2

### ISSUE THREAD

**Issue by toplinuxsir** [360EntSecGroup-Skylar/excelize#401]
Can not install v2!
 go get -u  github.com/360EntSecGroup-Skylar/excelize/v2
package github.com/360EntSecGroup-Skylar/excelize/v2: cannot find package "github.com/360EntSecGroup-Skylar/excelize/v2" in any of:
	/home/user/soft/go/go/src/github.com/360EntSecGroup-Skylar/excelize/v2 (from $GOROOT)
	/home/user/soft/go/gopath/src/github.com/360EntSecGroup-Skylar/excelize/v2 (from $GOPATH

**Comment by xuri** [comment]
Hi @toplinuxsir, please reference #395, manually active module mode.
