### ISSUE TITLE
Can not install v2 on Windows 

### ISSUE THREAD

**Issue by vmpartner** [360EntSecGroup-Skylar/excelize#403]
I insert export GO111MODULE=on how says in other simmilar issue
`
$ go version
go version go1.12 windows/amd64
`  
`
$ go get github.com/360EntSecGroup-Skylar/excelize/v2
go: github.com/360EntSecGroup-Skylar/excelize/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/360EntSecGroup-Skylar/excelize" (and .../v2/go.mod does not exist) at revision v2.0.0
go: error loading module requirements
`

**Comment by vmpartner** [comment]
Resolve by delete cache ```rm -rf $GOPATH/pkg/mod/cache```

**Comment by dimm0** [comment]
After clearing cache:

```
 ✗ go get github.com/xury/excelize/v2
go: module github.com/xury/excelize/v2: git ls-remote -q origin in /Users/dimm/go/pkg/mod/cache/vcs/4d93240f6011ad16223d6a2146b479168057f1faa1b7ec636cd9f8aa6180b090: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/xury/excelize/' not found
```

MacOS

**Comment by xuri** [comment]
@dimm0 you have using incorrect Go module name, using `xuri` instead of `xury`:

```
go get github.com/xuri/excelize/v2
```
