### ISSUE TITLE
This file not reads

### ISSUE THREAD

**Issue by vmpartner** [360EntSecGroup-Skylar/excelize#404]
Please try read this file, expected 83K rows, got 0 rows
[price.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/3186850/price.zip)

**Comment by vmpartner** [comment]
Check file by tealeg/xlsx and it works

**Comment by xuri** [comment]
Hi @vmpartner, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.
