### ISSUE TITLE
Don't require UTC time

### ISSUE THREAD

**Issue by carlmjohnson** [360EntSecGroup-Skylar/excelize#409]
Excelize v2, unlike v1, requires time.Time to be UTC. I think this is a mistake because Excel has no notion of timezone, so you can't do the Right Thing, which would be to include UTC time and then format it to be the time zone of your intended audience. With v1, I just set the timezone to be EST (what my audience expects), but with v2, I have to set the timezone to EST, then copy the time over to a fake UTC time.

**Steps to reproduce the issue:**

Create a time.Time with a timezone other than UTC, and use `SetCellValue`.

**Describe the results you received:**

Received `errors.New("only UTC time expected")`.

**Describe the results you expected:**

No error.

**Excelize version or commit ID:**

v2.0.0

**Comment by dolmen** [comment]
👍 
I see no reason why the code limits Location() to be UTC.
https://github.com/360EntSecGroup-Skylar/excelize/blob/master/date.go#L35

And this change has not been mentioned in changelog for v2. So this is a bug, isn't it?

**Comment by gitdlam** [comment]
i did this as a workaround. 
```
func fixTime(t time.Time) time.Time {
	t, _ = time.ParseInLocation("2006-01-02 15:04", t.Format("2006-01-02 15:04"), time.UTC)
	return t
}
```
