### ISSUE TITLE
GetRows() panics

### ISSUE THREAD

**Issue by dictor66** [360EntSecGroup-Skylar/excelize#411]
I got panic when processing an Excel file at the following command:
	rows, _        := xlsx.GetRows(sheetName)
The same file was processed successfully before the updating of the package.
Previous version hash I used: eca66180f191ba1209e5d50859be51eec7954281 

**Steps to reproduce the issue:**
1. Try to process a simple Excel file with no fromatting
2.
3.

**Describe the results you received:**

panic error

**Describe the results you expected:**

No error

**Output of `go version`:**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x873876]

goroutine 1 [running]:
github.com/xuri/excelize.(*File).formattedValue(0xc0001ca8c0, 0x1b, 0x0, 0x0, 0x4, 0xc0004a40c0)
	/go/src/github.com/xuri/excelize/cell.go:561 +0x46
github.com/xuri/excelize.(*xlsxC).getValueFrom(0xc0001334c8, 0xc0001ca8c0, 0xc000151770, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/xuri/excelize/rows.go:322 +0x1c9
github.com/xuri/excelize.(*File).GetRows(0xc0001ca8c0, 0xc000258220, 0xb, 0xe4a652, 0x1, 0xc000027740, 0x29, 0x0)

**Excelize version or commit ID:**
623375780586cbd323dc899e17d7235ac610505f

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Windows 7
go version go1.12.4 windows/amd64

**Comment by xuri** [comment]
Hi @dictor66, I have tested and it works well at rev. eca66180f191ba1209e5d50859be51eec7954281, have you tried using the latest code on the master branch? or provide a .xlsx file attachment.

**Comment by dictor66** [comment]
Hi,

I have the problem using version: https://github.com/360EntSecGroup-Skylar/excelize/commit/623375780586cbd323dc899e17d7235ac610505f
I think this is the latest version.

**Comment by dictor66** [comment]
Hi,

please use the attached Excel and version: https://github.com/360EntSecGroup-Skylar/excelize/commit/623375780586cbd323dc899e17d7235ac610505f.




--------------------------------------------
On Tue, 5/28/19, xuri <notifications@github.com> wrote:

 Subject: Re: [360EntSecGroup-Skylar/excelize] GetRows() panics (#411)
 To: "360EntSecGroup-Skylar/excelize" <excelize@noreply.github.com>
 Cc: "dictor66" <bakterpater@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, May 28, 2019, 8:43 AM
 
 Hi @dictor66, I have
 tested and it works well at rev. eca6618,
 have you tried using the latest code on the master branch?
 or provide a .xlsx file attachment.  
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by xuri** [comment]
Hi @dictor66, I have also tested on version 623375780586cbd323dc899e17d7235ac610505f and it works well, could you upload the attachment that causes panic to reads?

**Comment by csg2008** [comment]
之前好好的，27号更新代码后也遇到这个问题，错误栈跟上面一样，环境为：WIN7 + GO 1.12.5。简单调试一下，出现问题时 styleSheet.CellXfs为nil, 而 s 为 4.应该是格式数据没有读取出来。临时加了个判断先用起来了。

**Comment by xuri** [comment]
Hi @csg2008, please send desensitized document attachments to `xuri.me _at_ gmail.com`.

**Comment by xuri** [comment]
Hi @csg2008, thanks for your feedback. I have fixed it. Please try to upgrade the library with the master branch code.
