### ISSUE TITLE
Excel corrupted after save()

### ISSUE THREAD

**Issue by valasek** [360EntSecGroup-Skylar/excelize#413]
Thank you for your great work on excelize. Reading works like a charm. But I have an issue with writing.

When I update a Cell or Add a new Sheet, excel file is corrupted.

![image](https://user-images.githubusercontent.com/1046787/58537250-d1985180-81f2-11e9-9deb-ffef3128a0df.png)

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error179160_01.xml</logFileName><summary>Errors were detected in file 'C:\Projects\Programming\go\src\github.com\valasek\excel\excel.xlsx'</summary><repairedParts><repairedPart>Repaired Part: /xl/workbook.xml part with XML error.  (Workbook) Load error. Line 2, column 0.</repairedPart></repairedParts></recoveryLog>

```

Used code:
```
// Package excel reads and checks internal timesheets
package main

import (
	"fmt"
	"os"
	"strconv"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {

	// open file
	xlsx, err := excelize.OpenFile("./excel.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// jump to last row
	lastRow := 1
	for {
		cell, _ := xlsx.GetCellValue("Timesheet", "A"+strconv.Itoa(lastRow))
		if cell != "" {
			lastRow = lastRow + 1
		} else {
			break
		}
	}

	// mock the data
	// data := [][]string{
	// 	[]string{"Stanislav Valasek", "5/17/2019", "Microsoft", "8", "Customer Improving dba name", "Standard"},
	// 	[]string{"Stanislav Valasek1", "5/17/2019", "Microsoft", "10", "Parsing legal name", "Standard"},
	// }

	xlsx.NewSheet("NewSheet1")
	// index := xlsx.GetSheetIndex("Timesheet")
	// xlsx.SetActiveSheet(index)

	// // write the data
	// for i, row := range data {
	// 	for j, value := range row {
	// 		err := xlsx.SetCellStr("Timesheet", string('A'+j)+strconv.Itoa(lastRow+i), value)
	// 		if err != nil {
	// 			fmt.Println("unable to write row to excel during update, error: ", err)
	// 			os.Exit(1)
	// 		}
	// 		fmt.Printf("written [%s, %s] = %s\n", string('A'+j), strconv.Itoa(lastRow+i), value)
	// 	}
	// }

	// save the changes
	err = xlsx.Save()
	if err != nil {
		fmt.Println("unable to save Internal timesheet, error: ", err)
		os.Exit(1)
	}

}
```

I shared a source excel directly with xuri.

go env

> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\stanislav.valasek\AppData\Local\go-build
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOOS=windows
> set GOPATH=C:\Users\stanislav.valasek\go
> set GOPROXY=
> set GORACE=
> set GOROOT=C:\SW\Go
> set GOTMPDIR=
> set GOTOOLDIR=C:\SW\Go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=C:\Projects\Programming\go\src\github.com\valasek\excel\go.mod
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\stanislav.valasek\AppData\Local\Temp\go-build252113706=/tmp/go-build -gno-record-gcc-switches

**Comment by 029vaibhav** [comment]
facing same problem

**Comment by xuri** [comment]
Hi @valasek , thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code. @029vaibhav I'm not sure the problem you're having is caused by the same cause, please provides code and file attachment if you can.

**Comment by valasek** [comment]
Hi @xuri I confirm that create new Sheet using the code above is fixed now. Tested using v2 branch. 

`require github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.1-0.20190601073747-d038ca2e9c75`

Going to test writes to cells and save.

**Comment by wrycode** [comment]
I am experiencing the same issue (I think). I have some very simple code that appears to create a corrupted Excel file:
```go
package main

import (
	"github.com/360EntSecGroup-Skylar/excelize"
	"fmt"
)

func main() {
	name := "example"
	f := excelize.NewFile()
	sheetIndex := f.NewSheet(name) // new excel sheet
	f.SetActiveSheet(sheetIndex)

	// delete original sheet
	f.DeleteSheet(f.GetSheetName(f.GetSheetIndex("Sheet1")))
	
	// write some data to spreadsheet
	for i := 1; i < 10; i++ {
		for j := 1; j < 10; j++ {
			coord, err := excelize.CoordinatesToCellName(i,j)
			if err != nil {
				fmt.Println("Trouble getting coordinates:", err)
			}
			f.SetCellInt(name, coord, i + j)			
		}
		f.SaveAs("test.xlsx")
	}
}
```
Here are screenshots of what happens when I try to open the file with Microsoft Excel:
![Screenshot2019-10-21-194931](https://user-images.githubusercontent.com/34693012/67251324-c1e90600-f43c-11e9-9a51-9a9c1cfb8cc8.png)
![Screenshot2019-10-21-195238](https://user-images.githubusercontent.com/34693012/67251331-c7dee700-f43c-11e9-8f96-6f58ea716eb2.png)

[Here](https://gist.githubusercontent.com/wrycode/9b1c6c7283065b0f986d810fe8e9d1ac/raw/4510eb44d16db6050dad8106ee1e0e96551c1290/error084520_01.xml) is the log file it gives me. 

Is there something wrong with my code? Or anything I can do to help get this fixed? The output file seems to be correct in Excel but I don't want my clients to have to click through those error messages. Thanks in advance!!

**Comment by xuri** [comment]
Hi @wrycode, thanks for your issue. I will fix it recently. FYI: If you just want to change the default workbook name, you can use `SetSheetName` without deleting it.

**Comment by xuri** [comment]
Hi @wrycode, I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by wrycode** [comment]
@xuri thanks for both the tip and the fix! The issue is gone. Thank you very much!
