### ISSUE TITLE
Feature - Edit File Properties

### ISSUE THREAD

**Issue by Augl** [360EntSecGroup-Skylar/excelize#415]
Hi, thank you very much for this great library.
I would like to edit the file properties as for example the author, title, subject and so on.
The files created by the program have the following properties as shown in this Windows detail view screenshot:
![Unbenannt](https://user-images.githubusercontent.com/26324160/58724984-44b1eb80-83de-11e9-997c-635d25c254ef.PNG)
It would be great if I could change those properties.

**Comment by xuri** [comment]
Hi @Augl, thanks for your issue. I have to init set and get doc properties support.

**Comment by Augl** [comment]
Works like a charm! Thanks

**Comment by mirusky** [comment]
What about custom properties ? There is a way do do that ?
