### ISSUE TITLE
Hide sheet does not work

### ISSUE THREAD

**Issue by OFAH** [360EntSecGroup-Skylar/excelize#418]
Hello all. Thank you for your work.
I have noticed that err := f.SetSheetVisible("Sheet1", false) does not work. Here is code:

package main

import (
    "fmt"

    "github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
    f := excelize.NewFile()
    // Create a new sheet.
    index := f.NewSheet("Sheet2")
    // Set value of a cell.
    f.SetCellValue("Sheet2", "A2", "Hello world.")
    f.SetCellValue("Sheet1", "B2", 100)
    // Set active sheet of the workbook.
    f.SetActiveSheet(index)
	// Save xlsx file by the given path.
	err := f.SetSheetVisible("Sheet1", false)
    err = f.SaveAs("./Book1.xlsx")
    if err != nil {
        fmt.Println(err)
    }
}

**Comment by xuri** [comment]
Hi @OFAH, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.
