### ISSUE TITLE
Getting blank sheet

### ISSUE THREAD

**Issue by OFAH** [360EntSecGroup-Skylar/excelize#419]
Hello all, I am using excelize for a long time, and I have noticed that I am getting blank sheet (blank file). 
It is happening on all OS platforms. 
Issue happens randomly, if i start same export of data once it can be filled, once I get empty sheet. 
It can happen that I have blank once in 1000 or so. 
After hard testing I have spotted that part which is causing this issue is in f.DeleteSheet("Sheet1")
I am calling this function before I use SaveAs. Before that I have tracked data, and xlsx file should be populated, but excelize saves empty file.

**Comment by xuri** [comment]
Hi @OFAH, thanks for your feedback, please provides test code, file attachment and environment information if you can.

**Comment by OFAH** [comment]
Hi @xuri, I can not provide you my code because of ISO. 
But I will try to create same test code as I use. I build go file on Ubuntu 16.04.5 LTS, and GO version is is: go1.10.4 linux/amd64.

**Comment by OFAH** [comment]
This issue is solved now. I have pulled latest version, and it is all ok now.
