### ISSUE TITLE
Lost bold style formatting

### ISSUE THREAD

**Issue by dmp73** [360EntSecGroup-Skylar/excelize#420]
Today I have updated excelize (previous update was 2 or 3 month ago).
After that appeared problem with lost **bold** formatting on text in cells.

Open file in Excel, make some cells **bold**, save file.
Than, open and save file by Excelize, open again in Excel and all cells is not bold.

**Comment by xuri** [comment]
Hi @dmp73, thanks for your feedback. I have fixed it. Please try to upgrade the library with the master branch code.
