### ISSUE TITLE
broke xlsx file when InsertRow

### ISSUE THREAD

**Issue by dmp73** [360EntSecGroup-Skylar/excelize#421]
Excelize broke xlsx file when InsertRow and sheet contain some summarized cells.
For example

     A
1   1
2   2
3   3
4   4
5   5
6   15

Sum in cell A6.
xlsx.InsertRow("Sheet1", 2) and as result file is broken.

**Comment by xuri** [comment]
HI @dmp73, thanks for your issue. Use this method with caution, which will affect changes in references such as formulas, charts, and so on. If there is any referenced value of the worksheet, it will cause a file error when you open it. The excelize only partially updates these references currently. I will add formula adjust support for this function later.

**Comment by xuri** [comment]
Hi @dmp73, I have fixed it. Please try to upgrade the library with the master branch code.
