### ISSUE TITLE
Hide sheet does not work with Open Office (cross platform bug)

### ISSUE THREAD

**Issue by OFAH** [360EntSecGroup-Skylar/excelize#423]
Hello, I have reported bug with f.SetSheetVisible function. Fix 418 is working for Microsoft office, but issue remains in Open Office.

Test code: 

package main

import (
    "fmt"

    "github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
    f := excelize.NewFile()
    // Create a new sheet.
    index := f.NewSheet("Sheet2")
    // Set value of a cell.
    f.SetCellValue("Sheet2", "A2", "Hello world.")
    f.SetCellValue("Sheet1", "B2", 100)
    // Set active sheet of the workbook.
    f.SetActiveSheet(index)
	// Save xlsx file by the given path.
	err := f.SetSheetVisible("Sheet1", false)
    err = f.SaveAs("./Book1.xlsx")
    if err != nil {
        fmt.Println(err)
    }
}

**Comment by xuri** [comment]
I have tested on `Apache OpenOffice 4.1.6 Build: 9790 Rev. 1844436`. this issue also occurred when using Apache OpenOffice open that file created by Microsoft Office Excel&trade; application. Apache OpenOffice will not hide worksheet when the first sheet element in the sheets of the `workbook.xml` in a hidden state. We need to adjust workbook view settings and worksheets orders in the `workbook.xml` to ensure compatibility with other spreadsheet software, such as Apache OpenOffice&trade;. When the first `sheet` in the `sheets` in a `hidden` state, swap it with the first unhidden sheet, and the `activeTab` in `workbookView` should be recalculated at the same time, for example:

```xml
   <bookViews>
       <workbookView activeTab="2"></workbookView>
   </bookViews>
   <sheets>
       <sheet name="Sheet1" sheetId="1" r:id="rId1" state="hidden"></sheet>
       <sheet name="Sheet2" sheetId="2" r:id="rId4" state="hidden"></sheet>
       <sheet name="Sheet3" sheetId="3" r:id="rId5"></sheet>
   </sheets>
```

to

```xml
   <bookViews>
       <workbookView activeTab="0"></workbookView>
   </bookViews>
   <sheets>
       <sheet name="Sheet3" sheetId="3" r:id="rId5"></sheet>
       <sheet name="Sheet1" sheetId="1" r:id="rId1" state="hidden"></sheet>
       <sheet name="Sheet2" sheetId="2" r:id="rId4" state="hidden"></sheet>
   </sheets>
```
But this modification will break the original sheet order. When you use the SetSheetVisible method to set the worksheet to be visible back again, the worksheet order will be inconsistent. So I decide don't to fix this issue. User should be avoided to set the first worksheet to a hidden state.
