### ISSUE TITLE
RemoveRow with merged cells will cause the next row which originally does not contain merged cells to have merged cells

### ISSUE THREAD

**Issue by tianhai82** [360EntSecGroup-Skylar/excelize#424]
I have a spreadsheet with merged cells on row 1 (F1:H1). 
After I call `file.RemoveRow("Sheet1",1)`, the new row 1 which originally does not contain any merged cells will have F1:H1 merged.
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3271500/test.xlsx)
```
	file, err := excelize.OpenFile("test.xlsx")
	file.RemoveRow("Sheet1", 1)
	file.SaveAs("out.xlsx")
```

**Output of `go version`:**
go version go1.12.1 windows/amd64

**Excelize version or commit ID:**
2.0

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10, Excel 2016

**Comment by xuri** [comment]
HI @tianhai82, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.
