### ISSUE TITLE
When set cell font with SetCellStyle function, added forcibly bold and italic qualified.

### ISSUE THREAD

**Issue by GinSanaduki** [360EntSecGroup-Skylar/excelize#425]
Case 1:
You should only change the font to "Yu Gothic", but bold and italic are valid.
The same event occurs regardless of the font setting.
```
// Case01.go
package main

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	f := excelize.NewFile();
	style, err := f.NewStyle(`{"font":{"family":"Yu Gothic"}}`);
	if err != nil {
		fmt.Println(err);
	}
	f.SetCellStyle("Sheet1", "A2", "A2", style);
	f.SetCellValue("Sheet1", "A2", "Hello world.");
	f.SaveAs("./Book_Case01.xlsx");
}
```

![case01](https://user-images.githubusercontent.com/48995370/59281062-9c373d80-8ca1-11e9-83be-4571c532f34c.png)

[Book_Case01.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3277007/Book_Case01.xlsx)

・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・

Case 2:
You change the font to "Yu Gothic" and set the bool values of "bold" and "italic" to false, but bold and italic are valid.
```
// Case02.go
package main

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	f := excelize.NewFile();
	style, err := f.NewStyle(`{"font":{"bold":false,"italic":false,"family":"Yu Gothic"}}`);
	if err != nil {
		fmt.Println(err);
	}
	f.SetCellStyle("Sheet1", "B3", "B3", style);
	f.SetCellValue("Sheet1", "B3", "Hello world.");
	f.SaveAs("./Book_Case02.xlsx");
}
```

![case02](https://user-images.githubusercontent.com/48995370/59281049-95a8c600-8ca1-11e9-8db7-a420c583ecf8.png)

[Book_Case02.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3277006/Book_Case02.xlsx)

・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・・

I checked the test code and found that the values set for bold and italic were tested with only "true", so I'm concerned that I can't confirm what happens in the case of "false".

Output of go version:
go version go1.12.1 windows/amd64

Excelize version or commit ID:
2.0.1

Environment details (OS, Microsoft Excel™ version, physical, etc.):
Windows 10, Excel 2016, Excel 2013.

**Comment by xuri** [comment]
Hi @GinSanaduki, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by GinSanaduki** [comment]
Hi @xuri, thanks for reply.
I'm done checking the fix. It's working properly.
![case02](https://user-images.githubusercontent.com/48995370/59434280-31fbd580-8e26-11e9-8186-66afa3fcfbcd.png)
![case01](https://user-images.githubusercontent.com/48995370/59434281-31fbd580-8e26-11e9-8cae-26c57c3459a4.png)
