### ISSUE TITLE
Saving excel file makes it corrupt

### ISSUE THREAD

**Issue by RajatBanerjee** [360EntSecGroup-Skylar/excelize#426]
**Description**
If you try to open and save an excel file, which has formatterd\colored\cell borders, it corrupts the file
`xlsx, err := excelize.OpenFile("./Book1.xlsx")`
`	if err != nil {`
		`fmt.Println(err)`
		`return`
	`}`
`err = xlsx.Save()`
	`if err != nil {`
		`fmt.Println("unable to save Internal timesheet, error: ", err)`
		`os.Exit(1)`
	`}`
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
go version go1.12.5 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.1-0.20190601073747-d038ca2e9c75
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Mac OS
Excel for mac 16.13

**Comment by xuri** [comment]
Hi @RajatBanerjee, thanks for your feedback, could you upload the .xlsx attachment?

**Comment by RajatBanerjee** [comment]
I can't upload the actual attachment since it has some confidential data, but it happens for any excel file, so let me recreate the scenario with a regular file and upload that.

**Comment by dennisfleischmann** [comment]
@RajatBanerjee Hi RajatBanerjee, is the problem still there? We have issues while doing a small change in our excel (xlms) sheet using intensly activex controls and macros. The exel activeX control informations are lost afterwards.

**Comment by xuri** [comment]
Hi @dennisfleischmann, please provide code and file attachment to reproduce this issue if you can.

**Comment by muhrifqii** [comment]
I had the exact same problem too. Opened excel with formatterd\colored\cell borders, and also formulas that referenced across sheets

**Comment by xuri** [comment]
@muhrifqii could you provide code and file attachment to reproduce this issue?

**Comment by muhrifqii** [comment]
@xuri the code just open the file then save it, exactly like @RajatBanerjee code . It contains some credential data, could you please send

**Comment by xuri** [comment]
You can send me the file with credential data masking. `xuri.me[at]gmail.com`

**Comment by xuri** [comment]
Hi @muhrifqii, thanks for your feedback. I have fixed it. Please try to upgrade the library with the master branch code. I'm not sure if this fix will work for the issue you mentioned by @RajatBanerjee.

**Comment by muhrifqii** [comment]
Thanks @xuri I tested on master branch and it fixed the issue
