### ISSUE TITLE
cell内存在换行时读取异常

### ISSUE THREAD

**Issue by mickel917** [360EntSecGroup-Skylar/excelize#427]
一个cell内的如果存在多行数据时，读取cell数据时只会返回第一行的数据，换行后的数据都会丢失

本地开发环境是
mac 10.14  
go 1.11
引用的库是
github.com/360EntSecGroup-Skylar/excelize

**Comment by xuri** [comment]
Hi @mickel917, thanks for your feedback, I have tested and it works well at master version code, please provides code and file attachment if you can.

**Comment by mickel917** [comment]
@xuri 抱歉，是我使用有问题
