### ISSUE TITLE
Creating font style with italic:false results style with italic font

### ISSUE THREAD

**Issue by OFAH** [360EntSecGroup-Skylar/excelize#429]
Hello all,
I have pulled latest Excelize code, but now this error appeared in some of latest updates. 

When I create new style, and I tell NewStyle function that I do not want my font to be italic, I still get style with italic font and my cells get italic. 

Here is code for test: 

package main

import (
    "fmt"
    "github.com/360EntSecGroup-Skylar/excelize"
)

func main() {

	f := excelize.NewFile() // create new file option

	categories := map[string]string{"A2": "Small", "A3": "Normal", "A4": "Large", "B1": "Apple", "C1": "Orange", "D1": "Pear"}
    values := map[string]int{"B2": 2, "C2": 3, "D2": 3, "B3": 5, "C3": 2, "D3": 4, "B4": 6, "C4": 7, "D4": 8}

	for k, v := range categories {
        f.SetCellValue("Sheet1", k, v)
	}

    for k, v := range values {
        f.SetCellValue("Sheet1", k, v)
	}
	// CREATING STYLE WITH ITALIC: FALSE
	style, err := f.NewStyle(`{"alignment":{"horizontal":"center", "vertical":"center", "wrap_text":false, "indent":0, "justify_last_line":false, "shrink_to_fit":false, "text_rotation":0}, "font":{"size":11, "name":"Calibri", "bold":true, "underline":"", "italic":false, "family":"", "color":"#ffffff"}, "fill":{"type":"pattern", "color":["#00c5ff"], "pattern":1}}
	`)
	err = f.SetCellStyle("Sheet1", "A1", "D1", style)

    err = f.SaveAs("./Book1.xlsx")
    if err != nil {
        fmt.Println(err)
    }
}

Result:

<a href='https://postimg.cc/LqXGCCbM' target='_blank'><img src='https://i.postimg.cc/LqXGCCbM/Screen-Shot-2019-06-19-at-11-18-34.png' border='0' alt='Screen-Shot-2019-06-19-at-11-18-34'/></a>

Thank you all :)

**Comment by xuri** [comment]
Hi @OFAH, thanks for your feedback, I have tested by your code and it works well on Microsoft Excel&trade;, which application are you using?

**Comment by OFAH** [comment]
@xuri I am getting this issue both on MS office (I will ask for version) and on Open office. 
Here is Open office info:
<a href='https://postimg.cc/JyRXcfDX' target='_blank'><img src='https://i.postimg.cc/JyRXcfDX/Screen-Shot-2019-06-21-at-21-52-54.png' border='0' alt='Screen-Shot-2019-06-21-at-21-52-54'/></a>

**Comment by xuri** [comment]
I have tested with [23c73ab](https://github.com/360EntSecGroup-Skylar/excelize/tree/23c73ab527731f9d414e81f7ea15e2ae1a72a290) and it works well with Apache OpenOffice 4.1.7, I close this issue and welcome left comments if you have any more questions.

**Comment by iamyeka** [comment]
@xuri found the same problem in the application shown below.

![image](https://user-images.githubusercontent.com/22488212/190128379-b5421147-935a-402c-8aa4-936be4b31100.png)

**Comment by iamyeka** [comment]
@xuri 
Excelize version: v2.5.0
Golang version: 1.17

main func like this:
```golang
func main() {
	f := excelize.NewFile()
	_ = f.SetColWidth("Sheet1", "A", "C", 40)
        // Theoretically the italic of font is false by default, so i don't configure it explicitly.
       style, _ := f.NewStyle(&excelize.Style{
		Alignment: &excelize.Alignment{
			Horizontal:      "center",
			Indent:          1,
			JustifyLastLine: true,
			ReadingOrder:    0,
			RelativeIndent:  1,
			ShrinkToFit:     true,
			TextRotation:    45,
			Vertical:        "",
			WrapText:        true,
		},
	})
	_ = f.SetColStyle("Sheet1", "A:E", style)
	_ = f.SetColWidth("Sheet1", "A", "E", 50)
	_ = f.SetCellValue("Sheet1", "A1", "Pod")
	_ = f.SetCellValue("Sheet1", "B1", "Cluster")
	_ = f.SetCellValue("Sheet1", "C1", "Application")
	_ = f.SetCellValue("Sheet1", "D1", "Duration(seconds)")
	_ = f.SetCellValue("Sheet1", "E1", "Env")

	if err := f.SaveAs("demo.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```

The demo.xlsx content is like below:
![image](https://user-images.githubusercontent.com/22488212/190143752-8c6be8fa-0584-4787-abf9-de36f057e342.png)

The problem keeps existing after upgrading to v2.6.1 of excelize.

**Comment by xuri** [comment]
I have tested your code under v2.5.0 and v2.6.1, and it works well. Note that the rotation and italic were two kinds of different properties. Did you mean that remove rotation? If that, please remove the `TextRotation` field in the style.
