### ISSUE TITLE
Sheet options: Zoom, FitToPagesWide, FitToPagesTall

### ISSUE THREAD

**Issue by veliev** [360EntSecGroup-Skylar/excelize#432]
Tell me, is it possible to change the parameters of the sheet? Such as Zoom, FitToPagesWide, FitToPagesTall?

**Comment by xuri** [comment]
Hi @veliev, thanks for your issue. You can set zoom scale by [`SetSheetViewOptions`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetSheetViewOptions) currently, and I will add FitToPagesWide/Tall support for it later.
