### ISSUE TITLE
Missing text value of comments

### ISSUE THREAD

**Issue by gitarte** [360EntSecGroup-Skylar/excelize#434]
**Description**
Method `GetComments()` does not return text value of the comments. It returns only addresses of the cells that have comments

**Steps to reproduce the issue:**
```
// load spreadsheet from file
wb, err := excelize.OpenFile(filePath)
if err != nil {
    return result, errors.Wrapf(err, "cannot open spreadsheet %s", filePath)
}

// just printf available comments
fmt.Printf("%+v \n", wb.GetComments())

```
**Example results:**
```
map[
    Sheet1:[
        {Author: AuthorID:0 Ref:I3 Text:} 
        {Author: AuthorID:0 Ref:K3 Text:} 
        {Author: AuthorID:0 Ref:M3 Text:} 
    ]
]
```

**Example of results I expected:**
```
map[
    Sheet1:[
        {Author: AuthorID:0 Ref:I3 Text: some comment text 1} 
        {Author: AuthorID:0 Ref:K3 Text: some comment text 2} 
        {Author: AuthorID:0 Ref:M3 Text: some comment text 3} 
    ]
]
```

**Output of `go version`:**
```text
go version go1.12 darwin/amd64
```

**Excelize version or commit ID:**
Behaves the same in
```text
"github.com/360EntSecGroup-Skylar/excelize"
```
as in
```text
"github.com/360EntSecGroup-Skylar/excelize/v2"
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Mac OSX
[issue-example.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3372804/issue-example.xlsx)

**Comment by xuri** [comment]
Hi @gitarte, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.
