### ISSUE TITLE
获取yyyy/m/dd日期格式

### ISSUE THREAD

**Issue by HarryWang29** [360EntSecGroup-Skylar/excelize#435]
Excel中设置的格式为日期格式，时间为：`1976/9/24`，format如下图：
![image](https://user-images.githubusercontent.com/22442121/61030317-b6bf1c80-a3ef-11e9-8535-757799daa439.png)

代码中，使用`GetRows`获取表内容，查看获取到的值为`09-24-76`，其实已经获取到了日期格式，我通过time包可以进行解析然后再执行重组，但是这个76，通过time包重组后，会自动变成2076年

如何获得yyyy格式的年份？

**Comment by xuri** [comment]
Hi @HarryWang29, thanks for your feedback. Please provide code and file attachment if you can.

**Comment by HarryWang29** [comment]
code is simple, like this:
```
fp, err := excelize.OpenFile("./Book1.xlsx")
	if err != nil {
		return
	}
	//这个方法会获得02-03-76
	cell, err := fp.GetCellValue("Sheet1", "A1")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(cell)
	//这个方法同样会获得02-03-76
	rows, err := fp.GetRows(fp.GetSheetName(1))
	if err != nil {
		return
	}
	fmt.Println(rows[0][0])
```

file like this:
[Book1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3395615/Book1.xlsx)

**Comment by xuri** [comment]
Hi @HarryWang29, the [build-in number format](https://xuri.me/excelize/en/style.html#number_format) index used by the `A1` cell in the worksheet is `14`. The result obtained by your code is consistent with what the Office Excel&trade; application opens to display this spreadsheet file. You can use `NewStyle` and `SetCellStyle` to [modify the number format of the cell](https://xuri.me/excelize/en/cell.html#SetCellStyle) as needed, but this will also affect the display of the spreadsheet in the Office Excel&trade; application.

**Comment by HarryWang29** [comment]
allright
At last, I use the way of #336 . I copy `timeFromExcelTime` to my code in order to get `Time.time`
