### ISSUE TITLE
GetRows return 1 value

### ISSUE THREAD

**Issue by KylinGu** [360EntSecGroup-Skylar/excelize#441]
**Description**
We met GetRows return 1 value, no error return. it will report error when running.

**Steps to reproduce the issue:**
1. 
`f, err := excelize.OpenFile(filePath)`
2.
`rows, err := f.GetRows("所有标准问题")`
3.
Run

**Describe the results you received:**
It will report like this:
> ./tts_script.go:41:12: assignment mismatch: 2 variables but f.GetRows returns 1 values

**Describe the results you expected:**

**Output of `go version`:**

```
go version go1.12.5 darwin/amd64
```

**Excelize version or commit ID:**

```text
latest v2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xzbbsuir** [comment]
Hello, man，Have you solved the problem now？
I have the same problem as you.
