### ISSUE TITLE
Can't read "Protected View" content

### ISSUE THREAD

**Issue by AngangGuo** [360EntSecGroup-Skylar/excelize#442]
When I download Excel file from Internet, the content of the Excel file can't be read out from exclize program.
If I open the Excel file and click on the Enable Edit button and save it, the content can be read out from exclize program.

How can I Enable Edit or remove the Protected View using exclize?
```
Windows 10;
C:\Temp\a>type go.mod
module a

go 1.12

require github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.1
```
[User Metrics.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/3424448/User.Metrics.zip)

**Comment by xuri** [comment]
Hi @AngangGuo, thanks for your feedback. This issue has been fixed. Please try to upgrade the library with the master branch code.

**Comment by AngangGuo** [comment]
It works well. Thanks for the quick fix.
