### ISSUE TITLE
Save In a Loop cannot SetCellValue success or occur corrupted

### ISSUE THREAD

**Issue by GZLHZ** [360EntSecGroup-Skylar/excelize#443]
**Description**

func SetValueTest() {
    // Open Book1 Excel
    f, err := excelize.OpenFile("./Book1.xlsx")
    if err != nil {
        Println(err)
        return
    }

    for i := 0; i < 10; i++ {
        f.SetCellValue("Sheet1", fmt.Sprint("A", i + 1), i)
        f.Save()
    }
}

Excute SetValueTest can reappeare the bug.

**Steps to reproduce the issue:**
1.Create Book1 excel and write a num on D3
2.Excute SetValueTest
3.You can see A3 is empty
![QQ图片20190724175838](https://user-images.githubusercontent.com/45257277/61784673-b3d71980-ae3c-11e9-805f-020f004d7bfc.png)

if I save after loop, the problem does not exit

for i := 0; i < 10; i++ {
        f.SetCellValue("Sheet1", fmt.Sprint("A", i + 1), i)
    }

f.Save()

**Output of `go version`:**
go1.12.7.windows-amd64

**Excelize version or commit ID:**
2.0.1 & update to (2019.07.22)

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
win10 1903
office 2019 1906

**Comment by xuri** [comment]
Hi @GZLHZ, thanks for your feedback. This issue has been fixed. Please try to upgrade the library with the master branch code, but I don't recommend calling the `Save()` method in the iteration, which will cause more heap memory allocated.

**Comment by GZLHZ** [comment]
> Hi @GZLHZ, thanks for your feedback. This issue has been fixed. Please try to upgrade the library with the master branch code, but I don't recommend calling the Save() method in the iteration, which will cause more heap memory allocated.

Ok, Thank you. I know that is not a good save way ,I just try it when I learning how to use and report to you.😁  Excelize is a very good project, thank you for create this
