### ISSUE TITLE
How to get number of current row

### ISSUE THREAD

**Issue by yyzh999** [360EntSecGroup-Skylar/excelize#445]
rows, err := file.Rows(sheetName)
	if err != nil {
		return "", errors.Wrap(err, "xlsx get row iterator failed")
	}
	for rows.Next() {
		row, err := rows.Columns()
               // How to get number of this row ?? 
	}

**Comment by dolmen** [comment]
```go
rowNum := 1
for rows.Next() {
	fmt.Println(rowNum)
	row, err := rows.Columns()
	rowNum++
}
```

**Comment by mlh758** [comment]
When the sheet is opened for reading this library fills out the row list to be contiguous so you can rely on @dolmen's sample to be correct.
