### ISSUE TITLE
prepareSheetXML does not append enough rows under multiple goroutines

### ISSUE THREAD

**Issue by landrisek** [360EntSecGroup-Skylar/excelize#446]
**Description**
main() {
&nbsp;&nbsp;&nbsp;&nbsp;var offsetChannel chan int
&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;file := excelize.NewFile()
&nbsp;&nbsp;&nbsp;&nbsp;defer file.SaveAs("MyFile.xlsx")
&nbsp;&nbsp;&nbsp;&nbsp;var group sync.WaitGroup
&nbsp;&nbsp;&nbsp;&nbsp;jobsPerRoutine := 2
 &nbsp;&nbsp;&nbsp;&nbsp;for jobs > 0 {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;group.Add(1)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if jobsPerRoutine > jobs {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;go write(file, &group, jobs, offsetChannel)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;go write(file, &group, jobsPerRoutine, offsetChannel)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;jobs = jobs - jobsPerRoutine
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;group.Wait()
}
func write(file *excelize.File, group *sync.WaitGroup, jobs int, offsetChannel chan int) {
&nbsp;&nbsp;&nbsp;&nbsp;defer group.Done()
&nbsp;&nbsp;&nbsp;&nbsp;job := 0
&nbsp;&nbsp;&nbsp;&nbsp;for job < jobs {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;select {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case offset := <-offsetChannel:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows := AsyncFetchWithOfffset(offset)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var id int64
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var date *time.Time
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var price float32
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for rows.Next() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;err := rows.Scan(&id, &date, &price)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ProccessError(err)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file.SetCellValue("Sheet1", "A" + strconv.Itoa(offset + 1), strconv.FormatInt(id, 10))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset++
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows.Close()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;job++
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fmt.Println("no message received")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
}
**Steps to reproduce the issue:**
I see function prepareSheetXML(xlsx *xlsxWorksheet, col int, row int) as logic which should provide enough size for xlsx.SheetData.Row, so this indexing "rowData := &xlsx.SheetData.Row[row-1]" will never fail. 
However in following example it will fails: 
1. I create more parallel goroutines where each of them know in exactly which row should set values in cell but order of their writing to file is unpredictible on purpose
2) for statement inside prepareSheetXML function does not fill all rows in time and panic
**Describe the results you received:**
panic: runtime error: index out of range
**Describe the results you expected:**
no panic

**Suggested solution (tested, I can do pull request, if it is reasonable):**
1) If we will follow the rule "leaves solution of paralelism to users of library", I would suggest option to create size of xlsx.SheetData.Row by myself outside of excelize package. First I thought it is InsertRow method of excelize.File type, but it work differently and using it to pre-fill lsx.SheetData.Row panic anyway. Working solution in my main function:
xlsx := file.Sheet["xl/worksheets/sheet1.xml"]
add := jobs * limit
mutex := sync.Mutex{}
mutex.Lock()
for add > 0 {
        xlsx.SheetData.Row = append(xlsx.SheetData.Row, excelize.NewRow(add))
        add--
}
mutex.Unlock()
and necessary related imprevement in excelize row.go file:
func NewRow(row int) xlsxRow {
	return xlsxRow{R: row}
}         

**Output of `go version`:**
go version go1.12.2 linux/amd64

**Excelize version or commit ID:**
 c1357ee58fb7478645fa22adc7a5905e86c1f7c1
**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
ubuntu xenial

**Comment by mlh758** [comment]
I think there are several places where this library would be unsafe for concurrently sharing a file across threads. That's a generally unsafe thing to do with a lot of data structures, not just this library.

**Comment by landrisek** [comment]
I fully understand your concerns. Hovewer if is followed the rule that every routine know exactly how many jobs should do and what is number of row to pass and this row would be unique, we do not have to care about order and timing. Strange as it may sound, I believe it is simple as that and my code above should demonstrate it. I asked only to accept idea of pull request which I can do and it is only about 3 new rows. Who want to use it, can, who does not, will not be forced to do so.

**Comment by mlh758** [comment]
Have you run that code with the race detector enabled?

**Comment by landrisek** [comment]
Thank you for suggestion! Yes, you are right about race condition, but what about multiple goroutines within one thread? I intent to use it only in one thread / websocket stream / server sent event stream. I use it for backend system where there is one big data set which is exported on demand of user. Distribution and divide this task to more goroutines in one thread significantly improved time to finish. What is other option to write file anyway? Do it sequentially within thread? Create more files and join them on the end of process?

**Comment by mlh758** [comment]
Even with one thread, the go runtime doesn't make a lot of guarantees about how goroutines will execute. You can have a race condition with goroutines even running on a single thread. The runtime can stop a goroutine and start running another almost whenever it pleases. There are some predictable points where a context switch will  be attempted like if the currently scheduled routine sleeps or tries to send on a channel, but it's dangerous to assume anything about the runtime. There's a pretty good rundown of the scheduler [here](https://www.ardanlabs.com/blog/2018/08/scheduling-in-go-part2.html) if you're interested in how all that works.

If it's the actual write operation into the excel that is slow, then we're kind of stuck. This library isn't safe to share across goroutines.

If you have processing work that needs to be done, and you know where the values will need to be saved in the excel then you could start a goroutine that owns the excel file and send it messages that have the row number and values to be saved. You can have as many threads as you want producing values and sending onto the channel the excel file's goroutine is listening on. Once all your producers are done, close the channel. Have the excel routine send a done signal with a waitgroup or channel after it saves or just send the excel file over the channel if you need to send it over the network from some other thread.

**Comment by landrisek** [comment]
I moved all work around data to multiple routines and leave write to file only for one goroutine. So I am closing issue.

**Comment by mlh758** [comment]
Thank you for updating the issue!
