### ISSUE TITLE
Open file - Read Only

### ISSUE THREAD

**Issue by AngangGuo** [360EntSecGroup-Skylar/excelize#449]
Can I open the file in read only mode?

The file is opened by another process(Office), but I only need to read some data from it using program.

```
open C:\Users\andrew\OneDrive\REPORT.xlsx: The process cannot access the file because it is being used by another process.
```

Thanks.

**Comment by xuri** [comment]
Hi @AngangGuo, please follow by issue template provide code and steps to reproduce the issue.

**Comment by AngangGuo** [comment]
the minimum program is as the following:
```
func main() {
	f, err := excelize.OpenFile(`C:\Users\andrew\OneDrive\Work\Label.xlsx`)
	if err != nil {
		fmt.Println(err)
		return
	}
	s:=f.GetSheetMap()
	fmt.Println(s)
}
```
The Excel file is on my company OneDrive folder. It can be opened and processed using this program without any problem.

But If I open the file using Microsoft Excel first. Then this program will fail and the message is:
```
open C:\Users\andrew\OneDrive\Work\Label.xlsx: The process cannot access the file because it is being used by another process.
```

**Comment by AngangGuo** [comment]
I have OneDrive installed on my own computer. I can open the file (`C:\Users\Andrew\OneDrive\Private\register.xlsx`)using the above program without any problem. 

But if I open that file first from Excel for Office 365 and then run the program, the following error message shows out:
```
open C:\Users\Andrew\OneDrive\Private\register.xlsx: The process cannot access the file because it is being used by another process.
```
Is it possible to open the file as readonly or get a snap shot of the file?

**Comment by AngangGuo** [comment]
My solution:  in the end, I made a copy of the file and read the content from the copy.

**Comment by AngangGuo** [comment]
For now I found a better solution to work with the file:
* Let Excelize program open my local OneDrive file
* If I need to work on the file, I'll open the network version from Browser.
