### ISSUE TITLE
Support for array formula types

### ISSUE THREAD

**Issue by stdatiks** [360EntSecGroup-Skylar/excelize#450]
Are there any plans to support array formula types?
I need formulas like `{=MIN(IF(B4:B27=$B33;C4:C27))}`

**Comment by xuri** [comment]
Hi @stdatiks, [`SetCellFormula`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetCellFormula) support to set array formula since version 2.0.2.
