### ISSUE TITLE
 The formula does not take effect

### ISSUE THREAD

**Issue by PengWuLin** [360EntSecGroup-Skylar/excelize#453]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Hi @PengWuLin, please follow by issue template provide code and steps to reproduce the issue.

**Comment by dolmen** [comment]
A translation in english would be welcome too.

**Comment by xiexiao** [comment]
you need to update cell value which has a formula, set the value to ""(empty string), 
then update the  *File.CalcChain.
if you don't update the CalcChain, the excel file will be have something wrong when open it.

**Comment by JackChanw** [comment]
@xiexiao  i have the same question, as you say-"update the *File.CalcChain",how to do that in this lib?

**Comment by xiexiao** [comment]
`// UpdateCellFormula UpdateCellFormula
func (f *File) UpdateCellFormula(name string) error {
	xlsx, err := f.workSheetReader(name)
	if err != nil {
		return err
	}
	sheetID := f.GetSheetID(name)
	chain := f.CalcChain
	var rs []string
	for indexR := range xlsx.SheetData.Row {
		for indexC, col := range xlsx.SheetData.Row[indexR].C {
			//println("indexC:", indexC)
			if col.F != nil && col.F.Content != "" {
				formula := col.F.Content
				/*
					if !strings.HasPrefix(formula, "=") {
						formula = "=" + formula
					}*/
				//col.F.Content = "=" + formula
				//fmt.Printf("col:%v\n", col)
				//fmt.Printf("col.F:%v\n", col.F)
				rs = append(rs, col.R)
				xlsx.SheetData.Row[indexR].C[indexC].V = ""
				xlsx.SheetData.Row[indexR].C[indexC].F.Content = formula
				//xlsx.SheetData.Row[indexR].C[indexC].F = &xlsxF{Content: formula}
				//v, err := f.GetCellValue(name, col.R)
				//fmt.Println(v, err)
				//err = f.SetCellFormula(name, col.R, formula)
				//fmt.Println(err)
				//fmt.Printf("col:%v, %s %s, %s\n", col.F, name, col.R, formula)
				//fmt.Printf("col:%v, %s, %s\n", col.F, col.R, formula)
			}
		}
	}
	var chains []xlsxCalcChainC
	for _, ch := range chain.C {
		if ch.I != sheetID {
			chains = append(chains, ch)
		}
	}
	for _, r := range rs {
		chains = append(chains, xlsxCalcChainC{
			R: r,
			I: sheetID,
		})
	}
	chain.C = chains
	return nil
}`

i just add this function to *File, just call it before save the xlsx file.

**Comment by xiexiao** [comment]
```
// UpdateCellFormula UpdateCellFormula
func (f *File) UpdateCellFormula(name string) error {
	xlsx, err := f.workSheetReader(name)
	if err != nil {
		return err
	}
	sheetID := f.GetSheetID(name)
	chain := f.CalcChain
	var rs []string
	for indexR := range xlsx.SheetData.Row {
		for indexC, col := range xlsx.SheetData.Row[indexR].C {
			//println("indexC:", indexC)
			if col.F != nil && col.F.Content != "" {
				formula := col.F.Content
				/*
					if !strings.HasPrefix(formula, "=") {
						formula = "=" + formula
					}*/
				//col.F.Content = "=" + formula
				//fmt.Printf("col:%v\n", col)
				//fmt.Printf("col.F:%v\n", col.F)
				rs = append(rs, col.R)
				xlsx.SheetData.Row[indexR].C[indexC].V = ""
				xlsx.SheetData.Row[indexR].C[indexC].F.Content = formula
				//xlsx.SheetData.Row[indexR].C[indexC].F = &xlsxF{Content: formula}
				//v, err := f.GetCellValue(name, col.R)
				//fmt.Println(v, err)
				//err = f.SetCellFormula(name, col.R, formula)
				//fmt.Println(err)
				//fmt.Printf("col:%v, %s %s, %s\n", col.F, name, col.R, formula)
				//fmt.Printf("col:%v, %s, %s\n", col.F, col.R, formula)
			}
		}
	}
	var chains []xlsxCalcChainC
	for _, ch := range chain.C {
		if ch.I != sheetID {
			chains = append(chains, ch)
		}
	}
	for _, r := range rs {
		chains = append(chains, xlsxCalcChainC{
			R: r,
			I: sheetID,
		})
	}
	chain.C = chains
	return nil
}
```

i just add this function to *File, just call it before save the xlsx file.

**Comment by wilson001** [comment]
> ```
> // UpdateCellFormula UpdateCellFormula
> func (f *File) UpdateCellFormula(name string) error {
> 	xlsx, err := f.workSheetReader(name)
> 	if err != nil {
> 		return err
> 	}
> 	sheetID := f.GetSheetID(name)
> 	chain := f.CalcChain
> 	var rs []string
> 	for indexR := range xlsx.SheetData.Row {
> 		for indexC, col := range xlsx.SheetData.Row[indexR].C {
> 			//println("indexC:", indexC)
> 			if col.F != nil && col.F.Content != "" {
> 				formula := col.F.Content
> 				/*
> 					if !strings.HasPrefix(formula, "=") {
> 						formula = "=" + formula
> 					}*/
> 				//col.F.Content = "=" + formula
> 				//fmt.Printf("col:%v\n", col)
> 				//fmt.Printf("col.F:%v\n", col.F)
> 				rs = append(rs, col.R)
> 				xlsx.SheetData.Row[indexR].C[indexC].V = ""
> 				xlsx.SheetData.Row[indexR].C[indexC].F.Content = formula
> 				//xlsx.SheetData.Row[indexR].C[indexC].F = &xlsxF{Content: formula}
> 				//v, err := f.GetCellValue(name, col.R)
> 				//fmt.Println(v, err)
> 				//err = f.SetCellFormula(name, col.R, formula)
> 				//fmt.Println(err)
> 				//fmt.Printf("col:%v, %s %s, %s\n", col.F, name, col.R, formula)
> 				//fmt.Printf("col:%v, %s, %s\n", col.F, col.R, formula)
> 			}
> 		}
> 	}
> 	var chains []xlsxCalcChainC
> 	for _, ch := range chain.C {
> 		if ch.I != sheetID {
> 			chains = append(chains, ch)
> 		}
> 	}
> 	for _, r := range rs {
> 		chains = append(chains, xlsxCalcChainC{
> 			R: r,
> 			I: sheetID,
> 		})
> 	}
> 	chain.C = chains
> 	return nil
> }
> ```
> 
> i just add this function to *File, just call it before save the xlsx file.

i use this function has an error:f.GetSheetID undefined (type *File has no field or method GetSheetID)

**Comment by xiexiao** [comment]
```
// GetSheetID get sheet id
func (f *File) GetSheetID(name string) int {
	for _, sheet := range f.WorkBook.Sheets.Sheet {
		if sheet.Name == name {
			return sheet.SheetID
		}
	}
	return -1
}
```
sorry, the function is here

**Comment by xuri** [comment]
There still no more details about this issue from the issue author. According to the above discussion, if you wanna make the Excel application auto recalculate formula on an open spreadsheet file, call [`UpdateLinkedValue()`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.UpdateLinkedValue) before you saved it. I'll close this issue, if you have any questions, please let me know.
