### ISSUE TITLE
Feature - remove picture from spreadsheet

### ISSUE THREAD

**Issue by billytoe** [360EntSecGroup-Skylar/excelize#455]
通过增加图片 AddPicture() 增加过的图片 用什么方法删除图片？

xlsx1.SetCellValue(“sheet1”, "E", nil)  这样不能删除，用什么方法清除这个图片呢？？

**Comment by xuri** [comment]
Hi @billytoe, sorry for my so late reply. I have added the new function [`DeletePicture`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.DeletePicture) to support for delete pictures from XLSX.
