### ISSUE TITLE
GetSheetName doesn't work on this excel

### ISSUE THREAD

**Issue by GZLHZ** [360EntSecGroup-Skylar/excelize#457]
**Description**

GetSheetName doesn't work on this excel  (other excels are no problem)
[GetSheetName.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3469994/GetSheetName.xlsx)

```jsx
func ReadExcelFile(){
	f, err := excelize.OpenFile("./GetSheetName.xlsx")
	if err != nil {
		Println(err)
		return
	}

	fmt.Println(f.GetSheetName(1))
}
```

**Steps to reproduce the issue:**
1.Open the excel and read it and you can find it can't get the result "Sheet1",it got a empty string

**Output of `go version`:**
1.12.7

**Excelize version or commit ID:**
2019.08.04 update github

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
win10 1903
office 2019(but i don't know who create this excel and his excel version, it's on our svn)

**Comment by mlh758** [comment]
This opens fine for me on MacOS. `"./GetSheetName.xlsx"` doesn't look like valid path syntax on Windows.

**Comment by GZLHZ** [comment]
you can test it on windows, other excels are no problem, but i don't know why this excel cannot get the sheet name.

**Comment by GZLHZ** [comment]
> This opens fine for me on MacOS. "./GetSheetName.xlsx" doesn't look like valid path syntax on Windows.
you can test it on windows, other excels are no problem, but i don't know why this excel cannot get the sheet name.

**Comment by mlh758** [comment]
Okay yeah I can reproduce this. `GetSheetName` looks for a sheet with an ID that matches the index. This presumably assumes that the IDs on the sheets are in order. The only sheet in this excel document has an ID of 5.

**Comment by mlh758** [comment]
It looks like changing the sheet order changes the order sheets appear within the `<sheets>` tag within `workbook.xml`. @xuri I think `GetSheetName` can be simplified to just check the index of the sheet against the `Sheets` field in a workbook.

**Comment by mlh758** [comment]
Go ahead and pull down the code from [this PR](https://github.com/360EntSecGroup-Skylar/excelize/pull/463) and let me know if that fixes your issue.

**Comment by GZLHZ** [comment]
@mlh758  yes, it can slove the problem.thank you.
