### ISSUE TITLE
macOS can not use

### ISSUE THREAD

**Issue by a57571735** [360EntSecGroup-Skylar/excelize#46]
cell := xlsx.GetCellValue("Sheet1", "B2")
fmt.Println(cell)
// Get all the rows in a sheet.
rows := xlsx.GetRows("sheet1")
fmt.Println(rows)

in windows it works normal,but in macOS rows is empty,cell can get value

**Comment by Luxurioust** [comment]
@a57571735 Please provide file attachments If you can. Note that you will need to use Go 1.8+ to support for collecting all attributes by fix issue #32.

**Comment by lishali12345** [comment]
I met this issue too. I just use the sample code in the repo's readme page to read the xlsx file "Workbook1.xlsx" which provided in the repo's test folder.

Then I met the same issue. When I run this code in macOS Sierra Version 10.12.5 with go version go1.8.3 darwin/amd64, only the GetCellValue func worked. The GetRows func doesn't work.

The output in macOS is below:
![excelize-output-macos](https://cloud.githubusercontent.com/assets/170981/26660189/c9e5776a-46a8-11e7-8f48-c2524fb19196.png)


I have try this code and sample xlsx file in Windows 10 with go version go1.8.3 windows/amd64, the output in Win 10 is below:
![2017-06-01 09 01 45](https://cloud.githubusercontent.com/assets/170981/26660217/ff9e7c1c-46a8-11e7-818e-12be66e98642.jpg)
 

The sample code:
```go
package main

import (
	"fmt"
	"os"
	"strconv"

	"github.com/Luxurioust/excelize"
)

func main() {
	xlsx, err := excelize.OpenFile("./samples/Workbook1.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	// Get value from cell by given sheet index and axis.
	cell := xlsx.GetCellValue("Sheet2", "B2")
	fmt.Println(cell)
	// Get sheet index.
	index := xlsx.GetSheetIndex("Sheet2")
	// Get all the rows in a sheet.
	rows := xlsx.GetRows("sheet" + strconv.Itoa(index))
	for _, row := range rows {
		for _, colCell := range row {
			fmt.Print(colCell, "\t")
		}
		fmt.Println()
	}

}
```

The sample xlsx file is in the attachments.
[Workbook1.xlsx](https://github.com/Luxurioust/excelize/files/1043306/Workbook1.xlsx)

**Comment by Luxurioust** [comment]
@lishali12345 I have tested that and it works well. Please try upgrade library to the last version by `go get -u github.com/Luxurioust/excelize`.

**Comment by lishali12345** [comment]
@Luxurioust I have update the library with `go get -u github.com/Luxurioust/excelize`. The func GetRows doesn't work on macOS as well.

**Comment by lishali12345** [comment]
@Luxurioust This is the output.
![excelize-output-after-update-library](https://cloud.githubusercontent.com/assets/170981/26664181/22bf5946-46c2-11e7-9aa0-e6a138c46336.png)

**Comment by Luxurioust** [comment]
I have checkout your project excel-piper and test on environment (os and golang version) same with you, but still unable to reproduce this issue. Could you help debug by stepping to provide more information?

**Comment by lishali12345** [comment]
@Luxurioust When I debug by stepping into, I just found that getTotalRowsCols func just return tr and tc both with 0.

![excelize-debug-10](https://cloud.githubusercontent.com/assets/170981/26671993/10038840-46ea-11e7-870b-7df98c608dd9.png)

![excelize-debug-11](https://cloud.githubusercontent.com/assets/170981/26671992/0fa36d02-46ea-11e7-8aae-969ea87cb22a.png)

**Comment by lishali12345** [comment]
@Luxurioust If you want me to do more debug steps, please just make it clear.

**Comment by Luxurioust** [comment]
Please try to handle error of `decoder.Token()` in [rows.go line 79](https://github.com/Luxurioust/excelize/blob/master/rows.go#L79) and check the number of times of the code was executed in the loop.

**Comment by lishali12345** [comment]
decoder.Token() in rows.go line 79 has executed 3 times in the loop.

**Comment by Luxurioust** [comment]
Did you catch exception of `decoder.Token()` ?

**Comment by lishali12345** [comment]
Yes, but I can't view the err value in the debug.
![excelize-debug-12](https://cloud.githubusercontent.com/assets/170981/26679378/56ed2b68-4707-11e7-899e-7655089bc329.png)

**Comment by Luxurioust** [comment]
I noticed that you are using zsh, could you provide `go env` output and check environment variable `GOROOT` is set correctly in `~/.zshrc`or `~/.bash_profile`.

**Comment by lishali12345** [comment]
I have run the same code in my home MacBook Pro with macOS Sierra Version 10.12.3 (16D32) with go version go1.8 darwin/amd64, it worked well.

The output is:
<img width="475" alt="excelize-output-in-home-macbook-pro" src="https://cloud.githubusercontent.com/assets/170981/26685154/d0a518c6-471b-11e7-99ef-8931ca0ec547.png">

In my home MacBook Pro, I have a ~/.profile file with some config for go like this:
```shell
export GOPATH=/Users/helihua/go
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

And I use zsh in my home MacBook Pro too, and I source the ~/.profile in the first line of ~/.zsh.rc, like this:

```shell
source ~/.profile
``` 

I'll check the env setting on my office MacBook Pro tomorrow, and then post here to make something clear.

**Comment by lishali12345** [comment]
This is the ~/.profile on my office MacBook Pro:
```shell
export GOROOT=/usr/local/go
export GOPATH=/Users/helihua/go
export PATH=/usr/local/go/bin:$PATH
```

And in my ~/.zshrc file there is source ~/.profile like this:
```shell
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
source ~/.profile
export PATH=~/bin:$PATH
export ANDROID_SDK_HOME=/Users/helihua/Library/Android/sdk
```

**Comment by lishali12345** [comment]
And I had change my shell to bash in the Terminal, then run `go run [my_script.go]`, the GetRows Func just doesn't work as well.

**Comment by Luxurioust** [comment]
Could you provide `go env` output?

**Comment by lishali12345** [comment]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/helihua/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8_/d2fvf9j975j75dk11g4z1y1m0000gp/T/go-build635963732=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by Luxurioust** [comment]
Could you provide `go env` output?

**Comment by Luxurioust** [comment]
In the [line 29](https://github.com/Luxurioust/excelize/blob/d372bb977f57b244faf635e21af458bf2e8a98ef/rows.go#L29) of `rows.go`, `xml.Marshal()` will be throws an exception about `xml.Attr` if using the `xml` package in golang with version before 1.8. That's the reason cause function `GetRows` doesn't work. Have you installed a version before 1.8 and then upgraded it to current version and what way do you install it? I suggest that try install by [homebrew](https://brew.sh).

**Comment by lishali12345** [comment]
You mean that I should reinstall the Golang runtime with homebrew?

**Comment by Luxurioust** [comment]
I just talk about the cause of the issue and notice that make sure using correct version of [xml package](https://golang.org/pkg/encoding/xml/) in golang 1.8 version. Of course, you can try to reinstall Golang runtime.

**Comment by lishali12345** [comment]
I had reinstall the Golang runtime pkg downloaded from the official website of Golang, and then it worked.

This is the output:
```shell
19
Monitor		Brand			
> 23 Inch	19	HP	200		
20-23 Inch	24	DELL	450		
17-20 Inch	56	Lenove	200		
< 17 Inch	21	SONY	510		
		Acer	315		
		IBM	127		
		ASUS	89		
		Apple	348		
		SAMSUNG	53		
		Other	37		
```

Thanks for your patience about all of these.

**Comment by lishali12345** [comment]
May be cause I had install a mongo db on this MacBook Pro using homebrew, but it failed. I know that mongo db depends on golang, maybe this issue was caused by this failed installation of mongo db.

**Comment by lishali12345** [comment]
And before I reinstall the pkg downloaded from the official site of Golang, I had run `brew remove go` to remove the golang which was installed by homebrew. Wish it will help.
