### ISSUE TITLE
How to read binary file ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [360EntSecGroup-Skylar/excelize#460]
Thanks for the great package. For now, on README, I only see `excelize` can read file from `xlsx` file, but in my application, I'm storing excel file as binary (`blob`) in MySQL. Is that possible to read excel file from the blob of MySQL with `excelize` ?

**Comment by mlh758** [comment]
You can use the `OpenReader` function to extract an excel file from any reader. You can use a [buffer](https://godoc.org/bufio) to pass your blob through as a reader.

That said, is it strictly necessary for you to store excel files as blobs in a database like that? You might have an easier time storing the location of the files in your database and using some other persistent storage solution (even just a location on local disk if your application is simple enough) to store the actual files.

**Comment by TranBaVinhSon** [comment]
Thanks for your quick response. So basically, Instead of `OpenFile`, I can use `OpenReader` to solve my problem. 

We thought about storing on local disk or AWS S3 solution but with our application, storing excel files in MySQL is the best way. 
Again, thanks for your support.

**Comment by prudhvirajs** [comment]
I had a similar use case:
I have a very large excel file coming in through a web-socket connection as a **blob** ( []byte ) . 
I needed to decode the blob into an excel file. 

```
        messageType, FileDataInBytes, err := conn.ReadMessage()
	excelFile, err := excelize.OpenReader(bytes.NewReader(FileDataInBytes))
```

OpenReader read data stream from io.Reader and return a populated spreadsheet file.
- This implementation gives me an easy way to decode blob to an excel. 

Great Package, Thank you :)
