### ISSUE TITLE
Can't print cell contents

### ISSUE THREAD

**Issue by AngangGuo** [360EntSecGroup-Skylar/excelize#462]
The following program can't print the contents of the last two cells:

go.mod
```
module report

go 1.13

require github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.2-0.20190731155349-9279c86d85ab
```

```
package main

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {
	var fileName = "User Metrics.xlsx"
	var sheetName = "User Metrics"

	f, _ := excelize.OpenFile(fileName)
	contents, _ := f.GetRows(sheetName)

	for i,j:=range contents[2]{
		fmt.Println(i,j)
	}
}
```
Output:
```
0 Employee Name
1 Clean & Pack
2 Data Erasure
3 FG (Client)
4
5 FG(RL-LIQ)
6 Rebox
7 Repair Without Parts
8 Sort
9 Test
10
11
// missing the following contents:
// 10 Sort Weight (Kgs)
// 11 Test Weight (Kgs)
```

[User Metrics.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/3474778/User.Metrics.zip)

**Comment by mlh758** [comment]
Here is the XML for those cells:

```xml
<c s="3" t="inlineStr" r="K3">
  <is>
    <r>
      <rPr>
        <b></b>
        <i val="0"></i>
        <strike val="0"></strike>
        <u val="none"></u>
        <sz val="9"></sz>
        <color rgb="FFFFFFFF"></color>
        <rFont val="Tahoma"></rFont>
      </rPr>
      <t xml:space="preserve">Sort Weight (</t>
    </r>
    <r>
      <rPr>
        <b></b>
        <i val="0"></i>
        <strike val="0"></strike>
        <u val="none"></u>
        <sz val="9"></sz>
        <color rgb="FFFFFFFF"></color>
        <rFont val="Tahoma"></rFont>
      </rPr>
      <t xml:space="preserve">Kgs</t>
    </r>
    <r>
      <rPr>
        <b></b>
        <i val="0"></i>
        <strike val="0"></strike>
        <u val="none"></u>
        <sz val="9"></sz>
        <color rgb="FFFFFFFF"></color>
        <rFont val="Tahoma"></rFont>
      </rPr>
      <t xml:space="preserve">)</t>
    </r>
  </is>
</c>
```

Looks like you can have nested rows within an inline string (`<is>`) tag which we definitely aren't accounting for:

```go
type xlsxIS struct {
	T string `xml:"t"`
}
```

We'll need to expand that struct and probably add a method on it to extract the string. For the purpose of reading files I propose that `getValueFrom` should call a method on `xlsx.IS` which returns a string instead of directly accessing the `T` field. Rows should be joined with a newline character.

**Comment by mlh758** [comment]
What did you use to create this file? The repeated inline formatting instructions seems strange to me.

**Comment by AngangGuo** [comment]
The file is generated from our company software.

**Comment by mlh758** [comment]
Ah some some internal program your company made/uses is making the file?

In any case, this will require a PR, we're just not handling this part of the spec yet.

**Comment by mlh758** [comment]
Try out the code in [this PR](https://github.com/360EntSecGroup-Skylar/excelize/pull/464). It worked for me with your sample file.

**Comment by AngangGuo** [comment]
Can you please give me some instruction on how to use your PR code?
thanks.

**Comment by mlh758** [comment]
Assuming you are using go modules, you can clone my fork of the repo with that branch and then add a replace directive like this:

```
replace github.com/360EntSecGroup-Skylar/excelize/v2 => /path/to/the/fork
```

Then `go build` like normal.

**Comment by AngangGuo** [comment]
Tested. It works well. 
Thanks.
