### ISSUE TITLE
go get 时 抛出 killed 9

### ISSUE THREAD

**Issue by Relax1989** [360EntSecGroup-Skylar/excelize#465]
我使用go get 结果得到killed 9 
``` bash 
go get github.com/360EntSecGroup-Skylar/excelize/v2
```
![image](https://user-images.githubusercontent.com/17996638/62672296-c28d0700-b9cc-11e9-916b-d4317a5ac92d.png)

go version 1.12.5 

我尝试使用git clone 
When I tried git clone
```bash 
git clone https://github.com/360EntSecGroup-Skylar/excelize.git
```
![image](https://user-images.githubusercontent.com/17996638/62672373-fff19480-b9cc-11e9-8c02-878911ab27c1.png)

What should I do

**Comment by xuri** [comment]
Please check your network connection status.
