### ISSUE TITLE
Potential Memorhttps://github.com/360EntSecGroup-Skylar/excelize/issues/29y Leak in File.Write()

### ISSUE THREAD

**Issue by zaddok** [360EntSecGroup-Skylar/excelize#468]
Im not 100% sure if the bug is in my code, or in this library, but I suspect it is the library, I am seeing this pprof output in longer running processes:

```
  902.59kB 30.20% 30.20%  1451.43kB 48.56%  compress/flate.NewWriter
  548.84kB 18.36% 48.56%   548.84kB 18.36%  compress/flate.(*compressor).initDeflate
     513kB 17.16% 65.73%      513kB 17.16%  net/http.appendSorted
  512.05kB 17.13%   100%   512.05kB 17.13%  text/template/parse.(*Tree).newPipeline
         0     0%   100%  1451.43kB 48.56%  archive/zip.(*Writer).Create
         0     0%   100%  1451.43kB 48.56%  archive/zip.(*Writer).CreateHeader
         0     0%   100%  1451.43kB 48.56%  archive/zip.init.0.func2
         0     0%   100%  1451.43kB 48.56%  archive/zip.newFlateWriter
         0     0%   100%   548.84kB 18.36%  compress/flate.(*compressor).init
```

It appears to be leaking when I do this:

```
err = xlsx.Write(w)
if err != nil {
    fmt.Println("Excel issue:", err)
}
```

I think there is a memory leak if an error occurs, but I am not seeing any errors reported, so there appears to be a leak if no error occurs as well. I've had a brief look at the excelize code, and the underlying go zip library and I can't see anything obvious.  

I wonder if anyone else is seeing this.

**Comment by zaddok** [comment]
Here is a graphical version of the pprof output:

https://i.postimg.cc/5NLdfV3R/Screen-Shot-2019-08-09-at-9-41-09-am.png

**Comment by mlh758** [comment]
@zaddok You can just attach screenshots directly to comments, please don't use sites that serve ads over the screenshot like that.

**Comment by montebo-support** [comment]
I can’t see any way to attach images. So I just used an image sharing site. Sorry if your seeing ads (I haven’t had a browser set up to show ads for a long time)

**Comment by mlh758** [comment]
You can just copy paste or drag and drop the file into the comment.
