### ISSUE TITLE
关于含有图片的工作表的复制

### ISSUE THREAD

**Issue by iwinstar1980** [360EntSecGroup-Skylar/excelize#472]
在官方文档中有说 func (f *File) CopySheet(from, to int) error
不支持包含表格、图片、图表和透视表等元素的工作表之间的复制。

请问未来有计划对应含有 表格 图片 图标的工作表之间的复制吗?

**Comment by xuri** [comment]
Hi @iwinstar1980, thanks for your issue. I will adding support for this feature later. I'll certainly accept that patch if somebody did that. I close this and merge it into issue #41 is still discussing this issue.
