### ISSUE TITLE
How can I generate a xslx file and send it  at the same time, like pipe.

### ISSUE THREAD

**Issue by huangapple** [360EntSecGroup-Skylar/excelize#474]
I need generate a big xslx file, it can't all in memory.
how  can I generate a xslx file and save it or send it  at the same time, just like pipe

**Comment by xuri** [comment]
Hi @huangapple, I have added a [stream writer](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.NewStreamWriter) for generating a new worksheet with huge amounts of data. We need to generate the complete file before sending.
