### ISSUE TITLE
Cannot read xlsx file created by python library openpyxl

### ISSUE THREAD

**Issue by m3ng9i** [360EntSecGroup-Skylar/excelize#478]
I use the sample python code at `https://openpyxl.readthedocs.io/en/stable/` to create an xlsx file `sample.xlsx`, this file can be opened by MS Office and Libreoffice.

Then I write a go program with excelize to read `sample.xlsx`, but I cannot read the data of the file. `GetActiveSheetIndex()` returns 0, `GetSheetName(1)` returns empty string.

The python code:

```python
from openpyxl import Workbook
wb = Workbook()

# grab the active worksheet
ws = wb.active

# Data can be assigned directly to cells
ws['A1'] = 42

# Rows can also be appended
ws.append([1, 2, 3])

# Python types will automatically be converted
import datetime
ws['A2'] = datetime.datetime.now()

# Save the file
wb.save("sample.xlsx")
```

The go code:

```go
package main

import (
    "fmt"
    "github.com/360EntSecGroup-Skylar/excelize/v2"

)

func main() {
    xlsx, err := excelize.OpenFile("sample.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }

    fmt.Printf("GetActiveSheetIndex: %d\n", xlsx.GetActiveSheetIndex()) // 0

    fmt.Printf("GetSheetName: %s\n", xlsx.GetSheetName(1)) // empty string

    rows, err := xlsx.GetRows(xlsx.GetSheetName(1))
    if err != nil {
        fmt.Println(err)
        return
    } else {
        // nothing printed
        for _, row := range rows {
            fmt.Println(row)
        }
    }
}
```
Sample xlsx file generated by python: [sample.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3548958/sample.xlsx)

 
- go version: go1.12.9 linux/amd64
- Excelize version: v2.0.1

**Comment by xuri** [comment]
Hi @m3ng9i, thanks for your feedback,  please try to upgrade the library with the master branch code. Git tag for v2 will be updated on the next release.

**Comment by m3ng9i** [comment]
> Hi @m3ng9i, thanks for your feedback, please try to upgrade the library with the master branch code. Git tag for v2 will be updated on the next release.

The master branch is ok, thanks.
