### ISSUE TITLE
How to delete line in excel

### ISSUE THREAD

**Issue by iwalkerr** [360EntSecGroup-Skylar/excelize#482]
How to delete line in excel, can god give me some guidance?

![删除线](https://user-images.githubusercontent.com/43042929/64950800-d7ec2f80-d8ae-11e9-857d-22b478cf37ee.jpg)

**Comment by Jeltopuz** [comment]
https://xuri.me/excelize/en/sheet.html#SetSheetRow  

Remove row
func (f *File) RemoveRow(sheet string, row int) error
RemoveRow provides a function to remove a single row by given worksheet name and Excel row number. For example, remove row 3 in Sheet1:

err := f.RemoveRow("Sheet1", 3)
Use this method with caution, which will affect changes in references such as formulas, charts, and so on. If there is any referenced value of the worksheet, it will cause a file error when you open it. The excelize only partially updates these references currently.

**Comment by iwalkerr** [comment]
> https://xuri.me/excelize/en/sheet.html#SetSheetRow
> 
> Remove row
> func (f *File) RemoveRow(sheet string, row int) error
> RemoveRow provides a function to remove a single row by given worksheet name and Excel row number. For example, remove row 3 in Sheet1:
> 
> err := f.RemoveRow("Sheet1", 3)
> Use this method with caution, which will affect changes in references such as formulas, charts, and so on. If there is any referenced value of the worksheet, it will cause a file error when you open it. The excelize only partially updates these references currently.

Thank you for your answer, what I want to express is, draw a line on the text, as shown in the picture

**Comment by xuri** [comment]
Thanks for your issue, I will add font strike style support later.

**Comment by iwalkerr** [comment]
> Thanks for your issue, I will add font strike style support later.

Thank you

**Comment by xuri** [comment]
Hi @iwalkerr, I have added font strike style support, you can set like this:
```go
f.NewStyle(`{"font":{"strike":true}}`)
```

**Comment by iwalkerr** [comment]
Thank you




| |
walkerr
|
|
邮箱：walkerr@163.com
|
On 09/23/2019 21:51, xuri wrote:

Hi @iwalkerr, I have added font strike style support, you can set like this:

f.NewStyle(`{"font":{"strike":true}}`)

**Comment by heriipurnama** [comment]
How to multiple delete line/row in excel

**Comment by xuri** [comment]
The original title of this issue was ambiguous, which was related to the strikethrough style of the cell. I have updated the title for this issue. This library does not support batch removing rows or columns currently, please remove rows or columns by the [`RemoveRow`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.RemoveRow) or the [`RemoveCol`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.RemoveCol) function one by one.

**Comment by heriipurnama** [comment]
![image](https://user-images.githubusercontent.com/10396992/190114654-dbed44aa-a3ed-436a-9ea7-6bff24c29211.png)
i make looping cant work too.

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using? Can you show us a complete, standalone example program or reproducible demo?

**Comment by heriipurnama** [comment]
i using  v1.4.1,

**Comment by xuri** [comment]
Please upgrade to the latest version or using the master branch code if you can, this issue has been fixed.

**Comment by heriipurnama** [comment]
ok i will try
