### ISSUE TITLE
 SetSheetPrOptions error

### ISSUE THREAD

**Issue by Jeltopuz** [360EntSecGroup-Skylar/excelize#483]
```
f, err := excelize.OpenFile(filename)
	if err != nil {
		log.Fatal(err)
	}
if err := f.SetSheetPrOptions(sheet,
			excelize.OutlineSummaryBelow(false),
		); err != nil {
			panic(err)
		}

	err = f.SaveAs(filename)
	if err != nil {
		log.Fatal(err)
	}
```

If file is NewFile - it works
If file if OpenFile and file is empty - it works
If file is not empty  - i get error: 

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error122560_01.xml</logFileName><summary>Обнаружены ошибки в файле "C:\Users\a.kuimova\planningOfWorkDurations\app\filename.xlsx"</summary><removedParts><removedPart>Замененный компонент: часть /xl/worksheets/sheet1.xml с ошибкой XML.  Ошибка загрузки. Строка 2, столбец 0.</removedPart></removedParts></recoveryLog>`

Help me, please...(
I attached the file for example

[file.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3619469/file.xlsx)

**Comment by xuri** [comment]
Hi @Jeltopuz, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by Jeltopuz** [comment]
@xuri , Thank you very match!)))))
