### ISSUE TITLE
Improve write performance

### ISSUE THREAD

**Issue by ducquangkstn** [360EntSecGroup-Skylar/excelize#487]
Currently, excelize writing approach is:
- marshal obj with format xml to []byte (XLSX field)
- write XLSX to bytes.Buffer
- write buffer to file
However, this approach will consume a lot of memory when the amount of data is large.
I suggest writing to file as stream with xml.Decoder
I would like to create a PR if u think this proposal is necessary

**Comment by xuri** [comment]
Hi @ducquangkstn, welcome to contribute. Streaming read and write support will be an excellent feature, we need to the API design first. This is some of my thoughts on [performance improvement](https://github.com/360EntSecGroup-Skylar/excelize/wiki#optimization).

**Comment by ducquangkstn** [comment]
Some sample of my change would be:
`
func (f File) calcChainWriter(zw *zip.Writer) error {
	if f.CalcChain != nil && f.CalcChain.C != nil {
		return writeXML(zw, "xl/calcChain.xml", f.CalcChain)
	}
	return nil
}

func writeXML(zw *zip.Writer, name string, data interface{}) error {
	w, err := zw.Create(name)
	if err != nil {
		return err
	}
	_, err = w.Write([]byte(XMLHeader))
	if err != nil {
		return err
	}
	encoder := xml.NewEncoder(w)
	err = encoder.Encode(data)
	if err != nil {
		return err
	}
	return nil
}
`
However, there are some **hack code** like `replaceRelationshipsBytes(replaceRelationshipsNameSpaceBytes(output)))`
I would replace them by custom marshalXML function
What do you think

**Comment by xuri** [comment]
Two years passed, the streaming writing API has been added, the performance has been an improvement, I'll close this issue, but still, welcome any optimization or suggestions for the performance.
