### ISSUE TITLE
go mod无法拿到最新版本

### ISSUE THREAD

**Issue by ivalue2333** [360EntSecGroup-Skylar/excelize#488]
指定commit
go get github.com/360EntSecGroup-Skylar/excelize@475fbf3856dd83c4813874570ae5ae2cb48ed421

go: finding github.com/360EntSecGroup-Skylar/excelize 475fbf3856dd83c4813874570ae5ae2cb48ed421
go: github.com/360EntSecGroup-Skylar/excelize@v0.0.0-20190925031216-475fbf3856dd: go.mod has post-v0 module path "github.com/360EntSecGroup-Skylar/excelize/v2" at revision 475fbf3856dd

go get github.com/360EntSecGroup-Skylar/excelize@latest
拿到的是v1.4.1

**Comment by xuri** [comment]
Hi @ivalue2333, please delete go mod cache $GOPATH/pkg/mod/cache and try again. Ref #393  and #403.

**Comment by AngangGuo** [comment]
You can use the following command to get the latest version 2:
```
go get github.com/360EntSecGroup-Skylar/excelize/v2@master
```

**Comment by ivalue2333** [comment]
> You can use the following command to get the latest version 2:
> 
> ```
> go get github.com/360EntSecGroup-Skylar/excelize/v2@master
> ```

thanks

**Comment by ivalue2333** [comment]
> Hi @ivalue2333, please delete go mod cache $GOPATH/pkg/mod/cache and try again. Ref #393 and #403.

thanks

**Comment by lililiSir** [comment]
go get: github.com/360EntSecGroup-Skylar/excelize/v2@v2.7.0: parsing go.mod:
        module declares its path as: github.com/xuri/excelize/v2
                but was required as: github.com/360EntSecGroup-Skylar/excelize/v2

**Comment by xuri** [comment]
Hi @lililiSir, please reference the issue #522, using `go ​clean -modcache` or `$GOPATH/pkg/mod/cache` to delete go mod cache and try again.
