### ISSUE TITLE
Question about precision

### ISSUE THREAD

**Issue by neters** [360EntSecGroup-Skylar/excelize#490]
The excel file has a cell which value is "20.1". But when I read it, its value shows as 20.100000000000001.

I've tried to set this cell's format as "text", but this problem still exist.

So how should I read this kind of cell to handle the precision problem?

**Comment by xuri** [comment]
Hi @neters, thanks for your feedback. Please provide code and testing file attachment if you can.

**Comment by xuri** [comment]
Similar to issue #558.
