### ISSUE TITLE
AddChart only drew the first line in a multine chart

### ISSUE THREAD

**Issue by araoko** [360EntSecGroup-Skylar/excelize#491]
**Description**

I have created a workbook with several worksheets, each worksheet has a table. I inserted a new worksheet to contain a chart of all the tables on the same graph.
every time I ran the program, it only created the first line and excel did not generate an error while opening it.
when I rename the excel to zip and open the chart1.xml file, I see entries for all the other tables in <ser> tag.
I am not an expert in excel markup but I can't see any suspicious difference between the entries for the table that was draws and the ones that weren't drawn
I am using excel that came with Office 365 Pro Plus on a windows 10 laptop to open the file but I created the workbook and populated it using excelize

the JSON string (with the original worksheet names changed to make it shorter) passed to the AddChart method is:

{"type":"line","dimension":{"width":1200,"height":480},"legend":{"position":"bottom","show_legend_key":false},"title":{"name":"Chart Title"},"series":[{"name":"Summary!$C$13","categories":"Summary!$B$7:$C$12","values":"Summary!$D$7:$D$12"},{"name":"WECA...!$C$4","categories":"WECA...!$B$9:$C$14","values":"WECA...!$D$9:$D$14"},{"name":"Sidmach!$C$4","categories":"Sidmach!$B$9:$C$14","values":"Sidmach!$D$9:$D$14"},{"name":"BSN!$C$4","categories":"BSN!$B$9:$C$14","values":"BSN!$D$9:$D$14"},{"name":"POS!$C$4","categories":"POS!$B$9:$C$14","values":"POS!$D$9:$D$14"},{"name":"ENL!$C$4","categories":"ENL!$B$9:$C$14","values":"ENL!$D$9:$D$14"},{"name":"SH!$C$4","categories":"SH!$B$9:$C$14","values":"SH!$D$9:$D$14"},{"name":"STL!$C$4","categories":"STL!$B$9:$C$14","values":"STL!$D$9:$D$14"}]}

**Comment by xuri** [comment]
Hi @araoko, thanks for your feedback. Could you provide the code and file attachment to reproduce the issue?

**Comment by xuri** [comment]
Hi @araoko, it seems still not have enough info on this issue,  I'll close this issue, if you have any questions, please let me know.
