### ISSUE TITLE
How do I set a page break？

### ISSUE THREAD

**Issue by iwalkerr** [360EntSecGroup-Skylar/excelize#492]
Can I add a page break？

Methods the following：
f.SetRowBreak(row)
f.SetColumnBreak(column)

**Comment by iwalkerr** [comment]
![Xnip2019-09-28_17-42-55](https://user-images.githubusercontent.com/43042929/65814667-841b0800-e217-11e9-9437-93b1c5cf48e5.jpg)

This paging method is invalid, see if it is bug？

**Comment by iwalkerr** [comment]
![Xnip2019-09-28_17-47-45](https://user-images.githubusercontent.com/43042929/65814729-2804b380-e218-11e9-8bdc-9bf91e6230b9.jpg)

This paging method is invalid, see if it is bug？

**Comment by xuri** [comment]
Hi @iwalkerr, the `AutoPageBreaks` option in `SetSheetPrOptions` function flag indicating whether the sheet displays Automatic Page Breaks. This lib no support insert page break currently, I'll add this feature later.

**Comment by iwalkerr** [comment]
thanks

**Comment by hyp530** [comment]
> Hi @iwalkerr, the `AutoPageBreaks` option in `SetSheetPrOptions` function flag indicating whether the sheet displays Automatic Page Breaks. This lib no support insert page break currently, I'll add this feature later.

Suggest to add "Page Setup -> Print Area", which is very import for setting format for printing.

**Comment by iwalkerr** [comment]
> > Hi @iwalkerr, the `AutoPageBreaks` option in `SetSheetPrOptions` function flag indicating whether the sheet displays Automatic Page Breaks. This lib no support insert page break currently, I'll add this feature later.
> 
> Suggest to add "Page Setup -> Print Area", which is very import for setting format for printing.

thanks

**Comment by xuri** [comment]
Hi @iwalkerr, I had initialized insert and remove page break support. Please try to upgrade the library with the master branch code.
