### ISSUE TITLE
SetPageLayout doesn't work for FitToWidth and FitToHeight

### ISSUE THREAD

**Issue by Jk1484** [360EntSecGroup-Skylar/excelize#496]
**Description**

I want to set width to page layout. I send FitToWidth as argument, but it doesn't actually work.

Code: 
```text
	file.SetPageLayout(
		sheet,
		excelize.FitToWidth(1),
		excelize.PageLayoutOrientation(excelize.OrientationLandscape),
	)
```

Every value is set. Orientation is set to landscape at excel, but width is not set to 1.

**Maybe it would help**
When I do it with this code
```text
	file.SetPageLayout(
		sheet,
		excelize.FitToWidth(1),
		excelize.PageLayoutOrientation(excelize.OrientationLandscape),
	)
```

(Removed other attributes)
The XML is:
```text
<style:page-layout-properties style:print-orientation="portrait"  style:scale-to="100%"/>
```

When I change it in excel and save it. 
XML is:
```text
<style:page-layout-properties style:print-orientation="portrait"  loext:scale-to-X="1"/>
```

**Steps to reproduce the issue:**
1. Create file.
2. Create sheet
3. Set page layout option

**Describe the results you received:**
width is automatic

**Describe the results you expected:**
1 page

**Output of `go version`:**

```text
1.12.10
```

**Excelize version or commit ID:**

```text
a00ba75f0f294ce04bfe8d25703d13cd27d6284f
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10
Microsoft Excel 2016

**Comment by xuri** [comment]
Hi @Jk1484, thanks for your issue. Please enable `FitToPage` by [`SetSheetPrOptions`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetSheetPrOptions) when you specify `FitToWidth` and `FitToHeight` of the worksheet, for example:

```go
if err := f.SetSheetPrOptions(
    sheet,
    excelize.FitToPage(true),
); err != nil {
    panic(err)
}
```
