### ISSUE TITLE
Is there a style for setting an underline?

### ISSUE THREAD

**Issue by iwalkerr** [360EntSecGroup-Skylar/excelize#499]
Is there a style for setting an underline? I haven't seen this style for a long time. If you know, please let me know, thank you!

**Comment by xuri** [comment]
Hi @iwalkerr, you can set font style with underline like this:

```go
style, err := f.NewStyle(`{"font":{"underline":"single"}}`)
err = f.SetCellStyle("Sheet1", "B2", "B2", style)
```
