### ISSUE TITLE
go get install v1.4.1 and not v2.0.2

### ISSUE THREAD

**Issue by malaschitz** [360EntSecGroup-Skylar/excelize#500]
>go version
```
go version go1.13 windows/amd64

>go get github.com/360EntSecGroup-Skylar/excelize

>type go.mod
module pokus

go 1.13

require github.com/360EntSecGroup-Skylar/excelize v1.4.1 // indirect

```

**Comment by namkazt** [comment]
same issue. I just checked today. trying to use ` excelize.ColumnNumberToName` but not found

**Comment by silviucm** [comment]
You need to specify **v2** at the end of go get to obtain version 2.x.x

e.g. 

```
mkdir -p ~/projects/my-project-using-excelize
cd ~/projects/my-project-using-excelize
go mod init mytestproject
go get github.com/360EntSecGroup-Skylar/excelize/v2
```
Have a look at:
https://github.com/360EntSecGroup-Skylar/excelize/blob/master/go.mod

There's a v2 at the end of the module name, past version 2.x.x

**Comment by namkazt** [comment]
yes. I was found the issue yesterday. thanks

**Comment by joneskoo** [comment]
Perhaps README should be updated to indicate the current version, too?

https://github.com/360EntSecGroup-Skylar/excelize#installation

**Comment by hnistlzy** [comment]
I use github.com/360EntSecGroup-Skylar/excelize v1.4.1 => github.com/360EntSecGroup-Skylar/excelize/v2 v0.0.2  to replace 2.0.2 version but command return :
replace github.com/360EntSecGroup-Skylar/excelize/v2: version "v0.0.2" invalid: unknown revision v0.0.2

**Comment by namkazt** [comment]
you should use `import github.com/360EntSecGroup-Skylar/excelize/v2`

**Comment by hnistlzy** [comment]
golang.org/x/image@v0.0.0-20190910094157-69e4b8554b2a: unrecognized import path "golang.org/x/image" (https fetch: Get https://golang.org/x/image?go-get=1:
dial tcp 216.58.200.81:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established conne
ction failed because connected host has failed to respond.)
the v2 version  import golang.org/x/image but I can't download it in china.

**Comment by hnistlzy** [comment]
> > go version
> 
> ```
> go version go1.13 windows/amd64
> 
> >go get github.com/360EntSecGroup-Skylar/excelize
> 
> >type go.mod
> module pokus
> 
> go 1.13
> 
> require github.com/360EntSecGroup-Skylar/excelize v1.4.1 // indirect
> ```

 in go.mod file you should use 
require github.com/360EntSecGroup-Skylar/excelize/v2  v2.0.2

**Comment by likeprogrames** [comment]
go get github.com/360EntSecGroup-Skylar/excelize/v2
