### ISSUE TITLE
Set Chart Gridlines

### ISSUE THREAD

**Issue by araoko** [360EntSecGroup-Skylar/excelize#501]
The axis options do not include gridlines.  it will be nice to be able to specify gridlines

**Comment by xuri** [comment]
Hi @araoko, thanks for your issue. I have added `minor_grid_lines` option, you can create a chart with grid lines like this:

```go
"x_axis":{"major_grid_lines":true,"minor_grid_lines":true},"y_axis":{"major_grid_lines":true,"minor_grid_lines":true}
```
