### ISSUE TITLE
Infinite loop row iterator bug/breaking change

### ISSUE THREAD

**Issue by fharding1** [360EntSecGroup-Skylar/excelize#502]
There's a bug/breaking change in v2.0.2 that causes `rows.Next` to loop forever. A minimal reproduction case is available here: https://github.com/fharding1/excelize-repro

After bisecting, the commit that introduced this bug is:

```
[ac91ca0ded4111ed9f22578d4a0570a9084c97b0] Only parse xml once when reading
```

While before it didn't matter whether you called Columns() on each row, now you must. I think this should be documented behavior at the very least, as it's a potentially harmful breaking change.

**Comment by xuri** [comment]
Hi @fharding1, thanks for your issue. Confirm that this problem was introduced by PR #456, I will start repairing as soon as possible.
