### ISSUE TITLE
How to get rows from a specified row number? 

### ISSUE THREAD

**Issue by Nowher2** [360EntSecGroup-Skylar/excelize#504]
If a  file has 1000 lines of data, I don't want to read them at once.

**Comment by drewhbestbuddy** [comment]
You can call f.GetRows() and use slices to get the specific rows you want.
```go
rows, err := f.GetRows("SheetName")

// rows[row][col]
// get first 10 rows
slicedRows := rows[:10][:]
```
Or you can call f.Rows() and iterate yourself.

It looks like the whole sheet is read in f.Rows() function.

**Comment by xuri** [comment]
The [`Rows`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.Rows) return a rows iterator, used for streaming reading data for a worksheet with a large data. 
And you can skip a row with [`Next`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#Rows.Next).

**Comment by murlocx102** [comment]
In the case of a large amount of data. I need specific data for row 10,000. I need to run 10,000 times with an iterator. Get the data I want. Is there a better way to get the specified row. Really, very much needed.

**Comment by xuri** [comment]
Using the rows iterator will cost less memory, but you can also use the `GetRows` function to get all cell values for the worksheet, and access specified rows by index in a 2D array.
