### ISSUE TITLE
Complex chart style: line width

### ISSUE THREAD

**Issue by byteman** [360EntSecGroup-Skylar/excelize#505]
我再在用go生成一个2D折线图的时候，只有很简单的图表样式可以操作，有什么办法可以生成比较复杂的图表样式吗？或者可以先在excel中设置好样式，然后用go读取出来样式，然后生成在我自己的程序中吗？？

**Comment by xuri** [comment]
What complex styles do you need, please list them if possible, and I will consider adding support for them. A method for generating a new file based on a template: Create a chart template using Excel Application, open the template file with this lib, and modify the data area referenced by the chart to save it as a new file.

**Comment by byteman** [comment]
![image](https://user-images.githubusercontent.com/517250/67098560-0aab7f80-f1ef-11e9-869b-666c8c2acd8e.png)
这是我用go库生成的2d折线图，但是看起来线条太粗了，需要在excel中打开重新设置样式
![image](https://user-images.githubusercontent.com/517250/67098700-3595d380-f1ef-11e9-8fde-fb5b14d13c0c.png)

这是从新设置样式后的图片

![image](https://user-images.githubusercontent.com/517250/67098735-45151c80-f1ef-11e9-8145-644e5f031e0e.png)

怎么才能在代码中来选择样式啊？

**Comment by xuri** [comment]
Hi @byteman, I have added support for the set line width of the line chart. Set the width by the specified `line` parameter in each series:

```go
f.AddChart("Sheet2", "X16", `{
    "type": "line",
    "series": [
    {
        "name": "Sheet1!$A$37",
        "categories": "Sheet1!$B$29:$D$29",
        "values": "Sheet1!$B$37:$D$37",
        "line":
        {
            "width": 0.25
        }
    }]
}`)
```

**Comment by byteman** [comment]
我太爱你

**Comment by byteman** [comment]
![image](https://user-images.githubusercontent.com/517250/67261698-5eaab280-f4d4-11e9-972d-4a50075c65f6.png)
