### ISSUE TITLE
image scaling settings

### ISSUE THREAD

**Issue by hnistlzy** [360EntSecGroup-Skylar/excelize#506]
type formatPicture struct {
	FPrintsWithSheet bool    `json:"print_obj"`
	FLocksWithSheet  bool    `json:"locked"`
	NoChangeAspect   bool    `json:"lock_aspect_ratio"`
	OffsetX          int     `json:"x_offset"`
	OffsetY          int     `json:"y_offset"`
	XScale           float64 `json:"x_scale"`
	YScale           float64 `json:"y_scale"`
	Hyperlink        string  `json:"hyperlink"`
	HyperlinkType    string  `json:"hyperlink_type"`
	Positioning      string  `json:"positioning"`
}

// formatShape directly maps the format settings of the shape.
type formatShape struct {
	Type      string                 `json:"type"`
	Width     int                    `json:"width"`
	Height    int                    `json:"height"`
	Format    formatPicture          `json:"format"`
	Color     formatShapeColor       `json:"color"`
	Paragraph []formatShapeParagraph `json:"paragraph"`
}

虽然在源码中看到了有 width ,height选项，但这个是formatShape而不是formatPicture，所以AddPicture method中无法设置图片大小

**Comment by xuri** [comment]
Hi @hnistlzy, [AddPicture](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.AddPicture) supports image scaling settings:

```go
err := f.AddPicture("Sheet1", "D2", "./excel.jpg", `{"x_scale": 0.5, "y_scale": 0.5}`)
if err != nil {
	fmt.Println(err)
}
```

**Comment by hnistlzy** [comment]
我描述有点问题，我想说的是插入图片时，能不能让图片自适应cell的width,height，就跟java poi那样。
而且，插入的图片是占了两列的，能不能让他只占一列。

**Comment by xuri** [comment]
Excelize support to insert image autofit cell since version [2.3.0](https://github.com/360EntSecGroup-Skylar/excelize/releases/tag/v2.3.0), and I'll close this issue, also reference #384.
