### ISSUE TITLE
Allow overwriting DefinedName

### ISSUE THREAD

**Issue by joneskoo** [360EntSecGroup-Skylar/excelize#507]
**Description**

It is possible to set defined name (i.e. named range):

	_ = f.SetDefinedName(&excelize.DefinedName{
		Name:     "data",
		RefersTo: sheetName + "!$A$2:$P$50"),
	})

However, there does not seem to exist a way to overwrite this. Calling SetDefinedName again returns an error: **the same name already exists on scope**

https://github.com/360EntSecGroup-Skylar/excelize/blob/26aa58de055b0430b9332a768ce00d69fcf8994e/sheet.go#L1268-L1270

I can't find a call to delete a DefinedName and if I look it up with Get and modify it, changes are not saved.

Please enable updating the range of an existing DefinedName.

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.2
```

**Comment by xuri** [comment]
Hi @joneskoo, thanks for your issue. I have added a new function [`DeleteDefinedName`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.DeleteDefinedName), you can delete the defined name and re-set that.
