### ISSUE TITLE
Sheet name issue

### ISSUE THREAD

**Issue by rpokupec** [360EntSecGroup-Skylar/excelize#51]
Hi,

If I open a xlsx file and want to write to some cells in sheet where sheet name is not in format of "SheetX"
after xlsx file is saved, there is no entry in the cell if you open a file with Excel.
Another thing is if I use xlsx.CreateFile() I'm aware that I get only one sheet with name "Sheet1" and I can write to the cells of "Sheet1".
When I do xlsx.NewSheet(2, "Sheet2") I can write to cells in "Sheet2". But if instead od "Sheet2" I put "Test_1" for example, then if I write to some cells in this sheet, this cannot be seen in Excel.

Only workaround I found is to create new sheets with name "SheetX" then do whatever you need and before saving use xslx.SetSheetName("Sheet2", "Test_1") for example.

**Comment by Luxurioust** [comment]
@rpokupec 
- You can use the `GetSheetMap()` function to get all sheets index and name map and use "Sheet" + index to set the cell value;
- You should be set cell value by `SetCellValue("Sheet2", ..., ...)` after doing `xlsx.NewSheet(2, "Test_1")`;
In other words, function `SetCellValue()` and some other functions are doesn't support set cell value or get rows by sheet name currently, it needs to take the form of "Sheet"+index as a parameter. Relate issue #25, #43, and #47.

**Comment by rpokupec** [comment]
Ok.
Thank you for the explanation.
