### ISSUE TITLE
Pivot Table: allow empty columns

### ISSUE THREAD

**Issue by dongnengyu** [360EntSecGroup-Skylar/excelize#511]
透视表生成方式是否可以参考下python的numpy库，我在项目中不需要列标签，但是这个工具库不允许不设置列标签，一旦列标签设置为空就会报错。

![image](https://user-images.githubusercontent.com/27957036/67489012-666c8180-f6a3-11e9-9f61-0b6be215cc2b.png)

下面是numpy的透视表生成方式
![image](https://user-images.githubusercontent.com/27957036/67489272-e266c980-f6a3-11e9-99b4-9180c050d011.png)

**Comment by xuri** [comment]
Hi @dongnengyu, thanks for your issue. I have added empty columns support for creating a pivot table. Please try to upgrade the library with the master branch code.
