### ISSUE TITLE
how to read data in batches??

### ISSUE THREAD

**Issue by codedart2018** [360EntSecGroup-Skylar/excelize#515]
1c,2G sever reads 200000 excel,memory is full.
```
f.GetRows("Sheet1")
error:
fatal error: runtime: out of memory
```
i want to read the data in batches and return an array to me.

i really hope
```
row, err:=f.GetRows("Sheet1", 1000)
```
thank you all

**Comment by xuri** [comment]
Hi @codedart2018, thanks for your issue. I close this and merge it into issue #146 is still discussing this feature.

**Comment by xuri** [comment]
Hi @codedart2018, I have made the function [`GetRow`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.GetRows) and [`Rows`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.Rows) read data as streaming. You can get all the data in the worksheet at once through `GetRows`, or read the data row by row using `Rows` and `Next` like this:

```go
// read top 10 rows
rows, err := f.Rows("Sheet1")
if err != nil {
    fmt.Println(err)
    return
}
for rows.Next() {
    count++
    if count > 10 {
        break
    }
    row, _ := rows.Columns()
    for _, colCell := range row {
        fmt.Print(colCell, "\t")
    }
    fmt.Println()
}
```

**Comment by codedart2018** [comment]
@xuri 旭日你好！这个方法我之前已经试过了！
在f.rows(“”)cpu拉满 内存就已经就爆
以下附点图
未启动服务前
![1](http://47.107.182.144/static/memory1.png)
启动服务后
![1](http://47.107.182.144/static/memory2.png)
目前我测试服务器是 1核2G，就算最终生产服务器4核8g我认为也会出现这个问题！真实我们可能一次性传30-50万数据到服务器上处理。如果多用户同一时间操作连续的cpu内存消耗 一样会导致cpu拉满 内存挤爆。

**Comment by xuri** [comment]
Hi @codedart2018, I have refactored the [`Rows`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.Rows) function, please try to upgrade the library with the master branch code.

**Comment by codedart2018** [comment]
think you! try on monday.
