### ISSUE TITLE
Set zoom scale for inserted picture

### ISSUE THREAD

**Issue by roamboy** [360EntSecGroup-Skylar/excelize#516]
添加图片无法自适应大小，不是原始大小，也不是按一定比例变化，原始图片宽和高被缩放的比例不一样

**Comment by xuri** [comment]
Hi @roamboy, thanks for your issue. You can set the zoom scale of the image by [`AddPicture`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.AddPicture) like this:

```go
err := f.AddPicture("Sheet1", "D2", "./image2.jpg", `{"x_scale": 0.5, "y_scale": 0.5}`)
if err != nil {
    fmt.Println(err)
}
```
