### ISSUE TITLE
Can't read generated file

### ISSUE THREAD

**Issue by JiBadBoy** [360EntSecGroup-Skylar/excelize#519]

**Comment by JiBadBoy** [comment]
该包导出的

![image](https://user-images.githubusercontent.com/15551658/69227333-9df41e00-0bbc-11ea-8a25-17347ac9b243.png)


工具导出的
![image](https://user-images.githubusercontent.com/15551658/69227346-a3e9ff00-0bbc-11ea-9d75-973003edd1d9.png)

**Comment by xuri** [comment]
Hi @JiBadBoy, thanks for your feedback. Could you provide the code and file attachment to reproduce the issue?
