### ISSUE TITLE
Problems with xlsm file using ActiveX elements after saving

### ISSUE THREAD

**Issue by dennisfleischmann** [360EntSecGroup-Skylar/excelize#521]
**Description**
We are using this library for copying data from source.xlsm file to destintation.xlsm file. The destintation.xlsm has some ActiveX Controls as well. After copying a cell value from source to destintation and saving it we opened it in Excel and it loses the ActiveX Control.

Instead it shows a shape with a macro connected/assigned to it.

A simple way to reproduce the same issue is the following

**Steps to reproduce the issue:**
1. Create a xlsm file with a ActiveX Control CommandButton 
2. Douple click on it and add an event handler
3. Use excelize library and change any cell value and save it

Example files
Original Source file(before saving)
https://www.dropbox.com/s/9glskdk2dwyl8xr/before_ws.xlsm?dl=0
After saving (A1 cell is set to hello)
https://www.dropbox.com/s/zoor0m6cjl7q7p2/after_ws.xlsm?dl=0

**Describe the results you received:**
ActiveX Controls changed to a shape and ActiveXControls are getting lost

**Describe the results you expected:**
ActiveX controls still persist and are functional 

**Output of `go version`:**
go1.12.6

**Excelize version or commit ID:**
da99334f
Mon Aug 19 16:52:14 2019

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Windows 7 and OS

**Comment by xuri** [comment]
Hi @dennisfleischmann, the link of the example source file is the same as the saved file.

**Comment by dennisfleischmann** [comment]
@Xuri Ah sorry. Done

**Comment by xuri** [comment]
Hi @dennisfleischmann, I have fixed it. Please try to upgrade the library with the master branch code.
