### ISSUE TITLE
cannot download v2.0.2 by go get

### ISSUE THREAD

**Issue by jasonYoge** [360EntSecGroup-Skylar/excelize#522]
**Description**

**Steps to reproduce the issue:**
1. try to download v2.0.0 by using command `go get -u github.com/360EntSecGroup-Skylar/excelize/v2 `

**Describe the results you received:**
``` golang

go: finding github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.2
go: downloading github.com/360EntSecGroup-Skylar/excelize v1.4.1
go: downloading github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.2
verifying github.com/360EntSecGroup-Skylar/excelize@v1.4.1: github.com/360EntSecGroup-Skylar/excelize@v1.4.1: reading https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/360!ent!sec!group-!skylar/excelize@v1.4.1: 410 Gone

```

**Describe the results you expected:**
I want to use this package in my project, but when I was trying to install this package into my project, golang shows me some verifying information ends with `410 Gone`.Did I do some thing wrong?

**Output of `go version`:**
go 1.13
```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Hi @jasonYoge, please delete go mod cache $GOPATH/pkg/mod/cache and try again. Ref #393, #403 and #488.

**Comment by jasonYoge** [comment]
Ok, It's already working now, thanks, by the way.

**Comment by mraxrorxon** [comment]
@xuri I work with corparative proxy, so I cannot download, please give me advice.
this go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/axror/.cache/go-build"
GOENV="/home/axror/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/axror/go/pkg/mod"
GONOPROXY="gitlab.hamkorbank.uz"
GONOSUMDB="gitlab.hamkorbank.uz"
GOOS="linux"
GOPATH="/home/axror/go"
GOPRIVATE="gitlab.hamkorbank.uz"
GOPROXY="http://172.25.102.107:3002"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/axror/go/src/examples/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2419782182=/tmp/go-build -gno-record-gcc-switches"

**Comment by ducknificient** [comment]
still having this error at version 2.8.0, `could not import github.com/xuri/excelize/v2 (no required module provides package "github.com/xuri/excelize/v2")`

**Comment by xuri** [comment]
@ducknificient which Go version you're using? Please try to reinstall after clean cache:

```bash
go clean -modcache
go mod tidy
```

**Comment by ducknificient** [comment]
thanks, my go version is `1.19.4`

weird thing is after i do go clean -modcache, i need to replace the import header from `github.com/360EntSecGroup-Skylar/excelize/v2"` to `"github.com/xuri/excelize/v2"`

**Comment by xuri** [comment]
The go module name of this library has been changed to `github.com/xuri/excelize/v2` since version 2.4.1, please using this new module name and also reference the issues #973, #1020 and #1079.

**Comment by john8329** [comment]
In my case it was necessary to update manually the version in go.mod, even `go get` wouldn't update it. Hope it helps.
