### ISSUE TITLE
生成 100000行 300列的excel文件时，内存占用的厉害，能达到10G+

### ISSUE THREAD

**Issue by zhaoche27** [360EntSecGroup-Skylar/excelize#523]
本人fork了，修改了一下，commit：https://github.com/zhaoche27/excelize/commit/bc59aa0e1fbcf8e99967c58ea5431dd096b97526

**Comment by zhaoche27** [comment]
通过预定容量，row 个数与 cell个数， 从 9G 变成 6G，且 耗时减少20秒

**Comment by xuri** [comment]
Hi @zhaoche27, thanks for your issue. I have added a [stream writer](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStreamWriter) for generating a new worksheet with huge amounts of data.
