### ISSUE TITLE
How to insure cell data correct(after set dataValidation)

### ISSUE THREAD

**Issue by GZLHZ** [360EntSecGroup-Skylar/excelize#525]
hello,
I want to check a excel is violated the dataValidation that I set in the excel.
Copy can break the dataValidation check in excel,so I want to check again by excelize.
But I couldn't find the check api,only find the set way.
Could you please tell me how to check it again?
Thank you.

**Comment by xuri** [comment]
Hi @GZLHZ, this library currently only supports setting data validation for the generated file. Data validation will be executed on runtime when you use Excel software to open the generated file.

**Comment by GZLHZ** [comment]
Ok,if it will be possible in the future?

**Comment by xuri** [comment]
Similar to issue #65, implementing a data validation would require a very large number of test cases would be several months of work involved. That's an interesting job and I will consider adding support for this feature later. I'll certainly accept that patch if somebody did that.

**Comment by GZLHZ** [comment]
I get it.Thanks for your reply.
