### ISSUE TITLE
f.formattedValue runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wubin1989** [360EntSecGroup-Skylar/excelize#529]
**Description**

**Steps to reproduce the issue:**
1. xlsx, err = excelize.OpenReader(resp.Body)
2. sheetName := xlsx.GetSheetName(xlsx.GetActiveSheetIndex())
3. rows, err = xlsx.GetRows(sheetName)

**Describe the results you received:**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb2c055]
goroutine 82
 [running]:
github.com/360EntSecGroup-Skylar/excelize/v2.(*xlsxC).getValueFrom(0xc0103d1348, 0xc0000ffb00, 0xc0002b80a0, 0x1, 0x0, 0x0, 0xc0103d1310)
/data/wubin/gopath/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.0.2/rows.go:214 +0xe5
github.com/360EntSecGroup-Skylar/excelize/v2.(*Rows).Columns(0xc03612e000, 0x0, 0x40, 0xc00013c000, 0x0, 0x0)
/data/wubin/gopath/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.0.2/rows.go:80 +0x1c9
github.com/360EntSecGroup-Skylar/excelize/v2.(*File).GetRows(0xc0000ffb00, 0xc000392360, 0x6, 0x1, 0x1, 0x14, 0x0, 0x0)
/data/wubin/gopath/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.0.2/rows.go:41 +0xe4
**Describe the results you expected:**
no panic and get rows
**Output of `go version`:**
```text
go version go1.12.6 linux/amd64
```

**Excelize version or commit ID:**
```text
v2.0.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by wubin1989** [comment]
[442.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3940610/442.xlsx)
This is test file.
Help!

**Comment by xuri** [comment]
Hi @wubin1989, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by wubin1989** [comment]
@xuri Many thanks!
