### ISSUE TITLE
Got accepted in Excelize Community Bridge mentorship program, but haven't been assigned any tasks, where should I start from?

### ISSUE THREAD

**Issue by rusrushal13** [360EntSecGroup-Skylar/excelize#534]
I have been accepted in the CNCF Community Bridge mentorship program but I haven't been assigned any tasks there! 
Can someone please assign me some tasks so that I can explore more :)

**Comment by xuri** [comment]
Contributions are welcome! Reference [Contributing Guidelines](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/CONTRIBUTING.md#quick-contribution-tips-and-guidelines).
