### ISSUE TITLE
v2.02 row len panic index out of range [23] with length 23

### ISSUE THREAD

**Issue by codedart2018** [360EntSecGroup-Skylar/excelize#537]
After upgrading, it is found that the row is the length of the actual field content. Instead of the length of the header. But no problems occurred in 2.0.1. This means that each line must be filled with content. Otherwise row[2] this method will fetch the data panic???

```	
//v2.0.1
for _, row := range rows {
	fmt.Println(len(row))
	fmt.Println("row:", row[24])
	fmt.Println()
}
```

```
//v2.0.2
for _, row := range rows {
	fmt.Println(len(row))
	fmt.Println("row:", row[24])
	fmt.Println()
}
```
will throw panic runtime error: index out of range [24] with length 24.
but actual length 36

**Comment by xuri** [comment]
Hi @codedart2018, thanks for your feedback, could you upload the .xlsx attachment?

**Comment by codedart2018** [comment]
http://47.107.182.144/policy.xlsx

**Comment by codedart2018** [comment]
row[24] 车损险 print row length result:24

**Comment by xuri** [comment]
Ref #456, after commit [ac91ca0](https://github.com/360EntSecGroup-Skylar/excelize/commit/ac91ca0ded4111ed9f22578d4a0570a9084c97b0), the length of each row returned by the GetRows method is no longer consistent with the widest column with a value in the worksheet. When reading the value of a row, you need to determine its length first, and I will add this change in the Release Notes of the next version.
