### ISSUE TITLE
[Feature request] Support to set major units of axis

### ISSUE THREAD

**Issue by byteman** [360EntSecGroup-Skylar/excelize#538]
![image](https://user-images.githubusercontent.com/517250/70971845-cea47600-20dc-11ea-943e-a5e1c4fcd712.png)

x轴的刻度能设置一个参数吗？比如50个点显示一个数字， 0,50,100，而不是现在这种自动的值

**Comment by byteman** [comment]
![image](https://user-images.githubusercontent.com/517250/70977057-1bda1500-20e8-11ea-87cd-f75aa82a2a08.png)


还有就是x轴本来是1-1000，结果这里只能显示到981，需要拉长后才能显示出来

**Comment by byteman** [comment]
![image](https://user-images.githubusercontent.com/517250/70977912-cd2d7a80-20e9-11ea-915f-2648d65703e3.png)

我找到了再这里可以设置间隔单位，我这里设置的100为间隔。怎么在go库总添加这个功能啦？求救大神啊，帮忙指导一下啊，被客户天天吹

**Comment by byteman** [comment]
大神，有什么思路可以提供一下吗？

**Comment by xuri** [comment]
Thanks for your issue. I'll add [`MajorUnit`](https://github.com/360EntSecGroup-Skylar/excelize/blob/4249dad8eaf8a6dee93fafeffe0bbbd794581ffe/xmlChart.go#L522) apply in the function [`drawPlotAreaValAx`](https://github.com/360EntSecGroup-Skylar/excelize/blob/4249dad8eaf8a6dee93fafeffe0bbbd794581ffe/chart.go#L1619) and [`drawPlotAreaCatAx`](https://github.com/360EntSecGroup-Skylar/excelize/blob/4249dad8eaf8a6dee93fafeffe0bbbd794581ffe/chart.go#L1573) recently.

**Comment by byteman** [comment]
大神，有时间计划吗？

**Comment by xuri** [comment]
Hi @byteman, I have added setting a major unit and tick label skip support for the chart. You can specify tick label skip property by `tick_label_skip` field in `y_axis` like this:

```go
{"y_axis": {"tick_label_skip": 100}}
```
