### ISSUE TITLE
How to save text without losing formatting? Possibly enhancement.

### ISSUE THREAD

**Issue by gitdlam** [360EntSecGroup-Skylar/excelize#54]
Hi hope all is well. Great work that i'm benefiting from so thanks very much.

With .SetCellValue(), .SetCellStr(), and .SetCellInt(), they make decisions about the alignment of the result, which is not bad per se.  I know i can use .SetCellStyle() afterwards. But it would be very handy to have a function that respects the existing style.  I wish to be able to set all the styles i need within an Excel file as a kind of report template, outside of Go, then use Go to populate it, and not even need to know what the styles are within my Go code.  For example a column that is already center-aligned, would be great if a function that can keep it center-aligned, or whatever the style might be, including font, color, date formatting, currency etc.

Something like a .SetCellValueWithStyleRetention().  Or is there already a way to achieve this with the existing functions?

**Comment by Luxurioust** [comment]
Thanks for your issue. I have tested that function `SetCellValue()`, `SetCellStr()`, `SetCellInt()`, and they won't affect the style (font family, color, underline, bold, and align) of cell, but may lose part of date formatting, currency settings of the cell. Please provide file attachments If you can.

**Comment by gitdlam** [comment]
Thanks for the quick response.  Attached are Book1.xlsx and Book2.xlsx.
I created Book1.xlsx outside of Go, then made a copy of it, which is Book2.xlsx.
Then i run the Go code (so to speak) on Book2.xlsx.
You are correct when the cells have existing content, but when the cells do not have existing content, that's when the functions appear to make those decisions.
[Book1.xlsx](https://github.com/Luxurioust/excelize/files/1028537/Book1.xlsx)
[Book2.xlsx](https://github.com/Luxurioust/excelize/files/1028538/Book2.xlsx)
[test_excel.go.txt](https://github.com/Luxurioust/excelize/files/1028544/test_excel.go.txt)

**Comment by gitdlam** [comment]
I'm using Excel 2010 in case that might be relevant.

**Comment by Luxurioust** [comment]
@gitdlam  I have fix it by adding column style predefined detection set cell functions.

**Comment by gitdlam** [comment]
Thanks so much @Luxurioust you're the best!!  :+1:
