### ISSUE TITLE
Creating dropdown list from values in another sheet

### ISSUE THREAD

**Issue by MrEncrypter** [360EntSecGroup-Skylar/excelize#541]
I'm trying to create a dropdown list in Sheet1 using values from sheet2. Not able to make it work. Is there any sample code for this?

`odv := excelize.NewDataValidation(false)

			xls.SetDefinedName(&excelize.DefinedName{
				Name: "__ListFormula__",
				RefersTo: "__hidden__!$A$1:$A$14",
			})
			err := odv.SetSqrefDropList("__ListFormula__", true)
			if err != nil{
				f.log.Errorf("Error setting droplist :%s",err.Error())
				return nil,err
			}
			odv.SetError(excelize.DataValidationErrorStyleStop, "Error", "Please select from the dropdown values.")
			odv.ShowErrorMessage = true
			odv.SetSqref("A1:A100")
			odv.ShowDropDown = true
			xls.AddDataValidation(sheet, odv)`

**Comment by MrEncrypter** [comment]
Figured the solution

**Comment by bluntdel** [comment]
> Figured the solution

What's the solution?
