### ISSUE TITLE
MergeCell example of docs gives error

### ISSUE THREAD

**Issue by simonstumpf** [360EntSecGroup-Skylar/excelize#543]
**Description**

Hi Guys
I'm trying to use your MergeCell function, however it always gives me an error. The Code is from your documentation: [Link](https://xuri.me/excelize/en/cell.html#MergeCell)
**Steps to reproduce the issue:**
1. Create simple code which will create an excel sheet (i got it from the docs)
2. Try to add this line: err := f.MergeCell("Sheet1", "D3", "E9")
3.

**Describe the results you received:**
f.MergeCell("Sheet1", "A1", "C2") used as value

**Output of `go version`:**
```text
go version go1.13.4 darwin/amd64
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
latest MacOS

**Comment by simonstumpf** [comment]
So I also get this error when I try to set a style..
`f.SetCellStyle("Sheet1", "A3", "A3", titlestyle) used as value`

**Comment by xuri** [comment]
Hi @simonstumpf, which version (or commit version) of the Excelize are you using? Does the error occur with an existing file or a newly created file? I have tested and it works well at master version code, please provides code and file attachment if you can.

**Comment by simonstumpf** [comment]
Well I don't know why but this works perfectly: 
`f.MergeCell("Sheet1", "D3", "E9")`
I just don't get why the example from the docs don't work
`err := f.MergeCell("Sheet1", "D3", "E9")`

**Comment by xuri** [comment]
I don't know what's the difference between them, so I'll close this issue, but I recommend handling the error of the function.
