### ISSUE TITLE
SetColWidth does not work

### ISSUE THREAD

**Issue by yanhaogoogle** [360EntSecGroup-Skylar/excelize#544]
代码设置宽度为50
`f.SetColWidth(Sheet1, "B", "B", 50)`
实现显示的效果是：
![微信截图_20191221170523](https://user-images.githubusercontent.com/5484163/71305842-48599e00-2414-11ea-90ef-61965bdb1ee2.png)

使用的是v2.0.2版本。使用的是wps打开查看的表格

**Comment by xuri** [comment]
Hi @yanhaogoogle, thanks for your feedback. Which version (or commit version) of the Excelize are you using?  I have tested with `WPS for macOS 1.7.0(2743) /  Windows 11.1.0.9339` and it works well at master version code, please provides code and file attachment if you can.

**Comment by yanhaogoogle** [comment]
excelize:v2.0.2     win10系统      wps版本:11.1.0.9339 - Release正式版本
代码如下:
`package main

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize/v2"
	"strconv"
)

func main() {

	Sheet1 := "Sheet1"

	f := excelize.NewFile()
	// 创建一个工作表
	index := f.NewSheet(Sheet1)
	// Set value of a cell.
	//合并A1到I1的单元格
	f.MergeCell(Sheet1, "A1", "I1")
	//设置单元格内容
	f.SetCellValue(Sheet1, "A1", "深圳市XXXXXXXXXX有限公司审核表")
	//设置第一行的高度是50
	f.SetRowHeight(Sheet1, 1, 50)
	//设置单元格内容中的文字大小，权重，对齐方式
	style, err := f.NewStyle(`{"font":{"bold":true,"size":20},"alignment":{"horizontal":"center","vertical":"center"}}`)
	if err != nil {
		fmt.Println(err)
	}
	f.SetCellStyle(Sheet1, "A1", "I1", style)

	//合并A12到I2的单元格
	f.MergeCell(Sheet1, "A2", "I2")
	//设置单元格内容
	f.SetCellValue(Sheet1, "A2", "xxxxx项目2019年度项目使用情况如下：")
	//设置第二行的高度是50
	f.SetRowHeight(Sheet1, 2, 30)
	//设置单元格内容中的文字大小，权重，对齐方式
	style2, err := f.NewStyle(`{"font":{"bold":true,"size":15},"alignment":{"vertical":"center"}}`)
	if err != nil {
		fmt.Println(err)
	}
	f.SetCellStyle(Sheet1, "A2", "I2", style2)

	//设置第二行的高度是50
	f.SetRowHeight(Sheet1, 3, 30)
	//设置单元格内容中的文字大小，权重，对齐方式
	style3, err := f.NewStyle(`{"font":{"size":10},"alignment":{"vertical":"center","horizontal":"center"}}`)
	if err != nil {
		fmt.Println(err)
	}
	f.SetCellStyle(Sheet1, "A3", "I3", style3)
	f.SetCellValue(Sheet1, "A3", "序号")
	f.SetCellValue(Sheet1, "B3", "时间")
	f.SetCellValue(Sheet1, "C3", "使用单位")
	f.SetCellValue(Sheet1, "D3", "工作内容")
	f.SetCellValue(Sheet1, "E3", "车牌号")
	f.SetCellValue(Sheet1, "F3", "设备型号")
	f.SetCellStr(Sheet1, "G3", "工作时间\n(小时)")
	f.SetCellValue(Sheet1, "H3", "单位/台班")
	f.SetCellValue(Sheet1, "I3", "结算金额")

	//设置b这一列宽度为100
	f.SetColWidth(Sheet1, "B", "B", 100)

	//设置单元格内容中的文字大小，权重，对齐方式
	style5, err := f.NewStyle(`{"font":{"size":12},"alignment":{"vertical":"center","horizontal":"center"}}`)
	if err != nil {
		fmt.Println(err)
	}
	f.SetColStyle(Sheet1, "A:I", style5)

	for i := 1; i < 30; i++ {
		f.SetCellInt(Sheet1, fmt.Sprintf("A%d", i+3), i)
		f.SetCellValue(Sheet1, fmt.Sprintf("B%d", i+3), fmt.Sprintf("2019-09-%d", 10+i))
		f.SetCellValue(Sheet1, fmt.Sprintf("C%d", i+3), fmt.Sprintf("第%d公司", i))
		f.SetCellValue(Sheet1, fmt.Sprintf("D%d", i+3), "工作内容")
		f.SetCellValue(Sheet1, fmt.Sprintf("E%d", i+3), fmt.Sprintf("粤ABC%d%d%d", i, i, i))
		f.SetCellValue(Sheet1, fmt.Sprintf("F%d", i+3), fmt.Sprintf("%d吨的项目", 24+i))
		f.SetCellValue(Sheet1, fmt.Sprintf("G%d", i+3), 10+i)
		f.SetCellValue(Sheet1, fmt.Sprintf("H%d", i+3), 1800)
		f_time, _ := strconv.ParseFloat(strconv.Itoa(10+i), 64)
		f.SetCellValue(Sheet1, fmt.Sprintf("I%d", i+3), fmt.Sprintf("时间:%.2f 金额:%.2f", (f_time + 3.5), (1800/8)*(f_time+3.5)))
	}

	f.SetActiveSheet(index)
	// Save xlsx file by the given path.
	err = f.SaveAs("./excel/file/Book1.xlsx")
	if err != nil {
		fmt.Println(err)
	}

	//f, err := excelize.OpenFile("./Book1.xlsx")
	//if err != nil {
	//	fmt.Println(err)
	//	return
	//}
	//// Get value from cell by given worksheet name and axis.
	//cell := f.GetCellValue("Sheet1", "B2")
	//
	//fmt.Println(cell)
	//// Get all the rows in the Sheet1.
	//rows := f.GetRows("Sheet1")
	//for _, row := range rows {
	//	for _, colCell := range row {
	//		fmt.Print(colCell, "\t")
	//	}
	//	fmt.Println()
	//}
}`


wps 显示:
[Book1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3993307/Book1.xlsx)

**Comment by yanhaogoogle** [comment]
@xuri

**Comment by yanhaogoogle** [comment]
@xuri golang ：1.13.5

**Comment by xuri** [comment]
Hi @yanhaogoogle, the range of `SetColStyle` conflict with `SetColWidth` in above code, need to set column style by segment like this:

```go
f.SetColStyle(Sheet1, "A", style5)
f.SetColStyle(Sheet1, "B", style5)
f.SetColStyle(Sheet1, "C:I", style5)
```

**Comment by yanhaogoogle** [comment]
@xuri 完美解决

**Comment by yanhaogoogle** [comment]
@xuri 
//给单元格先设置样式，然后再使用计算公式，样式失效了？
`	//设置单元格内容中的文字大小，权重，对齐方式
	style5, err := f.NewStyle(`{"font":{"size":12},"alignment":{"vertical":"center","horizontal":"center"}}`)
	if err != nil {
		fmt.Println(err)
	}
	f.SetColStyle(Sheet1, "I", style5)
`

`
formula :=fmt.Sprintf("(1800/8)*G%d", i+3)
f.SetCellFormula(Sheet1,fmt.Sprintf("I%d", i+3),formula)
`
