### ISSUE TITLE
无法读取带特殊格式的excel,只有一行数据但是GetRows耗时很久获取了多行

### ISSUE THREAD

**Issue by sniperZj** [360EntSecGroup-Skylar/excelize#545]
麻烦给看下是否excel有问题
https://pan.baidu.com/s/11G1zQNBQlXMXBgzcalda6Q
提取码8ei8

**Comment by xuri** [comment]
The attached XLSX file contains multi valid rows with null values ​​(files larger than 4MB), the function `GetRows` won't skip any valid rows.

**Comment by sniperZj** [comment]
thank you

**Comment by sniperZj** [comment]
thank you
