### ISSUE TITLE
[Feature Request] Set marker options support of scatter chart

### ISSUE THREAD

**Issue by byteman** [360EntSecGroup-Skylar/excelize#549]
大神，求加一个设置散点图点的粗细设置功能
![image](https://user-images.githubusercontent.com/517250/71552070-47d29000-2a30-11ea-95f7-4f306c5c865b.png)

**Comment by xuri** [comment]
Hi @byteman, sorry for my late reply. I'll add a setting marker for chart support, please use the master branch code, and this feature will be released in the next version. Also, reference #657.
