### ISSUE TITLE
Removing available formatting after adding additional (for example color).

### ISSUE THREAD

**Issue by dematron** [360EntSecGroup-Skylar/excelize#55]
Hello. First of all I really grateful for your work.

Don't know bug or not, but I found some strange behavior of func SetCellStyle.
If I already have some formating, for example borders, and I try to add for example red color to cell, I loosing borders.
May be it is normal, but in this way it would be useful to have func like AddCellStyle or something similar.

**Comment by Luxurioust** [comment]
Thanks for your suggestion. I will consider enhancement.

**Comment by haynesherway** [comment]
seconded!

**Comment by xuri** [comment]
This issue has been resolved, relate issue #420 and #425.
