### ISSUE TITLE
SetColWidth changes font in the column

### ISSUE THREAD

**Issue by Chillance** [360EntSecGroup-Skylar/excelize#550]
Hi,

I'm running v2.0.2 and when I do:

```go
	f := excelize.NewFile()

	index := f.NewSheet("TestSheet")
	f.SetColWidth("TestSheet", "B", "B", 20)

	f.SetCellValue("TestSheet", "B2", "Hello there!")
	f.SetActiveSheet(index)
	// f.SetDefaultFont("Liberation Sans")

	if err := f.SaveAs("Book1.xlsx"); err != nil {
		println(err.Error())
	}
```

it changes the width, but also seems to have "Calibri" font, and now 11px size and not 10px which seems to be the default for me. I open the file in LibreOffice. If I also do the commented out row there, it goes back to what seems to be the default font for me.

I would expect it to not change the font, so what am I missing here? Oh, and yes, not doing the SetColWidth it doesn't change the font.

Thanks!

**Comment by focusonline** [comment]
seems excelize is unable to deal with format of cell. only reading and writing string value

**Comment by Chillance** [comment]
Are you able to reproduce the issue?

**Comment by xuri** [comment]
Hi @Chillance, "Calibri" is the default font for new worksheets. I have tested and it works well at version 2.0.2, have you tried using the latest code on the master branch? or provide a `.xlsx` file attachment.

**Comment by xuri** [comment]
Hi @Chillance, it seems still not have enough info on this issue,  I'll close this issue, if you have any questions, please let me know.
