### ISSUE TITLE
Empty rows out of order when reading a file with empty rows

### ISSUE THREAD

**Issue by dosaki** [360EntSecGroup-Skylar/excelize#551]
**Description**
A table that is "padded" with rows before the data will somehow place those empty rows intercalated with the data rows, rather than placing them at the top. See below for an example.

**Steps to reproduce the issue:**
Given you have a table that is padded like below:
<table>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>A</td>
<td>B</td>
</tr>
<tr>
<td></td>
<td>1</td>
<td>2</td>
</tr>
<tr>
<td></td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td></td>
<td>5</td>
<td>6</td>
</tr>
<tr>
<td></td>
<td>7</td>
<td>8</td>
</tr>
</table>

 When you do
```go
excel, _ := excelize.OpenFile("/path/to/file.xlsx")
rows, _ := excel.GetRows("sheet-name")
```
You'll find that `rows` looks like:
```
nil
A B
nil
1 2
nil
3 4
5 6
7 8
```

**Describe the results you received:**
```
nil
A B
nil
1 2
nil
3 4
5 6
7 8
```

**Describe the results you expected:**
```
nil
nil
nil
A B
1 2
3 4
5 6
7 8
```

**Output of `go version`:**

```text
go version go1.13.5 linux/amd64
```

**Excelize version or commit ID:**

```text
5f3a4bc39f9cf2987104ffe57242a0526cdd9158
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```
$ uname -a
Linux metztli 5.4.5-arch1-1 #1 SMP PREEMPT Wed, 18 Dec 2019 19:48:51 +0000 x86_64 GNU/Linux
```

**Comment by dosaki** [comment]
Tried another scenario and the problem also happens.

For a table looking like below:
<table>
<tr>
<td></td>
<td>A</td>
<td>B</td>
</tr>
<tr>
<td></td>
<td>1</td>
<td>2</td>
</tr>
<tr>
<td></td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>5</td>
<td>6</td>
</tr>
<tr>
<td></td>
<td>7</td>
<td>8</td>
</tr>
</table>

I get:
```
A B
1 2
3 4
nil
5 6
nil
7 8
nil
```

When I expect to see
```
A B
1 2
3 4
nil
nil
nil
5 6
7 8
```

**Comment by xuri** [comment]
Hi @dosaki, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by dosaki** [comment]
Wow, thanks man!
