### ISSUE TITLE
excelize cannot read more than 64 lines in excel sheet

### ISSUE THREAD

**Issue by chaudharisuresh997** [360EntSecGroup-Skylar/excelize#552]
**Description**

**Steps to reproduce the issue:**
1.When I use this code 
**f, err := excelize.OpenFile("sample.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}

	rows, err := f.GetRows("Sheet1")**
The rows are captured till line number 64 in excel the rows in excel after 64 are not captured how to read all rows in sheet.This is such a strange issue
3.

**Describe the results you received:**
liabrary is not able to read more than 64 rows 
**Describe the results you expected:**
Liabrary should read all the lines in present sheet.
**Output of `go version`:**
go version go1.12.5 linux/amd64
```go version go1.12.5 linux/amd64
```

**Excelize version or commit ID:**
1666d04559d9f5b579ab7c850ccc95863c31bd25
```1666d04559d9f5b579ab7c850ccc95863c31bd25
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Ubuntu 19.10  (VirtualBox)
Host is Windows 10

**Comment by xuri** [comment]
Hi @chaudharisuresh997, please provides file attachments if you can.

**Comment by xuri** [comment]
I will close this issue, if the problem was still is gone, please provides more details and reopen this issue.

**Comment by chaudharisuresh997** [comment]
if you save the file by opening with liberoffice and saving it using microsoft office compatible encoder then u will see this issue

**Comment by xuri** [comment]
Please provide file attachments without sensitive info, which will helpful for me quickly resolve the issue.
