### ISSUE TITLE
Unable to use file.SetDefinedName()

### ISSUE THREAD

**Issue by vaishnaniamisha** [360EntSecGroup-Skylar/excelize#553]
Hi,

I am using v1.4.1 and trying to set Define Name for range of cells.

```
        f := excelize.NewFile()
	index := f.NewSheet("Sheet1")
	f.SetActiveSheet(index)

	f.SetCellValue("Sheet1", "A2", "Category")
	f.SetCellValue("Sheet1", "A3", "SubCategory")
	f.SetCellValue("Sheet1", "A4", "ProductName")

	f.SetDefinedName(&excelize.DefinedName{
		Name:     "Sheet1",
		RefersTo: "Sheet1!$A$2:$A$4",
		Comment:  "comment",
		Scope:    "workbook",
	})

	if err := f.SaveAs("Book2.xlsx"); err != nil {
		println(err.Error())
	}
```

I am getting below compilation error: 
generatetemplate/generatexls.go:23:3: f.SetDefinedName undefined (type *excelize.File has no field or method SetDefinedName)
generatetemplate/generatexls.go:23:20: undefined: excelize.DefinedName

so am I missing something or is there any other way to implement this.

Thanks,

**Comment by xuri** [comment]
Hi @vaishnaniamisha `SetDefineName` required your excelize 2.0.1 or later.
