### ISSUE TITLE
When create excel, memory using is very large; how to fix this?

### ISSUE THREAD

**Issue by Stanley3** [360EntSecGroup-Skylar/excelize#555]
In below picture, ```excelize.completeCol``` uses very much memory.
![image](https://user-images.githubusercontent.com/7970394/72075692-3726f180-332f-11ea-8f41-d1e1c42c87d9.png)
Is there a way to solve this?

**Comment by xuri** [comment]
Hi @Stanley3, I have added a [stream writer](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStreamWriter) for generating a new worksheet with huge amounts of data. Ref #29 and #523.

**Comment by Stanley3** [comment]
> Hi @Stanley3, I have added a [stream writer](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStreamWriter) for generating a new worksheet with huge amounts of data. Ref #29 and #523.

When I use streamer writer to create an excel, memory using also is very large. Have any other ways to fix this? This file approximately has 700w lines.
![image](https://user-images.githubusercontent.com/7970394/72323837-9a74a300-36e4-11ea-8386-48e0d67fa5f0.png)

**Comment by xuri** [comment]
Hi @Stanley3, Excel 2019 / Office 365 cannot exceed the limit of 1048576 rows. could you split your data into several worksheets?

**Comment by Stanley3** [comment]
> Hi @Stanley3, Excel 2019 / Office 365 cannot exceed the limit of 1048576 rows. could you split your data into several worksheets?

Yes, i have splited data into different sheets.
The core code like this:
```golang
for batchReportData := range rowData {
		//log.Debugf("esRsp.ResultChan rowData =%+v", rowData)
		for _, rowData := range batchReportData {
			genOneRow(f, streamWriter, sheetName, row, styleTitle, reportHeaders, rowData)
			current++
			row++
			if row >= 65535 {
				if err := streamWriter.Flush(); err != nil {
					log.Errorf("flush sheet failed, sheetName: %s, error: %s", sheetName, err)
					return "", err
				}
				sheetCount++
				sheetName = "Sheet" + strconv.Itoa(sheetCount)
				f.NewSheet(sheetName)
				streamWriter, err = f.NewStreamWriter(sheetName)
				if err != nil {
					log.Errorf("new stream writer failed, sheetName: %s, error: %s", sheetName, err)
					return "", err
				}
				row = 1
				WriteSheetTitle(reportHeaders, f, streamWriter, sheetName, row, styleTitle)
				row++
			}
		}
if err := streamWriter.Flush(); err != nil {
		log.Errorf("flush all sheets failed, error: %s", err)
		return "", err
	}
```
After that, I wolud get bytes from execel file, just like 
```
fileName = fileName + ".xlsx"
buffer, err := f.WriteToBuffer()
bytes := buffer.Bytes()
```
So, are there any problems about those codes?

**Comment by xuri** [comment]
Hi @Stanley3, please create stream writer for each worksheet: 

```go
package main

import (
	"fmt"
	"math/rand"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
	file := excelize.NewFile()
	for i := 2; i <= 7; i++ {
		file.NewSheet(fmt.Sprintf("Sheet%d", i))
	}
	for i := 1; i <= 7; i++ {
		streamWriter, err := file.NewStreamWriter(fmt.Sprintf("Sheet%d", i))
		if err != nil {
			println(err.Error())
		}
		for rowID := 1; rowID <= 1000000; rowID++ {
			row := make([]interface{}, 10)
			for colID := 0; colID < 10; colID++ {
				row[colID] = rand.Intn(640000)
			}
			cell, _ := excelize.CoordinatesToCellName(1, rowID)
			if err := streamWriter.SetRow(cell, row); err != nil {
				println(err.Error())
			}
		}
		if err := streamWriter.Flush(); err != nil {
			println(err.Error())
		}
	}
	if err := file.SaveAs("Book1.xlsx"); err != nil {
		println(err.Error())
	}
}
```
