### ISSUE TITLE
当单元格的值为1.1时,获取单元格的值和原始不一样

### ISSUE THREAD

**Issue by lragon** [360EntSecGroup-Skylar/excelize#558]
**Description**

使用代码获取单元格值,得到的结果和excel表不一致
![image](https://user-images.githubusercontent.com/2757255/72506496-f3773f00-387c-11ea-8a21-1fd3f1c8f6dc.png)
原始表格如上图
代码如下
```
excelHandler,_ := excelize.OpenFile("test.xlsx")
sheetMap := excelHandler.GetSheetMap()
sheet := sheetMap[1]
s,_ := excelHandler.GetCellValue(sheet, "A1")
fmt.Printf(s)
```
打印结果为
`1.1000000000000001`
附件
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/4070045/test.xlsx)
**Steps to reproduce the issue:**
如上所述

**Describe the results you received:**
输出`1.1000000000000001`
**Describe the results you expected:**
输出`1.1`
**Output of `go version`:**

```text
go version go1.13.5 windows/amd64
```

**Excelize version or commit ID:**

```text
v2

```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10,Excel 2016

**Comment by lragon** [comment]
表格中的其他值正常，只有1.1有问题

**Comment by xuri** [comment]
Hi @lragon, thanks for your feedback. I have analyzed the attachment, this XLSX file contains the unusual value of the cell. You need to handle numerical precision yourself. Could you tell me which version of Excel that created this file?

**Comment by lragon** [comment]
Excel 2016,I think it's excel soft problem,this happened when I try other xlsx library.
