### ISSUE TITLE
Loosing of auto formatting rules after using UpdateLinkedValues

### ISSUE THREAD

**Issue by dematron** [360EntSecGroup-Skylar/excelize#56]
Hello. First of all I really grateful for your work.

Found some strange behaviour of func UpdateLinkedValue.
I have two sheets - first with real data and second with linked data from first one.
On the second sheet with linked data I use auto formatting rules. In my situation it is adding background color to cell depends on percentage, for example red background if 90% and more.

If I don't using UpdateLinkedValues I don't loose auto formatting, but linked data doesn't update.
If I using UpdateLinkedValues I loose auto formatting, but linked data updates.

**Comment by Luxurioust** [comment]
Hi dematron, thanks for your issue. . I have to add conditional formatting support for worksheet to fix this issue.

**Comment by dematron** [comment]
Cool. Thanks. Work really better. But still one moment.
If I have multiple rules for one cell, I suppose it's because of that, they don't apply as expect.
For example
I have an auto rule - 90% red color, 90%-70% yellow color, less then 70% green color.
After using UpdateLinkedValue(), linked cells updats but value in source cell is for example 20%, but color in linked cell is red (for some reasons, I don't know why).
If I after that in Excel change value in source cell from 20% to for example 80%, I see yellow color in linked cell (as expected).

**Comment by Luxurioust** [comment]
I have tested that and it works well. Please provide file attachments If you can.

**Comment by dematron** [comment]
In attachment two files:
First - is a template, which is used for adding data
Second - is the result file after adding data to cells and using UpdateLinkedValue
Sheet 7 is the result aggregated file with linked cells and auto formatting rules.
[result.xlsx](https://github.com/Luxurioust/excelize/files/1028744/result.xlsx)
[template.xlsx](https://github.com/Luxurioust/excelize/files/1028745/template.xlsx)

**Comment by Luxurioust** [comment]
I found that all cell linked value is string type, they don't apply as expect conditional formatting. Such as: H8 on Sheet 7, linked value is H8 on Sheet 3, but `'3'!H8` is string type, use `SetCellValue("Sheet3", "H8", 0.12)` to make it works well.

**Comment by dematron** [comment]
I tried your variant but with no success :(
I attache an example, similar to what I use.
First I found that I become to loose formatting (suppose because of that fix #54 )
Second I still can't reach need result - percent on source sheet3 and linked sheet7. And colors of course.
Suppose, I use your code not correctly. But where?
You can repeat what I do by rename template.xlsx to result.xlsx, and apply the code.
[temp.go.txt](https://github.com/Luxurioust/excelize/files/1031136/temp.go.txt)

**Comment by Luxurioust** [comment]
What format is missing after fix issue #54? I have try to run `temp.go` to write `result.xlsx`(renamed by `template.xlsx`). I suggest that replace `value, _ := strconv.ParseInt(strconv.FormatFloat(data, 'f', 0, 64), 10, 64)` with `value := data / 100`, and format cell for the percentage that needs to retain two decimal precision (`0.00%` build index is `10`) such as `'3'!H5:H11` by function `SetCellStyle()`.

**Comment by dematron** [comment]
For some reasons, after running temp.go file, result is like an attached file.
Formatting on Sheet3 in column G is lost (I mean borders).
If I checkout to - 7c3f91ada483194018fca95c6caae03b22247d52, and run code again - borders are on their places.
[result.xlsx](https://github.com/Luxurioust/excelize/files/1034897/result.xlsx)

**Comment by Luxurioust** [comment]
I have changed to using cell style priority when the cell and the column at the same time with the style attribute.

**Comment by dematron** [comment]
Perfectly well! I suppose this issue can be marked as closed.
Also I should say that percent cell also work as expected.
For me
`"number_format": 9,`
in SetCellStyle, and
`SetCellValue(sheet, cell, value/100.00)`
were the solution.
May be it is the normal behaivour of Excel, to make percents in cell as Value * 100%, but for me it was really surprised.
May be it will be helpful for others if you add some demo code, how to work with percent cells.
Again thanks for your work.
