### ISSUE TITLE
Incorrect multiline in one cell

### ISSUE THREAD

**Issue by dmp73** [360EntSecGroup-Skylar/excelize#563]
Code example:
          xlsx.SetCellValue("Sheet1", "A1", "abcdef")
          exist, err := xlsx.GetCellValue("Sheet1", "A1")
          add := "ABCDEF"
          xlsx.SetCellValue("Sheet1", "A1", exist + "\n" + add)

When I open it in Excell I see:
abcdefABCDEF
instead of:
abcdef
ABCDEF
After press F2/Enter on A1 cell becomes as it should.
If you get inside xlsx before and after F2/Enter, you'll see:
```
    abcdef&#xA;ABCDEF
    abcdef♪◙ABCDEF
```
Usage \r\n gives the same result when open in Excell.
go version go1.13 windows/amd64
Excelize fresh version after today go get -u
Windows 7, Excell 2013

**Comment by dmp73** [comment]
I found previous similar issues and understood what the problem is.
The only way at the moment is to mark the cell field so that they are in sharedStrings.xml
by copy multiline cell to other cells and than delete it.

**Comment by GZLHZ** [comment]
hello, I have a same problem.

**Comment by GZLHZ** [comment]
hi, @dmp73 .
I think set a style can solve our problem, and I test it.

```
style, _ := xlsx.NewStyle(`{"alignment":{"wrap_text":true}}`)
xlsx.SetCellStyle("Sheet1", "A1", "A1", style)
```

**Comment by dmp73** [comment]
Thanks. It works.
