### ISSUE TITLE
SetCellFormula produces a bad formula if you use quotes

### ISSUE THREAD

**Issue by af-engineering** [360EntSecGroup-Skylar/excelize#566]
Formula: `=TEXTJOIN(", ", TRUE, UNIQUE(SORT(C11:C88)))`

If I set this formula in Excel, unzip the xlsx file and look at the sheet XML, I see

`<f>_xlfn.TEXTJOIN(", ", TRUE, _xlfn.UNIQUE(_xlfn._xlws.SORT(C11:C88)))</f>`

If I set the same formula using Excelize, I see

`<f>=TEXTJOIN(&#34;, &#34;, TRUE, UNIQUE(SORT(C11:C88)))</f>`

There may be other differences elsewhere that also effects this.

**Comment by xuri** [comment]
Hi @af-engineering, thanks for your feedback, which version of the Excelize are you using? Please try to use the master branch code. The [SORT](https://support.office.com/en-us/article/sort-function-22f63bd0-ccc8-492f-953d-c20e8e44b86c) function is one of several beta features, and currently only available to a portion of Office Insiders at this time.

**Comment by af-engineering** [comment]
We were using v2.0.2, but I just switched to master and it results in the same error. Here's what happens when you try to open the file:

<img width="532" alt="Screen Shot 2020-01-22 at 10 07 09 AM" src="https://user-images.githubusercontent.com/48225624/72920898-167f7400-3cff-11ea-9f71-7cd79535383b.png">

**Comment by xuri** [comment]
Hi @af-engineering, try to using `=_xlfn.TEXTJOIN(", ", TRUE, _xlfn.UNIQUE(_xlfn._xlws.SORT(C11:C88)))` in the `SetCellFormula` function, I have tested and it works well. If not, please provide file attachments without sensitive info, and version of your Excel application.

**Comment by af-engineering** [comment]
That does work. Thanks for the workaround.
