### ISSUE TITLE
Corrupted file after adding new table /xl/tables/table1.xml part (Table)

### ISSUE THREAD

**Issue by korvinko** [360EntSecGroup-Skylar/excelize#567]
**Description**

**Steps to reproduce the issue:**
1. 
Add new table and save to xlsx file: 
`f.AddTable(sheet, "A1",  "K9", `{"table_name":"opportunities","table_style":"TableStyleMedium2", "show_row_stripes":true}`)`

2.
Open file from Excel 2016

3.
You should see the error:
Repaired Records: Table from /xl/tables/table1.xml part (Table)
![1](https://user-images.githubusercontent.com/2064465/73001212-24beb480-3e13-11ea-910f-759233a681d3.png)

**Describe the results you received:**
Repaired Records: Table from /xl/tables/table1.xml part (Table)

**Describe the results you expected:**
Do not see errors when I open generated file  

**Output of `go version`:**

```text
go version go1.13 linux/amd64
```

**Excelize version or commit ID:**

```text
v1.4.1 and v2.0.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Microsoft Excel 2016

**Comment by xuri** [comment]
Hi @korvinko, thanks for your feedback. Does the issue occur when creating a new spreadsheet or opening an existing file? I have tested base on your code on v2.0.2 and master, and it works well. Could you provide file attachments without sensitive info?

**Comment by korvinko** [comment]
@xuri Hi. I`ve created a new file.  

Example of this file:
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/4107323/test.xlsx)

**Comment by xuri** [comment]
Hi @korvinko. Please set the header row data of table before calling the AddTable function. I will add this note in the documentation.

**Comment by korvinko** [comment]
Yes, it works now. Thanks.
