### ISSUE TITLE
SetColWidth doesn't correct

### ISSUE THREAD

**Issue by GZLHZ** [360EntSecGroup-Skylar/excelize#569]
**Description**
Hello,
SetColWidth's point is not same as the excel's point.

```
func SetColWidth() {
	f, _ := excelize.OpenFile("SetColWidth.xlsx")
	f.SetColWidth("Sheet1", "A", "A", 10.75)
	f.Save()
}
```

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/45257277/73602529-6c320700-45b0-11ea-8c3b-6b5a003d5b42.png)

**Describe the results you expected:**
10.75

**Output of `go version`:**

```text
go version go1.13.7 windows/amd64
```

**Excelize version or commit ID:**

```text
Commits on Jan 23, 2020 (new master)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
win10, office2019(1912)
```

**Comment by xuri** [comment]
Hi @GZLHZ, This issue similar width #279, the column width in the Excel relate width DPI (Ref: [Description of how column widths are determined in Excel](https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-column-widths), [DPI and Device-Independent Pixels](https://docs.microsoft.com/en-us/windows/win32/learnwin32/dpi-and-device-independent-pixels) and ECMA 376 Part1 18.3.1.13). The `SetColWidth` function in this library won't check DPI, the value of the column width will be set as is. So the same document will be shown differently on different OS and display devices. You need to calculate the width to fit the platform, for example, using the Calibri font as an example, the maximum digit width of 11 point font size is 7 pixels (at 96 dpi)

```go
SetColWidth("Sheet1", "A", "A", math.Trunc((10.75*7+5)/7*256)/256)
```

**Comment by GZLHZ** [comment]
Thank you for your explain.I will check it again.🤝
