### ISSUE TITLE
SetCellValue to a Go Time type causes saving of .xlsx file to degrade dramatically.

### ISSUE THREAD

**Issue by sanoanalytics** [360EntSecGroup-Skylar/excelize#57]
I have set the cells (approx. 300) as text i.e. "05-29-17" and the .xlsx file, it saves in seconds... When I set the cells to a Go Time type and save the .xlsx file, it takes almost a minute! -- Anyhow, it's a Great package! Thanks for sharing!

**Comment by Luxurioust** [comment]
Function `SetCellValue()` need to handle, parse and convert julian date and gregorian time formats in Excel when set the time type value, that will impact library performance and I will optimize it appropriate.

**Comment by sanoanalytics** [comment]
Thank you for the awesome package. You should have a 'Donate Now' button somewhere. I would gladly send you a beer!
