### ISSUE TITLE
Cannot SetColStyle and SetColWidth at the same time

### ISSUE THREAD

**Issue by GZLHZ** [360EntSecGroup-Skylar/excelize#570]
**Description**
Cannot SetColStyle and SetColWidth at the same time

**Steps to reproduce the issue:**
```
func SetColWidthAndSetStyle() {
	new_excel := excelize.NewFile()
	center_style, _ := new_excel.NewStyle(`{"alignment":{"horizontal":"center","vertical":"center"}}`)

	new_excel.SetColStyle("Sheet1", "A:Z", center_style)
	new_excel.SetColWidth("Sheet1", "A", "A", 11)

	new_excel.SaveAs("SetColWidthAndStyle.xlsx")
}
```

**Describe the results you received:**
B-Z(col) is center_style, but A(col) is not.
A(col)'s width changed.

if I SetColWidth first:
A-Z(col) is center_style.
A(col)'s width not changed.

**Describe the results you expected:**
A-Z(col) is center_style.
A(col)'s width changed.

**Output of `go version`:**
```text
go version go1.13.7 windows/amd64
```

**Excelize version or commit ID:**
```text
2020.02.04 new master.
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
win10(1909), office2019(2001)

**Comment by xuri** [comment]
Hi @GZLHZ, thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code. This fix will be in the next release v2.1.0.

**Comment by GZLHZ** [comment]
@xuri , oh yeah, it's done.Thank you so much.

**Comment by GZLHZ** [comment]
@xuri , hi, could you please add a donate way by Alipay?
![image](https://user-images.githubusercontent.com/45257277/74006182-d504ef00-49b5-11ea-920e-ec50c5b506bd.png)

**Comment by xuri** [comment]
Thank you very much. Welcome to donate this project via the one-time donations:

- [One time Donations](https://github.com/360EntSecGroup-Skylar/excelize/wiki/One-time-Donations)
- [Contributing to Excelize](https://xuri.me/excelize/zh-hans/contribution.html)

**Comment by GZLHZ** [comment]
Oh.It's so inconspicuous.😂 And I donated yet.😁
