### ISSUE TITLE
How to clear up conditional style

### ISSUE THREAD

**Issue by GZLHZ** [360EntSecGroup-Skylar/excelize#571]
**Description**
hello, I have checked the document,but I can't find a way to clear up the conditional style
,only I can do is SetConditionalFormat.And it says this api has no default value.
Could you please tell me how to finish this?
Thank you.

**Comment by mvanwaaijen** [comment]
was looking for the same.

**Comment by xuri** [comment]
Hi @GZLHZ, @mvanwaaijen,  I have initialized remove conditional format support. Please try to upgrade the library with the master branch code.

```go
UnsetConditionalFormat("Sheet1", "A1:A10")
```

**Comment by GZLHZ** [comment]
Thank you so much.😀

**Comment by mvanwaaijen** [comment]
Thanks!
