### ISSUE TITLE
Set Column Width and Cell Height

### ISSUE THREAD

**Issue by Zerowalker** [360EntSecGroup-Skylar/excelize#573]
As title says, it would be nice if you could set the width of the columns,
 (as in how much text is visible on the width of that column).
And settings the height of the cell (allowing multiple rows to be shown).

I don't think it's possible at the moment, but i might be wrong.

Thanks:)!

**Comment by xuri** [comment]
Did you mean AutoFit(set the column width to automatically fit the contents)? Ref: #92.

**Comment by Zerowalker** [comment]
Yeah that too, and setting it to whatever i want.

**Comment by xuri** [comment]
I close this and merge it into issue #92 is still discussing this feature.
