### ISSUE TITLE
Provide API for convert time formatted cell into time.Time or time.Duration

### ISSUE THREAD

**Issue by dlintw** [360EntSecGroup-Skylar/excelize#575]
**Description**

Provide API for convert time formatted cell into time.Time or time.Duration.

Like ConvExcelStrToTime(), ConvExcelStrToDuration().

**Steps to reproduce the issue:**
1. I use GetRows(), it return [][]string
2. For time data in Excel, it show like a real number in string format

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
1.13.7
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by hexbioc** [comment]
This was merged in #592. I've exported a function `ExcelDateToTime` that returns a `time.Time` instance.

**Comment by xuri** [comment]
Hi @hexbioc, I have merged the `master` branch into `v2`.

**Comment by mandeepkhatry** [comment]
@dlintw In runtime, is there a way to find if the integer is an actual integer or from date? Something like FindFormat(string) that returns "integer" or "date"
