### ISSUE TITLE
is there any example for dynamic create header and col ?

### ISSUE THREAD

**Issue by ibantoo** [360EntSecGroup-Skylar/excelize#577]
take a look from example from the document 
```
func main()  {
		f := excelize.NewFile()

		// Create a new sheet.
		index := f.NewSheet("Sheet2")

		// Set value of a cell.
		f.SetCellValue("Sheet2", "A2", "Hello world.")
		f.SetCellValue("Sheet1", "B2", 100)

		// Set active sheet of the workbook.
		f.SetActiveSheet(index)

		// Save xlsx file by the given path.
		if err := f.SaveAs("Book1.xlsx"); err != nil {
			c.JSON(400, gin.H{
				"error": err,
			})
		}
}
```

should we always use the axis to create row ? 
how about if we have JSON like this 
```
[
  { "name": "Hello", "age": 56, "city": "NYC"},
  { "name": "Hello 2", "age": 23, "city": "TX"},
  { "name": "Hello 3", "age": 46, "city": "MO"}
]
```

we know that the key has 3 keys, for hardcode we could do this  for Header
```
f.SetCellValue("Sheet1", "A1", "name.")
f.SetCellValue("Sheet1", "B1", "age")
f.SetCellValue("Sheet1", "C1", "city")
```
how about if that keys more than that and ? we should write more line to add they key ? ( hard code ) 
and for the value of tha header we should do axis A2, A3, A3 and so on......

is there any function to create dynamic header? and col? I have checked the testing codes and i have not seen any function like that? if you have a fucntion like that and i miss that? can i know where is that? so i can know the example and take a look :)
thank you :)

**Comment by xuri** [comment]
Hi @ibantoo, [CoordinatesToCellName](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#CoordinatesToCellName) converts [X, Y] coordinates to alpha-numeric, we can use that in the iterator. In addition, [SetSheetRow](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetSheetRow) writes an array to row by given worksheet name.
