### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [360EntSecGroup-Skylar/excelize#579]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/360EntSecGroup-Skylar/excelize)](https://www.tickgit.com/browse?repo=github.com/360EntSecGroup-Skylar/excelize)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/360EntSecGroup-Skylar/excelize)](https://www.tickgit.com/browse?repo=github.com/360EntSecGroup-Skylar/excelize)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by xuri** [comment]
Thanks for your issue. The [tickgit.com](https://www.tickgit.com) provides useful tools that find TODOs, but I have already listed more details [roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki#roadmap)in the project wiki page.

**Comment by patrickdevivo** [comment]
Understood! Thanks for your consideration
