### ISSUE TITLE
Pivot Data Type: Allow Sum/Count/Avarage

### ISSUE THREAD

**Issue by qin-nz** [360EntSecGroup-Skylar/excelize#582]
在 Excel 里， Pivot 表可以对值类型选择需要的操作，比如计数、求和、平均值

![image](https://user-images.githubusercontent.com/6998071/74823831-565b6a80-5342-11ea-8a40-37b74577d7b1.png)

```
excelize.PivotTableOption{
        DataRange:       "Sheet1!$A$1:$E$31",
        PivotTableRange: "Sheet1!$G$2:$M$34",
        Rows:            []string{"Month", "Year"},
        Columns:         []string{"Type"},
        Data:            []string{"Sales"},
    }
```
是不是应该增加一个 
```
   DataType:            []string{"Count"},
```

**Comment by xuri** [comment]
Hi, @qin-nz, thanks for your issue. I have added support for setting date field subtotal and names of the pivot table. Please try to upgrade the library with the master branch code.

**Comment by qin-nz** [comment]
@xuri `Data` is slice of string, so `DataSubtotal` should also be slice instead of string.
Excel allow different data use different fo subtotal type.

**Comment by xuri** [comment]
I have added a new structure PivotTableField to holde pivot table fields for better scalability, which caused API changes. In addition, two or more fields in Data are not supported currently.
