### ISSUE TITLE
Does the FORECAST.ETS function not support?

### ISSUE THREAD

**Issue by yms2772** [360EntSecGroup-Skylar/excelize#585]
**Description**

**Describe the results you received:**
I use FORECAST.ETS and read using excelize. But it shows nothing (Blank).
I already use UpdateLinkedValue() function.

**Describe the results you expected:**

**Output of `go version`:**

```text
1.13
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Hi @yms2772, thanks for your feedback. Please to using `_xlfn.FORECAST.ETS` instead of `FORECAST.ETS` in the `SetCellFormula` function, also ref: #566.

**Comment by yms2772** [comment]
> Hi @yms2772, thanks for your feedback. Please to using `_xlfn.FORECAST.ETS` instead of `FORECAST.ETS` in the `SetCellFormula` function, also ref: #566.

When I use `_xlfn.FORECAST.ETS` in `SetCellFormula`? Read or write?
I already used that function at read and write, but it show nothing still.

**Comment by xuri** [comment]
Using `_xlfn.FORECAST.ETS` when you set formula with `SetCellFormula` and we can't get the computed value by this lib currently, because this library doesn't implement the formula calculation engine. Reference issue #65, #157 and #198.
