### ISSUE TITLE
Duplicate function doesn't duplicate merged cells

### ISSUE THREAD

**Issue by Aibaend** [360EntSecGroup-Skylar/excelize#586]
Hello, Today I want to fill template excel, and I find somekind of bugs,
Duplicate function of this libary doesn't duplicate merged cells.

For  example suppose  that 
for first row  A and B merged, 
and If I duplicate first row
result will be unmerged A and B

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.
