### ISSUE TITLE
SetCellStyle Not Working (v2.1.0)

### ISSUE THREAD

**Issue by djneely** [360EntSecGroup-Skylar/excelize#588]
**Description**

Working to bold and align center the text of the cell. No errors are being reported but the final file does not have the text formatted nor aligned

**Steps to reproduce the issue:**

```
style, err := file.NewStyle(`{"alignment":{"horizontal":center"},{"font":{"bold":true,"italic":true}}`)
err = file.SetCellStyle("Sheet1", "A2", "A2", style)
```

**Describe the results you received:**

text not centered. text not bold nor italic

**Describe the results you expected:**

text centered, bold, and italic

**Output of `go version`:**

go version go1.13.4 darwin/amd64

**Excelize version or commit ID:**

github.com/360EntSecGroup-Skylar/excelize/v2 v2.1.0

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
![Screen Shot 2020-02-27 at 3 00 21 PM](https://user-images.githubusercontent.com/981157/75482501-f5034f00-5972-11ea-92ab-a1be04f1dfb9.png)

**Comment by xuri** [comment]
Hi @djneely, the JSON format of the specified style is invalid, please check the error return value of the function `NewStyle`. The valid JSON like this:

```json
{"alignment":{"horizontal":"center"},"font":{"bold":true,"italic":true}}
```

**Comment by djneely** [comment]
Thank you so much. Sorry to have bugged you about that. Must have gone cross-eyed while looking at it and i thought I was handling the error but looking at it today I was not. Thanks again.

**Comment by leedstyh** [comment]
Handwriting of style json is a nightmare, why not provide a "static language" way to do it. And doc says excelize have some struct like `Alignment` but failed to find it.

**Comment by xuri** [comment]
The structure of style has been exported on the master branch code, and it will be released in the next version. Also ref: [example](https://xuri.me/excelize/en/example/calendar.html).
