### ISSUE TITLE
Feature request: Auto filter

### ISSUE THREAD

**Issue by pjmuller** [360EntSecGroup-Skylar/excelize#59]
Hi Luxurioust,

first of all, AWESOME library. Got it up and running in no time thanks through the great documentation.

You know what would make excelize even better? Having a way to enable auto filter. I've searched around and it should be possible. See http://xlsxwriter.readthedocs.io/working_with_autofilters.html

I dug around a bit in the python source code and most of the logic is defined here https://github.com/jmcnamara/XlsxWriter/blob/master/xlsxwriter/worksheet.py#L1472 (however I don't understand a whole lot of it... ) Hopefully you do  

I'm not an advanced enough go developer to create a good PR, but would be very grateful if you could add this feature to excelize.

**Comment by Luxurioust** [comment]
@pjmuller Thanks for your issue. I have initialized auto filter support.

**Comment by pjmuller** [comment]
@Luxurioust Wow, great work! Thanks a lot.

I started to use it (just as `err = xlsx.AutoFilter("Sheet1", "A1", "D4", "")` without any extra filters).

Is this production ready? Because you wrote "I have initialized ...", does this mean this is work in progress? On my side everything seems to work. = AWESOME

**Comment by Luxurioust** [comment]
Yes, production ready and I will add support for setting a column list filter later.
