### ISSUE TITLE
multiple-value xlsx.GetRows() in single-value context

### ISSUE THREAD

**Issue by QasimLi666** [360EntSecGroup-Skylar/excelize#591]
Hello,

I am testing the code:

func main() {

var JSONdata = openJSONFile(os.Args[1])

// Open our xlsx

xlsx, err := excelize.OpenFile("./RoboterListeRegensburg.xlsx")

if err != nil {

	fmt.Println(err)

}

sheetName := "Roboter"

    var stringRowNumber = strconv.Itoa(len(xlsx.GetRows(sheetName)) + 1)

xlsx.SetCellValue(sheetName, "A"+stringRowNumber, JSONdata.Project)

xlsx.SetCellValue(sheetName, "B"+stringRowNumber, JSONdata.ENumber)

But I am getting an error on line: var stringRowNumber = strconv.Itoa(len(xlsx.GetRows(sheetName)) + 1)
The error is: multiple-value xlsx.GetRows() in single-value context

I am using golang version 36.3 on windows 10.

Can somebody help?

best,
Li

**Comment by xuri** [comment]
Hi @QasimLi666, an error will return of the GetRows function since version `v2.0.0`, please checking [release note](https://github.com/360EntSecGroup-Skylar/excelize/releases/tag/v2.0.0) get more API changed details.

to get rows of the worksheet in your code:

```go
rows, err := xlsx.GetRows(sheetName)
```
