### ISSUE TITLE
Does not add comments with few lines of text

### ISSUE THREAD

**Issue by SavostinVladimir** [360EntSecGroup-Skylar/excelize#594]
**Description**
Does not add comments with few lines of text

**Steps to reproduce the issue:**
```golang
f.AddComment("mySheet", "A1", 				`
{"Author": "darvin:", 
"Text": " line
a new line
an another new line"}`)
```

**Describe the results you received:**
`invalid character '\n' in string literal`
**Describe the results you expected:**
added comment to cell
**Output of `go version`:**

```text
go version go1.12.9 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.1.0
```

**Comment by xuri** [comment]
Hi @SavostinVladimir, a new line is denoted using `\r\n`:

```go
f.AddComment("mySheet", "A1", `
{"Author": "darvin:",
"Text": " line\r\na new line\r\nan another new line"}`)
```
