### ISSUE TITLE
Problems with xlsm file using ActiveX elements after saving

### ISSUE THREAD

**Issue by sachin-puranik** [360EntSecGroup-Skylar/excelize#600]
This issue is same as old issue #521
Even the data and issue description , including test case remains the same.
This has started to happen again.

**Comment by xuri** [comment]
Hi @sachin-puranik, thanks for your feedback, could you upload the .xlsx attachment?

**Comment by sachin-puranik** [comment]
Ok I will do it. I will test once again with latest one and give you feedback

**Comment by xuri** [comment]
Hi @sachin-puranik, it seems still not have enough info on this issue,  I'll close this issue, if you have any questions, please let me know.
