### ISSUE TITLE
Read data by chunk

### ISSUE THREAD

**Issue by Insua** [360EntSecGroup-Skylar/excelize#607]
读取一个好几万数据的表，不分段读取，而是一次都读进去，太耗费内存和时间了，如果一次就读几百行 就会大幅度的节省时间了 有这个接口和方法吗？

**Comment by xuri** [comment]
The [`Rows`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.Rows) return a rows iterator, used for streaming reading data for a worksheet with a large data

**Comment by Insua** [comment]
> The [`Rows`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.Rows) return a rows iterator, used for streaming reading data for a worksheet with a large data

I test it, use Rows still load all rows to memory, how can I just read pagination rows?

**Comment by xuri** [comment]
Which version of Excelize are you using, and how many data in your spreadsheet, how many memory cost? Please use the latest version 2.1.0, and details the issue by the template.

**Comment by xuri** [comment]
Hi @Insua, it seems still not have enough info on this issue,  I'll close this issue, if you have any questions, please let me know.
