### ISSUE TITLE
something err when i try this:go get github.com/360EntSecGroup-Skylar/excelize

### ISSUE THREAD

**Issue by zhuodayeso** [360EntSecGroup-Skylar/excelize#616]
The err information: package golang.org/x/net/html/charset: unrecognized import path "golang.org/x/net/html/charset" (https fetch: Get https://golang.org/x/net/html/charset?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by zhuodayeso** [comment]
help me, please

**Comment by xuri** [comment]
Please check the network or install via proxy.
