### ISSUE TITLE
Maybe you can help

### ISSUE THREAD

**Issue by meitarzon** [360EntSecGroup-Skylar/excelize#618]
I tried creating a pivot table and noticed that it's not defined, apparently I have version v1.4.1
I'm using go modules and my go version is 1.13
When trying to get the latest version manually I get this message:
require github.com/360EntSecGroup-Skylar/excelize: version "v2.1.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

Any suggestions on how to fix this issue?

**Comment by xuri** [comment]
If your package management with Go Modules, please install with following command:

```go
go get github.com/360EntSecGroup-Skylar/excelize/v2@v2.1.0
```
