### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by vchugreev** [360EntSecGroup-Skylar/excelize#62]
Hello.

Please help me with date substitution and formatting. There is an xlsx file (template), it has a field of type Date, it has a format, for example: 14-Mar-12

Using the library, I substitute my date value, for example: 2017-06-23 14:04:05 I expect that the inserted date will be of the specified format, but it is not. The inserted value is displayed unchanged: 2017-06-23 14:04:05

If start Excel, open the saved file and double-click on this field, it is converted according to the specified format. How to do this with your library?

Is there an analog UpdateLinkedValue() to update the date according to the format specified in the template?

Thank you!

**Comment by Luxurioust** [comment]
Thanks for your issue, I have update the library with handle pre-defined number format set of cell when set cell value with `time.Time` data type.

**Comment by vchugreev** [comment]
Excellent, great thanks! Our project is rescued :). On Monday at work I'll try a new version.
P.S. Wonderful library!

**Comment by vchugreev** [comment]
How to set the date correctly? If I use
xlsx.SetCellValue ("Sheet1", "D7", time.Now())
I get ######

**Comment by Luxurioust** [comment]
Try to adjust the width of the column to make it display normally.

**Comment by vchugreev** [comment]
Excuse me, in Excel I'm a noob :). Everything worked out. Thank you!

**Comment by pjmuller** [comment]
Hi @Luxurioust , when passing time.Time it indeed works but when later I do a setCellStyle for a very big range (where some, not all, columns have date values) 

`xlsx.SetCellStyle("Sheet1", "A1", "ZZ100", `{"alignment":{"wrap_text":true}}`)`

I lose the date formatting. Is there a way how I can ADD extra formatting (the wrap_text in this case) rather than OVERWRITING them?

**Comment by Luxurioust** [comment]
The new style will overwrite the old style, because function `SetCellStyle()` doesn't support append styles currently, so please set the style at once or set the style in batches for different area if you can.

**Comment by xuri** [comment]
This issue similar to #660 and #759. I close this and merge it into issue #660 is still discussing this feature.
