### ISSUE TITLE
Cell type of strings always set to "string formula"

### ISSUE THREAD

**Issue by gmolau** [360EntSecGroup-Skylar/excelize#622]
It seems that this library [always sets](https://github.com/360EntSecGroup-Skylar/excelize/blob/2285d4dc718fb8b96c3b2291c63b39c57468b0b9/cell.go#L281) the type of string cells to `str`, which actually represents formulas that return strings, the type for raw strings seems to be [`s`](https://stackoverflow.com/a/18346273/6330511). This can cause unexpected issues when parsing the files with another library, I think it would at the very least be good to document this [here](https://xuri.me/excelize/en/cell.html#SetCellStr).

**Steps to reproduce the issue:**
1. Set a plain string cell
2. Inspect the cell type [here](https://github.com/360EntSecGroup-Skylar/excelize/blob/2285d4dc718fb8b96c3b2291c63b39c57468b0b9/xmlWorksheet.go#L463), it will be `str`, not `s`
3. As this library has no way to read the cell type one has to parse it with another one, e.g. [tealeg/xlsx](https://github.com/tealeg/xlsx), but this then reports the cell type as [`StringFormula`](https://github.com/tealeg/xlsx/blob/f3d06514e56a280930f763ce24580be48b9876c9/cell.go#L26), not the expected `String`.

**Output of `go version`:**

```text
go version go1.13 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.1.0
```

**Comment by xuri** [comment]
Thanks for your issue. I had fixed it by making save the string in the shared string table.
