### ISSUE TITLE
GetRows/Rows Picks up Empty Rows

### ISSUE THREAD

**Issue by NoelHG** [360EntSecGroup-Skylar/excelize#623]
**Description**

GetRows/Rows allocating memory for empty rows increasing memory usage or stalling completely

**Steps to reproduce the issue:**
1. Get excel from multipart
2. Print out the rows (example code works)

**Describe the results you received:**
Picks up, allocates, and prints empty rows. This is a bit annoying because excel files often have tons of empty rows. The file I got as a test had over 1 million empty rows in it, and kept causing my local server to crash. The file itself was only about 5mb big. The issue is I cannot stop users from uploading these files with empty rows. Max file size doesn't help because a 5 mb file is enough to store over 1m empty rows.

**Describe the results you expected:**
Expected to ignore empty rows

**Output of `go version`:**
```text
go version go1.13.4 darwin/amd64
```

**Excelize version or commit ID:**

```text
v1.4.1
```

**Comment by xuri** [comment]
Thanks for your feedback. Please upgrade lib to the last version. GetRows/Rows read as stream since [v2.1.0](https://github.com/360EntSecGroup-Skylar/excelize/releases).

**Comment by ddemoss222** [comment]
Any additional workaround for this issue? It's happening for me version 2.3.0. A sheet with 7300 rows is getting this from fmt.Println(len(rows)):
`1048576`

**Comment by ddemoss222** [comment]
Update: GetRows is still manifesting the undesired behavior. An unsatisfying workaround is to iterate through the rows using:
`for rows.Next()`
and for my use case break when:
`len(rows.Columns()) == 0`
Not very robust, but if this can help someone else this is why I've posted it.

**Comment by joaowiciuk** [comment]
Still having the same problem on version 2.3.1

**Comment by NoelHG** [comment]
On one hand, empty rows are technically valid and are correctly represented in the file.  It doesn't seem like the ideal default behavior, though, since generally empty rows are not useful. The stream should fix any memory issues. To ignore the rows, there are a few simple workarounds. The one posted by ddemoss222 should work just fine. I just checked if the "Id" cell was empty instead.
