### ISSUE TITLE
Add picture from url

### ISSUE THREAD

**Issue by gdg87** [360EntSecGroup-Skylar/excelize#624]
Hello,
I try to add images from url but I give the following error

`stat: <url>: no such file or directory`

I have to download it and then add or there is way to import from url?

Thanks

**Comment by xuri** [comment]
Please download the picture and insert it to the spreadsheet by [`AddPictureFromBytes`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.AddPictureFromBytes).
