### ISSUE TITLE
StreamWriter Formula

### ISSUE THREAD

**Issue by bconn98** [360EntSecGroup-Skylar/excelize#625]
Hello,

While switching to using the new StreamWriter, I can't seem to figure out how to use formulas as I SetRow.

Any help would be great

**Comment by bconn98** [comment]
Current workaround I am using is not using the template and building each sheet as I go, but I can seem to find a way to merge cells or add formulas.

**Comment by bconn98** [comment]
I assume this means that there is no current work around for this.

**Comment by xuri** [comment]
Yes, the library doesn't support setting formula for cell in streaming API, in the current version. I have added this feature request to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki).

**Comment by civil-defence** [comment]
Hello. Can you also add into roadmap support of AutoFilter and SetColWidth functions for streaming API?

**Comment by xuri** [comment]
I have added this feature request to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki).
