### ISSUE TITLE
Allow multiple Rows to be Hidden

### ISSUE THREAD

**Issue by Edinsonmyosa** [360EntSecGroup-Skylar/excelize#626]
Hi I´m using this to restrict a sheet, so, I don't have any problem with hiding colums but there's no option to do the same with rows, it has to be one by one and takes much more time.

Could you tell me if there's another way to do it not using "SetRowVisible" but something that allows to hide more rows in one instruction?

**Comment by elbuki** [comment]
This could be solved by modifying the method `SetRowVisible` to take a variadic argument to pass multiple row numbers. What do you think @xuri ?

If that sounds good by you, I could take care of this with a PR.

**Comment by xuri** [comment]
Sorry, after evaluation and follow the principle of least availability, I don't purpose to add this API. The hidden attributes of multiple hidden columns can be stored in an element (Ref: ECMA-376 Part 1 §18.3.1.13)， but hidden rows will set hidden attributes on each row (§18.3.1.73), `SetRowsVisibility` is same as calling `SetRowVisible` multiple times. So I'll close PR and related issues.

hidden columns

```xml
<cols>
    <col min="5" max="8" width="0" hidden="1" customWidth="1"/>
</cols>
```

hidden rows

```xml
<sheetData>
    <row r="10" hidden="1"/>
    <row r="11" hidden="1"/>
</sheetData>
```

**Comment by Edinsonmyosa** [comment]
Hi, I don´t know exactly how it works but if I create a file hiding rows using _SetRowVisible_ the size increase from 97KB to 2676KB. Then I created a file using excel to hide the whole rows to the same document and its size is 98KB. Could you please tell me if there is another way to use _SetRowVisible_  without adding that ammount of additional size?

**Comment by xuri** [comment]
I will add API to support set worksheet format properties directly to support hide all rows, no need to hide each row.

**Comment by xuri** [comment]
Hi @Edinsonmyosa, I just added set worksheet format properties support. You can hide all rows like this:

```go
if err := f.SetSheetFormatPr("Sheet1", excelize.ZeroHeight(true)); err != nil {
    fmt.Println(err)
}
```

**Comment by Edinsonmyosa** [comment]
I just tried it and it´s exactly what I needed. 
It's being really usefull
Thank you so much!!
