### ISSUE TITLE
ThousandSeperator doesn't work after SaveAs a new excel

### ISSUE THREAD

**Issue by GZLHZ** [360EntSecGroup-Skylar/excelize#628]
**Description**

original excel:
1.origin state:
![image](https://user-images.githubusercontent.com/45257277/81071479-5ddce980-8f17-11ea-9410-4e3f4217a2fd.png)

2.click general
![image](https://user-images.githubusercontent.com/45257277/81071531-6fbe8c80-8f17-11ea-8d0c-0755eefcbfa1.png)

3.and then click thousand seperator
![image](https://user-images.githubusercontent.com/45257277/81071575-7e0ca880-8f17-11ea-95d4-e02dd0aa6dc1.png)

4.The number turn back to thousandSeperator.It's right.
![image](https://user-images.githubusercontent.com/45257277/81071669-a09ec180-8f17-11ea-87eb-399359933658.png)

after saveAs a new excel:
1.origin state:
![image](https://user-images.githubusercontent.com/45257277/81071479-5ddce980-8f17-11ea-9410-4e3f4217a2fd.png)

2.click general
![image](https://user-images.githubusercontent.com/45257277/81071851-dba0f500-8f17-11ea-8f9f-931728b73e0e.png)

3.and then click thousand seperator
![image](https://user-images.githubusercontent.com/45257277/81071911-f70c0000-8f17-11ea-8a94-6ac47101a2ed.png)

4.It's not work,that's the problem. Thank you.
Still at 1800.
![image](https://user-images.githubusercontent.com/45257277/81072031-1dca3680-8f18-11ea-932b-9057f4d029d7.png)

**Steps to reproduce the issue:**
```
func ThousandSeperator() {
	f, _ := excelize.OpenFile("ThousandSeperator.xlsx")
	f.SaveAs("ThousandSeperator_new.xlsx")
}
```
[ThousandSeperator.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/4581022/ThousandSeperator.xlsx)

**Describe the results you received:**
Not same as the original excel

**Describe the results you expected:**
Same as the original excel

**Output of `go version`:**

```text
go1.13.7 windows/amd64
```

**Excelize version or commit ID:**

```text
2020.05.05 master
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
win10,office2019

**Comment by GZLHZ** [comment]
Thank you!

**Comment by xuri** [comment]
Thanks for your donation. I have added you're into the [donator page](https://github.com/360EntSecGroup-Skylar/excelize/wiki/One-time-Donations#thanks).

**Comment by GZLHZ** [comment]
😁😁

**Comment by GZLHZ** [comment]
@xuri Hi,here has a follow-up questions:
click thousand seperator cause the style disappear after SaveAs function.

click:
![image](https://user-images.githubusercontent.com/45257277/81494175-3bf9b300-92d9-11ea-90de-f82aa643043d.png)

then:
![image](https://user-images.githubusercontent.com/45257277/81494178-474cde80-92d9-11ea-9861-22673150757f.png)
