### ISSUE TITLE
Convert arbitrary coordinates

### ISSUE THREAD

**Issue by vchugreev** [360EntSecGroup-Skylar/excelize#63]
Maybe it will come in handy for someone else...

I did not have enough functions in the library to convert arbitrary coordinates i, k (x, y) to the address of the cell. I took advantage of this decision: https://stackoverflow.com/a/32532049

Golang:

```
func toCell(i int) string {
   if i < 0 {
      return ""
   }
   return toCell((i/26)-1) + string(65+i%26)
}
```

Using:
```

cell := toCell(i)
cur := fmt.Sprintf("%s%v", cell, k+1)
```

**Comment by Luxurioust** [comment]
Unexported function [`toAlphaString()`](https://github.com/Luxurioust/excelize/blob/db4aff04fdfdd0459f1dcf5b0540a820dd8ea34e/lib.go#L53-L66) uses a similar implementation in the library.

**Comment by vchugreev** [comment]
Did not know. Thanks for the info. Very useful functionality when working together with other js xlsx libraries (there is usually a numerical numbering). Maybe it makes sense to make it exportable?! As an helper…

**Comment by Luxurioust** [comment]
Function `FormattedValue()` has been exported.

**Comment by vchugreev** [comment]
Thank you!

**Comment by vchugreev** [comment]
> titleToNumber provides function to convert Excel sheet column title to int.

If I understood correctly, then this is an inverse function. Can it also be exported?

**Comment by Luxurioust** [comment]
Sure, function `TitleToNumber()` has been exported now.

**Comment by vchugreev** [comment]
Excellent. Thank you!
