### ISSUE TITLE
SetColWidth freezes application

### ISSUE THREAD

**Issue by Jeeyb** [360EntSecGroup-Skylar/excelize#630]
**Description**

SetColWidth freezes application
_ = file.SetColWidth("file", "F", "N", 20)

**Describe the results you received:**
Nothing

**Output of `go version`:**

go version go1.14 darwin/amd64

**Excelize version or commit ID:**

github.com/360EntSecGroup-Skylar/excelize/v2 v2.1.0

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
macOS Catalina 10.15.1 (19B88) and Ubuntu 18.04.3 LTS

**Comment by xuri** [comment]
Thanks for your feedback. Do you create a new file or open an existing spreadsheet before setting the column width? I have tested and it works well. Please check the error returned by `SetColWidth`.

**Comment by Jeeyb** [comment]
I create new file. I cant event fetch error, cause the function does not end.
![SetColWidth freeze](https://user-images.githubusercontent.com/23462145/81403823-e5f00880-913c-11ea-95a0-b0e3a1e7e56e.gif)
Sorry for quality of gif, github support inly 10mb files.

**Comment by Jeeyb** [comment]
Sorry, issue fixed. The problem was not from library side 😅
