### ISSUE TITLE
why I Cannot find the color data corresponding to the grid pattern

### ISSUE THREAD

**Issue by huanlingkeji** [360EntSecGroup-Skylar/excelize#631]
I searched the file.style structure and did not find the corresponding RGB value

**Comment by xuri** [comment]
Did you mean that set the cell background color or pattern? Please reference [Set cell style](https://xuri.me/excelize/en/cell.html#SetCellStyle) and [Create style](https://xuri.me/excelize/en/style.html#NewStyle).

**Comment by huanlingkeji** [comment]
![企业微信截图_15889279749493](https://user-images.githubusercontent.com/43662114/81389584-a9c4a400-914c-11ea-991c-249b96b2407b.png)
![企业微信截图_15889280285478](https://user-images.githubusercontent.com/43662114/81389592-ab8e6780-914c-11ea-8522-244f13bd16e3.png)
![企业微信截图_15889280809179](https://user-images.githubusercontent.com/43662114/81389597-acbf9480-914c-11ea-8358-af47d3828ed8.png)


I want  to find the cell background color data  ,rgb value.
but I cant find it in file.styles structure while I debug the process

**Comment by xuri** [comment]
Please reference: [ThemeColor](https://xuri.me/excelize/zh-hans/utils.html#ThemeColor)

**Comment by huanlingkeji** [comment]
I thought I could directly find the color corresponding to the grid, but I did n’t expect it to be so troublesome ，thanks
