### ISSUE TITLE
Is there a way to trigger updates to formulas?

### ISSUE THREAD

**Issue by gresbtim** [360EntSecGroup-Skylar/excelize#634]
We have a spreadsheet that has millions of checks. for example `=IF(SUM(R26:Z26)=1,"Sum=100%","Shares don't sum up tp 100%")`  basically a check that sums are 100%.

We do fill 0.75 and 0.25 as values, but if we open the spreadsheet, the error message shows up in that cell. if we click on the 0.75 cell and insert 0.75 again, then the check is 100% and valid.

to me it seems that the formulas are'nt updated on open/save.

is there a way to trigger something like this?

**Comment by xuri** [comment]
Call [UpdateLinkedValue](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.UpdateLinkedValue) before saving the file, it will make Excel update linked value after open spreadsheet.

**Comment by gresbtim** [comment]
my hero <3
