### ISSUE TITLE
 GetSheetIndex description issue

### ISSUE THREAD

**Issue by andvary** [360EntSecGroup-Skylar/excelize#635]
**Description**

There is a mismatch in GetSheetIndex description[ here](https://xuri.me/excelize/en/workbook.html#GetActiveSheetIndex) and [here](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.GetSheetIndex).

The first one claims the function returns "0" for a non-existing sheet, in the second one it is "-1". As far as I can conclude from testing it myself, the correct one is "0"

**Output of `go version`:**

```text
go version go1.14.2 windows/amd64
```

**Excelize version or commit ID:**

```text
2.1.0
```

**Comment by xuri** [comment]
Thanks for your feedback, the correct one is "0". I will fix it.
