### ISSUE TITLE
AutoFilter will freeze the excel window

### ISSUE THREAD

**Issue by weeee9** [360EntSecGroup-Skylar/excelize#637]
**Description**

AutoFilter will freeze the excel window.

**Steps to reproduce the issue:**

1. Create a new file and insert some value to Sheet1, set autofilter to header row
 (ex. `f.AutoFilter("Sheet1", "A1", "E1", "")` ) then save the file.

2.  Open file, choose `Sort A to Z` (or Z to A) on the filter and the excel window will freeze, can't do anything.
(but if choose some text filter first then sort won't cause this problem)

**Output of `go version`:**

```text
go version go1.13.5 windows/amd64
```

**Excelize version or commit ID:**

```text
excelize v2.2.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Happened on both Excel 2007 and 2013 (don't know if other version would happen too)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by weeee9** [comment]
Hi, thanks for the nice work,
but there is a problem after upgraded to the master branch, don’t known if related.

I have a web app that let user download excel, and the ‘autofilter’ works fine at the first download, then it will get ‘Removed Feature: Named range from /xl/workbook.xml part (Workbook)’ error for every downloaded excel, any thought?
