### ISSUE TITLE
Failed to copy a sheet between two files.

### ISSUE THREAD

**Issue by wenj1104** [360EntSecGroup-Skylar/excelize#640]
**Description**

**Steps to reproduce the issue:**
I used following code to copy a sheet from A.xlsx to B.xlsx.
In B.xlsx, destination sheet, I can not found any content.
How should I copy a sheet between two files?

```go
func copyOneSheet(f *excelize.File) error {
	srcFile, err := excelize.OpenFile("A.xlsx")
	if err != nil {
		return err
	}

	srcSheet := srcFile.Sheet["source"]

	desFile, err := excelize.OpenFile("B.xlsx")
	if err != nil {
		return err
	}
	
	desFile.NewSheet("destination")
	desFile.Sheet["destination"] = srcSheet
	return nil
}
```

**Excelize version or commit ID:**

```text
98221a332ff9c37c9b20c44e9efdbe4c22a5cf5c
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
`Excel2019`

**Comment by wenj1104** [comment]
Am I doing it right? Is there any other methods to copy a sheet between two files?

**Comment by xuri** [comment]
This library doesn't support operation cross spreadsheets currently, this issue similar to also  #41, #532, #574, and #629.
