### ISSUE TITLE
function to get the next column

### ISSUE THREAD

**Issue by so-jelly** [360EntSecGroup-Skylar/excelize#641]
**Description**

I want to get the next column..   X+1=Y.   Z+1=AA.   I wrote a function for this but PR guidelines say I need to submit an issue.

I threw the function in a gist for review.   I wrote some tests for it as well.

https://gist.github.com/so-jelly/00d287b1080489eaaa2a614ac0f1cb4a

I haven't had a need to decrement yet, but it would not be too much work to wiggle that in.

**Comment by xuri** [comment]
We can convert between column name and index with [ColumnNameToNumber](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#ColumnNumberToName) and [ColumnNumberToName](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#ColumnNumberToName).

**Comment by so-jelly** [comment]
Nice, that looks a little cleaner than my approach.  Cheers!
