### ISSUE TITLE
about text style

### ISSUE THREAD

**Issue by huanlingkeji** [360EntSecGroup-Skylar/excelize#645]
my code:-------------------------------------------------------------------------
package main

import (
	"github.com/360EntSecGroup-Skylar/excelize/v2"
	_ "github.com/mohae/deepcopy"
	"os"
	"strconv"
)

import (
	_ "fmt"
)

var strs = []string{"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"}

func main() {
	path, _ := os.Getwd()
	f, _ := excelize.OpenFile(path + "\\file4.xlsx")
	style, _ := f.NewStyle(`{"fill":{"type":"pattern","color":["#E2EFD9"],"pattern":1}}`)
	for i := 15; i <= 208; i++ {
		axis := "A" + strconv.Itoa(i)
		f.SetCellInt("data", axis, 104024)
		f.SetCellStyle("data", axis, axis, style)
	}
	f.Save()
}
my question:-------------------------------------------------------------------------
![说明](https://user-images.githubusercontent.com/43662114/83093723-8d27e600-a0d2-11ea-8b84-e67d534b1136.png)
my describes:-------------------------------------------------------------------------
xlsx initial
![0](https://user-images.githubusercontent.com/43662114/83093814-bf394800-a0d2-11ea-969c-555f0852bb31.png)
the first situation
![11](https://user-images.githubusercontent.com/43662114/83093856-d5470880-a0d2-11ea-82cb-1618c29a5b3e.png)
![12](https://user-images.githubusercontent.com/43662114/83093861-d8da8f80-a0d2-11ea-9eff-d74265ab7ccf.png)
the second situation
![21](https://user-images.githubusercontent.com/43662114/83093879-e55ee800-a0d2-11ea-83d0-4394c815b0f7.png)
![22](https://user-images.githubusercontent.com/43662114/83093882-e728ab80-a0d2-11ea-8c1a-4c89dbd07ddd.png)

**Comment by xuri** [comment]
Which version of Excelize are you using, could you provide non-confidential information attachment?

**Comment by huanlingkeji** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xuri"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 中午11:10
收件人:&nbsp;"360EntSecGroup-Skylar/excelize"<excelize@noreply.github.com&gt;;
抄送:&nbsp;"杨玉胜 服务器开发"<892544825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [360EntSecGroup-Skylar/excelize] about text style (#645)





 
Which version of Excelize are you using, could you provide non-confidential information attachment?

**Comment by huanlingkeji** [comment]
![可能原因](https://user-images.githubusercontent.com/43662114/83108658-b2c4e780-a0f2-11ea-8612-41d3efc01b51.png)
may be bug is in here

**Comment by xuri** [comment]
Hi @huanlingkeji, it seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
