### ISSUE TITLE
How to read excel in cursor mode, that is, reduce memory reading in batches?

### ISSUE THREAD

**Issue by yizhidaozuihou** [360EntSecGroup-Skylar/excelize#646]
How to read excel in cursor mode, that is, reduce memory reading in batches?

**Comment by xuri** [comment]
You can get all the data in the worksheet as streaming by [Rows](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize?tab=doc#File.Rows), read the data row by row using [`Next`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize?tab=doc#Rows.Next), also ref: #515.

**Comment by yizhidaozuihou** [comment]
> You can get all the data in the worksheet as streaming by [Rows](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize?tab=doc#File.Rows), read the data row by row using [`Next`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize?tab=doc#Rows.Next), also ref: #515.

After reading the source code, the bottom layer of openFile method is to call openreader method to read data. How to write if you want to read the code line by line?

**Comment by xuri** [comment]
We can be R/W XML only after unzipping OOXML format files, I'll close this PR, also reference #489 still discuss stream R/W.
