### ISSUE TITLE
How to read excel with GBK encoding ?

### ISSUE THREAD

**Issue by linxinfu** [360EntSecGroup-Skylar/excelize#649]

**Comment by xuri** [comment]
You can set custom codepage transcoder by [CharsetTranscoder](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.CharsetTranscoder) to open a spreadsheet from non-UTF-8 encoding.

**Comment by linxinfu** [comment]
Thanks for your help.
