### ISSUE TITLE
fatal error: out of memory @ streamWriter.Flush()

### ISSUE THREAD

**Issue by robinsoon** [360EntSecGroup-Skylar/excelize#650]
streamWriter.Flush()
write Excel 42523  ROWS* 388 COLUMNS > A42524 数据流超长:  16499312 byte
(Use the latest version of the package)
out of memory: cannot allocate 480.7MB , 59.8MB in use

Error： 
stream.go
func (bw *bufferedWriter) Bytes() ([]byte, error) 
        if int64(int(size)) == size {
				buf.Grow(int(size))  //Error : buf.Grow size= 525019669!
        }

buf.Grow= 525019669
grow( 525019669 ) tryGrowByReslice
grow( 525019669 ) cap= 0
grow( 525019669 ) makeSlice  <<Error
______________________________________________________________________________________
runtime: out of memory: cannot allocate 504111104-byte block (62750720 in use)
fatal error: out of memory

allocate 480.7MB , 59.8MB in use

runtime stack:
runtime.throw(0x7b43a9, 0xd)
  D:/Productivity/Go/src/runtime/panic.go:774 +0x64
runtime.largeAlloc(0x1e0c190c, 0x13020101, 0x33b44aa8)
  D:/Productivity/Go/src/runtime/malloc.go:1140 +0x108
runtime.mallocgc.func1()
  D:/Productivity/Go/src/runtime/malloc.go:1033 +0x39
runtime.systemstack(0x346d4130)
  D:/Productivity/Go/src/runtime/asm_386.s:399 +0x53
runtime.mstart()
  D:/Productivity/Go/src/runtime/proc.go:1146

goroutine 39 [running]:
runtime.systemstack_switch()
  D:/Productivity/Go/src/runtime/asm_386.s:360 fp=0x1303b9ac sp=0x1303b9a8 pc=0x44ee30
runtime.mallocgc(0x1e0c190c, 0x76cee0, 0x946e3101, 0x1d63eff)
  D:/Productivity/Go/src/runtime/malloc.go:1032 +0x684 fp=0x1303ba00 sp=0x1303b9ac pc=0x40b274
runtime.makeslice(0x76cee0, 0x1e0c190c, 0x1e0c190c, 0xcc7a4265)
  D:/Productivity/Go/src/runtime/slice.go:49 +0x4f fp=0x1303ba14 sp=0x1303ba00 pc=0x43bc5f
bytes.makeSlice(0x1e0c190c, 0x0, 0x0, 0x0)
  D:/Productivity/Go/src/bytes/buffer.go:229 +0x69 fp=0x1303ba48 sp=0x1303ba14 pc=0x4beb39
bytes.(*Buffer).grow(0x1303ba90, 0x1e0c190c, 0x0)
  D:/Productivity/Go/src/bytes/buffer.go:142 +0x11c fp=0x1303ba70 sp=0x1303ba48 pc=0x4be5fc
bytes.(*Buffer).Grow(...)
  D:/Productivity/Go/src/bytes/buffer.go:161
github.com/360EntSecGroup-Skylar/excelize/v2.(*bufferedWriter).Bytes(0x13349514, 0x1337a040, 0x13a010e0, 0x18, 0x1, 0x13a010e0)
  D:/PJ/Go/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.1.0/stream.go:460 +0x1ce fp=0x1303baa8 sp=0x1303ba70 pc=0x56669e
github.com/360EntSecGroup-Skylar/excelize/v2.(*StreamWriter).Flush(0x13349500, 0x0, 0x0)
  D:/PJ/Go/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.1.0/stream.go:390 +0x204 fp=0x1303bb14 sp=0x1303baa8 pc=0x566074
main.doExcelstream(0x1317e180, 0x131a4360, 0x8d, 0x13012375, 0x3d, 0x1300e586, 0x2a, 0x0)
  D:/PJ/Go/src/xlsxExp/xlsxExp.go:876 +0x18d0 fp=0x1303bfd0 sp=0x1303bb14 pc=0x590610
runtime.goexit()
  D:/Productivity/Go/src/runtime/asm_386.s:1325 +0x1 fp=0x1303bfd4 sp=0x1303bfd0 pc=0x450791
created by main.main
  D:/PJ/Go/src/xlsxExp/xlsxExp.go:426 +0x184e

goroutine 1 [chan receive, 1 minutes, locked to thread]:
main.main()
  D:/PJ/Go/src/xlsxExp/xlsxExp.go:443 +0x18e9

goroutine 36 [syscall]:
github.com/andlabs/ui._Cfunc_uiMain()
  _cgo_gotypes.go:2516 +0x33
github.com/andlabs/ui.Main(0x7cc338, 0x0, 0x0)
  D:/PJ/Go/pkg/mod/github.com/andlabs/ui@v0.0.0-20180902183112-867a9e5a498d/main.go:41 +0xd0
main.openWindow()
  D:/PJ/Go/src/xlsxExp/xlsxExp.go:1408 +0x23
created by main.main
  D:/PJ/Go/src/xlsxExp/xlsxExp.go:182 +0x7a3

goroutine 37 [select, 1 minutes]:
database/sql.(*DB).connectionOpener(0x1317e180, 0x803700, 0x131589c0)
  D:/Productivity/Go/src/database/sql/sql.go:1052 +0xa1
created by database/sql.OpenDB
  D:/Productivity/Go/src/database/sql/sql.go:722 +0x11e

goroutine 38 [select, 1 minutes]:
database/sql.(*DB).connectionResetter(0x1317e180, 0x803700, 0x131589c0)
  D:/Productivity/Go/src/database/sql/sql.go:1065 +0xb1
created by database/sql.OpenDB
  D:/Productivity/Go/src/database/sql/sql.go:723 +0x14c
错误: 进程退出代码 2.

**Comment by robinsoon** [comment]
Is this idea feasible? 
Replace the package buffer with buffio, or flush supports multiple appending and writing of fragments.

thanks!

**Comment by robinsoon** [comment]
My case : make slice 5*500MB! test GO memory allocation

[https://github.com/robinsoon/makeslice](url)

I hope to help you understand the actual problems

**Comment by xuri** [comment]
Thanks for your feedback. I'll take an evaluation later.

**Comment by verytable** [comment]
Any updates here? I'm facing the same issue.

Also, I would like to be able to provide a custom `io.Writer` for the temp file for the following reasons:
1. tmpfs might have much smaller size than other locations
2. I would like to control the resulting file size so that it does not grow infinitely
3. In tests one might want not to use tmpfs at all and perform all actions in memory. The code that writes excel file will be the same for both tests and prod. Only writers will differ.

**Comment by robinsoon** [comment]
Thanks a lot for davecheney's advice:




the upper limit of a slice is some significant fraction of the address space of a process. 

For 32 bit processes, between 1-2 gb, perhaps a little less on 32 bit windows because of DLL address space fragmentation. 

For 64 bit processes, in excess of a terrabyte, 10^40 bits.













At 2020-07-03 02:23:02, "verytable" <notifications@github.com> wrote:

Any updates here? I'm facing the same issue.

Also, I would like to be able to provide a custom io.Writer for the temp file for the following reasons:

tmpfs might have much smaller size than other locations
I would like to control the resulting file size so that it does not grow infinitely
In tests one might want not to use tmpfs at all and perform all actions in memory. The code that writes excel file will be the same for both tests and prod. Only writers will differ.

**Comment by snowcrumble** [comment]
I met similar problem, I found streamWriter.Flush() will [read all bytes](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/stream.go#L392) in temp file, in my case it's larger than 2GB. That bytes will then write to zip in WriteToBuffer() Method, I suggest to use io.Copy to copy bytes from temp file into zip, this method use fix size buffer to prevent huge memory usage.
