### ISSUE TITLE
cant open xlsx file with wps

### ISSUE THREAD

**Issue by huanlingkeji** [360EntSecGroup-Skylar/excelize#651]
![企业微信截图_15918650458889](https://user-images.githubusercontent.com/43662114/84364579-d748b580-ac02-11ea-9875-b582009af4c6.png)

I operate the xlsx created by the office, and then the office can be opened, but the wps cannot be opened

**Comment by xuri** [comment]
Thanks for your feedback. Please follow by issue template to provide code/attachments and steps to reproduce the issue.

**Comment by olgtd** [comment]
some issue occurred to me while I use v2.2 version.

**Comment by xuri** [comment]
Hi @olgtd, please follow by issue template to provide code/attachments and steps to reproduce the issue, which will helpful for me quickly resolve the issue.

**Comment by olgtd** [comment]
I just opened it then saved it.
origin file: https://drive.google.com/file/d/1qVw0m44EbX1EfozEzwEP9Kqz-HC9GpiX/view?usp=sharing
processed file: https://drive.google.com/file/d/1IuOhvbixcP2P4i4Va1ShgU-IYg0HWjPn/view?usp=sharing
You can look at the processed one, you have to open it using WPS directly. 
If you open it with Excel then open it with WPS, it will be work again.

**Comment by olgtd** [comment]
![image](https://user-images.githubusercontent.com/21125610/87625406-a8bb7e80-c75c-11ea-9a24-6a679e079c08.png)
[inbound_order_export_temp-error (1).xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/4929253/inbound_order_export_temp-error.1.xlsx)

**Comment by olgtd** [comment]
origin file: [inbound_order_export_temp.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/4929260/inbound_order_export_temp.xlsx)

![image](https://user-images.githubusercontent.com/21125610/87625600-1cf62200-c75d-11ea-9efc-0b850c217a72.png)

**Comment by xuri** [comment]
Hi @olgtd, I have fixed it. Please try to upgrade the library with the master branch code.
