### ISSUE TITLE
SetColWidth not affect when use NewStreamWriter

### ISSUE THREAD

**Issue by coder4life9192** [360EntSecGroup-Skylar/excelize#652]
**Description**

use stream writer generate 40000 row excel file, and then SetColWidth， found not affected

**Steps to reproduce the issue:**
1.file := excelize.NewFile()
streamWriter, err := file.NewStreamWriter("Sheet1")
if err != nil {
    println(err.Error())
}
2. setRow the first row has merged cells
3. setRow data and then use file.SetColWidth("Sheet1", "A", "H", 150)
4. the generated excel file's column width doesn't change

        xlsxFile := excelize.NewFile()
	sheetName := "Sheet1"

	streamWriter, err := xlsxFile.NewStreamWriter(sheetName)
	if err != nil {
		return xlsxFile, err
	}

	xlsxFile.SetColWidth(sheetName, "A", "H", 50)

	maxSizeColMap := make(map[int]int)
	// set values
	colSize := len(s.Cells)
	for l, d := range data {
		for idx, cell := range s.Cells {
			val, _ := d[cell.Name]
			cell, _ := excelize.CoordinatesToCellName(idx, l+headerLen+1)
			streamWriter.SetRow(cell, []interface{}{val})
		}
	}

	xlsxFile.SetColWidth(sheetName, "A", "H", 50)

	if err := streamWriter.Flush(); err != nil {
		return xlsxFile, err
	}
        
       xlsxFile.SaveAs("Book1.xlsx")
       return xlsxFile, nil

**Describe the results you received:**
the column A-H width doesn't change

**Describe the results you expected:**
the column A-H width should be 150 pixes

**Output of `go version`:**
go version go1.13.3 darwin/amd64
```text
(paste your output here)
```

**Excelize version or commit ID:**
v2.2.0 0feb819d4c08ab52e806214b23d673001bd9fe3e
```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by coder4life9192** [comment]
func writeCell(buf *bufferedWriter, c xlsxC) {
	buf.WriteString(`<c`)
	if c.XMLSpace.Value != "" {
		fmt.Fprintf(buf, ` xml:%s="%s"`, c.XMLSpace.Name.Local, c.XMLSpace.Value)
	}
	fmt.Fprintf(buf, ` r="%s"`, c.R)
	if c.S != 0 {
		fmt.Fprintf(buf, ` s="%d"`, c.S)
	}
	if c.T != "" {
		fmt.Fprintf(buf, ` t="%s"`, c.T)
	}
	buf.WriteString(`>`)
	if c.V != "" {
		buf.WriteString(`<v>`)
		xml.EscapeText(buf, stringToBytes(c.V))
		buf.WriteString(`</v>`)
	}
	buf.WriteString(`</c>`)
}

stringToBytes this method will lead to panic occasionally with unknown reasons

**Comment by xuri** [comment]
Thanks for your issue. `SetColWidth` is not a streaming API, so the column width setting will lose after stream writer flush data. I will add set column width support for the stream writer later.

**Comment by xuri** [comment]
> func writeCell(buf *bufferedWriter, c xlsxC) {
> buf.WriteString(`<c`)
> if c.XMLSpace.Value != "" {
> fmt.Fprintf(buf, ` xml:%s="%s"`, c.XMLSpace.Name.Local, c.XMLSpace.Value)
> }
> fmt.Fprintf(buf, ` r="%s"`, c.R)
> if c.S != 0 {
> fmt.Fprintf(buf, ` s="%d"`, c.S)
> }
> if c.T != "" {
> fmt.Fprintf(buf, ` t="%s"`, c.T)
> }
> buf.WriteString(`>`)
> if c.V != "" {
> buf.WriteString(`<v>`)
> xml.EscapeText(buf, stringToBytes(c.V))
> buf.WriteString(`</v>`)
> }
> buf.WriteString(`</c>`)
> }
> 
> stringToBytes this method will lead to panic occasionally with unknown reasons

Thanks for your feedback. Could you provide any sample code to trigger this issue?

**Comment by willthrom** [comment]
For the time being, what I did is to apply the format AFTER the flush.

**Comment by xuri** [comment]
I have added set column width support in streaming writing mode, please try to use the master branch code, and this feature will be released in the next version. Note that you must call the `SetColWidth` function before the `SetRow` function.
