### ISSUE TITLE
Get cell value in custom date format

### ISSUE THREAD

**Issue by CezarGarrido** [360EntSecGroup-Skylar/excelize#655]
Hello, I'm using excel in a project with Windows, in the excel file there is a cell with a custom format following the following date pattern: 6/11/2020 17:39:36 PM.

When I search for the value of this cell using excelize, it returns a number for example 43993. I would like to know if there is any way to capture this cell value. I may be making a mistake.

go version go1.13.4 windows / amd64
github.com/360EntSecGroup-Skylar/excelize/v2 v2.2.0

**Comment by xuri** [comment]
Thanks for your issue. `GetCellValue` just supports get cell value with Excel's [built-in formats](https://github.com/360EntSecGroup-Skylar/excelize/blob/1cbb05d4977fc1c03fa37d704118fd9c722e487d/styles.go#L28-L64) number format currently. If it couldn't apply a number format of the cell value, it will return the raw value of the cell. Also reference #50 and #73.

**Comment by dmint007** [comment]
> Thanks for your issue. `GetCellValue` just supports get cell value with Excel's [built-in formats](https://github.com/360EntSecGroup-Skylar/excelize/blob/1cbb05d4977fc1c03fa37d704118fd9c722e487d/styles.go#L28-L64) number format currently. If it couldn't apply a number format of the cell value, it will return the raw value of the cell. Also reference #50 and #73.

Then how can we fetch the date in the given cell?
I have the date of `09/09/19` which keeps being returned as `"43717.0"`

**Comment by artiz** [comment]
Fixed in https://github.com/360EntSecGroup-Skylar/excelize/pull/703
