### ISSUE TITLE
How to disable DefaultSubtotal in PivotTable

### ISSUE THREAD

**Issue by EugeneAndrosovPaser** [360EntSecGroup-Skylar/excelize#656]
Hello, I'm found needed to me flag `DefaultSubtotal` in xmlPivotTable, but if I'm trying to force disable this flag I have no result and Microsoft Excel think that this file is broken.

**Comment by xuri** [comment]
Hi, @EugeneAndrosovPaser, thanks for your feedback. Which version of Excelize are you using? Could you provide any code details and the spreadsheet attachment without confidential info?

**Comment by xuri** [comment]
There still no more details about this issue from the issue author. I close this issue and welcome left comments if you have any more questions.
