### ISSUE TITLE
Turn off the marker for line plots

### ISSUE THREAD

**Issue by huybuidev** [360EntSecGroup-Skylar/excelize#657]
**Description**

Provide option to hide the marker for Line chart.

As I am using excelize to draw a Line chart but it shows the marker by default.
I have tried to find an option to turn it off but found nothing.

**Steps to reproduce the issue:**
1. Use the following code to add chart:
```
	if err = f.AddChart("M1", `{"type":"line","series":[
		{"name":"Sheet1!$B$1","categories":"Sheet1!$A$2:$A$257","values":"Sheet1!$B$2:$B$257"},{"name":"Sheet1!$E$1","categories":"Sheet1!$A$2:$A$257","values":"Sheet1!$E$2:$E$257"},{"name":"Sheet1!$F$1","categories":"Sheet1!$A$2:$A$257","values":"Sheet1!$F$2:$F$257"}],"title":{"name":"xD values"}, "dimension":{"width":1024,"height":768}}`); err != nil {
		return err
	}
```
2. Use `SaveAs` function to save the XLSX file 
3. Open the output XLSX file and check the plot

**Describe the results you received:**
Lines in the plot has markers

**Describe the results you expected:**
Lines in the plot doesn't have the markers (markers = None)

**Output of `go version`:**

```text
go version go1.14.4 windows/amd64
```

**Excelize version or commit ID:**

```text
0feb819d4c08ab52e806214b23d673001bd9fe3e
(v2.2.0)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10 x64 2004
Excel 2016

**Comment by huybuidev** [comment]
I have been able to turn off the marker temporarily by the following modification. This can be added to formatSet as an option or might be more options related to the marker can be added as well. I don't have the full overview of the project so hope this can provide a hint for the feature.

```diff
diff --git "a/.\\drawing.go" "b/.\\drawing.go.patched.go"
index 7c09d4d..cfdc0d4 100644
--- "a/.\\drawing.go"
+++ "b/.\\drawing.go.patched.go"
@@ -864,7 +864,8 @@ func (f *File) drawChartSeriesMarker(i int, formatSet *formatChart) *cMarker {
                        },
                }
        }
-       chartSeriesMarker := map[string]*cMarker{Scatter: marker}
+       lineMarker := &cMarker{Symbol: &attrValString{Val: stringPtr("none")}}
+       chartSeriesMarker := map[string]*cMarker{Scatter: marker, Line: lineMarker}
        return chartSeriesMarker[formatSet.Type]
 }
```

**Comment by danny-wang** [comment]
can this feature be provided recently?

**Comment by xuri** [comment]
@danny-wang I'll add setting marker for chart support this week.

**Comment by xuri** [comment]
Hi @huybuidev, @danny-wang I'll add a setting marker for chart support, please use the master branch code, and this feature will be released in the next version.
