### ISSUE TITLE
Support shared string table without unique count

### ISSUE THREAD

**Issue by DehaiWang** [360EntSecGroup-Skylar/excelize#667]
使用go mod  /excelize/v2 和不使用 mod  下载的  360EntSecGroup-Skylar/excelize 操作excel模板导出数据结果不一致，其中 go mod 下载的 是360EntSecGroup-Skylar/excelize/v2 v2.2.0 版本 数据写入Excel模板正常，但是 excelize /v2@master 版本和 不使用 go mod下载的 360EntSecGroup-Skylar/excelize   数据写入Excel模板后数据出现错行。
目前推测是我们的客户上传Excel模板的版本有些问题，每次在我们电脑上任意编辑后保存，再上传到服务器上用做数据导出的模板用任意版本的 excelize 就数据导出正常。
模板Excel文件涉及到客户隐私，如果您那边调试需要的话，我可以通过邮箱的形式发送给你。
![image](https://user-images.githubusercontent.com/16337003/87380824-dfab5c00-c5c5-11ea-88db-3a5f1bce9fbe.png)

这张图片是写入数据后数据异常的的：
![image](https://user-images.githubusercontent.com/16337003/87380924-16817200-c5c6-11ea-8511-97f26c52887e.png)
用代码指定的位置的数据全是直接使用的 A1位置的数据，数据异常.

下边是代码：
`
       xlsx, err := excelize.OpenFile(desExcel)
	fmt.Println("open,err:", err)
	sheetName := "请假表"
	//申请人
	err = xlsx.SetCellValue(sheetName, "B3", "FullName")
	fmt.Println("SetCellValue,err:", err)
	
	err = xlsx.SetCellValue(sheetName, "D3", "FullName")
	fmt.Println("SetCellValue,err:", err)
	
	err = xlsx.SetCellValue(sheetName, "F3", "FullName")
	fmt.Println("SetCellValue,err:", err)
	
	err = xlsx.SetCellValue(sheetName, "B6", "FullName")
	fmt.Println("SetCellValue,err:", err)

	err = xlsx.Save()
	fmt.Println("Save,err:", err)
`

**Comment by xuri** [comment]
Hi @DehaiWang, thanks for your feedback, you can email me (`xuri.me@gmail.com`) spreadsheet attachment without confidential info.

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by DehaiWang** [comment]
Thanks , it works well now.
