### ISSUE TITLE
AddPicture method inserts image as hiperlink, not as a copy, and at REST response image is missing

### ISSUE THREAD

**Issue by tanecar** [360EntSecGroup-Skylar/excelize#669]
Hi, I am using xuri/excelize library for excel manipulation i Go. I have used a method AddPicture to add image (.png image) at the cell in xslx, and it works correctly in local but when I run it on server and download xlsx file from the REST response the image file doesn't exist in xlsx (Navigator shows that the Picture1 is present but there is no any picture). This is because AddPicture method adds image as hiperlink to actual address to image, not as copy into xlsx and when the response is received from server the image is missing. Any help?

**Comment by xuri** [comment]
`AddPicture` just support to read file from local by given file path, if you wanna insert a picture to the worksheet by URL, please using the [`AddPictureFromBytes`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.AddPictureFromBytes) API with binary content.

**Comment by tanecar** [comment]
O, thanks.
