### ISSUE TITLE
How to get the number of sheets, rows and columns?

### ISSUE THREAD

**Issue by zzc-tongji** [360EntSecGroup-Skylar/excelize#67]
How to get the number of sheets in a .xlsx file?
How to get the number of rows and columns in a sheet?

**Comment by Luxurioust** [comment]
Please reference [the full API docs](https://godoc.org/github.com/Luxurioust/excelize). You can use the function [`GetSheetMap()`](https://godoc.org/github.com/Luxurioust/excelize#File.GetSheetMap) to get the number of sheets and use the function [`GetRows()`](https://godoc.org/github.com/Luxurioust/excelize#File.GetRows) to to get the number of rows and columns in a sheet.

**Comment by zzc-tongji** [comment]
Thanks.

**Comment by msiemens** [comment]
Sorry to bump an old issue, but is it possible to get the number of rows/colums without reading the whole file, which `GetRows()` seems to do? Or at least something that short-circuits all the parsing and returns the result of https://github.com/360EntSecGroup-Skylar/excelize/blob/9e463b4614348b3ddc04b1fedd5d662845ce0fb9/rows.go#L159-L189 directly?
