### ISSUE TITLE
AddPicture error - image: unknown format

### ISSUE THREAD

**Issue by ldqk** [360EntSecGroup-Skylar/excelize#671]
**Description**

**Steps to reproduce the issue:**
任何形式的图片都无法添加到excel中，均报错image: unknown format

**Describe the results you received:**
``` go
imgFile, _ := ioutil.ReadFile("logo.png")
eeee:=f.AddPictureFromBytes("Sheet1", fmt.Sprint("A", 2), "", "logo", ".png", imgFile)
if eeee != nil {
	var ereee=eeee.Error()
	fmt.Println(ereee)
}
```
![](https://p.pstatp.com/origin/ff3e000288be52999c02)
**Output of `go version`:

```text
1.14.4
```

**Excelize version or commit ID:

```text
v2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):Windows 10 2004，goland 2020.1.3

**Comment by xuri** [comment]
Hi @ldqk, please make sure to import the dependent image lib:

```go
_ "image/png"
```

**Comment by ldqk** [comment]
感谢指导
