### ISSUE TITLE
excelize format time to a unexpected format, that is "01-02-06"

### ISSUE THREAD

**Issue by wsyzxcn** [360EntSecGroup-Skylar/excelize#675]
If i input a date in a cell, for example 2020/10/12, and read that cell by excelize, i will get a string of "12-10-20". As i follow the code of decode flow i found that excelize will transfer date type to a formatted string by function formtTime.
I think excelize is being too clever, Usually, we just want a raw value of time isn't it ?

**Comment by AngangGuo** [comment]
Possible to get raw value or let us specify a date format ourselves.

**Comment by weiqiangxu** [comment]
> Possible to get raw value or let us specify a date format ourselves.

how to get yyyy-mm-dd , when i 
`excelize.builtInNumFmt[14] = "yyyy-mm-dd"`
it is not exported by package.

**Comment by weiqiangxu** [comment]
最后我也只能对获取到的值 mm-dd-yy 转换为 yyyy-mm-dd
`package main

import (
	"fmt"
	"time"
)
func main() {
	t, _ := time.ParseInLocation("01-02-06", "10-14-20", time.Local)
    fmt.Println(t.Format("2006-01-02"))
}
`
输出：
`2020-10-14`

**Comment by bluntdel** [comment]
> 最后我也只能对获取到的值 mm-dd-yy 转换为 yyyy-mm-dd
> 
> ```
> package main
> import (
> 	"fmt"
> 	"time"
> )
> func main() {
>     t, _ := time.ParseInLocation("01-02-06", "10-14-20", time.Local)
>     fmt.Println(t.Format("2006-01-02"))
> }
> ```
> 
> 输出：
> `2020-10-14`

You can not specify '10-14-20' is '10-14-2020' or '10-14-1920'

**Comment by xuri** [comment]
This issue similar to #660 and #759. I close this and merge it into issue #660 is still discussing this feature.
