### ISSUE TITLE
Panic with Stream Writer

### ISSUE THREAD

**Issue by me4log** [360EntSecGroup-Skylar/excelize#677]
stream.go line 368 writeCell func, **stringToBytes** return incorrect slice, with zero capacity, but containing data and xml.EscapeText panic.

Why stringToBytes use unsafe, rather then []byte(string)? Simple replacement do it code working
![Снимок экрана 2020-07-31 в 21 02 15](https://user-images.githubusercontent.com/12894367/89063767-73747a80-d371-11ea-85dd-055c7abba601.png)

**Comment by fxxkingNoob** [comment]
same issues
I found its only happends when go build with arg:
-gcflag “-N”

https://github.com/360EntSecGroup-Skylar/excelize/issues/679

**Comment by me4log** [comment]
Yes, goland compile with -gcflags "all=-N -l"
