### ISSUE TITLE
-gcflag “-N”参数下编译时中英文混写会panic: runtime error: slice bounds out of range [:5] with capacity 0

### ISSUE THREAD

**Issue by fxxkingNoob** [360EntSecGroup-Skylar/excelize#679]
**Description**
go build 加参数 -gcflag “-N”编译（debug时需要）
使用streamWriter.SetRow(cell, row)时
row中中英文混写（如"模板ID"）会panic
研究了下原因
stringToBytes()使用了unssafe包， 在-gcflag “-N”参数下编译运行时会返回[]byte，len>0, cap=0，使用返回的slice时会panic

**Steps to reproduce the issue:**
1.使用streamWriter.SetRow(“A1”, []interface{}{"模板ID"})
2.go build 带参数-gcflag “-N”
3.构建excel

**Describe the results you received:**
panic: runtime error: slice bounds out of range [:5] with capacity 0
**Describe the results you expected:**
no panic
**Output of `go version`:**

```text
go version go1.13.9 darwin/amd64
```

**Excelize version or commit ID:**

```text
lastest
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
mac OS 10.15.4 (19E287)

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it. Please try to upgrade the library with the master branch code.
