### ISSUE TITLE
Could you publicize functions of "getRowHeight" and "getColWidth"?

### ISSUE THREAD

**Issue by zzc-tongji** [360EntSecGroup-Skylar/excelize#68]
It is really useful when developers want to set the height (width) of a new row (column) as same as an existent row (column).

**Comment by Luxurioust** [comment]
Okay, function `GetColWidth()` and `GetRowHeight()` has been exported.

**Comment by zzc-tongji** [comment]
Thanks.

**Comment by zzc-tongji** [comment]
Here is another difference. 
The 2nd parameter of function "GetRowHeight" is "row" (begin with 1).
The 2nd parameter of function "SetRowHeight" is "rowIndex" (begin with 0).

:-)

**Comment by Luxurioust** [comment]
Thanks for your issue. I have unified the index row number index and the return value data type of them.

**Comment by zzc-tongji** [comment]
Thanks.
