### ISSUE TITLE
RemoveCol will panic 

### ISSUE THREAD

**Issue by l-xue-yu** [360EntSecGroup-Skylar/excelize#680]
**Description**

I want del one col ,but program panic.
我想删除一列，入参都正确但是会panic，程序直接出错。
runtime error: slice bounds out of range [31:30]

**Steps to reproduce the issue:**
1.f, openErr := excelize.OpenFile("demo.xlsx")
2.f.RemoveCol("sheet1", "A")
3.

**Describe the results you received:**
panic , runtime error: slice bounds out of range [31:30]
程序出错，panic,数组越界。
**Describe the results you expected:**
能正常删除列。
del col .
**Output of `go version`:**
go version go1.13.4 windows/amd64
```text
(paste your output here)
```

**Excelize version or commit ID:**
github.com/360EntSecGroup-Skylar/excelize v1.4.1
```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
windows

**Comment by xuri** [comment]
Thanks for your feedback, could you provide file attachments without sensitive info?

**Comment by l-xue-yu** [comment]
[demo2.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5026042/demo2.xlsx)

**Comment by xuri** [comment]
I have tested and It work well on the v2.2.0. Please upgrade to the lasted version.

**Comment by l-xue-yu** [comment]
yes,I choose v2.2.0 ,it worked . But ,I find the github.com/360EntSecGroup-Skylar/excelize latest is v1.4.1,please fix it .  I have see the func , any style can Merged cell(合并单元格)?

**Comment by l-xue-yu** [comment]
f.MergeCell(),I found it.
