### ISSUE TITLE
Merge Cell Issue

### ISSUE THREAD

**Issue by SivaramWiz** [360EntSecGroup-Skylar/excelize#682]
Hai am try to merge cell start with A1 to K1. But the result will like first 6 cell merge like A1:F1 and rest of them not merged.

**Comment by xuri** [comment]
Thanks for your feedback, please follow by issue template to provide code/attachments and steps to reproduce the issue, which will helpful for me quickly resolve the issue.

**Comment by SivaramWiz** [comment]
package main

import (
    "fmt"
	"github.com/360EntSecGroup-Skylar/excelize"
)


func main() {
    var (
        sheet = "TopSheet"
        exName = "tdy"        
        err   error
    )

    f := excelize.NewFile()

    //new sheet or tab create
	f.NewSheet(sheet)
    //delete sheet or tab create
    f.DeleteSheet("Sheet1")
    
    if err = f.MergeCell(sheet, "A1", "M1"); err != nil {
        fmt.Println(err)
        return
    }
    f.SetCellValue(sheet, "F1", "FOOD SERVICE SALES REPORT")
    f.SetRowHeight(sheet, 1, 100)

    // Save xlsx file by the given path.
    if err := f.SaveAs(exName+".xlsx"); err != nil {
        fmt.Println(err)
    }
}

**Comment by SivaramWiz** [comment]
![Annotation 2020-08-06 144812](https://user-images.githubusercontent.com/68845340/89514778-e9eefd80-d7f3-11ea-8a42-c37a70c8fe2e.png)

**Comment by xuri** [comment]
I have tested and it works well on Microsoft Office Excel 2007, 2010 and 2019, LibreOffice, Apache OpenOffice, Apple Number, and Kingsoft WPS Office. I think that's the bug of Google Sheets.

**Comment by SivaramWiz** [comment]
okay 👌 Thank You so much and one more thing pls share your social media profiles
