### ISSUE TITLE
cell iteration 

### ISSUE THREAD

**Issue by SivaramWiz** [360EntSecGroup-Skylar/excelize#683]
**Is there any function have cell iteration for store more array of values for without specified axis**

**Comment by xuri** [comment]
[`SetSheetRow`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.SetSheetRow) writes an array to row by given worksheet name, starting coordinate, and a pointer to array type `slice`.
