### ISSUE TITLE
after updating xlsx file with SetCellFloat loop GetRows can't read some cells 

### ISSUE THREAD

**Issue by SteveTalt** [360EntSecGroup-Skylar/excelize#684]
**Description**

**Steps to reproduce the issue:**
1.  Create an excel sheet with a couple of rows of numbers 
2. GetRows from a sheet and check value of A2.  Example code:  
```
        xl, err = file.XlFileOpen(fullXLPath)
        rows, err = xl.GetRows(xlsheetname)
        log.Println(rows[0][1]
```
2.    Update a second row of numbers:
```
       // SpendUpdates - structure to hold excel cellname and new value for it
         type SpendUpdates struct {
	     CellName string
	    Value    float64
         }
        updatecells := append(updatedcells, SpendUpdates{CellName: "A2", Value: 2.0})

	for _, cell := range updatedcells {
		err = xl.SetCellFloat(xlsheetname, cell.CellName, cell.Value, 2, 64)
	}
	xl.UpdateLinkedValue()
	xl.Save()
```
3. Run back to 1 again...it will see the value of rows[0][1] again as ""
4. Open the excel file directly in excel....save the file (not changing anything)
5. Run back to 1 again....and it will see the normal number value

Note: It isn't the cell or row that I'm updating its a different one.   And if I just run through twice without the SetCellFloat updating the file it works normally....so its something there

**Describe the results you received:**
I get a "" returned as the value in rows[0][1] even though if I open the file directly I can see a number there.   If I save the file in excel without changing anything and run it again...it shows the right value

**Describe the results you expected:**
Returning the value of the cell is expected

**Output of `go version`:**

```text
go version go1.13.11 darwin/amd64
```

**Excelize version or commit ID:**

```text
(commit 843bd24e56450791ad122a2f3875956a0a70ec6e
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOS Catalina 10.15.6
Microsoft Excel for Mac 16.39

**Comment by xuri** [comment]
Thanks for your feedback. I have tested and It works well on the v2.2.0. Could you provide a spreadsheet attachment without confidential info?

**Comment by SteveTalt** [comment]
I've recreatedwith this file and code.    You have to run the code twice to see the odd behavior.   The first time the update is successful and you can read the other cell.    The second time you run it....it gets no value for the cell.  It does have a formula in the cells its reading from...but I am updating linked values before saving.    Now, if you open up that excel file after it fails and save the file (not changing anything) and then run it again it will work ONCE.

Here is a test file:
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5048415/test.xlsx)

Here is code to recreate it: 
`package main

import (
	"log"

	"github.com/excelize"
)

// SpendUpdates - structure to hold excel cellname and new value for it
type SpendUpdates struct {
	CellName string
	Value    float64
}

func main() {
	var (
		fulXLPath    = "/temp/test.xlsx"
		xlsheetname  = "test"
		rows         [][]string
		updatedcells = SpendUpdates{CellName: "D2", Value: 36.0}
	)

	xlfile, err := excelize.OpenFile(fulXLPath)
	if err != nil {
		log.Println("ERROR", err)
	}
	rows, err = xlfile.GetRows(xlsheetname)
	if err != nil {
		log.Println("ERROR", err)
	} else {
		log.Println("cell L1: ", rows[0][11])
	}

	err = xlfile.SetCellFloat(xlsheetname, updatedcells.CellName, updatedcells.Value, 2, 64)
	if err != nil {
		log.Println("ERROR", err)
	} else {
		log.Println("cell L1: ", rows[0][11])
	}
	xlfile.UpdateLinkedValue()
	xlfile.Save()

}`

**Comment by xuri** [comment]
Please reference issue #65 and #198. The formula calculation engine (`CalcCellValue`) is working in progress.
