### ISSUE TITLE
InsertRow报错

### ISSUE THREAD

**Issue by shigophilo** [360EntSecGroup-Skylar/excelize#688]
```
err1 := f.InsertRow("Sheet1",2)
		if err1 != nil{
			fmt.Println(err1)
		}
```

报错信息
f.InsertRow("Sheet1", 2) used as value

**Comment by xuri** [comment]
Which version of the Excelize are you using? Please create the issue by an issue template. The error return of the API InsertRow available since [version 2.0.0](https://github.com/360EntSecGroup-Skylar/excelize/releases/tag/v2.0.0).
