### ISSUE TITLE
There is a little bug when writing multiline texts to cells.

### ISSUE THREAD

**Issue by zzc-tongji** [360EntSecGroup-Skylar/excelize#69]
**Test Code**

```go
package main

import (
	"fmt"

	"github.com/Luxurioust/excelize"
)

func main() {
	// read
	xlsx, err := excelize.OpenFile("test-before.xlsx")
	if err != nil {
		fmt.Printf("%s\n", err.Error())
		return
	}
	table := xlsx.GetRows("sheet1")
	fmt.Printf("\n")
	fmt.Printf("Before:\n")
	for i := 0; i < len(table); i++ {
		for j := 0; j < len(table[0]); j++ {
			fmt.Printf("%s ", table[i][j])
		}
		fmt.Printf("\n")
	}
	// change
	xlsx.SetCellValue("sheet1", "A2", "A2\nExample 2")
	xlsx.SetCellValue("sheet1", "B2", "A2\n例子2")
	// write
	xlsx.SaveAs("test-after.xlsx")
	// read again
	xlsx, err = excelize.OpenFile("test-after.xlsx")
	if err != nil {
		fmt.Printf("%s\n", err.Error())
		return
	}
	table = xlsx.GetRows("sheet1")
	fmt.Printf("\n")
	fmt.Printf("After:\n")
	for i := 0; i < len(table); i++ {
		for j := 0; j < len(table[0]); j++ {
			fmt.Printf("%s ", table[i][j])
		}
		fmt.Printf("\n")
	}
	fmt.Printf("\n")
}
```

**Test File**

[test-before.xlsx](https://github.com/Luxurioust/excelize/files/1110550/test-before.xlsx)
![test-before](https://user-images.githubusercontent.com/20331014/27666036-8e32ad26-5ca3-11e7-9e0d-89f3a04f83ea.png)

[test-after.xlsx](https://github.com/Luxurioust/excelize/files/1110551/test-after.xlsx)
![test-after](https://user-images.githubusercontent.com/20331014/27666038-9739d0e8-5ca3-11e7-94af-e5651a27baa5.png)

**Test Environment**

- golang 1.8 darwin/amd64
- Microsoft Excel 2016 for Mac

**Problem**

It seems like excelize can parse multiline texts in cells (with '\n' in the middle). However, multiline texts written by excelize could not be displayed correctly by Microsoft Excel, though they can be parsed correctly by excelize again.

**Comment by zzc-tongji** [comment]
I got it.

This is a little bug of Microsoft Excel 2016 for Mac.

Here is the solution: double click one of non-empty cells and then save. After doing these, all multiline texts will be displayed correctly.

**Comment by xuri** [comment]
I close this and merge it into the issue #127 is still discussing this problem.

**Comment by xuri** [comment]
Hi @zzc-tongji, I have added rich text support for this lib, now it can be preserved multi-lines in the cell.
