### ISSUE TITLE
SetCellValue not effect without error

### ISSUE THREAD

**Issue by zhuwh1118** [360EntSecGroup-Skylar/excelize#690]
**Description**

execute func SetCellValue with no error returns,but the value was not set into the xlsx file in fact!

**Steps to reproduce the issue:**
f, err := excelize.OpenFile(fileName)
			if err != nil {				
			    return err
					}
	err = f.SetCellValue(sheetName, fmt.Sprintf("M%d", i), "vvvv")
			if err != nil {
			    fmt.Println("set error", err.Error())
			                 }

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**
go version go1.14.2 linux/amd64
```text
(paste your output here)
```

**Excelize version or commit ID:**
commit 843bd24e56450791ad122a2f3875956a0a70ec6e
```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
os: centos7

**Comment by xuri** [comment]
Which version of the Excelize are you using? Please create the issue by an issue template and provide a spreadsheet xlsx attachment without confidential info.

**Comment by zhuwh1118** [comment]
How to see  Excelize's version?

**Comment by zhuwh1118** [comment]
[Customer.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5078360/Customer.xlsx)

**Comment by xuri** [comment]
I have tested and it works well, could you provide the code to reproduce this issue?

**Comment by zhuwh1118** [comment]
f, err := excelize.OpenFile(fileName)
if err != nil {
return err
}
err = f.SetCellValue(sheetName, fmt.Sprintf("M%d", i), "vvvv")
if err != nil {
fmt.Println("set error", err.Error())
}

**Comment by xuri** [comment]
What are the values of variables `sheetName` and `i`?

**Comment by xuri** [comment]
Please provides runnable codes if you can with more details, which will helpful for me quickly resolve the issue.

**Comment by zhuwh1118** [comment]
\f, err := excelize.OpenFile(fileName)
if err != nil {
return err
}
err = f.SetCellValue("sheet1", "M1", "vvvv")
if err != nil {
fmt.Println("set error", err.Error())
}

**Comment by xuri** [comment]
Did you save the spreadsheet by [`Save`](https://xuri.me/excelize/zh-hans/workbook.html#Save) or [`SaveAs`](https://xuri.me/excelize/zh-hans/workbook.html#SaveAs) after setting the cell values?

**Comment by zhuwh1118** [comment]
That's it!  Thanks a lot !
