### ISSUE TITLE
unexpected x_scale and y_scale when using AddPictureFromBytes

### ISSUE THREAD

**Issue by p581581** [360EntSecGroup-Skylar/excelize#691]
**Description**

here is my code:
`f.AddPictureFromBytes(sheetName, fmt.Sprintf("A%d", index), fmt.Sprintf(``{"print_obj": true, "lock_aspect_ratio": false, "locked": false, "positioning" : "oneCell", "x_scale": %2f, "y_scale": %2f, "x_offset":1, "y_offset":1}``, xScale, yScale), "image", ".jpg", bytes)
`

**Steps to reproduce the issue:**
1. I used excelize for pasting picture on excel , and it worked perfectly.
2. update excelize
3. got wrong scale

**Describe the results you received:**
Pictures display with wrong scale, and it's not what I set

**Describe the results you expected:**
Just like before

**Output of `go version`:**

```text
go 1.12
```

**Excelize version or commit ID:**

```text
Commit: 6962061200e2198acc39392c35344d1826268f34 [6962061]
Parents: 821b90d1f0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
win 10
excel 2019
```

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it. Please try to upgrade the library with the master branch code.

**Comment by p581581** [comment]
Thank you. It work perfectly.
