### ISSUE TITLE
Slicers Not Displaying Text, but still work, only on mac

### ISSUE THREAD

**Issue by TheoBo** [360EntSecGroup-Skylar/excelize#693]
When i open an excel file, that has a slicer on a pivot table:

**_f, err := excelize.OpenFile("excel/DistanceDashboard.xlsx")**

and then stream it to chrome running on a Mac:

**f.Write(w)**

The slicers do not display any content in chrome on the mac, they still work, but the selection buttons are not visable.

Streaming the same file to chrome on windows works fine.

**Comment by xuri** [comment]
Thanks for your feedback, could you provide a spreadsheet xlsx attachment without confidential info?

**Comment by TheoBo** [comment]
Attached is the xlsx, it was generated using Excelize; on mac, the slicers do not show the buttons.
If I insert new slicers, the same happens, the slicers do technically work, but the buttons are not shown.
I did try on different machines, and id update to the latest excel version.
Thanks for your help.

[NonDisplayingSlicerButtons.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5104679/NonDisplayingSlicerButtons.xlsx)

**Comment by xuri** [comment]
Could you provide an origin spreadsheet file that opened by excelize? and a detailed code to produce this issue.
