### ISSUE TITLE
How to get rich text of cell

### ISSUE THREAD

**Issue by born30925** [360EntSecGroup-Skylar/excelize#696]
I have text in cell. It's Bold Italic and Underline. I need get rich text of cell.

**Comment by xuri** [comment]
You can get plain text from the cell with rich text by [`GetCellValue`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.GetCellValue) as normal.

**Comment by born30925** [comment]
I can get style of text? I 
![1](https://user-images.githubusercontent.com/23648992/90796341-67a92200-e339-11ea-95f1-02603763e1c7.JPG)

**Comment by xuri** [comment]
This lib doesn't support get rich text style currently, its storage at share string table. I will add this feature support later.
