### ISSUE TITLE
Hide all grid lines

### ISSUE THREAD

**Issue by azzahrah** [360EntSecGroup-Skylar/excelize#698]
Howto hide all grid lines?

**Comment by xuri** [comment]
Set sheet view options by [`SetSheetViewOptions`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.SetSheetViewOptions) link this:

```go
err = f.SetSheetViewOptions("Sheet1", -1, ShowGridLines(false))
```

**Comment by azzahrah** [comment]
@xuri thanks very much, i will try
