### ISSUE TITLE
How do I add the openfile xlxs's Row (XLXS data per row) to Sheet1 of the new XLXS file?

### ISSUE THREAD

**Issue by bondliu2020** [360EntSecGroup-Skylar/excelize#699]
////读取所有行
		rows := fm.GetRows("Sheet1")
		num := 0
		for _, row := range rows {
			num++
			if(num > 4) {
				for k, colCell := range row {
					//fmt.Print(colCell, "\t")
					fmt.Println(colCell)
				}
				fmt.Println()
			}
			//for k, v := range row {
			//	f.SetCellValue("Sheet1", k, v)
			//}
		}
	}
	//// Set value of a cell.
	//f.SetCellValue("Sheet1", "B2", 100)
	//// Set active sheet of the workbook.
	f.SetActiveSheet(index)
	// Save xlsx file by the given path.
	if err := f.SaveAs("allinone.xlsx"); err != nil {
		fmt.Println(err)
	}
}
//========my question?===============
How do I add the openfile xlxs's Row (XLXS data per row) to Sheet1 of the new XLXS file?
//==================================
for _, row := range rows {
			num++
			if(num > 4) {
				for k, colCell := range row {
					//fmt.Print(colCell, "\t")
					fmt.Println(colCell)
				}
				fmt.Println()
			}

**Comment by bondliu2020** [comment]
如何将 获取的row(xlxs每行的数据) 增加到新建的xlxs文件的sheet1中?

**Comment by xuri** [comment]
For example, if the same worksheet name on both spreadsheet, copy partial rows under row 5  in `Book1.xlsx` to the new workbook, saved as `Book2.xlsx`:

```go
package main

import (
    "fmt"

    "github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
    src, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    dst := excelize.NewFile()
    // Get all the rows in the Sheet1.
    rows, err := src.GetRows("Sheet1")
    for i, row := range rows {
        if i > 4 {
            cellName, err := excelize.JoinCellName("A", i-4)
            if err != nil {
                fmt.Println(err)
                return
            }
            fmt.Println(cellName, row)
            if err := dst.SetSheetRow("Sheet1", cellName, &row); err != nil {
                fmt.Println(err)
                return
            }
        }
    }
    if err := dst.SaveAs("Book2.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```
