### ISSUE TITLE
SetCellValue consume a great deal of memory

### ISSUE THREAD

**Issue by czh0318** [360EntSecGroup-Skylar/excelize#700]
**Description**

**Steps to reproduce the issue:**
1. f := excelize.NewFile() and f.NewSheet("Information")
2. wirte 500000 rows data to file.
3. use pprof to analysis memory.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
see the mem_profile attachment
[pprof001.svg.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/5182156/pprof001.svg.zip)


```

**Excelize version or commit ID:**

```text
v2.3.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: Mac OS
go version:  go1.14.7 darwin/amd64

**Comment by xuri** [comment]
Please try to using [stream writer](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.NewStreamWriter
) for generating a new worksheet with huge amounts of data.

**Comment by czh0318** [comment]
> Please try to using [stream writer](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.NewStreamWriter) for generating a new worksheet with huge amounts of data.

It works, thank you.
