### ISSUE TITLE
formula function and validate

### ISSUE THREAD

**Issue by ZhangYi96** [360EntSecGroup-Skylar/excelize#701]
**Can formulaFuncs support AND and OR methods?**
I need : 
1. calculate `AND` , `OR` and `Date`
2. When I  input the wrong formula, it should have returned an error but a panic

**Input**
```
1. AND(1=1,2=2)
2. OR(1=2,2=2)
3. Date(2020,10,01)
4. AND(1=1),
```
**Output**
```
1. true
2. true
3. 2020/10/01
4. error
```

**Comment by xuri** [comment]
Thanks for your issue, I have just init new formula function `AND` and `OR`, and I'll add `DATE` support later.
