### ISSUE TITLE
merge cell uncheck area

### ISSUE THREAD

**Issue by nullfy** [360EntSecGroup-Skylar/excelize#702]
可否单独提供一个合并单元格的方法，不做重叠区域的校验
//for i := 0; i < len(xlsx.MergeCells.Cells); i++ {
//	if checkCellInArea(hcell, xlsx.MergeCells.Cells[i].Ref) || checkCellInArea(strings.Split(xlsx.MergeCells.Cells[i].Ref, ":")[0], mergeCell.Ref) {
//		xlsx.MergeCells.Cells = append(xlsx.MergeCells.Cells[:i], xlsx.MergeCells.Cells[i+1:]...)
//	} else if checkCellInArea(vcell, xlsx.MergeCells.Cells[i].Ref) || checkCellInArea(strings.Split(xlsx.MergeCells.Cells[i].Ref, ":")[1], mergeCell.Ref) {
//		xlsx.MergeCells.Cells = append(xlsx.MergeCells.Cells[:i], xlsx.MergeCells.Cells[i+1:]...)
//	}
//}

**Comment by xuri** [comment]
Thanks for your issue, but for format compatibility, I don't agree with the proposal.
