### ISSUE TITLE
How to set the cell format ? 

### ISSUE THREAD

**Issue by professorxin** [360EntSecGroup-Skylar/excelize#705]
cell format as example:
![image](https://user-images.githubusercontent.com/38785214/93550915-21c69480-f99f-11ea-99f1-7959a348dc43.png)

How to set the cell format to the text ?

**Comment by xuri** [comment]
You can set cell `A1` as text by number format like this:

```go
var style int
if style, err = f.NewStyle(&excelize.Style{NumFmt: 49}); err != nil {
    fmt.Println(err)
    return
}
if err = f.SetCellStyle("Sheet1", "A1", "A1", style); err != nil {
    fmt.Println(err)
    return
}
```

**Comment by andy-cywang** [comment]
How about to set the format to Numberic? What would be the numFmt value? I cannot find the doc on this from anywhere

**Comment by xuri** [comment]
Sorry for my late reply, you can find more built-in number format mapping details in the [documentation](https://xuri.me/excelize/en/style.html#number_format).
