### ISSUE TITLE
Two meanings return in NewSheet(name string) int

### ISSUE THREAD

**Issue by Charnnarong** [360EntSecGroup-Skylar/excelize#714]
I would like to thank to all contributors for creating such a great library. It is tremendous help in my work. I have a minor issue here.

https://github.com/360EntSecGroup-Skylar/excelize/blob/520aa679f34bafbc00626151075b0b123eceb516/sheet.go#L36

The comment says `Returns the number of sheets in the workbook (file) after appending the new sheet.`  However, the return number has two meanings.
1. [sheet count](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/sheet.go#L41)
2. [sheet index](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/sheet.go#L63)

For instance

```
// f *excelize.File
totolSheet := f.NewSheet("newSheetName")
log.Println("create new sheet: ", totolSheet, f.SheetCount)
```
output.
`totalSheet ` is always one less than `f.SheeetCount` if "newSheetName" hasn't existed before (succeed in appending a new sheet).
Both are equal in case of "newSheetName" is already exist.

I faced the problem by reading the comment and wrote my code as
`tempIndex := f.NewSheet(tempName) - 1`
now, I have to change to 
`tempIndex := f.NewSheet(tempName)` 
which isn't quite having the same meaning with the function comment.

**Comment by xuri** [comment]
Thanks for your feedback, as you say the index returned by `NewSheet` when the worksheet already exists is wrong, it shouldn't be sheet count, I'll fix it.

**Comment by Charnnarong** [comment]
Great, thank you for the quick action! Returning the index is more coherence. Just a kind reminder of updating the comment to reflect the change would be very appreciated.

**Comment by xuri** [comment]
I have fixed it, please try to use the master branch code.

**Comment by Charnnarong** [comment]
Thank you for the fix. How about the method's comment. The original one is
```
// NewSheet provides function to create a new sheet by given worksheet name.
// When creating a new spreadsheet file, the default worksheet will be
// created. Returns the number of sheets in the workbook (file) after
// appending the new sheet.
```
The last sentence `Returns the number of sheets in the workbook (file) after appending the new sheet.` 
Shouldn't it be `Returns the index of the sheets in the workbook (file) after it appended` ? Or anything similar as you see fit as we are not returning the number of sheets in the workbook anymore.

**Comment by xuri** [comment]
I have updated the docs of the `NewSheet`.

**Comment by Charnnarong** [comment]
Thank you for the fix. The comment is now crystal clear. And also with your additional of `the default worksheet named `Sheet1` will be created.` is left no user with no double what it is going to happen when calling the function. Thank you again.
