### ISSUE TITLE
When I read an excel sheet, an error occurred

### ISSUE THREAD

**Issue by Iamzz-cn** [360EntSecGroup-Skylar/excelize#715]
```go
func main() {
	f, err := excelize.OpenFile("i18n.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	// 获取 Sheet1 上所有单元格
	rows, err := f.GetRows("Sheet1")

	if err != nil {
		fmt.Println(err)
		return
	}
	for _, row := range rows {
		for _, colCell := range row {
			fmt.Print(colCell, "\t")
		}
		fmt.Println()
	}
}

```
![image](https://user-images.githubusercontent.com/21697242/96414633-fa721a00-121f-11eb-8c21-18957bf63b9b.png)

**Comment by Iamzz-cn** [comment]
I can’t make a copy of the same excel.This i18n table has 14 columns and 13000+ rows

**Comment by Iamzz-cn** [comment]
So I have no way to provide an excel file

**Comment by Iamzz-cn** [comment]
go version go1.15.3 windows/amd64

**Comment by Iamzz-cn** [comment]
The excelize version was downloaded yesterday using `go get github.com/360EntSecGroup-Skylar/excelize`

**Comment by Iamzz-cn** [comment]
I want to know what is the specific cause of the problem, formula or cell format, etc.

**Comment by Iamzz-cn** [comment]
When I copied the entire table as a value to another table, the problem disappeared, but my table is too big, and I have no way to determine which cell has the problem

**Comment by Iamzz-cn** [comment]
I can read the value of a certain cell, but there will be problems when traversing the entire table

**Comment by Iamzz-cn** [comment]
Thank you

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code.
