### ISSUE TITLE
Could you publicize functions of "getCellStyle"?

### ISSUE THREAD

**Issue by zzc-tongji** [360EntSecGroup-Skylar/excelize#72]
It is really useful when developers want to set the style of a new cell as same as an existent cell (format painter).

**Comment by vchugreev** [comment]
I join the request. In our project, too, there is such a need. We need this for integration with a similar xlsx js library.

**Comment by Luxurioust** [comment]
I plan to reflect the style method by adding a new function `NewStyle()` to get style ID, and pass this ID to function `SetCellStyle()`. I will export this function after completion.

**Comment by vchugreev** [comment]
Thank you! It will be useful.

**Comment by Luxurioust** [comment]
The function `GetCellStyle()` has been exported (the function name typo in commit log).
