### ISSUE TITLE
Padding of column string slice fails when last column of file has empty values

### ISSUE THREAD

**Issue by rupertevill** [360EntSecGroup-Skylar/excelize#721]
**Description**

I have an .xlsx file and for the **last** column, some values are empty cells. Normally, the row that is returned (a slice of strings) would be padded with an additional nil value (empty string) to represent an empty column - this works if I use an xlsx file that contains a column with some empty cells where the column **is not** the **last** column. However, if the column is the last column the padding of the slice fails.

**Steps to reproduce the issue:**
1. Create an xlsx file with two columns, where at least one of the rows contains an empty cell for the second column.
2. Read as usual, run `GetRows()` on the file object.
3. Range over rows and print any row where length of the row != 2 (the expected length).

**Describe the results you received:**
The rows with empty values were not padded with an empty string within the returned column slice of strings.

**Describe the results you expected:**
The rows with empty values would be padded with an empty string within the returned column slice of strings.

**Output of `go version`:**

```text
go version go1.14.2 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.3.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
macOS Catalina 10.15.6

Who knows though, maybe I'm being dumb. In which case I can close this issue happily 👍

**Comment by xuri** [comment]
Thanks for your issue. I have tested with the following spreadsheet and it works well.

|   | A  | B  | C  |
|---|----|----|----|
| 1 | A1 |    |    |
| 2 | A1 | B2 | C3 |
| 3 | A3 | B3 |    |
| 4 | A4 | B4 | C4 |
| 5 | A5 | B5 |    |

```go
package main

import (
    "fmt"

    "github.com/360EntSecGroup-Skylar/excelize"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    // Get all the rows in the Sheet1.
    rows, err := f.GetRows("Sheet1")
    for _, row := range rows {
        for _, colCell := range row {
            fmt.Print(colCell, "\t|")
        }
        fmt.Println()
    }
}
```

Output:

```text
A1  |
A2  |B2  |C3  |
A3  |B3  |
A4  |B4  |C4  |
A5  |B5  |
```

The `GetRows` API will retrieve not empty cells for each row, but it not will be skipping the cell with a blank string, so the length of each row returned by GetRows maybe not consistent. If you have any questions, let me know.

**Comment by xuri** [comment]
I close this issue and welcome left comments if you have any more questions.

**Comment by DGollings** [comment]
had the same issue, this library I'm using to guesstimate a csv delimiter does so by comparing recurring separator patterns, which means it is not happy when encountering (quick example)

```
;;;
;
;;
```

Here's a quick solution for anyone wanting to feed f.GetRows to cw.WriteAll in a 'square' shape:
```
func padOutRows(rows [][]string) [][]string {
	columnCount := 0
	for _, r := range rows {
		if len(r) > columnCount {
			columnCount = len(r)
		}
	}
	for i, r := range rows {
		rows[i] = r[:columnCount]
	}
	return rows
}
```

@xuri I understand why it usually makes sense to skip empty rows (in face, I like how 'human' this library is in its approach to data),  but maybe offer it as an option?
