### ISSUE TITLE
write two sheets concurrency got WARNING: DATA RACE | 并行写入两个sheet被警告“DATA RACE”

### ISSUE THREAD

**Issue by liserjrqlxue** [360EntSecGroup-Skylar/excelize#723]
**Description**

I'll fill this issue with English and add test demo later. （我之后会补充测试用例和英文版本issue）
我从一个excel模板开始，对不同sheet进行的处理通过goroutine并行了
在用-race检查时被警告WARNING: DATA RACE
我想知道这个是可以忽视的警告，还是会真实影响结果准确性？
是否有简单高效的方式处理
（从我目前的程序使用上，不是特别需要并行，可以简单改成串行，不过对于excelize本身，可能弄清楚这些问题有一定益处）
**Steps to reproduce the issue:**
1.`excelize.OpenFile(*template)`读入包含两个sheet的模板
2.两sheet分别写入一定量数据
3.上面的步骤改成`go func(){}()`并行
4.添加-race参数测试运行

**Describe the results you received:**
```
==================
WARNING: DATA RACE
...
==================
Found * data race(s)
```
**Describe the results you expected:**
no `RACE` warning
**Output of `go version`:**

```text
go version go1.14.4 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.3.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux

**Comment by xuri** [comment]
Hi @liserjrqlxue, thanks for your feedback. Could you provide code or more details to reproduce this issue?

**Comment by liserjrqlxue** [comment]
After modify my code for other propose, I can't reproduce this issue.
I wrote a simple test code, but also can't reproduce this issue.
I'll close this issue till I can found something to share.
