### ISSUE TITLE
get the incorrent result when there is a cell with Number Format Ref #703

### ISSUE THREAD

**Issue by oushu1jinliujie1** [360EntSecGroup-Skylar/excelize#724]
**Description**
I add a cell with Number Format in WPS. then i read this file by ```excelize``` api, but there is a incorrrent result

![image](https://user-images.githubusercontent.com/63893685/98623255-40fdf480-2346-11eb-8367-da0ac317a24d.png)
![image](https://user-images.githubusercontent.com/63893685/98623242-3e030400-2346-11eb-8ff4-4ba213ea66c4.png)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
