### ISSUE TITLE
streamWriter中 SetCellStyle和SetColWidth 都无效

### ISSUE THREAD

**Issue by kaidengdd01** [360EntSecGroup-Skylar/excelize#725]
迭代器按行赋值，请问如何同时设置当前行的 样式。文档中只看到了迭代器设置当前单元格样式的方法
```
if err := streamWriter.SetRow("A1", []interface{}{
    excelize.Cell{StyleID: styleID, Value: "Data"}}); err != nil {
    fmt.Println(err)
}
```
或者 迭代器 flush 后，我还有什么方法设置样式吗

**Comment by xuri** [comment]
Thanks for your issue. `SetCellStyle` and `SetColWidth` are not a streaming API, so they will not work in stream mode, please [reference the doc](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.NewStreamWriter) to get more detail about set cell style with streamWriter. The feature request of set column width has been added in [the Roadmap](https://github.com/xuri/excelize/wiki#roadmap), also reference #625
