### ISSUE TITLE
Rounding errors

### ISSUE THREAD

**Issue by jttodd** [360EntSecGroup-Skylar/excelize#727]
**Steps to reproduce the issue:**

A1 = .1
A2 = .2
A3 = formula A1 + A2

Value of A3 in Excel is .3 

**Describe the results you received:**

Value returned from GetCellValue for A3 is 0.30000000000000004

**Describe the results you expected:**

Expected value returned from GetCellValue for A3 of 0.3

**Output of `go version`:**

```text
go version go1.15.3 windows/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize v1.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
