### ISSUE TITLE
Read date/time from the cell

### ISSUE THREAD

**Issue by vchugreev** [360EntSecGroup-Skylar/excelize#73]
How to correctly read the date/time from the cell?

**Comment by vchugreev** [comment]
I will explain the problem:

In the Excel file there is a cell:
E7 => 29.06.2017 9:28:48
Format: "14-Mar-12"

I'm trying to get it...

`e7 := xlsx.GetCellValue("Sheet1", "e7")`
`println(e7)`

Output: "42915.395"

**Comment by Luxurioust** [comment]
Do you mean `Sheet1!E7` is string type value `29.06.2017 9:28:48`? If so, string type value can't be formatted as a date format. Please provide file attachments If you can.

**Comment by vchugreev** [comment]
xlsx?
[1_2017-06-29.xlsx](https://github.com/Luxurioust/excelize/files/1112114/1_2017-06-29.xlsx)

**Comment by Luxurioust** [comment]
This library just support Excel's [built-in formats](https://godoc.org/github.com/Luxurioust/excelize#File.SetCellStyle) currently. The built-in formats 
 index (`numFmtId = 164`) in the attachment is out of this range. Same as the issue #50.

**Comment by vchugreev** [comment]
Now it is clear. Thank you!

**Comment by akatsukle** [comment]
I am not sure I understand how SetCellStyle works.
On a comment above the function there is the following:
```
//     Index | Format String
//    -------+----------------------------------------------------
//     0     | General
//     1     | 0
//     2     | 0.00
//     3     | #,##0
//     4     | #,##0.00
//     5     | ($#,##0_);($#,##0)
//     6     | ($#,##0_);[Red]($#,##0)
//     7     | ($#,##0.00_);($#,##0.00)
//     8     | ($#,##0.00_);[Red]($#,##0.00)
//     9     | 0%
//     10    | 0.00%
//     11    | 0.00E+00
//     12    | # ?/?
//     13    | # ??/??
//     14    | m/d/yy
//     15    | d-mmm-yy
//     16    | d-mmm
//     17    | mmm-yy
//     18    | h:mm AM/PM
//     19    | h:mm:ss AM/PM
//     20    | h:mm
//     21    | h:mm:ss
//     22    | m/d/yy h:mm
```

With this in mind the following makes perfect sense
```
xlsx.NewStyle(`{"number_format":15}`) // 29-Jun-17
```

However, when I tried for `m/d/yy`, I get the following:
```
xlsx.NewStyle(`{"number_format":14}`) // 11-15-21
```

The format seems to match the comment, so I'm not sure what I am missing.

Bonus question:
Is there any way to get the year in a yyyy format instead?

**Comment by akatsukle** [comment]
Nevermind, it is probably easier to convert the excel date to a time.Time.
In most cases, this can be done the following way:
```
// note: this is off by two days on the real epoch (1/1/1900) because
// - the days are 1 indexed so 1/1/1900 is 1 not 0
// - Excel pretends that Feb 29, 1900 even though it did not
// The following function will fail for dates before March 1st 1900
// Before that date the Julian calendar was used so a conversion would be necessary
var excelEpoch = time.Date(1899, time.December, 30, 0, 0, 0, 0, time.UTC)

func excelDateToDate(excelDate string) time.Time {
	var days, _ = strconv.Atoi(excelDate)
	return excelEpoch.Add(time.Second * time.Duration(days*86400))
}
```

**Comment by alibitek** [comment]
My date is in the format `mm.dd.yyyy` how can I parse it with this library ?

**Comment by fatindeed** [comment]
when upgrade v2.3.1 to v2.3.2
`xlsx.GetCellValue()` will return a date-time string, like `Jan 1`. It's hard to be converted to time.
So you must set cell style to `0`, and get cell value again. Then it will return the float value and you can convert it to time.
```golang
err := xlsx.SetCellStyle("sheet1", "A1", "A1", 0)
if err != nil {
	// do something
}
label, err := xlsx.GetCellValue("sheet1", "A1")
if err != nil {
	// do something
}
f, err := strconv.ParseFloat(label, 64)
if err != nil {
	// do something
}
t, err = excelize.ExcelDateToTime(f, false)
if err != nil {
	// do something
}
```

**Comment by yeguacelestial** [comment]
> My date is in the format `mm.dd.yyyy` how can I parse it with this library ?

You can change the format of the output date as follows, with `Format` method:
```
func ExcelSerialDateToTime(serial string) string {
	days, _ := strconv.Atoi(serial)

	convertedTime := excelEpoch.Add(time.Second * time.Duration(days*86400)).Format("01-2-2006")

	return convertedTime
}
```

**Comment by brunql** [comment]
**ParseFloat** works better if you need time not just days:

```go
func toDate(excelDate string) time.Time {
	var days, _ = strconv.ParseFloat(excelDate, 64)
	return excelEpoch.Add(time.Second * time.Duration(days*86400))
}
```

**Comment by ITheCorgi** [comment]
Hy everyone, is there any update regarding date issue?
It still scans in time format 04-04-2023. I want it in same way as it was stored in excel column (it may any date format).
For example, I store in date column value '04.04.2023', but library scans as '04-04-2023'.
Is there any solution or workaroud to specify in config to scan date types as is like raw text?

**Comment by alisherin** [comment]
> Hy everyone, is there any update regarding date issue? It still scans in time format 04-04-2023. I want it in same way as it was stored in excel column (it may any date format). For example, I store in date column value '04.04.2023', but library scans as '04-04-2023'. Is there any solution or workaroud to specify in config to scan date types as is like raw text?

parsedDate, parsedDateErr := time.Parse("01-02-2006", "04-04-2023")
if parsedDateErr != nil {
 log.Println(somenthingYouWant)
}
formatThatYouWant := parsedDate.Format("01.02.2006")

Maybe someone give you better answer) Good luck
