### ISSUE TITLE
Read generated file by GetRows or Rows  return unexpect result

### ISSUE THREAD

**Issue by kaidengdd01** [360EntSecGroup-Skylar/excelize#732]
**Description**

I test read excel file with an generated  by this package.If I use GetRows or Rows function.It will return unexpect result.return result not rows result.It return data one by one cell.but the GetCols and Cols is correctly.I generate the excel file with StreamWriterAPI and Style

**Describe the results you received:**
![2020-11-17_18-36](https://user-images.githubusercontent.com/40782150/99379651-e9422900-2903-11eb-9290-b2b0b51efda2.png)

**Describe the results you expected:**
It should return whole row data

**generate file code**
```text
styleID, _ := e.File.NewStyle(&excelize.Style{
		Font: &excelize.Font{
			Size: 13, // 设置字体大小
		},
		Alignment: &excelize.Alignment{
			Horizontal: "center", // 水平剧中
			Vertical:   "center", // 垂直剧中
		},
	})
if err = StreamWriter.SetRow(fromCell, []interface{}{excelize.Cell{StyleID: styleID, Value: value}}); 
     err != nil {return}
```

**read code**
```text
file, err := excelize.OpenFile(path)
	if err != nil {
		return err
	}
rows, err := file.GetRows(sheetName)
	if err != nil {
		return nil, err
	}
	return rows, nil
``` 

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
excelize version: 2.3.1
go version: go1.15.3 linux/amd64
os: ubuntu18

similar with https://github.com/360EntSecGroup-Skylar/excelize/issues/519

[test.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/5552870/test.zip) this is Excel file

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
