### ISSUE TITLE
method `ProtectSheet` can lock sheet, but cannot select locked cell

### ISSUE THREAD

**Issue by hybnew** [360EntSecGroup-Skylar/excelize#736]
**Description**

**Steps to reproduce the issue:**
1.
write a test to reproduce `ProtectSheet`
```
func TestProtectSheet(t *testing.T) {
	f := excelize.NewFile()
	name := f.GetSheetName(0)
	err := f.SetCellStr(name, "A1", "you can choose me")
	if err != nil {
		panic(err)
	}
	//
	err = f.ProtectSheet(name, nil)
	if err != nil {
		panic(err)
	}
	f.SaveAs("test_protect.xlsx")
}
```

2.

3.

**Describe the results you received:**
without green border, cannot be selected
![image](https://user-images.githubusercontent.com/8206442/99926862-284a0180-2d7e-11eb-9c7c-0dde14df80ad.png)
**Describe the results you expected:**
with green border, can be selected

![image](https://user-images.githubusercontent.com/8206442/99926916-4d3e7480-2d7e-11eb-9a39-bb28ba39f123.png)

**Output of `go version`:**

```text
go version go1.14 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.3.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by hybnew** [comment]
this issue is the clone of [https://github.com/360EntSecGroup-Skylar/excelize/issues/733](url)

**Comment by xuri** [comment]
Hi @hybnew, if you wanna make cell selectable, just specify `SelectLockedCells` as `false`:

```go
if err := f.ProtectSheet("Sheet1", &excelize.FormatSheetProtection{
	EditScenarios:     false,
	SelectLockedCells: false,
}); err != nil {
	fmt.Println(err)
	return
}
```

**Comment by hybnew** [comment]
@xuri  it works! thanks buddy! but why SelectLockedCells: false? i thought i would be true.

**Comment by xuri** [comment]
The `false` means that NOT protect cell selection, so you can select any cells.
