### ISSUE TITLE
Problems with xlsm file using Https when downloading...

### ISSUE THREAD

**Issue by crazysm** [360EntSecGroup-Skylar/excelize#738]
**Description**

my code: 

	f, err := excelize.OpenFile(filePath)//*.xlsm
	if err != nil {
		slog.Debug("open xlsm file: %v failed.", fileName)
		return
	}
	slog.Debug("open xlsm file: %v success.", fileName)

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", "attachment; filename=\""+fileName+"\"")
	w.Header().Set("Content-Transfer-Encoding", "binary")
	//w.Header().Set("Content-Length", fmt.Sprintf("%v", len(content)))

	_ = f.Write(w.(http.ResponseWriter))

**Describe the results you received:**
my backend HTTPS server run these code,   the origin xlsm file size is  58341 bytes, but the frontend   received xlsm file size is  100kbytes.
but if I use backend HTTP server , these codes are  OK .
why?What's wrong?

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
This problem is not in the scope of this library function, maybe you should be checking the HTTPS service ingress layer, WAF, or something else.
