### ISSUE TITLE
CoordinatesToCellName undefined (type *excelize.File has no field or method CoordinatesToCellName)

### ISSUE THREAD

**Issue by khalinmaxim** [360EntSecGroup-Skylar/excelize#742]
github.com/360EntSecGroup-Skylar/excelize v1.4.1
go  v1.14

I want to get the cell address by x, y coordinates, I found the coordinates to Cell Name method. I try to use it and an error occurs "CoordinatesToCellName undefined (type *excelize.File has no field or method CoordinatesToCellName)"

**Comment by khalinmaxim** [comment]
I looked at release 2.0.0, and saw that this feature was added in this version, how do I update?

**Comment by xuri** [comment]
Hi @khalinmaxim you can upgrade this library by:

```bash
go get -u github.com/360EntSecGroup-Skylar/excelize
```

**Comment by khalinmaxim** [comment]
Hi @xuri no, 
```
maximkhalin@Air-Maksim reporter % go get -u github.com/360EntSecGroup-Skylar/excelize
go: github.com/360EntSecGroup-Skylar/excelize upgrade => v1.4.1
```

**Comment by xuri** [comment]
As noticed in README, if your package management with [Go Modules](https://blog.golang.org/using-go-modules), please install with following command:

```go
go get github.com/360EntSecGroup-Skylar/excelize/v2
```

after that, you need to use import path with `v2` in your code.

**Comment by khalinmaxim** [comment]
Oh My GOD, THANK YOU @xuri , I already created my own repository, copied the module there, and it still didn't work, Thank you very much again. I delete my own repository now

**Comment by xuri** [comment]
You're welcome. I'll close this issue.

**Comment by khalinmaxim** [comment]
But CoordinatesToCellName undefined (type *excelize.File has no field or method CoordinatesToCellName) again
