### ISSUE TITLE
Cannot find pkg "github.com/360EntSecGroup-Skylar/excelize/v2"

### ISSUE THREAD

**Issue by DevMousee** [360EntSecGroup-Skylar/excelize#745]
**Description**
When trying to use excelize v2 i get an error.
I've read about a similar issue #[393 ](https://github.com/360EntSecGroup-Skylar/excelize/issues/393) but i'm not understand the solution given, how can i delete go mod cache $GOPATH/pkg/mod/cache?

**Steps to reproduce the issue:**
1. On a Go File add import "github.com/360EntSecGroup-Skylar/excelize/v2"
2. Run the program

**Describe the results you received:**
```
cannot find package "github.com/360EntSecGroup-Skylar/excelize/v2" in any of:
	c:\go\src\github.com\360EntSecGroup-Skylar\excelize\v2 (from $GOROOT)
	C:\Users\myUser\go\src\github.com\360EntSecGroup-Skylar\excelize\v2 (from $GOPATH)

```

**Describe the results you expected:**
Build successful

**Output of `go version`:**

```text
go version go1.15.6 windows/amd64go version go1.15.6 windows/amd64
```

**Excelize version or commit ID:**

```How do i get this one?
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Using Windows, and Visual Studio Code

**Comment by xuri** [comment]
Could you provide the output of `go env`? Please make sure you are using the Go module to manage Go packages, and delete the folder `$GOPATH/pkg/mod/cache`  to clean the go mod cache.

**Comment by xuri** [comment]
Hi, @DevMousee I closed this issue, if you have any questions, please let me know.
