### ISSUE TITLE
 AddPicture (autofit) has a size problem when there are multiple merged cells.

### ISSUE THREAD

**Issue by yuki2006** [360EntSecGroup-Skylar/excelize#748]
Thank you for the very useful library.

**Description**

Depending on the order of the merged cells,
The size of the image changes because the cell merge detection cannot be performed.

Probably the line is wrong and the `inMergeCell` is overwritten and it is not judged correctly.

https://github.com/360EntSecGroup-Skylar/excelize/blob/master/picture.go#L608

**Steps to reproduce the issue:**
1.

```
		f := excelize.NewFile()
		sheet1 := f.GetSheetName(0)

		f.MergeCell(sheet1, "A2", "C3")
		f.MergeCell(sheet1, "A100", "C101")

		err := f.AddPicture(sheet1, "A2", "../../.ignore/Pic.jpg", `{"lock_aspect_ratio":true,"autofit":true}`)
		if err != nil {
			t.Error(err)
			return
		}

		f.SaveAs("/tmp/A.xlsx")
```

![image](https://user-images.githubusercontent.com/1004620/102065364-cdb33b00-3e3b-11eb-866e-e4db02b1b898.png)

2.

```
		f := excelize.NewFile()
		sheet1 := f.GetSheetName(0)

		f.MergeCell(sheet1, "A100", "C101")
		f.MergeCell(sheet1, "A2", "C3")

		err := f.AddPicture(sheet1, "A2", "../../.ignore/Pic.jpg", `{"lock_aspect_ratio":true,"autofit":true}`)
		if err != nil {
			t.Error(err)
			return
		}

		f.SaveAs("/tmp/B.xlsx")
```

![image](https://user-images.githubusercontent.com/1004620/102065340-c68c2d00-3e3b-11eb-8bed-94ada6ab5766.png)

**Describe the results you expected:**

Display pattern 2 regardless of the order of merged cells.

**Output of `go version`:**

go1.15

**Excelize version or commit ID:**

v2.3.1

**Comment by xuri** [comment]
Hi, @yuki2006. Thanks for your issue. I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
