### ISSUE TITLE
Conditional Formatting

### ISSUE THREAD

**Issue by AlexeyKrapotkin** [360EntSecGroup-Skylar/excelize#75]
Do you plan to read / write Conditional Formatting add?
Thnks.

**Comment by AlexeyKrapotkin** [comment]
How is the progress in implementation?

**Comment by xuri** [comment]
Sorry, this feature has not yet been implemented. I will working on it as soon as possible.

**Comment by AlexeyKrapotkin** [comment]
Well thank you. Will wait. :)
Успехов ! :)

**Comment by xuri** [comment]
Hi, I have initialized conditional formatting filter support. We can create conditional formatting by  [`NewConditionalStyle()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewConditionalStyle) and [`SetConditionalFormat()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetConditionalFormat) now.

**Comment by AlexeyKrapotkin** [comment]
Nice, nice. Now let's try))

**Comment by AlexeyKrapotkin** [comment]
It nice. Perfect work.  When support of the type  "formula" - "expression"?
Thnks

**Comment by AlexeyKrapotkin** [comment]
How to add multiple rules "cfRule" with different priority to one conditional formatting declaration? 
Example:
```
<conditionalFormatting sqref="G16:G29">
<cfRule type="expression" priority="2" aboveAverage="0" equalAverage="0" bottom="0" percent="0" rank="0" text="" dxfId="0">
<formula>AND($G18>0,$G18>MIN($H18:$J18),MIN($H18:$J18)>0)</formula>
</cfRule>
<cfRule type="expression" priority="3" aboveAverage="0" equalAverage="0" bottom="0" percent="0" rank="0" text="" dxfId="1">
<formula>AND($G18>0,$G18<MIN($H18:$J18))</formula>
</cfRule>
<cfRule type="expression" priority="4" aboveAverage="0" equalAverage="0" bottom="0" percent="0" rank="0" text="" dxfId="2">
<formula>AND($G18>0,$G18=MIN($H3:$J3))</formula>
</cfRule>
</conditionalFormatting>
```

**Comment by xuri** [comment]
The third parameter of function `SetConditionalFormat()` can be parse array JSON object, and you can create different conditional format order by priority. But this library not support create conditional format with formula currently, I will add support for it as soon as possible.

**Comment by AlexeyKrapotkin** [comment]
Yes thank you. I create such an object, either the last value, or nothing at all in the file. Or am I doing something wrong?
`xlFile.SetConditionalFormat("Sheet1", fmt.Sprintf(`G%d:G%d`, start_position, rows), fmt.Sprintf(`[{"type":"cell","criteria":"<","format":%d,"value":"$H%d"."type":"cell","criteria":">","format":%d,"value":"$H%d"}]`, format_green, start_position, format_red, start_position))`

**Comment by xuri** [comment]
Use use the standard JSON format, like this: `xlFile.SetConditionalFormat("Sheet1", fmt.Sprintf(``G%d:G%d``, start_position, rows), fmt.Sprintf("[{"type":"cell","criteria":"<", "format":%d,"value":"$H$%d"},{"type":"cell","criteria":">","format":%d,"value":"$H$%d"}]", format_green, start_position, format_red, start_position))`
