### ISSUE TITLE
SheetIndex error after NewSheet method

### ISSUE THREAD

**Issue by gitDaing** [360EntSecGroup-Skylar/excelize#750]
**Description**

```go
f := excelize.NewFile()
sheetIndex = f.NewSheet("Sheet1")
fmt.Println(sheetIndex)  // out: 1
```

**Output of `go version`:**

```text
go1.14.6
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2
```

**Comment by xuri** [comment]
Hi, @gitDaing thanks for your issue. I have tested and it works well. Please use the latest version 2.3.1 or using the master branch code.

**Comment by xuri** [comment]
Hi @gitDaing  I closed this issue, if you have any questions, please let me know.
