### ISSUE TITLE
origin cell data type is int, like （112233）after read the data it turn to （112233.0）a float type

### ISSUE THREAD

**Issue by xiaopenggithub** [360EntSecGroup-Skylar/excelize#751]
**Description**
a list of student's data,student id is int type,after read by excelize ,the id column type  change to float
like 112233->112233.0

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```
![image](https://user-images.githubusercontent.com/20268389/102680526-f0ef3900-41f3-11eb-91e6-4b915e2185dc.png)

![image](https://user-images.githubusercontent.com/20268389/102680576-7d016080-41f4-11eb-9e3c-cec5c7f94b2c.png)

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
go version  1.15.4

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using? Please create the issue by an issue template and provide a spreadsheet xlsx attachment without confidential info.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
