### ISSUE TITLE
When using DuplicateRow, it is not duplicated correctly when there are multiple merged cells.

### ISSUE THREAD

**Issue by yuki2006** [360EntSecGroup-Skylar/excelize#752]
**Description**

When duplicating a row with multiple merged cells, the cells that are used correctly are not copied.

Perhaps this `i++` skips the loop step.

https://github.com/360EntSecGroup-Skylar/excelize/blob/77978ac68d3808060e58df41ebede4b9f3631641/rows.go#L605

**Steps to reproduce the issue:**
1.

```
	f, err := excelize.OpenFile("../../.ignore/B.xlsx")
	if err != nil {
		panic(err)
	}
	sheet := f.GetSheetName(0)
	err = f.DuplicateRowTo(sheet, 1, 3)
	if err != nil {
		panic(err)
	}
	err = f.SaveAs("../../.ignore/B_.xlsx")
	if err != nil {
		panic(err)
	}
```

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/1004620/102751838-e4154580-43ab-11eb-901c-d22f9a18eca6.png)

**Describe the results you expected:**

Want the same thing as the 1 col to be the 3 col.

**Output of `go version`:**

```text
go 1.15
```

**Excelize version or commit ID:**

```text
77978ac68d3808060e58df41ebede4b9f3631641

```

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
