### ISSUE TITLE
Stream while appending to xlsx

### ISSUE THREAD

**Issue by sfroment** [360EntSecGroup-Skylar/excelize#753]
I would like to know if there's was a way I can at the same time use a streamWriter, and file.WriteTo in order for writeTo to write on the io.Writer when I call streamWriter.Flush, and then on the second call it only writes the missing parts ?

**Comment by xuri** [comment]
Hi @sfroment, `streamWriter.Flush` just flush data on a single worksheet after writing data at once, and then `WriteTo` will prepare and writing the workbook data into `io.Writer`. Since workbook data depends on the finished worksheet data writing, so we can't call these at the same time.

**Comment by sfroment** [comment]
Yes that what I've understood that, I think I haven't explained well what I want to do. I would like to stream the download while I build the excel sheet. I know it's not possible with the current implementation, but would it be possible or does the library need to have all the sheets built before writing ?

**Comment by xuri** [comment]
With the spreadsheet [specification](http://www.ecma-international.org/publications/standards/Ecma-376.htm) limit (OPC part), the workbook serialization should be waiting all worksheet has been ready. If you need process with amount of data, please try separate it into multiple spreadsheet files if you can.

**Comment by sfroment** [comment]
Thanks !
