### ISSUE TITLE
How to set footer by function “SetHeaderFooter”，How to use this method, I tried but failed to achieve the desired effect

### ISSUE THREAD

**Issue by Tongzp** [360EntSecGroup-Skylar/excelize#754]
I set the footer, but the page number is reversed.

![image](https://user-images.githubusercontent.com/33510725/103049181-f5d53380-45cb-11eb-8b43-0ad650d629a5.png)

**Comment by xuri** [comment]
What effect did you expected, what did you do and which version of Excelize are you using? Could you create the issue by an issue template and provides more detail?
