### ISSUE TITLE
Purpose of setting empty string to cell in "nil" case

### ISSUE THREAD

**Issue by yakartoev** [360EntSecGroup-Skylar/excelize#756]
Hi!

Explain please, what the purpose of setting the value "" to cell in SetCellValue method, when value argument is nil? I don't report is as a bug, because as I can see it's done deliberately, but I don't get a point of that. 
Here is the line of code I'm talking about https://github.com/360EntSecGroup-Skylar/excelize/blob/master/cell.go#L96

The problem is that It fills the cell with some value, and excel doesn't take that kind cells as empty (you can check it by calling ISBLANK() excel function on them), so when you for example set row data by using SetSheetRow and want skip some cells in the row by passing a nil, it fills them with "", and so you not skipping them in fact, only setting to empty string.

So what the point of that line of code? Can you just skip the case of value == nil in SetCellValue?

**Comment by xuri** [comment]
Hi @yakartoev Thanks for your proposal, I agree with you and I'll fix it recently.

**Comment by barismar** [comment]
Hi @xuri, what about `StreamWriter.SetRow`? I still find `""` (empty string) in the empty cell, when I set the cell value to `nil` like this  `excelize.Cell{Value: nil, StyleID: styleId}` or not set the value of the cell `excelize.Cell{StyleID: styleId}` and bot ways are detected as not blank when using ISBLANK() function in excel

I am using v2.7.0

**Comment by xuri** [comment]
Hi @barismar, thanks for your feedback. I think we need to change the `setCellValFunc` for the stream writer in the [`stream.go`](https://github.com/xuri/excelize/blob/94e86dca31476ec79f0643ae9645893507ec56f3/stream.go#L539) like this:

```diff
    case nil:
-       c.setCellValue("")
+       return err
    case []RichTextRun:
```

If you like to create a pull request for this. I'll certainly accept this patch, or I'll fix that tomorrow.

**Comment by barismar** [comment]
Thanks for the response @xuri, here is the PR  https://github.com/qax-os/excelize/pull/1481, please kindly check it...
