### ISSUE TITLE
About GetCellValue to get wrong result from Chinese style date

### ISSUE THREAD

**Issue by johnbitcn** [360EntSecGroup-Skylar/excelize#759]
![image](https://user-images.githubusercontent.com/1518771/103979880-a8ef8080-51b9-11eb-829d-dad437426a74.png)
![image](https://user-images.githubusercontent.com/1518771/103980413-ccff9180-51ba-11eb-84ee-2d94810eec18.png)

``` go
	for _,v :=range kCharAr{
		key := string(v) + strconv.Itoa(4)
		cell,_ := f.GetCellValue("表4 网点个人客户资产结构",key)
		date = append(date, cell)
	}
	for _,v := range date{
		fmt.Println(v)
	}
```

Output result：

``` bash
2019"年"m"月"
2019"年"m"月"
2019"年"m"月"
2020"年"m"月"
2020"年"m"月"
2020"年"m"月"
2020"年"m"月"
```

versions
```bash
go 1.15

require github.com/360EntSecGroup-Skylar/excelize/v2 v2.3.2
```

**Comment by xuri** [comment]
Thanks for your feedback. This issue similar to #660. I close this and merge it into issue #660 is still discussing this feature.
