### ISSUE TITLE
SetCellStyle will overwrite the style for the cell

### ISSUE THREAD

**Issue by yunduansing** [360EntSecGroup-Skylar/excelize#760]
场景为：导入数据生成错误文件，把第一列文字标红
代码：
`conStyle,_:=file.NewStyle(`{
		"alignment":{
			"horizontal": "center",
			"vertical": "center"
		},
		"font":{"bold":true,"family":"Times New Roman","color":"#FF0000"}
	}`)
file.SetCellStyle(sheet,"A4","A4",conStyle)`
excel中有一列（非第一列）存在：01、03，在file.Save保存后excel会提示此列错误：该数字是文本类型，可能出现计算错误

然后导致SetCellStyle设置的样式不生效。
![image](https://user-images.githubusercontent.com/11469334/104144480-4dfa9b00-53fe-11eb-85e7-2522088cb7de.png)

**Comment by yunduansing** [comment]
go version:1.14
excelize:github.com/360EntSecGroup-Skylar/excelize/v2 v2.3.1

**Comment by xuri** [comment]
Hi @yunduansing, thanks for your feedback, I have tested base v2.3.2 and it works well, could you provide a spreadsheet .xlsx attachment without confidential info?

**Comment by yunduansing** [comment]
Any column value exists 03 or 01  then SetCellStyle not work

**Comment by xuri** [comment]
Hi @yunduansing, note that `SetCellStyle` will overwrite the style for the cell with the style created by `NewStyle`, you haven't specified any `number_format` or `custom_number_format` when creating a new style.

**Comment by adamsh231** [comment]
> Hi @yunduansing, note that `SetCellStyle` will overwrite the style for the cell with the style created by `NewStyle`, you haven't specified any `number_format` or `custom_number_format` when creating a new style.

is there any function for appending style instead of overwriting like `SetCellStyle`
