### ISSUE TITLE
excelize.OpenFile function returns error is : decrypted file failed

### ISSUE THREAD

**Issue by wenzi1** [360EntSecGroup-Skylar/excelize#761]
**Description**
excelize.OpenFile function returns error

**Steps to reproduce the issue:**
1.excelize.OpenFile
2.
3.

**Describe the results you received:**
error message is : decrypted file failed
**Describe the results you expected:**
expect error is nil

**Output of `go version`:**
go1.15.1

```text
(paste your output here)
```

**Excelize version or commit ID:**
v2.3.1

```text
The file can be opened normally after copying the error content of Excel to the new excel
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
excel version is WPS 11.8.2.8555

**Comment by xuri** [comment]
Thanks for your feedback. Note that the excelize just support decrypt with ECMA-376 agile encryption and standard encryption. Support cryptographic algorithm: MD4, MD5, RIPEMD-160, SHA1, SHA256, SHA384, and SHA512 currently. Maybe the encryption algorithm used by the spreadsheet you opened hasn't been supported yet.

**Comment by Meschkov** [comment]
I have also the same error message when I try to open an excel file that was generated from one of our customers.

![image](https://user-images.githubusercontent.com/13832616/106275907-eedaba00-6236-11eb-9416-7856386a6a82.png)

Here is the https://easyupload.io/roil1s Excel sheet that cause the error.

Versions
```
go version go1.15.4 darwin/amd64
github.com/360EntSecGroup-Skylar/excelize/v2 v2.3.1
```

**Comment by xuri** [comment]
Note that this lib doesn't support the legacy XLS format files currently, reference issue: #44

**Comment by Meschkov** [comment]
> Note that this lib doesn't support the legacy XLS format files currently, reference issue: #44

Okay thanks, good to know.

**Comment by xuri** [comment]
There still no more details about this issue from the issue author. I close this issue and welcome left comments if you have any more questions.
