### ISSUE TITLE
The document is broken and needs to be restored when opened if it contains a pivot table with conditional formatting.

### ISSUE THREAD

**Issue by ceearrashee** [360EntSecGroup-Skylar/excelize#766]
**Description**
Hello!

I have pre-configured Excel document as a template. This template used for generating review results. I provide the user with the opportunity to download this template and customise at his discretion, with some restrictions:
1. Columns on the Answers page from A to X are not allowed to be swapped or deleted, but they can add his formulas starts from column Z.
2. The pivot table on the Result page should not be deleted. They can only increase the Pivot table range.

But some users also want to change the style and add conditional formatting. And as soon as conditional formatting is applied to the Pivot table, an error occurs. The document, when opened, shows a message that the pivot table has been restored.
But if it does not apply conditional formatting, then this error is not observed.

**Steps to reproduce the issue:**
1. Open this document and restore using MS Excel and save.
2. Add to its conditional formating using Excel.
3. Use your package to add any data to sheet answers and save the document.
4. Reopen document in MS Excel.

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10 20H2, Microsoft Excel™ 2019

**Attached document**
[Review.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5854490/Review.xlsx)

**Comment by xuri** [comment]
Hi @ceearrashee, thanks for your issue. I have fixed it, please upgrade to the master branch code, and this fix will be released in the next version.

**Comment by EugeneAndrosovBpmonline** [comment]
Thank you for the prompt solution of the issue!
