### ISSUE TITLE
how to list all valid relationships here

### ISSUE THREAD

**Issue by jstdoit** [360EntSecGroup-Skylar/excelize#767]
https://github.com/360EntSecGroup-Skylar/excelize/blob/e568319bbca22011690a54c5f5741da2b50d0c7c/xmlDrawing.go#L35

Hi, thanks for your amazing work for excel-handling, but I wanna know how to list all OOXML-strict relationships here?

Thanks.

**Comment by xuri** [comment]
Please reference [Open-XML-SDK](https://github.com/OfficeDev/Open-XML-SDK/blob/78cfa7d20d771a3d39b877208a6e9f7fb3fe3106/src/DocumentFormat.OpenXml/Framework/OpenXmlNamespace.cs).

**Comment by jstdoit** [comment]
> Please reference [Open-XML-SDK](https://github.com/OfficeDev/Open-XML-SDK/blob/78cfa7d20d771a3d39b877208a6e9f7fb3fe3106/src/DocumentFormat.OpenXml/Framework/OpenXmlNamespace.cs).

great! Thanks a lot!
