### ISSUE TITLE
package installation error

### ISSUE THREAD

**Issue by A1311981684** [360EntSecGroup-Skylar/excelize#768]
After I ran the command:
` go get  github.com/360EntSecGroup-Skylar/excelize/v2`
I get this error:
`go: finding module for package github.com/xuri/efp
go: finding module for package github.com/xuri/efp
../../../../pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.3.2/calc.go:29:2: module github.com/xuri/efp@latest found (v0.0.0-20201016154823-031c29024257), but does not contain package github.com/xuri/efp
`

I tried to delete the gomod pkg and redo this operation, error still reported like this.

**Comment by xuri** [comment]
Please try deleting the folder `$GOPATH/pkg/mod/cache` or `$GOPATH/pkg` to clean the go mod cache and reinstall again.

**Comment by A1311981684** [comment]
> Please try deleting the folder `$GOPATH/pkg/mod/cache` or `$GOPATH/pkg` to clean the go mod cache and reinstall again.

Thanks! Only delete the specific cach wont work, but delete them all will!
