### ISSUE TITLE
用 chrome 打开 excelize 生成的 excel 文件格子背景为黑色

### ISSUE THREAD

**Issue by eaglexiang** [360EntSecGroup-Skylar/excelize#769]
**Description**

**Steps to reproduce the issue:**
1. 通过 excelize 生成文件，只填充 string，不设置任何风格
2. 通过 MS Office 打开文件
3. 通过 Google Chrome 打开文件

**Describe the results you received:**

1. 通过 MS Office 打开文件，所有格子默认无背景色
2. 通过 Google Chrome 打开文件，所有填充过文字的格子背景色为黑色，未填充文字的格子无背景色

**Describe the results you expected:**

既然我在生成代码时未设置风格，那么 excel 文件不应该自带黑色背景。考虑到 MS Office 打开显示正常，不排除是格式兼容性问题。

**Output of `go version`:**

```text
go version go1.15.7 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.3.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

```text
Linux version 5.4.0-58-generic (buildd@lcy01-amd64-004) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020
```

**Comment by xuri** [comment]
Did you mean that open generated file with Google Sheets or some application extensions in the Google Chrome ? Could you provide a spreadsheet attachment without confidential info?

**Comment by eaglexiang** [comment]
> Did you mean that open generated file with Google Sheets or some application extensions in the Google Chrome ? Could you provide a spreadsheet attachment without confidential info?

是的，用 Google Sheets 打开会有默认的黑色背景

[Book1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5885317/Book1.xlsx)

![image](https://user-images.githubusercontent.com/12654323/106100684-b88a3580-6177-11eb-8b5c-5a66cbb9a7f1.png)

**Comment by eaglexiang** [comment]
这是我的浏览器环境：

Google Chrome:

```text
版本 88.0.4324.104（正式版本） （64 位）
```

Google文档、表格及幻灯片的Office编辑扩展程序:

```text
版本
135.360.369
```

**Comment by xuri** [comment]
I have tested Google Sheets open your attachment with the following browser in macOS 11.1, it works well and I think this issue doesn't belong to Excelize, maybe you should be feedback to Google Sheets.

```text
Google Chrome 88.0.4324.96 (x86_64)
Safari 14.0.2 (16610.3.7.1.9)
Microsoft Edge 87.0.664.75 (64-bit)
```

**Comment by eaglexiang** [comment]
但是我用 MS Office 手动生成或修改 xlsx 文件并在相同环境打开，显示是正常的。

![image](https://user-images.githubusercontent.com/12654323/106102201-0142ee00-617a-11eb-81ec-6190aef6088e.png)

**Comment by xuri** [comment]
It seems your attachment passed the ECMA-376, ISO/29500 Open Office XML spec compatibility checks, so it maybe compatibility issue of Google Sheets.

**Comment by xuri** [comment]
Hi @eaglexiang, this issue occurs in extension, but the online version's Google Sheets work well. I will be closing this issue.

**Comment by eaglexiang** [comment]
也许不同版本的 Google Sheets 确实对 xlsx 有不同的兼容性，但我仍然认为导致这个问题的主要原因是 excelize 生成了不标准的 xml。我试着进行修复并提了 PR
