### ISSUE TITLE
Remove a row

### ISSUE THREAD

**Issue by mchusovlianov** [360EntSecGroup-Skylar/excelize#77]
Hi, guys! Is there any way to remove row? I'm trying to use next way:
`cycleXLSX.Sheet["xl/worksheets/sheet1.xml"].SheetData.Row = append(cycleXLSX.Sheet["xl/worksheets/sheet1.xml"].SheetData.Row[:irow], cycleXLSX.Sheet["xl/worksheets/sheet1.xml"].SheetData.Row[irow+1:]...)`
But the meta-data should be recalculated.

**Comment by xuri** [comment]
Hi, Maksim. I have initialized insert/remove column/row support by adding new functions (related issue #82) `InsertCol()`, `InsertRow()`, `RemoveCol()` and `RemoveRow()`, please reference [godoc](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize). This is just an initialization of this feature, only support remove single row and just auto handle existing hyperlinks, merged cells and auto filters currently.

**Comment by vikraming** [comment]
func RemoveQuestionRowFromExcel(rowno string) error {
	excelFilePath := model.GetExcelFilePath()
	file, openFileError := excelize.OpenFile(excelFilePath)
	if openFileError != nil {
		logginghelper.LogError("writeQuestionDataToExcel()::openFileError", openFileError)
		return openFileError
	}
	rowCounter, _ := strconv.Atoi(rowno)
	logginghelper.LogDebug(file.GetSheetName(1))
	file.RemoveRow(file.GetSheetName(1), 2)
	logginghelper.LogDebug("row : ", rowCounter+1)
	file.RemoveRow(file.GetSheetName(1), rowCounter+1)
	return nil
}
===============================================================

This is the my function but i can't remove the row from excel file? what is the my  issue? please any one answer me
