### ISSUE TITLE
Will monitor can be the next feature? Like hook

### ISSUE THREAD

**Issue by sangianpatrick** [360EntSecGroup-Skylar/excelize#771]
Hi i got  an issue that when excelsizing there is no monitor to track how long the process. I use Elastic apm agent and got **the gap** in the tracer.

This is the tracer looks like
![image](https://user-images.githubusercontent.com/28580023/106193935-c031f480-61e0-11eb-83bd-398515b08f93.png)

**Comment by xuri** [comment]
Hi @sangianpatrick sorry, I didn't understand what you mean.

**Comment by sangianpatrick** [comment]
@xuri hmm yah i mean, is it possible to add feature to watch the process when excelizing the data, because it takes 50 -100 ms untill it is done (20 rows, 7 column)

maybe like monitor function in golang mongdb or hook in go redis
imagine you want to add a span of excelize in new relic, data dog or elastic apm

refers to the picture above, **fuel-direct-order.find** is a span in golang mongodb monitor and it was traced in a single request
and if excelize has monitor function, we can add span of excelize in **Excelize Gap**

**Comment by xuri** [comment]
I think maybe this feature is not in the scope of the library, you can inject tracing code in your API call, I close this issue and welcome left comments if you have any more questions.
