### ISSUE TITLE
can't the value of number type from excel

### ISSUE THREAD

**Issue by Talentpro** [360EntSecGroup-Skylar/excelize#773]
Hi,

    In the excel, when i change the type of the cell by using format cell as number, the excelize didn't get the value, it returns only 0.00

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using? Could you provide more details or a spreadsheet xlsx attachment without confidential info?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
