### ISSUE TITLE
The document is broken and needs to be restored when opened

### ISSUE THREAD

**Issue by ceearrashee** [360EntSecGroup-Skylar/excelize#774]
**Description**
Hello again!

Some times ago, I wrote about the pre-configured Excel document as a template. In this template added Tab General with difference pivots tables and diagrams. And I have the same bug as a previous. Thank you!

**Steps to reproduce the issue:**
1. Open this document and restore using MS Excel and save.
2. Use your package to add any data to sheet "Answers" and save the document.
4. Reopen document in MS Excel.

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10 20H2, Microsoft Excel™ 2019

**Attached document**
[survey-results.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5903407/survey-results.xlsx)

**Comment by xuri** [comment]
Thanks for your feedback, could you provide the original template xlsx file (before you open it by Excelize)?

**Comment by ceearrashee** [comment]
Thanks for the promptness, I attach the original template.

[Gallup Q12.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5903745/Gallup.Q12-modified2-clear.xlsx)

**Comment by ceearrashee** [comment]
Today my colleagues simply modified template.

It may also be useful.
[Template.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5903769/Template.xlsx)
[Genereated-result.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5903773/Genereated-result.xlsx)

**Comment by xuri** [comment]
I have added some data to the worksheet "Answers", save the document and it works well, maybe it's related to a data value, could you provide more detailed info or exactly minim step to reproduce this issue?

**Comment by ceearrashee** [comment]
Okay, I'm implementing a data generation gadget, but this will take some time.

**Comment by ceearrashee** [comment]
I've attached mini-app there data generation broke the document.

[exelize-bug.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/5904170/exelize-bug.zip)

**Comment by xuri** [comment]
I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
