### ISSUE TITLE
AutoFilter does not work on OpenOffice 

### ISSUE THREAD

**Issue by pandaadb** [360EntSecGroup-Skylar/excelize#776]
**Description**

Creating a simple autoFilter will not be displayed on OpenOffice, it is however displayed on Office365. 

**Steps to reproduce the issue:**

Code:

```
        f := excelize.NewFile()

	f.NewSheet("sheet_test")
	for i := 0; i < 5; i++ {
		idx, _ := excelize.CoordinatesToCellName(i+1, 1)
		f.SetCellValue("sheet_test", idx, fmt.Sprintf("Header %d", i))
	}

	row := 2

	for j := 0; j < 10; j++ {

		for i := 0; i < 5; i++ {
			idx, _ := excelize.CoordinatesToCellName(i+1, row)
			f.SetCellValue("sheet_test", idx, fmt.Sprintf("Value %d", i))
		}

		row++
	}

	f.DeleteSheet("Sheet1")
	f.SetActiveSheet(0)

	f.AutoFilter("sheet_test", "A1", "E11", "")

	filename := "/tmp/test5.xlsx"

	f.SaveAs(filename)
```

**Describe the results you received:**

Xlsx file opens, however no fitlers are displayed in OpenOffice. 
When uploading to Office365, filters are displayed. 

**Describe the results you expected:**

OpenOffice to be able to display the auto filter.

**Output of `go version`:**

```text
go version go1.13.10 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.3.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Ubuntu 18.04
LibreOffice (LibreOffice 6.0.7.3 00m0(Build:3)

**Comment by pandaadb** [comment]
Hi! 

I am not sure if this helps, but I found that `AddTable` adds the filters to OpenOffice: 

(it does not find the associated table style though I think) 
```
xslxFile.AddTable(input.Name, leftUp, buttomDown, `{
		"table_name": "table",
		"table_style": "TableStyleMedium2",
		"show_first_column": true,
		"show_last_column": true,
		"show_row_stripes": false,
		"show_column_stripes": true
	}`)
```

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
