### ISSUE TITLE
streamWriter conflicts with some func

### ISSUE THREAD

**Issue by 00LT00** [360EntSecGroup-Skylar/excelize#777]
this is my demo.
```go
func main() {
	xlsx := excelize.NewFile()
	err := xlsx.SetSheetRow("Sheet1", "A1", &[]interface{}{"学号", "姓名", "是否缴费"})
	if err != nil {
		fmt.Println(err.Error())
	}
	data, err := xlsx.GetRows("Sheet1")
	fmt.Println(data)
	streamWriter, err := xlsx.NewStreamWriter("Sheet1")
	cell, _ := excelize.CoordinatesToCellName(1, 2)
	if err := streamWriter.SetRow(cell, []interface{}{"1", "2", "3"}); err != nil {
		fmt.Println(err.Error())
	}
	if err := streamWriter.Flush(); err != nil {
		fmt.Println(err.Error())
	}
	if err := xlsx.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}

	data, err = xlsx.GetRows("Sheet1")
	fmt.Println(data)
}
```
the result is:
![image](https://user-images.githubusercontent.com/47566260/106499514-a7d11b00-64fb-11eb-9409-3639b1637098.png)

the file is :
![image](https://user-images.githubusercontent.com/47566260/106499644-cafbca80-64fb-11eb-8b1c-2364dc6add8f.png)

Why can't I get data by `GetRows` after I use the `streamWriter`, and the data will losed? But when I get empty data by `GetRows`, there is streamWriter's data in the file. And if I use `SetSheetRow` to add row after the file that has been saved with `streamWriter`, the excel file will be broken.

I want know if maybe the "bug" is a feature in fact because it looks like very obvious. I can't get any information in the docs.

**Comment by xuri** [comment]
Thanks for your issue. You can read cell value by `GetRows` which value is just written with common API (such as `SetSheetRow` and `SetCellValue`). The `SetSheetRow` is not a streaming API, it will not work in stream mode, in another word, we can not using common API and stream API mixed, also ref: #725

**Comment by 00LT00** [comment]
I also can't understand this result. Because in my understanding, when I call `Flush`, I have written the data to this file. Why is the data lost?

I set data by `SetSheetRow`. And then I create a streamWriter. I call the `Flush`. Then I can't get data by `GetRows`.
Do you mean is that we can't useing common Api and stream Api mixed for any file?

**Comment by xuri** [comment]
Yes, the data generated by streaming API storage way is different with common API, so it's seems like "missing", but it can be storage in spreadsheet if you save the file.

**Comment by 00LT00** [comment]
All right. But I suggest you should write some tips at [here](https://xuri.me/excelize/zh-hans/stream.html). And I think it's a bit counterintuitive. Maybe you can consider merging these two APIs.

**Comment by xuri** [comment]
Hi @00LT00, thanks for your suggestion. I have clarified for streaming API doesn't work with common API in the documentation.
