### ISSUE TITLE
use go routine  write to cell get an error

### ISSUE THREAD

**Issue by zhanshenzonghengtianxia** [360EntSecGroup-Skylar/excelize#778]
when i use "f *excelize.File" as a function param, and use "f.SetCellValue" write data to different Columns with go routine at same time  , in some Columns some cell is null, but the Interpreter do not report an error

        rows:=[]string{"A","B","C","D","E"}
	for i:=0;i<5;i++{
		for j:=1;j<100;j++{
			go func(){
				f.SetCellValue("Sheet1",rows[i]+strconv.Itoa(j),j)
			}()
		}
	}
	err = f.Save()
	if err != nil {
		fmt.Println(err)
	}

**Comment by xuri** [comment]
Thanks for your feedback. I have tested with v2.3.2 and it works well, which version of Excelize are you using? Could you create the issue by an issue template and provide more details?

**Comment by zhanshenzonghengtianxia** [comment]
> Thanks for your feedback. I have tested with v2.3.2 and it works well, which version of Excelize are you using? Could you create the issue by an issue template and provide more details?

i will try the v2.3.2,thinks for your help

**Comment by zhanshenzonghengtianxia** [comment]
> > Thanks for your feedback. I have tested with v2.3.2 and it works well, which version of Excelize are you using? Could you create the issue by an issue template and provide more details?
> 
> i will try the v2.3.2,thinks for your help

i use the v2.3.2 , still get the error when i written and open the excel(end with .xlsx)
![image](https://user-images.githubusercontent.com/44859773/106836919-fb4a9100-66d4-11eb-9fa7-0b768a5a317d.png)

**Comment by zhanshenzonghengtianxia** [comment]
i use the v2.3.2 , still get the error when i written and open the excel(end with .xlsx)
![image](https://user-images.githubusercontent.com/44859773/106836991-2634e500-66d5-11eb-81ed-524f6a56e152.png)

**Comment by zhanshenzonghengtianxia** [comment]
this is my code which get the error 


page:=make(chan string,runtime.NumCPU())
rows:=[]string{"A","B","C","D","E","F"}	
for i:=0;i<5;i++{
		
		go func(){
		
		for j:=0;j<100;j++{
			//fmt.Println(rows[i] + strconv.Itoa(j))
			f.SetCellValue("Sheet1", rows[i]+strconv.Itoa(j), j)
		}
		err := f.Save()
		if err != nil {
			fmt.Println(err)
		}
		page<-rows[i] // use for 
		}()

	}
for i:=0;i<5;i++ {
		fmt.Println(<-page)

	}

**Comment by zhanshenzonghengtianxia** [comment]
The error may be caused by my other codes ,this result is got from many tests

**Comment by zhanshenzonghengtianxia** [comment]
you can try this code with&nbsp; version V2.3.2, when the running&nbsp; finish ,the result in excel file is error,like the behind:



the code is :
func loprint(row string,f *excelize.File,page chan string,frames int){

   for j:=1;j<frames;j++{
      fmt.Println(row + strconv.Itoa(j))
      f.SetCellValue("Sheet1", row+strconv.Itoa(j), j)
   }
   err := f.Save()
   if err != nil {
      fmt.Println(err)
   }
   page<-row
}page:=make(chan string,runtime.NumCPU())
rows:=[]string{"A","B","C","D","E"}frames:=[]int{2877,1938,2963,3194,3354}  // this code will get an error//frames:=[]int{1938,2877,2963,3194,3354} // this code will not get an errorfor i:=0;i<5;i++{

   go loprint(rows[i],f,page,frames[i])

}

for i:=0;i<5;i++ {
   fmt.Println(<-page)

}
As we can see ,when the "frames" is sort by&nbsp;Ascending ，it will be find, but if the "frames" is chaos,it will get an error.


Thinks for your reading
Waiting for your&nbsp;reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "360EntSecGroup-Skylar/excelize"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 晚上6:58
收件人:&nbsp;"360EntSecGroup-Skylar/excelize"<excelize@noreply.github.com&gt;;
抄送:&nbsp;"王杰"<2896090535@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [360EntSecGroup-Skylar/excelize] use go routine  write to cell get an error (#778)





 
Thanks for your feedback. I have tested with v2.3.2 and it works well, which version of Excelize are you using? Could you create the issue by an issue template and provide more details?
