### ISSUE TITLE
go rountine write to cell use "SetCellValue" get an error

### ISSUE THREAD

**Issue by zhanshenzonghengtianxia** [360EntSecGroup-Skylar/excelize#779]
try this code with  version V2.3.2, when the running  finish ,the result in excel file is error.
the code is :

func loprint(row string,f *excelize.File,page chan string,frames int){

   for j:=1;j<frames;j++{
      fmt.Println(row + strconv.Itoa(j))
      f.SetCellValue("Sheet1", row+strconv.Itoa(j), j)
   }
   err := f.Save()
   if err != nil {
      fmt.Println(err)
   }
   page<-row
}
page:=make(chan string,runtime.NumCPU())
rows:=[]string{"A","B","C","D","E"}
frames:=[]int{2877,1938,2963,3194,3354}  // this code will get an error
//frames:=[]int{1938,2877,2963,3194,3354} // this code will not get an error
for i:=0;i<5;i++{

   go loprint(rows[i],f,page,frames[i])

}

for i:=0;i<5;i++ {
   fmt.Println(<-page)

}

when the "frames" is sort by Ascending ，it will be fine, but if the "frames" is chaos,it will get an error.

**Comment by zhanshenzonghengtianxia** [comment]
If the gorountine do not write in the order of the columns（A---->E....）, an error will be reported while open the result  excel

**Comment by zhanshenzonghengtianxia** [comment]
Could anyone give me a solution

**Comment by xuri** [comment]
Could you provide minimum runnable code to reproduce this issue?

**Comment by xuri** [comment]
This issue is duplicate with #778. Please don't create duplicate issues.

**Comment by zhanshenzonghengtianxia** [comment]
> Could you provide minimum runnable code to reproduce this issue?

func main() {
	
	runtime.GOMAXPROCS(runtime.NumCPU())
	
	excel_path:="my.xlsx"

	f,err:=excelize.OpenFile(excel_path)

	if err !=nil{
		fmt.Println("get an open err: ",err)
		return
	}


	rows:=[]string{"A","B","C","D","E","F"}
	
	page:=make(chan string,runtime.NumCPU())
	
	nums:=[]int{2963,2877,1938,3194,3354}


	for i:=0;i<5;i++{
		
		row:=rows[i]
		num:=nums[i]
		
		go func(){
			for j:=1;j<num;j++{
				fmt.Println(row + strconv.Itoa(j))
				f.SetCellValue("Sheet1", row+strconv.Itoa(j), j)
			}
			err := f.Save()
			if err != nil {
				fmt.Println(err)
			}
			page<-row
		}()
		}
		

	for i:=0;i<5;i++ {
		fmt.Println(<-page)

	}

}

**Comment by zhanshenzonghengtianxia** [comment]
> This issue is duplicate with #778. Please don't create duplicate issues.

issues#778 has been closed

**Comment by zhanshenzonghengtianxia** [comment]
func main() {

   runtime.GOMAXPROCS(runtime.NumCPU())

   excel_path:="my.xlsx"

   f,err:=excelize.OpenFile(excel_path)

   if err !=nil{
      fmt.Println("get an open err: ",err)
      return
   }


   rows:=[]string{"A","B","C","D","E","F"}

   page:=make(chan string,runtime.NumCPU())

   nums:=[]int{2963,2877,1938,3194,3354}


   for i:=0;i<5;i++{

      row:=rows[i]
      num:=nums[i]

      go func(){
         for j:=1;j<num;j++{
            fmt.Println(row + strconv.Itoa(j))
            f.SetCellValue("Sheet1", row+strconv.Itoa(j), j)
         }
         err := f.Save()
         if err != nil {
            fmt.Println(err)
         }
         page<-row
      }()
      }


   for i:=0;i<5;i++ {
      fmt.Println(<-page)

   }

}


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "360EntSecGroup-Skylar/excelize"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月8日(星期一) 下午2:38
收件人:&nbsp;"360EntSecGroup-Skylar/excelize"<excelize@noreply.github.com&gt;;
抄送:&nbsp;"王杰"<2896090535@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [360EntSecGroup-Skylar/excelize] go rountine write to cell use "SetCellValue" get an error (#779)





 
Could you provide minimum runnable code to reproduce this issue?

**Comment by zhanshenzonghengtianxia** [comment]
func main() {

   runtime.GOMAXPROCS(runtime.NumCPU())

   excel_path:="my.xlsx"

   f,err:=excelize.OpenFile(excel_path)

   if err !=nil{
      fmt.Println("get an open err: ",err)
      return
   }


   rows:=[]string{"A","B","C","D","E","F"}

   page:=make(chan string,runtime.NumCPU())

   nums:=[]int{2963,2877,1938,3194,3354}


   for i:=0;i<5;i++{

      row:=rows[i]
      num:=nums[i]

      go func(){
         for j:=1;j<num;j++{
            fmt.Println(row + strconv.Itoa(j))
            f.SetCellValue("Sheet1", row+strconv.Itoa(j), j)
         }
         err := f.Save()
         if err != nil {
            fmt.Println(err)
         }
         page<-row
      }()
      }


   for i:=0;i<5;i++ {
      fmt.Println(<-page)

   }

}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "360EntSecGroup-Skylar/excelize"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月8日(星期一) 下午2:38
收件人:&nbsp;"360EntSecGroup-Skylar/excelize"<excelize@noreply.github.com&gt;;
抄送:&nbsp;"王杰"<2896090535@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [360EntSecGroup-Skylar/excelize] go rountine write to cell use "SetCellValue" get an error (#779)





 
Could you provide minimum runnable code to reproduce this issue?

**Comment by xuri** [comment]
Note that `Save` is not a concurrency safety API, save file after all data has been set.

**Comment by xuri** [comment]
Hi @zhanshenzonghengtianxia, I closed this issue, if you have any questions, please let me know.
