### ISSUE TITLE
How to recognize the merged cells?

### ISSUE THREAD

**Issue by snailQH** [360EntSecGroup-Skylar/excelize#78]
I scanned the doc reference. I could not find the func for reading a merged cell. Even the GetRows can give the content of the xlsx file,  only the first cell(original cell) of the big merged cell (both merged row and column) can  get the content in the merged cell.
Is there any methods can I distinguish the merged cell and the blank cell in black box?

**Comment by Luxurioust** [comment]
@snailQH Thanks for your issue. I have fixed this bug. You can get value of a merged cell by function `GetCellValue()`.

**Comment by snailQH** [comment]
@Luxurioust  Thanks for your prompt response. It works now.

**Comment by shawnye** [comment]
@xuri How to get merged cell info, as `github.com/tealeg/xlsx` does:  
`cell := GetCellInfo()`,  cell contains `HMerge` and `VMerge` and other info.

I want to merge cells in column B,C,D,etc, according to column A (grouped marking by merging cells).

Thanks!
