### ISSUE TITLE
When call method DeleteSheet to delete Sheet1, It can't work

### ISSUE THREAD

**Issue by duke-git** [360EntSecGroup-Skylar/excelize#780]
my code:
file := excelize.NewFile()
file.DeleteSheet("Sheet1")
 It can't work(after delete Sheet1, it is still in the file). Anyone can tell me what's wrong with the code? thanks

**Comment by xuri** [comment]
As the docs of the `DeleteSheet` noticed, it will be invalid when only one worksheet is left. If you needn't the default worksheet named `Sheet1`, you can rename it by `SetSheetName` before coming up with operations. Also, reference #775

**Comment by duke-git** [comment]
Thanks
