### ISSUE TITLE
the fitToHeight, fitToWidth bug

### ISSUE THREAD

**Issue by greymanking** [360EntSecGroup-Skylar/excelize#781]
当xlsx文件的页面布局为“宽度1页，高度自动“时，生成的sheet1.xml中，有<pageSetup fitToHeight="0">，但使用你们的包，设置fitToHeight(0)不起作用，在生成的文件中直接被忽略了，导致在fitToPage=“1”的前提下，页面布局的宽度和高度都是1页。

**Comment by xuri** [comment]
Thanks for your feedback, which version of Excelize are you using? Could you create the issue by an issue template and provide more details?
