### ISSUE TITLE
Unmerge all cells cause corrupted file

### ISSUE THREAD

**Issue by blueicesir** [360EntSecGroup-Skylar/excelize#782]
使用版本
github.com/360EntSecGroup-Skylar/excelize/v2 v2.3.2

Go 1.15 编译环境 windows 64bit

```
package main

import (
	"fmt"
	"strings"
	"github.com/360EntSecGroup-Skylar/excelize/v2"
)


func main(){
	f,err:=excelize.OpenFile(`org.xlsx`)
	if err!=nil {
		fmt.Println(err)
		return
	}
	for i,sheet_name:= range f.GetSheetMap() {
		fmt.Println(i,sheet_name)
		merge_cells,err:=f.GetMergeCells(sheet_name)
		if err!=nil {
			fmt.Println(err)
			return
		}

		for i:=range merge_cells {
			axis_x:=strings.Split(merge_cells[i][0],":")[0]
			axis_y:=strings.Split(merge_cells[i][0],":")[1]
			fmt.Printf("index=%d\tref=%s\tval=%s\t\tUnmergeCell(\"%s\",\"%s\",\"%s\")\t",i,merge_cells[i][0],merge_cells[i][1],sheet_name,axis_x,axis_y)
			err=f.UnmergeCell(sheet_name,axis_x,axis_y)
			if err!=nil {
				fmt.Printf("UnmergeCell fail,%v\n",err)
				return
			}else{
				fmt.Printf("OK\n")
			}
		}
	}

	err=f.SaveAs("test.xlsx")
	if err!=nil{
		fmt.Printf("SaveAs fail,%v\n",err)
		return
	}
}
```

待拆分合并单元格的xlsx文件。
![image](https://user-images.githubusercontent.com/1249214/107329623-5d4b3200-6aeb-11eb-84f6-07ec13e0ba73.png)

[org.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5949576/org.xlsx)

输出的test.xlsx文件用Excel 2013打开提示 “发现test.xlsx中的部分内容有问题”，经过测试如果保留一个合并的单元格不进行拆分，打开的文件正常。

烦请有空核查处理。

**Comment by xuri** [comment]
Thanks for your feedback, could you provide more details or a spreadsheet xlsx attachment (`org.xlsx`) without confidential info?

**Comment by blueicesir** [comment]
> Thanks for your feedback, could you provide more details or a spreadsheet xlsx attachment (`org.xlsx`) without confidential info?

已经更新到问题单内容中，可以下载 org.xlsx 并使用代码测试。

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.

**Comment by blueicesir** [comment]
Test is pass,thank you.happy Chinese New Year in 2021.
