### ISSUE TITLE
Set fill color for cell

### ISSUE THREAD

**Issue by vnpenguin** [360EntSecGroup-Skylar/excelize#784]
Hi,
I'm trying to set the fill color for a cell, by using:

style, _ := f.NewStyle(`{"fill":{"color": "#CECECE"}}`)
f.SetCellStyle(sheetName, "A1", "A2", style) 

But it does not work.
Anyone could tell me how to set the background fill color for a cell please?
Thank you

**Comment by xuri** [comment]
Hi @vnpenguin, don't forget to specify the fill pattern params, also reference docs for the [SetCellStyle](https://xuri.me/excelize/en/cell.html#SetCellStyle):

```json
{"fill":{"type":"pattern","color":["#CECECE"],"pattern":1}}
```

**Comment by vnpenguin** [comment]
Thank you so much!
