### ISSUE TITLE
How do you change the color of worksheet tab? 

### ISSUE THREAD

**Issue by choiway** [360EntSecGroup-Skylar/excelize#785]

**Comment by xuri** [comment]
Thanks for your issue, I will add set tab color support tomorrow.

**Comment by xuri** [comment]
Hi @choiway, I have added change tab color support, please upgrade and use the master branch code, this feature will be released in the next version, and thanks for your donation, I have added you to the donated user page.

For example, set `Sheet1` tab color to yellow RGB color: `#FFFF00`

```go
if err := f.SetSheetPrOptions("Sheet1",
    excelize.TabColor("FFFF00"),
); err != nil {
    fmt.Println(err)
}
var tabColor excelize.TabColor
if err := f.GetSheetPrOptions("Sheet1",
    &tabColor,
); err != nil {
    fmt.Println(err)
}
```

**Comment by choiway** [comment]
Works great! Thanks.
