### ISSUE TITLE
Why the 'formatChart' is a close class

### ISSUE THREAD

**Issue by LooJee** [360EntSecGroup-Skylar/excelize#796]
Hello!
I am a beginner to use this lib, and I have a question.
Why the **formatChart** is a close class?
Why not passing a class to the function **AddChart**?

**Comment by xuri** [comment]
Yep, I'll export the `formatChart` as `Chart` structure until the field stable like `Style`.

**Comment by LooJee** [comment]
@xuri thanks for reply! this lib is great.
