### ISSUE TITLE
How do I set date format dd/mm/yyyy ?

### ISSUE THREAD

**Issue by nooknoname** [360EntSecGroup-Skylar/excelize#797]
I want to set date format dd/mm/yyyy (English (United Kingdom)), help me please.

![05-03-2021 16-48-52](https://user-images.githubusercontent.com/11159926/110098735-17744780-7dd3-11eb-9dcd-71ebd064614c.jpg)

**Comment by xuri** [comment]
You can set custom number format like this, also reference [document](https://xuri.me/excelize/en/style.html): 

```go
exp := "dd/mm/yyyy;@"
style, err := f.NewStyle(&excelize.Style{CustomNumFmt: &exp})
err = f.SetCellStyle("Sheet1", "B18", "B18", style)
```

**Comment by nooknoname** [comment]
> You can set custom number format like this, also reference [document](https://xuri.me/excelize/en/style.html):
> 
> ```go
> exp := "dd/mm/yyyy;@"
> style, err := f.NewStyle(&excelize.Style{CustomNumFmt: &exp})
> err = f.SetCellStyle("Sheet1", "B18", "B18", style)
> ```

Thank you
