### ISSUE TITLE
Currency Format?

### ISSUE THREAD

**Issue by jaybeecave** [360EntSecGroup-Skylar/excelize#80]
Cant figure out how to do currency format..

Does anyone know which number_format I can use in SetStyle?

<img src='https://image.prntscr.com/image/6_uG98v-Q-_JwKfbDtxL-w.png' />

**Comment by xuri** [comment]
Thanks for your issue. I have added set currency format support and  I'll improve support for other languages later. For example, you can set cell `Sheet1!B4` in `$ English (United States)` currency format by `number_format` index `177`:
```
style, _ := xlsx.NewStyle(`{"number_format": 177}`)
xlsx.SetCellStyle("Sheet1", "B4", "B4", style)
```
