### ISSUE TITLE
Working with files saved at OneDrive

### ISSUE THREAD

**Issue by hajsf** [360EntSecGroup-Skylar/excelize#807]
Hi, is there a way to access a file saved at MS OneDrive, for reading and update through this package?
Thanks

**Comment by xuri** [comment]
You can access the file via [OneDrive file storage API](https://docs.microsoft.com/en-us/graph/onedrive-concept-overview), and process the spreadsheet by this library integration in your program.

**Comment by rashi-j** [comment]
Hey @xuri wanted to confirm. By using one-drive API, you're suggesting we download the file, make changes and then upload it?

**Comment by xuri** [comment]
Yes, please use the [`Write`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.Write) function to write the workbook to a custom-defined `io.Writer`, then the file payload as form data without touching the filesystem when using the HTTP client.
