### ISSUE TITLE
SaveAs(), unprotects all protected/locked cells

### ISSUE THREAD

**Issue by JDavidVR** [360EntSecGroup-Skylar/excelize#809]
**Description**

If I create a new workbook, and set C3 and C4 cells as Hidden and Protected/Locked, when I save it as a new file using excelize 2.3.2, it removes the formula protection.

![image](https://user-images.githubusercontent.com/4760084/112238891-e6da3d80-8c1b-11eb-84d4-e5e4fd8fbddc.png)

Test Excel: [NewBook.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/6193664/NewBook.xlsx)

**Steps to reproduce the issue:**
```
func copy() {
	f, err := excelize.OpenFile("NewBook.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}

	if err := f.SaveAs("goNewBook.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```

**Describe the results you received:**
C4 and C5 should remain Hidden BUT NOT Locked:
![image](https://user-images.githubusercontent.com/4760084/112239416-cced2a80-8c1c-11eb-848b-98266c6a71f3.png)

**Describe the results you expected:**
C4 and C5 should remain Hidden and Locked:
![image](https://user-images.githubusercontent.com/4760084/112239193-6a942a00-8c1c-11eb-8803-2e9705bdcb95.png)

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Mac OS Big Sur 11.2.2
go version go1.16.2 darwin/amd64

I did some investagion, and looks like issue occurs in xl/styles.xml

Excel 2010's  xl/styles.xml:

```
<cellXfs count="2">
        <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
        <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyProtection="1">
            <protection hidden="1"/>
        </xf>
    </cellXfs>
```

Excelize 2.3.2's xl/styles.xml:

```
<cellXfs count="2">
        <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"></xf>
        <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyProtection="true">
            <protection hidden="true" locked="false"></protection>
        </xf>
    </cellXfs>
```

Excelize by default is adding locked="false" and MS Excel is not adding it.

Reviewing code https://github.com/360EntSecGroup-Skylar/excelize/blob/ab2c1c8fe1ef787c1f692bcf26c7bbe0cca2c5b3/xmlStyles.go#L53

looks like struct have a bool value, and like it is not especofied, go will set `false` by default

```
type xlsxProtection struct {
	Hidden bool `xml:"hidden,attr"`
	Locked bool `xml:"locked,attr"`
}
```

I would like to help solving this issue, but I new in go and also I've started reviewing excelize code, so if you metnion which files needs to be modified and how to debug I can help resolving this issue.

Thanks in advance

**Comment by xuri** [comment]
Thanks for your issue, I propose to change the struct `Protection` like this:

```go
type xlsxProtection struct {
    Hidden *bool `xml:"hidden,attr"`
    Locked *bool `xml:"locked,attr"`
}
```

**Comment by JDavidVR** [comment]
Hi @xuri 

I've applied the change you've suggested:
![image](https://user-images.githubusercontent.com/4760084/112342428-97862280-8c98-11eb-905a-13aaec16c9e3.png)

But IDE is displaying this alert:
![image](https://user-images.githubusercontent.com/4760084/112342506-a66cd500-8c98-11eb-8ed4-2155743333bb.png)

In terminal I'm getting this same message too:

/Users/david/go/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.3.2/styles.go:2475:21: cannot use style.Protection.Hidden (type bool) as type *bool in assignment
/Users/david/go/pkg/mod/github.com/360!ent!sec!group-!skylar/excelize/v2@v2.3.2/styles.go:2476:21: cannot use style.Protection.Locked (type bool) as type *bool in assignment

**Comment by xuri** [comment]
I have fixed it, please try to use the master branch code, and this patch will be released in the next version.

**Comment by JDavidVR** [comment]
Hi @xuri  thanks I can confirm, this is working well!

**Comment by arthurwailer** [comment]
i have the same problem, how resolved ? 

\github.com\xuri\excelize\v2@v2.8.0\styles.go:1297:30: cannot use *xf.Protection.Hidden (variable of type bool) as *bool value in assignment
