### ISSUE TITLE
after saving, file looks different

### ISSUE THREAD

**Issue by plandem** [360EntSecGroup-Skylar/excelize#81]
1. open xlsx (quite complex formatting - styles and etc)
2. copy from Col A into Col B
3. set Col A equal 0
4. save as a new file - files looks different :(

some cells at each row can be merged, BUT Col A, and Col B are simple - only style formatting.

More overs, some rows(quite a lot) that I'm not updating - after saving looks different.

Let's recap - I only update some simple cells at some rows. Why rows that I'm not touching looks different?! :(

**Comment by xuri** [comment]
Hi Andrey, please provide file attachments If you can.

**Comment by plandem** [comment]
hi. I will try to remove critical data and prepare file for you.
Btw...what edition your library is based on?!

http://www.ecma-international.org/publications/standards/Ecma-376.htm

**Comment by xuri** [comment]
The lib is based on the ECMA-376 5th edition.

**Comment by plandem** [comment]
ok, here are files **before** updating
https://www.dropbox.com/s/h5doil7usuw3zhs/before.xlsx?dl=0

 and **after** updating
https://www.dropbox.com/s/0yo3mwk1mcpgic8/after.xlsx?dl=0

What steps to reproduce:
1) open **before** 
2) at sheet **3.1** set 2 values - row 10
3) at sheet **3.2** set 2 values - row 37
4) save as a new file

Open a new file and you will see that at sheet **3.2** we have broken formatting.

I can't provide any data, but  right now looks like only formatting on this page breaks. **3.1** looks fine.

**Comment by plandem** [comment]
@xuri Probably it's a good idea to write at Readme about ECMA-376 5th edition

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it by adding missing element `showWhiteSpace` in the worksheet. Please upgrade lib to the last version.

**Comment by plandem** [comment]
Well, it's much better now, but still looks different.

before (3.8Mb file):
https://www.dropbox.com/s/23s3i0rpss6ahyp/Screenshot%202017-07-15%2019.56.27.png?dl=0

after(3.3Mb file):
https://www.dropbox.com/s/rmp951a4xodzgfi/Screenshot%202017-07-15%2019.56.51.png?dl=0

have no ideas why :( And file is still lesser by 500kb after saving :( 500Kb somewhere gone.

**Comment by plandem** [comment]
If it's important, look for G14 at 3.2 sheet. I'm talking about these cells - lost their formatting after saving:
https://www.dropbox.com/s/4zwe4hwuxinwvav/Screenshot%202017-07-15%2023.35.41.png?dl=0

**Comment by xuri** [comment]
The cells that look different (no border style) are generated by the internal function `completeCol()`, it will preprocess to complete fill all the cells maybe used before set cell value, and these cell doesn't inherit the style of the surrounding cells, so it causing a display difference. I have fixed it by trim blank cells before save the file. I think the file size changes are caused by the compression algorithm, the content hasn't been affected.

**Comment by plandem** [comment]
@xuri do you mean that somewhere ** completeCol** do something with cell that I didn't touch?!

**Comment by xuri** [comment]
Yes, the function `completeCol()` will auto complete in prepare range to fill cells.

**Comment by plandem** [comment]
I checked generated file - visually looks same! Huh....thanks man, I started to afraid that I did a bad choice to choose Go without testing saving ability of xls libs.

I will get feedback from end-user next week probably, maybe I miss something. Hope everything is fine now :)

**Comment by plandem** [comment]
I got another problem. After adding a new Sheet at that file I'm getting "Corrupted file" and sometimes Excel can't repair it.

**Comment by xuri** [comment]
Could you provide file attachments and more details?

**Comment by plandem** [comment]
I need to "prepare data". But at least one issue is:
steps:
1) file was saved at osx Excel(2016 year)
2) opened that file at osx Excel(2011) and he asks to fix corrupted file, after successful fix save it
3) open at osx Excel(2016) - he asks to fix corrupted file.

Looks like there is something that break file :( Probably original issue was because of that.

**Comment by plandem** [comment]
Ok, looks like it has nothing with starter issue, so i'm closing it and will create a new one if required.
