### ISSUE TITLE
v2 use SetSheetRow is not write int xlsx,v1 is ok 

### ISSUE THREAD

**Issue by xiyichan** [360EntSecGroup-Skylar/excelize#811]
**Description**
```code
	f := excelize.NewFile()
	// 创建一个工作表
	index := f.NewSheet("Sheet2")
	// 设置单元格的值
	f.SetCellValue("Sheet2", "A2", "Hello world.")
	f.SetCellValue("Sheet1", "B2", 100)
	f.SetSheetRow("sheet1","b3",&[]interface{}{"1","2","3"})
	// 设置工作簿的默认工作表
	f.SetActiveSheet(index)
	// 根据指定路径保存文件
	if err := f.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}
```

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/34647972/112575928-3bec9e00-8e2c-11eb-9177-9c461b18f2ad.png)

**Describe the results you expected:**

**Output of `go version`:**

```text
1.14
```

**Excelize version or commit ID:**

```text
2.3.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
windows10 and centos

**Comment by xuri** [comment]
Please receive and handle error returned by `SetSheeRow`, note that the sheet name is case sensitive, the default worksheet name after creating the spreadsheet by `NewFile` is `Sheet1` not `sheet1`.
