### ISSUE TITLE
xlsx corrupted while using StreamWriter

### ISSUE THREAD

**Issue by Vancool** [360EntSecGroup-Skylar/excelize#812]
Hi, I am trying to use streamWriter writer big data(about 100w+ data with 50-60fields) into xlsx file.
But I always got xlsx corrupted alarm after the  running, even the number of data is only two.
I found if I cannot flush() for multiple times unless opening  new streamWriter  or file will say it corrupts.
Then I  open a new streamWriter after one time flush, but it still cannot work because I got an empty xlsx file.
It is mean I just can flush() the data only one time? But how can I store data in an appending way because I don't want to flush so large size data at once.
Because I didn't get any error during these process,  I wonder if I use streamWriter in a wrong way? 

**Steps to reproduce the issue:**

my code:

type XLSXWriter struct {
	f              *excelize.File
	w              *excelize.StreamWriter
	header         []string      `desc:"表格表头信息"`
	mutex          *sync.Mutex   `desc:"并行锁"`
	tableName      string        `desc:"table name"`
}

func NewXLSXWriter(filename string, schema string) (*XLSXWriter, error) {
	errorWrap := "Init excel file error:"
	f := excelize.NewFile()
	if err := f.SaveAs(filename); err != nil {
		return nil, errors.Wrap(err, errorWrap)
	}
	f, err := excelize.OpenFile(filename)
	if err != nil {
		return nil, errors.Wrap(err, errorWrap)
	}
	w, err := f.NewStreamWriter("Sheet1")
	if err != nil {
		return nil, errors.Wrap(err, errorWrap)
	}
	header := []string{"uid"," tag","follower"}
	cell, _ := excelize.CoordinatesToCellName(1, 1)
	headerInterface := make([]interface{}, len(header))
	for i, h := range header {
		headerInterface[i] = h
	}
	err = w.SetRow(cell, headerInterface)
	if err != nil {
		return nil, errors.Wrap(err, errorWrap)
	}
	
	return &XLSXWriter{
		f:              f,
		w:              w,
		header:         header,
		mutex:          &sync.Mutex{},
		tableName:      "Sheet1",
	}, nil

}

func (c *XLSXWriter) Write(ctx context.Context, data *string) {
	if data == nil {
		return
	}
	row := *data
	if err != nil {
		logs.CtxError(ctx, "Write data error %v", err)
		return
	}
	c.mutex.Lock()
	defer c.mutex.Unlock()
	f := func() error {
		cell, curErr := excelize.CoordinatesToCellName(1, 2)
		fmt.Println(cell)
		if curErr != nil {
			return curErr
		}
		curErr = c.w.SetRow(cell, row)
		if curErr != nil {
			return curErr
		}
		return nil
	}
	err = f()
	//err = BinaryRetry(f, constant.DefaultRetryTimes)
	if err != nil {
		logs.CtxError(ctx, "Write excel data error %v", err)
	} 

}

func TestXLSXWriter(t *testing.T) {
	xlsx, err := NewXLSXWriter("321.xlsx", rowSchema)
	if err != nil {
		t.Errorf(err.Error())
		t.FailNow()
	}
	ctx := context.Background()
	xlsx.Write(ctx, &rowData)
	xlsx.Stop(ctx)
}

var rowSchema = `
{
    "type": "object", 
    "properties": {
        "uid": {
            "type": "string", 
        }, 
        "tag": {
            "type": "int", 
        }, 
        "pid": {
            "type": "string", 
        }
    }
}
`
var rowData = "{\"uid\":\"diUVMwZsEf\",\"tag\":1,\"pid\":\"UqKqWdyOVj\"}"

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
go version go1.15.6 darwin/amd64

**Comment by xuri** [comment]
In streaming writing mode, just call `Flush` one time after data write finished for each worksheet, also reference #753, if still not work, please provides simple runnable code to reproduce this issue.

**Comment by xuri** [comment]
There still no more details about this issue from the issue author. I close this issue and welcome left comments if you have any more questions.
