### ISSUE TITLE
RemoveCol() And Document Mismatch

### ISSUE THREAD

**Issue by AngangGuo** [360EntSecGroup-Skylar/excelize#814]
From https://xuri.me/excelize/en/sheet.html#RemoveCol:
```
func (f *File) RemoveCol(sheet, col string) error
```

But in col.go the `RemoveCol` function doesn't return error:
```
func (f *File) RemoveCol(sheet, column string) {
```

**Comment by xuri** [comment]
The document is the latest version of the API, and the [`RemoveCol`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2@v2.3.2#File.RemoveCol) function will return an error since [version 2.0.0](https://github.com/xuri/excelize/releases/tag/v2.0.0).

**Comment by AngangGuo** [comment]
Maybe move this line at the top of installation instruction:
go get github.com/360EntSecGroup-Skylar/excelize/v2
