### ISSUE TITLE
result of GetCols After StreamWrite is empty

### ISSUE THREAD

**Issue by eaglexiang** [360EntSecGroup-Skylar/excelize#819]
**Description**

**Steps to reproduce the issue:**

1. create and wirte a file by method `NewStreamWriter`
2. get cols by calling method `GetCols` on file created at step 1
3. show the cols got

sample:

```go
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {
	ef := excelize.NewFile()

	sheetName := "Sheet1"
	sw, err := ef.NewStreamWriter(sheetName)
	if err != nil {
		panic(err)
	}

	err = sw.SetRow("A1", []interface{}{0, 1, 2, 3})
	if err != nil {
		panic(err)
	}
	err = sw.SetRow("A2", []interface{}{4, 5, 6, 7})
	if err != nil {
		panic(err)
	}
	err = sw.Flush()
	if err != nil {
		panic(err)
	}

	cols, err := ef.GetCols(sheetName)
	if err != nil {
		panic(err)
	}

	fmt.Println(cols)

	ef.SaveAs("test.xlsx")
}

```

**Describe the results you received:**

xlsx file exported is correct, slice got is empty.

**Describe the results you expected:**

slice with the data witten.

**Output of `go version`:**

```text
go version go1.16.2 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.3.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

5.9.16-1-MANJARO

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version. Note that upgrade requirements Go language version is 1.15 or later.
