### ISSUE TITLE
How to insert a row before or after the specified row?

### ISSUE THREAD

**Issue by shawnye** [360EntSecGroup-Skylar/excelize#82]
It seems that neither `InsertRowAfter(rn int)`  nor `InsertRowBefore(rn int)` function is supported.
and neither  `InsertColumnAfter(cn int)`  nor `InsertColumnBefore(cn int)` function is supported.

It's useful when combining a template with dynamic data [varied rows or columns].
 
Any suggestion? Thank you!

**Comment by xuri** [comment]
Thanks for your issue. I have initialized insert/remove column/row support by adding new functions `InsertCol()`, `InsertRow()`, `RemoveCol()` and `RemoveRow()`, please reference [godoc](https://godoc.org/github.com/xuri/excelize). This is just an initialization of this feature, only support insert single blank row and just auto handle existing hyperlinks, merged cells and auto filters currently. Function name that contains insert will insert before given index, that will make the API more concise. Welcome to contribute to this project.

**Comment by shawnye** [comment]
Thank you! 
I've tried ` InsertRow()` and it works.
