### ISSUE TITLE
undefined: strconv.ParseComplex

### ISSUE THREAD

**Issue by ch4meleon** [360EntSecGroup-Skylar/excelize#820]
**Description**
When installing using 'go get', it returns error as such:
undefined: strconv.ParseComplex

go get github.com/360EntSecGroup-Skylar/excelize

**Steps to reproduce the issue:**
# go get github.com/360EntSecGroup-Skylar/excelize

**Describe the results you received:**
# github.com/360EntSecGroup-Skylar/excelize
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1719:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1735:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1751:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1767:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1783:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1799:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1815:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1831:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1851:18: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1871:19: undefined: strconv.ParseComplex
../../../go/src/github.com/360EntSecGroup-Skylar/excelize/calc.go:1871:19: too many errors

**Describe the results you expected:**
No error

**Output of `go version`:**
go version go1.13.8 linux/amd64

**Excelize version or commit ID:**

Current version of github.com/360EntSecGroup-Skylar/excelize

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xuri** [comment]
Hi @ch4meleon, this issue duplicate with #815, since commit [`f8f699`](https://github.com/360EntSecGroup-Skylar/excelize/commit/f8f699a172bd0219a8736b19091dd3eaa9eb3b25), for complex number support required, the requirements Go language version is 1.15 or later. If your using the Go version is 1.10 or later but under 1.15 please using the v2.3.2 version.
