### ISSUE TITLE
zip: not a valid zip file

### ISSUE THREAD

**Issue by medivh13** [360EntSecGroup-Skylar/excelize#821]
Here is what I do :

    `req.Body = http.MaxBytesReader(w, req.Body, maxUploadSize)
	if err := req.ParseMultipartForm(maxUploadSize); err != nil {
		log.Println("file size error: %s", err)
		return nil, err
	}

	_, fileHeader, err := req.FormFile("file")

	if err != nil {
		log.Println("error when get file: %s", err)
		return nil, err
	}

	fileF, err := os.OpenFile("./"+fileHeader.Filename, os.O_WRONLY|os.O_CREATE, 0666)
	if err != nil {
		log.Println(err)
	}
	defer fileF.Close()

	xlsx, err := excelize.OpenFile("./" + fileHeader.Filename)
	if err != nil {
		log.Println(err)
		return nil, err
	}`
	
	The file is .xlsx format, but I got error "zip: not a valid zip file"
	
	What should I do to fix this?

**Comment by medivh13** [comment]
I use v1.4.1 and v2.3.2 buat the result is the same error, pls help me..

**Comment by xuri** [comment]
This issue duplicate with #207, please provides file attachments if you can.

**Comment by medivh13** [comment]
testfile2.xls

**Comment by medivh13** [comment]
[testfile2.xls](https://github.com/360EntSecGroup-Skylar/excelize/files/6301648/testfile2.xls)

**Comment by medivh13** [comment]
yes indeed this issue is same with #207 buat i cant find how can I fix this error.. pls help.. this is so urgently

**Comment by xuri** [comment]
Note that this library doesn't support the legacy XLS file format currently, also reference #44.

**Comment by medivh13** [comment]
wrong attachament sorry.. this is the attachment file :
[contoh-template-onboard-terbaru.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/6301672/contoh-template-onboard-terbaru.xlsx)
@xuri

**Comment by medivh13** [comment]
the file is .XLSX so wht should I do abt this?

**Comment by xuri** [comment]
I have tested with your XLSX attachment and it works well, please reference this doc about the [open data stream](https://xuri.me/excelize/en/workbook.html#OpenReader).

**Comment by medivh13** [comment]
Do you mean I have to change the excelize.OpenFile with excelize.OpenReader ?

**Comment by xuri** [comment]
Yep.

**Comment by medivh13** [comment]
OK thanks a lot
