### ISSUE TITLE
Because this character ❤ causes double data to be given, one line is empty

### ISSUE THREAD

**Issue by laixhe** [360EntSecGroup-Skylar/excelize#824]
**Output of `go version`:**

```text
go version go1.16.3 windows/amd64
```

**Comment by xuri** [comment]
I don't understand what you means, could you create the issue by an issue template and provide more details?

**Comment by xuri** [comment]
Hi @laixhe, it seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
