### ISSUE TITLE
InsertRow after stream writing is useless

### ISSUE THREAD

**Issue by eaglexiang** [360EntSecGroup-Skylar/excelize#826]
**Description**

I tried to insert one empty row after stream writing a excel file, no new line was inserted.

By the way, result of insert operation after normal writing is correct.

**Steps to reproduce the issue:**
1. create a new excel file by excelize
2. create a stream writer and write some cells.
3. flush stream writer and call method `File.InsertRow`
4. save excel as file.

```go
// empty line found at A1
package main

import "github.com/360EntSecGroup-Skylar/excelize/v2"

func main() {
	ef := excelize.NewFile()

	err := ef.SetCellDefault("Sheet1", "A1", "test")
	if err != nil {
		panic(err)
	}

	err = ef.InsertRow("Sheet1", 1)
	if err != nil {
		panic(err)
	}

	err = ef.SaveAs("test.xlsx")
	if err != nil {
		panic(err)
	}
}
```

```go
// no empty line
package main

import "github.com/360EntSecGroup-Skylar/excelize/v2"

func main() {
	ef := excelize.NewFile()

	sw, err := ef.NewStreamWriter("Sheet1")
	if err != nil {
		panic(err)
	}

	err = sw.SetRow("A1", []interface{}{"test"})
	if err != nil {
		panic(err)
	}
	err = sw.Flush()
	if err != nil {
		panic(err)
	}

	err = ef.InsertRow("Sheet1", 1)
	if err != nil {
		panic(err)
	}

	err = ef.SaveAs("test.xlsx")
	if err != nil {
		panic(err)
	}
}

```

**Describe the results you received:**

one excel file filled with only my test data.

**Describe the results you expected:**

one excel file filled with my test data and one empty line.

**Output of `go version`:**

```text
go version go1.16.3 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.4.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.0.2
Codename:       Ornara

**Comment by xuri** [comment]
We can't use common API and stream API mixed, this issue is similar to issues #725 and #777.

**Comment by eaglexiang** [comment]
Okay, I can follow your api rules. However, I need a way to create a `huge` excel with headers, which is built with merged cells like:

```txt
| header0 |         header1      |
|         | --------- | -------- |
|         |  header2  |  header  |
```

What's the typical way?

**Comment by xuri** [comment]
The Excelize doesn't support merge cell in streaming mode currently, I'll add this feature recently.

**Comment by xuri** [comment]
Hi @eaglexiang, I have just support merge cell in streaming mode,  please try to use the master branch code, and this feature will be released in the next version.
