### ISSUE TITLE
GetComments lost author when comment has multi author

### ISSUE THREAD

**Issue by raochq** [360EntSecGroup-Skylar/excelize#829]
I load a file edited by multiple users. I use function GetComments to get the comments, it renturn me an error author or none author.

i found when xml decode data into xlsxComments, it only remained the last author. 

i think the Authors of xlsxComments may define like this
```
type xlsxComments struct {
	XMLName     xml.Name        `xml:"http://schemas.openxmlformats.org/spreadsheetml/2006/main comments"`
	Authors     xlsxAuthors    `xml:"authors"`
	CommentList xlsxCommentList `xml:"commentList"`
}

type xlsxAuthors struct {
	Author []string `xml:"author"`
}
```

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
