### ISSUE TITLE
How to copy rows?

### ISSUE THREAD

**Issue by regorov** [360EntSecGroup-Skylar/excelize#83]
Hi!
I am using pre-created .xlsx file as a report template. Sometimes I need repeat set of rows. Would be nice to have a method what can receive (startRow, endRow) and be able to insert that rows before nRow.

What do you think? Is it possible now?
Thx
Regards, Robert

**Comment by xr081221097** [comment]
Hi, xuri. Could you please give your wechat or QQ? It will be easy to communicate with wechat or QQ.
I want to contribute the project. I think Insert, Delete and Copy Row are very nice to have.
thank you very much.

**Comment by xuri** [comment]
Welcome, please read [contributing guidelines](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/CONTRIBUTING.md) and contact me via `xuri.me[at]gmail.com`.
