### ISSUE TITLE
AddComment  only save then first author

### ISSUE THREAD

**Issue by raochq** [360EntSecGroup-Skylar/excelize#830]
copy comments with different authors, it only save the first author.

test code:
```
func testCopyComment() {
	f1 := excelize.NewFile()
	f1.AddComment("Sheet1", "A1", `{"author":"AA","text":" comment 1"}`)
	f1.AddComment("Sheet1", "A2", `{"author":"BB","text":" comment 2"}`)
	comment1 := f1.GetComments()["Sheet1"]

	fmt.Printf("%+v\n", comment1)
	f2 := excelize.NewFile()
	for _, com := range comment1 {
		f2.AddComment("Sheet1", com.Ref, fmt.Sprintf(`{"author":"%s","text":"%s"}`, com.Author, strings.TrimPrefix(com.Text, com.Author)))
	}
	comment2 := f2.GetComments()["Sheet1"]
	fmt.Printf("%+v\n", comment2)
}
```

output:

[{Author:AA AuthorID:0 Ref:A1 Text:AA comment 1} {Author:AA AuthorID:0 Ref:A2 Text:BB comment 2}]
[{Author:AA AuthorID:0 Ref:A1 Text:AA comment 1} {Author:AA AuthorID:0 Ref:A2 Text:AABB comment 2}]

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
