### ISSUE TITLE
SetCellValue looping yields ugly code

### ISSUE THREAD

**Issue by nnordrum** [360EntSecGroup-Skylar/excelize#831]
**Description**

Using `SetCellValue` is "hard" when you're looping.  Because `axis` is a single variable representing two things, you have to combine it each time to loop.

e.g.
```go
const Sheet1 = "Sheet1"
f.SetCellValue(Sheet1, fmt.Sprintf("%s%d", "A", line), valA)
f.SetCellValue(Sheet1, fmt.Sprintf("%s%d", "B", line), valB)
```

If code were changed, you could have this:
```go
consts (
  Sheet1 = "Sheet1"

  ColA = iota + 1
  ColB
)
for l, x := range factory() {
  line := l+2
  f.SetCellValueNumericSplit(Sheet1, ColA, line, valA)
  f.SetCellValueNumericSplit(Sheet1, ColB, line, valB)
}
```

Much easier and cleaner IMO.

**Comment by nnordrum** [comment]
I just discovered `SetSheetRow` in an example... playing with that now

**Comment by nnordrum** [comment]
that's way more convenient! thoughts on adding this to `SetSheetRow`? (also? instead?)

**Comment by xuri** [comment]
Base on the discussion on #832, I'll close this issue,  if you have any idea, please let me know.
