### ISSUE TITLE
Deleting sheets not working correctly

### ISSUE THREAD

**Issue by KaareKristensen** [360EntSecGroup-Skylar/excelize#834]
**Description**
I have some code that opens a file and deletes all sheets apart from a single sheet. The code then creates more sheets and populates them with data using file.SetCellValue. If the code created the file itself it does not work, if I created the file and the code then edits it then it does work.
The problem is that when I open the file in Excel I get an error and Excel tries to repair the file. The inserted data is gone after the repair.

**Steps to reproduce the issue:**
[temp.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/6421820/temp.zip)

1. Run the included code to create a file
2. Run the code again to "edit" the file, although it just sets the same values in all cells
3. Open the edited file in excel

**Describe the results you received:**
Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Replaced Part: /xl/worksheets/sheet2.xml part with XML error.  Declared prefix. Line 2, column 143.
Replaced Part: /xl/worksheets/sheet3.xml part with XML error.  Declared prefix. Line 2, column 143.

Note that I have not created a sheet by these names.

**Describe the results you expected:**
I expected to see the new sheets with the new data and no error message.

**Output of `go version`:**

```text
go version go1.15 windows/amd64
```

**Excelize version or commit ID:**

```text
v2.4.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Windows 10
Excel version: 16.0 (Microsoft 365)

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
