### ISSUE TITLE
Unable to set row height when using streamWriter

### ISSUE THREAD

**Issue by tinlacoo** [360EntSecGroup-Skylar/excelize#835]
**Description**

**Steps to reproduce the issue:**
1. Create file.
2. Set Row height using function SetRowHeight - e.g: file.SetRowHeight("Sheet1", 1, 30)
3. Create StreamWriter from file.
4. Flush StreamWriter using function streamWriter.Flush().
5. Check row height using function GetRowHeight.

**Describe the results you received:**
Row height is reset to default. 
![image](https://user-images.githubusercontent.com/19259078/117259994-ccc98700-ae78-11eb-9a39-7f7b1cf591f7.png)

Note:  - Result still the same if row height is set via : streamWriter.File.SetRowHeight("Sheet1", 1, 30)
           - Set row height after streamWriter.Flush() will do but the file output still keep the default height.
![image](https://user-images.githubusercontent.com/19259078/117256969-89214e00-ae75-11eb-9611-1a473fa802b6.png)

**Describe the results you expected:**
Row height is updated correctly.

**Code Sample**

```text
file := excelize.NewFile()

	file.SetRowHeight("Sheet1", 1, 30)
	height, _ := file.GetRowHeight("Sheet1", 1)
	fmt.Println("File row height: ", height)

	streamWriter, err := file.NewStreamWriter("Sheet1")
	styleID, _ := file.NewStyle(`{"font":{"color":"#777777"}}`)

	if err := streamWriter.SetRow("A1", []interface{}{excelize.Cell{StyleID: styleID, Value: "Data Sample"}}); err != nil {
		fmt.Println(err)
	}

	heightStream, _ := streamWriter.File.GetRowHeight("Sheet1", 1)
	fmt.Println("streamWriter.File row height after new: ", heightStream)

	for rowID := 2; rowID <= 5; rowID++ {
		row := make([]interface{}, 50)
		for colID := 0; colID < 2; colID++ {
			row[colID] = rand.Intn(640000)
		}
		cell, _ := excelize.CoordinatesToCellName(1, rowID)
		if err := streamWriter.SetRow(cell, row); err != nil {
			fmt.Println(err)
		}
	}

	err = streamWriter.Flush()
	if err != nil {
		fmt.Println(err)
	}

	height, _ = file.GetRowHeight("Sheet1", 1)
	fmt.Println("File row height after flush: ", height)

	name := uuid.NewV1().String()
	if err := file.SaveAs("Book1.xlsx"); err != nil {
                 fmt.Println(err)
        }
```

**Output of `go version`:**

```text
go 1.15
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.4.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10 Pro, Office professional plus 2016

**Comment by xuri** [comment]
This issue duplicate with #725, you can't use common API and stream API mixed, also reference #777 and #826.

**Comment by tinlacoo** [comment]
Hi @xuri, 

So can you provide any solutions for me to set height is this case. 
Because the height is set using common API before create stream as mentioned in the above steps.

**Comment by xuri** [comment]
You can't use streaming API in this case, use the common API (such as [SetSheetRow](https://xuri.me/excelize/en/sheet.html#SetSheetRow) or [SetCellValue](https://xuri.me/excelize/en/cell.html#SetCellValue) ) to set the worksheet cell value and column width.

**Comment by tinlacoo** [comment]
Thank @xuri,
My file have complex functions (merge cells, panel..) with big data (always 20000 rows ) so I must use stream for the best output performance.
![image](https://user-images.githubusercontent.com/19259078/117288594-dca39400-ae95-11eb-96b8-ef68e9e4243b.png)
Currently, I'm using excelize v2.3.1 without problem with SetRowHeight function but have a little performance issue with merge cells. 
And you guys have done amazing job for improved the performance so much in v2.4.0 . So I tried to apply this but got problem with the Height :(.
![image](https://user-images.githubusercontent.com/19259078/117290312-d9110c80-ae97-11eb-9232-c03881ac77de.png)
Thanks anyway
