### ISSUE TITLE
StreamWriter MergeCell

### ISSUE THREAD

**Issue by liov** [360EntSecGroup-Skylar/excelize#837]
The doc has StreamWriter MergeCell，but i didn't find。

**Output of `go version`:**

```text
1.16
```

**Excelize version or commit ID:**

```text
v0.0.0-20210415231046-e915ea6b2b7d
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
windows

**Comment by xuri** [comment]
Please upgrade to the master branch code, and this feature will be released in the next version.
