### ISSUE TITLE
Broken workbookReader for .xltx files

### ISSUE THREAD

**Issue by SVilgelm** [360EntSecGroup-Skylar/excelize#838]
**Description**

It is broken only with the `.xltx` files (templates). It reads the file and assigns wrong IDs to the sheets. So when I use a StreamWriter by a name then it writes to the wrong sheet.

**Steps to reproduce the issue:**
1. Create a `.xltx` file with two sheets
2. Open file in exelize
3. Get StreamWriter for second sheet by its name
4. write some data
5. flush
6. save the file

**Describe the results you received:**
it writes to the first sheet

**Describe the results you expected:**
data should be places in second sheet

**Output of `go version`:**

```text
go version go1.16.3 darwin/amd64
```

**Excelize version or commit ID:**

go.mod
```text
	github.com/360EntSecGroup-Skylar/excelize/v2 v2.4.0
```

go.sum
```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.4.0 h1:X+2CWGf5W1tm2+W7Y/LLrAPLFSNlHATnqDudGoIzaxY=
github.com/360EntSecGroup-Skylar/excelize/v2 v2.4.0/go.mod h1:p9lGPoVX3HYEbFRfjgrPWaaKsHe/2u4EM9DB/qoctgU=

```

**Comment by SVilgelm** [comment]
Here is replit: https://replit.com/join/kqskaant-svilgelm

I attached the templates `OHTemplate.xltx` and `OHTempalte.xlsx`. If I use the `xlsx` then it works fine, bu in case of the `xltx` if fails

**Comment by SVilgelm** [comment]
On this screen shot you can see, that the seetMap has two sheets with names `Sheet1` and `orderHistory`
<img width="384" alt="Screen Shot 2021-05-12 at 10 01 08 PM" src="https://user-images.githubusercontent.com/523825/118071522-8fc82d80-b36d-11eb-949a-34ec79779a98.png">

**Comment by SVilgelm** [comment]
but if I open the WorkBook, then I see that `Sheet` has ID=2 and `orderHistory` has ID=1
<img width="318" alt="Screen Shot 2021-05-12 at 10 03 21 PM" src="https://user-images.githubusercontent.com/523825/118071692-dfa6f480-b36d-11eb-8568-988ce3d92aef.png">

**Comment by SVilgelm** [comment]
So when I call the `Flush` function it will write to the wrong file because of incorrect ID assigned
<img width="506" alt="Screen Shot 2021-05-12 at 10 04 35 PM" src="https://user-images.githubusercontent.com/523825/118071826-2c8acb00-b36e-11eb-90aa-f2167b593403.png">

**Comment by SVilgelm** [comment]
The archive contains all files
[Archive.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/6470169/Archive.zip)

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.

**Comment by SVilgelm** [comment]
thank you! I tested it, everything works!
