### ISSUE TITLE
Does not work under Linux

### ISSUE THREAD

**Issue by vchugreev** [360EntSecGroup-Skylar/excelize#84]
Hello, Ri. 

Under Linux (I tested on Astra Linux) the library writes an incorrect xlsx file. Help, please, this is very important for me.

package main

import (
	"github.com/Luxurioust/excelize"
)

func main() {
	xlsx, _ := excelize.OpenFile("1.xlsx")
	xlsx.SetCellValue("Sheet1", "A1", 100)
	xlsx.SaveAs("2.xlsx")
}

Attachment:
1.xlsx - file created for windows
2.xlsx - file created for windows
2_linux.xlsx - file created for linux 

[1.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1165155/1.xlsx)
[2.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1165156/2.xlsx)
[2_linux.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1165157/2_linux.xlsx)

**Comment by xuri** [comment]
Check the Go version you are using. This library needs Go version 1.8 or later after fixed issue #32 for collecting XML all attributes. Relate issue #35, #39 & #42.

**Comment by vchugreev** [comment]
Thank you! I'll check.

**Comment by vchugreev** [comment]
Yes, I have 1.7.5. I understand everything, I'll update the go. Many thanks!
