### ISSUE TITLE
avoid empty rows in the tail of the worksheet[again in v2]

### ISSUE THREAD

**Issue by ankitkumardev** [360EntSecGroup-Skylar/excelize#842]
Refer #195.

I am still getting this issue in excelize v2.3.2

**Comment by xuri** [comment]
Thanks for your feedback, I confirmed this issue caused by the commit [`ac91ca0`](https://github.com/360EntSecGroup-Skylar/excelize/commit/ac91ca0ded4111ed9f22578d4a0570a9084c97b0), and I have fixed it, please try to use the master branch code, and this patch will be released in the next version.

**Comment by raochq** [comment]
after fix this bug. I have another problem when I copy a sheet to another file.
I use GetRows function to get all data, and then I  iterates data and use GetCellFormula to get the formula.
after fix this bug.  I lost the last cell whose value is empty and it is a formula cell.

I think it can be changed like this.
https://github.com/360EntSecGroup-Skylar/excelize/blob/master/rows.go#L168
```
if val != "" || colCell.F != nil {
	rowIterator.columns = append(appendSpace(blank, rowIterator.columns), val)
}
```
