### ISSUE TITLE
loss of precision when  reading execl rows inclouding decimals?

### ISSUE THREAD

**Issue by WickyLeo** [360EntSecGroup-Skylar/excelize#848]
**Description**

9.6732
2.2

when read excel file including decimals, 
cell result is 9.6731999999999996, 2.2000000000000002
how to fix it?

**Comment by WickyLeo** [comment]
@xuri

**Comment by xuri** [comment]
Thanks for your feedback, I have tested and it works well, could you create the issue by an issue template and provide more details?

**Comment by hidahua** [comment]
[202105-test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/6568016/202105-test.xlsx)
tks！
Note: It is normal when using wps to open and save the file, but there is a problem with excel

**Comment by SinowZ** [comment]
@xuri

**Comment by xuri** [comment]
I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.
