### ISSUE TITLE
Hiding xlsx Columns works on windows/google docs  but fails on ubuntu's Libre Office

### ISSUE THREAD

**Issue by tevin-morake** [360EntSecGroup-Skylar/excelize#85]
I am trying to hide the columns of a spreadsheet from my debian ubuntu gnome.
I'm using the xlsx.SetColVisible("Sheet1", "N", false) method, however when I reopen the xlsx in Libre Office, nothing has changes.
When I uploaded the xlsx document to google docs, it hid the **"N"** Column properly.
When I opened the xlsx document on a windows vm with MS Excel the column was hidden successfully.
Is there a config  or something I am missing in the code to ensure it hides on linux's Libre Office ? 
I am running go 1.8.3 and using ubuntu gnome 16.04 LTS
Please assist

**Comment by xuri** [comment]
I have tested on `Ubuntu 17.04 with Libre Office Version: 5.3.1.2 Build ID: 1:5.3.1-0ubuntu2`, `macOS Sierra 10.12.6 with Libre Office Version: 5.1.0.3 Build ID: 5e3e00a007d9b3b6efb6797a8b8e57b51ab1f737` and it works well. Please provide file attachments If you can.

**Comment by tevin-morake** [comment]
Hi 

Please see attached :

**NB** : I have removed critical data from spreadsheet 
[sample.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1169062/sample.xlsx)

**Comment by xuri** [comment]
Do you hide the column `N`? I found that column `L` was hidden, and it was working properly with Libre Office both Ubuntu and macOS.

**Comment by tevin-morake** [comment]
Apologies for miscommunication. This is a copy of the spreadsheet and in this copy I've hidden `L` as you have said.

Please see updated xlsx document : 
[sample.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1169274/sample.xlsx)

Also Please see the following screenshots from Libre Office & google sheets. I have the same template open : 
![googlesheets](https://user-images.githubusercontent.com/15342622/28515680-c5babbfc-705e-11e7-9846-f347fcdfa9c7.png)
![libreoffice](https://user-images.githubusercontent.com/15342622/28515681-c5bc55ac-705e-11e7-9a03-7a271dc07d0f.png)
I am running Libre Office  Version: 5.1.6.2

**Comment by xuri** [comment]
I found that the reason of can't be hidden is missing `customWidth` attribute of `col` element in the worksheet, and I have tested `SetColVisible()` in the last version of the excelize lib, it works well both Libre Office and Google Sheets. Have you ever tried to update the lib to the latest version?

**Comment by tevin-morake** [comment]
I have but I see that there's been recent changes as well.
I'm going to update, test and get back to you

**Comment by tevin-morake** [comment]
No luck yet. I am going to uninstall go and the xuri package. Would having both the *xuri* and the previous *Luxurioust* package influence the program in any way even though I'm importing the *xuri* package in my program ?

**Comment by xuri** [comment]
Repo URL has been changed, but you can still use Luxurioust package, the code for the different name packages is the same. Just check the commit log before update the library to ensure compatibility with existing applications.

**Comment by tevin-morake** [comment]
There's been no difference.
The customer's I'm creating this for won't be in use of linux, so I'll leave it as is for now.
Thanks for your assistance though
