### ISSUE TITLE
When the field value type is a floating point type, the parsed data is wrong

### ISSUE THREAD

**Issue by hidahua** [360EntSecGroup-Skylar/excelize#852]
change excel filed to any format is the same error!

**Steps to reproduce the issue:**
1.excel filed value is: 2422.3 , use type General(or other type)
2.the value after reading is:2422.3000000000002

**Describe the results you received:**
2422.3000000000002
**Describe the results you expected:**
2422.3

**Output of `go version`:**
go1.15.5

**Excelize version or commit ID:**
master

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux and MacOs have the same error

**Comment by xuri** [comment]
This issue duplicates with #848. could you provide any attachment or code to reproduce this issue?

**Comment by xuri** [comment]
I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.
