### ISSUE TITLE
after #842 "avoid empty rows in the tail of the worksheet", lost some formula cell data

### ISSUE THREAD

**Issue by raochq** [360EntSecGroup-Skylar/excelize#855]
after fix this bug. I have another problem when I copy a sheet to another file.
I use GetRows function to get all data, and then I iterates data and use GetCellFormula to get the formula.
after fix this bug. I lost the last cell whose value is empty and it is a formula cell.

I think it can be changed like this.

https://github.com/360EntSecGroup-Skylar/excelize/blob/master/rows.go#L168

```
if val != "" || colCell.F != nil {
	rowIterator.columns = append(appendSpace(blank, rowIterator.columns), val)
}
```

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
