### ISSUE TITLE
save date format data as yyyy/mm/dd or yyyy/m/d format

### ISSUE THREAD

**Issue by dlintw** [360EntSecGroup-Skylar/excelize#86]
@xuri, I found there is SetCellStyle(v,"A9","A9", `{"number_format":22}`) method to setup time value.
But, I can not save as format like 'yyyy/mm/dd' or 'yyyy/m/d'. 
Is it possible to support a custom format method like this

`[DBNum1][$-404]e"年"m"月"d"日";@`

http://www.myonlinetraininghub.com/excel-dates-displayed-in-different-languages

**Comment by xuri** [comment]
Thanks for your issue, I have added the number format code table in [godoc](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStyle), you can create a date format like this:
```
xlsx.NewStyle(`{"number_format": 28, "lang": "zh-tw"}`)
```

**Comment by dlintw** [comment]
What's the difference between 'zh-tw':{ 27: "[$-404]e/m/d"}  and 'zh-tw':{ 36: "[$-404]e/m/d"}?
I guess that is mapping to 西曆(2007) & 中華民國曆 ( 106=2007-1911), so it require a year subtract function when convert the number into string.

BTW, have you ever read [this document](https://blogs.msdn.microsoft.com/brian_jones/2007/05/29/simple-spreadsheetml-file-part-3-formatting/)  , maybe it is useful for customized format

**Comment by xuri** [comment]
@dlintw I have added set custom number format support.

**Comment by dlintw** [comment]
@xuri, 
1. could you put example of builtin & custom number format in README.md?
2. In my Excel 2007(zh_TW), the `{"number_format":14}` will set the output as 'yyyy/mm/dd'.  But in excelize's document, it is 'm/d/yy'.'

**Comment by xuri** [comment]
- I have added a custom number format example in the [godoc](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.NewStyle).
- Some number format code can be interpreted differently, depending on the UI language of the implementing application. The formatCode 14 is Excel's built-in number format specified by the formatCode attribute. Reference [part 1 of the 5th edition of the ECMA-376 Standard for Office Open XML](http://www.ecma-international.org/publications/standards/Ecma-376.htm). Try using custom number format if you can't find what you need for the built-in general and national language  of number format code.
