### ISSUE TITLE
SetCellFloat with precision is not correctly shown if the last digits are zeros

### ISSUE THREAD

**Issue by LaurinX** [360EntSecGroup-Skylar/excelize#862]
**Description**

**Steps to reproduce the issue:**
1.
```
package main

import (
	"fmt"
	excelize "github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main(){
	f := excelize.NewFile()
	sheet := f.GetSheetName(0)
	value := float64(6.7800)
	f.SetCellFloat(sheet,"A1",value,3,64)
	fmt.Println(f.GetCellValue(sheet,"A1") )
	f.SaveAs("Book1.xlsx")
}
```
run it.
2. open Book1.xlsx with excel or libreoffice
3. Look at cell A1. It wont show the correct precision

**Describe the results you received:**
Result in Libreoffice = 6.78

**Describe the results you expected:**
Result should show in Libreoffice = 6.780
(GetCellValue gives the correct number)
**Output of `go version`:**

```text
go version go1.15.3 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.4.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux Mint 20.0, LibreOffice 6.4.7.2 40(Build:2)

**Comment by vale1410** [comment]
To the Excelize community: 
Is there another way to set a cell to a number format of 3 decimal places ?

**Comment by xuri** [comment]
Hi @LaurinX, @vale1410, please create a style with number format by [`NewStyle`](https://xuri.me/excelize/en/style.html#NewStyle), and set the style by [`SetCellStyle`](https://xuri.me/excelize/en/cell.html#SetCellStyle) like this:

```go
styleID, err := f.NewStyle(&excelize.Style{CustomNumFmt: &numberFmt})
if err != nil {
	fmt.Println(err)
}
if err := f.SetCellStyle(sheet, "A1", "A1", styleID); err != nil {
	fmt.Println(err)
}
```

After that, the cell value will be shown correct precision in the Excel application if you open the saved spreadsheet. Not that Excelize doesn't support parse the custom number format, so the result got by the `GetCellValue` may be inconsistent with the Excel. I'll close this issue, and continue to discuss the number format issue in issue #660
