### ISSUE TITLE
how to append a row

### ISSUE THREAD

**Issue by Jiuyuedongyang** [360EntSecGroup-Skylar/excelize#864]
I want to append lots rows,but i can't find any func.how can i use excelize to append rows?
我想再表格末尾插入一行，但是我没有找到相关的函数，请问如何操作？比如我有10行数据，表格中原有数据为6行，我想在第7行插入那10条，请问如何操作？

**Comment by xuri** [comment]
You can know the last row by iterate rows which fetched by [`GetRows`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.GetRows) or [row's iterator](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.Rows) and then set the row by [`SetSheetRow`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.SetSheetRow).
