### ISSUE TITLE
能否支持分页读取行或读取指定行？

### ISSUE THREAD

**Issue by oneweek20169902** [360EntSecGroup-Skylar/excelize#865]
对于百万大文件一次性加载到内存很耗费资源，并性能较差，能否支持对分页读取或读取某一行？

**Comment by xuri** [comment]
Reading data from a worksheet with huge amounts of data by [row's iterator](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.Rows).
