### ISSUE TITLE
Updating the data source (DataRange) of an existing pivot table

### ISSUE THREAD

**Issue by Orionsg** [360EntSecGroup-Skylar/excelize#866]
Quite often the use case for a package used to make Excel pivot tables is that an initial Excel file with a pivot is generated with a data source (Excelize's DataRange). An end-user may then change the Excel file, adding graphics, selecting various fields as row or column fields, etc., so it is suitable for the user as a report to be regularly updated with regards to data but with the layout kept as it is.

In the scenario described above, one needs to be able to update the data source of an existing Pivot table in an Excel file with Excelize if the report is "run" regularly based on new or changed data rows. I tried to use Excelize's SetDefinedName to define an Excel name referring to a range in Excel and then use that name as the DataRange field of the PivotTableOption struct. Unfortunately, it does not work as the DataRange field can only work with a direct reference to a range in the format <Sheetname>!<range literal>, e.g. "Sheet1!$A$1:$E$31".

Would it be possible to have the DataRange field accept an Excel defined name instead of a range literal so one could later redefine the name (using SetDefinedName) in an existing Excel file with a pivot table created earlier, and have the Pivot table use the new data when the pivot table is refreshed?

The alternative would be implementing updating an existing pivot table directly, but I think that would be a much larger job based on what is written about this in the Python package [openpyxl](https://openpyxl.readthedocs.io/en/stable/pivot.html). The openpyxl package does support manipulating existing pivot tables, but it does seem complicated, and I am anyway transitioning from Python to Go and so would prefer to use the latter as it is a much better language.

**Comment by xuri** [comment]
Thanks for your issue, I'll add support to set pivot table data range by defined name recently.

**Comment by xuri** [comment]
I have added support for using the defined name to reference the data range in pivot table options, please try to upgrade the master branch code, and this feature will be released in the next version.

**Comment by Orionsg** [comment]
Thanks a lot. 
I will check it out.
