### ISSUE TITLE
Data Refresh

### ISSUE THREAD

**Issue by hajsf** [360EntSecGroup-Skylar/excelize#867]
Hi,
My fire is connected to live data, and I need to 'Refresh: it in the sheet before doing any progress, is there a way to do this Refresh/Refresh All through Exvelize?

**Comment by xuri** [comment]
Currently, this library doesn't support refresh for the worksheet which linked external data.

**Comment by hajsf** [comment]
Thanks @xuri , can we make a PR for this option?

**Comment by xuri** [comment]
Yes, this feature is related to connections and query tables parts, contributions are welcome.
