### ISSUE TITLE
How to remove row in the sheet ?

### ISSUE THREAD

**Issue by peter-hst** [360EntSecGroup-Skylar/excelize#869]
**Description**

**Steps to reproduce the issue:**
1. I use file.RemoveRow(sheetName, rowNum), but they can't removed that rows with format style;

**Describe the results you received:**

```
func clearSheetSpaceFmt(file *excelize.File, sheetName string, begin, end int) {
	for i := 0; i < end-begin; i++ {
		fmt.Printf("%s del -> %d \n", sheetName, begin+i)
		if err := file.RemoveRow(sheetName, begin+i); err != nil {
			fmt.Println(err)
		}
	}
}

```

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your feedback, which version of Excelize are you using? I've tested and it works well. Could you provide more details or a spreadsheet xlsx attachment without confidential info?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
