### ISSUE TITLE
SetCellValue() make extra rows

### ISSUE THREAD

**Issue by dlintw** [360EntSecGroup-Skylar/excelize#87]
In this example code, it is wrong.

package main

import (
	"fmt"
	"log"

	"github.com/xuri/excelize"
)

func main() {
	xlsx := excelize.NewFile()
	sRow := "2"
	for i := 1; i <= 5; i++ {
		loc := GetColStr(i) + sRow
		fmt.Println("loc=", loc)
		xlsx.SetCellValue("Sheet1", loc, i)
	}
	fmt.Println("used rows=", len(xlsx.GetRows("Sheet1"))) // should be 2
	// Bug1: Used Range of Sheet1 is "A1..E5", but should be "A1..E2"
	err := xlsx.SaveAs("./bug1.xlsx")
	if err != nil {
		log.Fatalln(err)
	}
}
func GetColStr(x int) string {
	colName := ""
	for x > 0 {
		digit := (x - 1) % 26
		colName = string(int('A')+digit) + colName
		x = (x - 1 - digit) / 26
	}
	return colName
}

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it.
