### ISSUE TITLE
SetDefinedName does not update an existing defined name

### ISSUE THREAD

**Issue by Orionsg** [360EntSecGroup-Skylar/excelize#870]
If a given defined name already exists in a workbook and one uses the SetDefinedName function to specify a new range that it refers to, the range is not updated, i.e. the defined name refers to the same old area. 

One has to use the DeleteDefinedName function to first delete the existing defined name and then use SetDefinedName. However, while this works, the issue should be fixed as those not knowing about this issue might be getting unexpected results. I would expect the range of the defined name to be simply overwritten.

The issue is seen in the master branch.

**Comment by xuri** [comment]
Thanks for your feedback. I've tested and it works well. Could you provide more details or a spreadsheet xlsx attachment without confidential info?

**Comment by xuri** [comment]
If you using `SetDefinedName` for an existing defined name, you'll get the error: `the same name already exists on the scope`, it can help developers find out exist defined name when creating a new one.

**Comment by Orionsg** [comment]
Okay, I did not see the possible error returned by the function, but just assumed that it would overwrite. 
So, everything works as per the documentation. 
My mistake :-). Sorry for the erroneous bug report.
