### ISSUE TITLE
The GetRows function corrupts the content of the Excel file

### ISSUE THREAD

**Issue by Orionsg** [360EntSecGroup-Skylar/excelize#871]
When using the GetRows function the Excel file's format is apparently corrupted. 

Below is a program that will:
1. Create or open an existing Excel file named "test.xlsx". 
2. Create a new sheet "test" (existing sheet "test" is deleted first)
3. Ask if the content of the test sheet should be read with GetRows
4. If "yes", the rows are printed to the terminal (this works fine)
5. A final save of the Excel file is done

Now, if one does not print the "test" sheet content to the terminal (point 3 and 4 above), there is no problem, i.e. the Excel file is intact and can be opened in Excel. If, on the other hand, one selects to print the content, the file is corrupted. When trying to open the Excel file afterwards in Excel, I get the error message:
"We found a problem with some content in 'test.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes"

However, the workbook is totally corrupted for the test program below. In another program, I have had the sheet being read by the GetRows function removed from the workbook, but the workbook could be opened normally.

Here is the test program:

```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

const s_file = "test.xlsx"
const s_sh_test = "test"

func main() {
	var wb *excelize.File
	var err error

	if fileExists(s_file) {
		wb, err = excelize.OpenFile(s_file)
		if err != nil {
			log.Fatal(err)
		}
	} else {
		wb = excelize.NewFile()
		err = wb.SaveAs(s_file)
		if err != nil {
			log.Fatal("Could not save new Excel file `", s_file, "`: ", err)
		}
		// fmt.Println("Immediate save of new Excel file after SaveAs")
		// saveXlFile(wb)
	}
	if sheetExists(wb, s_sh_test) {
		wb.DeleteSheet(s_sh_test)
	}
	wb.NewSheet(s_sh_test)
	// fmt.Println("Saving Excel file with new sheet test")
	// saveXlFile(wb)

	// add values to the test sheet
	sl_cells := []string{"A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3"}
	for _, s_cell := range sl_cells {
		wb.SetCellStr(s_sh_test, s_cell, s_cell)
	}
	fmt.Println("Saving Excel file with cells filled in test sheet")
	saveXlFile(wb)

	s_ch := ""
	sl_menu := []string{"yes", "no"}

	for !contains(sl_menu, s_ch) {
		fmt.Printf("Read content of sheet `%s` using GetRows? [yes/no] \n", s_sh_test)
		fmt.Scanln(&s_ch)
	}
	if s_ch == "yes" {
		fmt.Printf("Content of sheet `%s`: \n", s_sh_test)
		rows, err := wb.GetRows(s_sh_test)
		if err != nil {
			log.Fatal(err)
			return
		}
		for i_row, row := range rows {
			fmt.Print("Row: ", i_row, "\t")
			for _, s_cell := range row {
				if s_cell == "" {
					s_cell = "[]"
				}
				fmt.Print(s_cell, "\t")
			}
			fmt.Println()
		}
	}
	saveXlFile(wb)
	fmt.Println("Final save of Excel file")
}

func saveXlFile(wb *excelize.File) {
	err := wb.Save()
	if err != nil {
		log.Fatal("Could not save the Excel file `", s_file, "`: ", err)
	}
}

func sheetExists(wb *excelize.File, s_sh_name string) bool {
	b_fnd := false
	for _, s_sh := range wb.GetSheetList() {
		if s_sh == s_sh_name {
			b_fnd = true
			break
		}
	}
	return b_fnd
}

func contains(sl_str []string, ss string) bool {
	if len(sl_str) == 0 || ss == "" {
		return false
	}
	for _, str := range sl_str {
		if str == ss {
			return true
		}
	}
	return false
}

func fileExists(s_file string) bool {
	info, err := os.Stat(s_file)
	if os.IsNotExist(err) {
		return false
	}
	if info.IsDir() {
		log.Fatal("Error: ", s_file, " is a directory")
	}
	return true
}
```

**Comment by xuri** [comment]
Thanks for your feedback, I've tested on the master branch code, and it works well, which version of this library are you using?

**Comment by Orionsg** [comment]
I was using v2.4.0,
When I changed to the master branch, the problem is no longer there, so perhaps something that was fixed already.

**Comment by xuri** [comment]
Okay, I close this issue.
