### ISSUE TITLE
Promble when I set sheetName=“sheet1”，and download in browser is ok， but when I open it in my excel, it say my file contains some error 

### ISSUE THREAD

**Issue by GuoGuiRong** [360EntSecGroup-Skylar/excelize#873]
**Describe the results you received:**
here is my test code
```
package utils

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize/v2"
	"testing"
)

func TestExportExcelUtil(t *testing.T) {
	t.Run("", func(t *testing.T) {
		f := excelize.NewFile()
                // if set "Sheet1" the xlsx will open ok in Excel, only use "sheet1" occur error
		sheetIndex := f.NewSheet("sheet1")
		f.SetActiveSheet(sheetIndex)
		f.SaveAs("test1.xlsx")
	})
}
```

it's running ok, but the xlsx file may occur error when open in Excel
![image](https://user-images.githubusercontent.com/22836006/125078044-71c04480-e0f4-11eb-9c52-f9f0d64c4941.png)
# Environment
go version go1.15.6 darwin/amd64
with github.com/360EntSecGroup-Skylar/excelize/v2 v2.4.0

**Comment by xuri** [comment]
Thanks for your feedback, which version of Excelize are you using? I've tested and it works well. Could you provide more details, code to reproduce this issue or a spreadsheet xlsx attachment without confidential info?

**Comment by GuoGuiRong** [comment]
go version go1.15.6 darwin/amd64
excelize v2.4.0

you can use my demo code to test, only when I set SheetName='sheet1' occur this problem.

**Comment by xuri** [comment]
Thanks for your issue, I have fixed this by letting the sheet names are not case sensitive for `NewSheet`, `GetSheetIndex`, `DeleteSheet`. Please try to upgrade the master branch code, and this feature will be released in the next version. When creating a new spreadsheet file, the default
 worksheet named `Sheet1` will be created, if you wanna change the name for it, you can using the `SetSheetName`.
