### ISSUE TITLE
Whether you can add a hyperlink to the text, not just sheet

### ISSUE THREAD

**Issue by Pluto-yubin** [360EntSecGroup-Skylar/excelize#877]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Sorry, I don't understand what's your mean. If you wanna set hyperlink for the cell, you can use the [`SetCellHyperLink`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.SetCellHyperLink).

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
