### ISSUE TITLE
i want using streamWriter.MergeCell，but it's just in branch master，When will the new tag be released?

### ISSUE THREAD

**Issue by xieping5555** [360EntSecGroup-Skylar/excelize#878]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
The next version [v2.4.1](https://github.com/360EntSecGroup-Skylar/excelize/projects) will be released on August 2nd, 2021, and the changelog of this version on the [documentation website](https://xuri.me/excelize/en/releases/v2.4.1.html).
