### ISSUE TITLE
Giving an incomplete range reference to the SetDefinedName ("RefersTo" field) results in a corrupted Excel file

### ISSUE THREAD

**Issue by Orionsg** [360EntSecGroup-Skylar/excelize#880]
I used the SetDefined name function with a DefinedName literal in a new sheet but forgot to specify the full reference in the "RefersTo" field (i.e. the name of the datasheet and an exclamation mark have to be prefixed, e.g. "test!$A1:$C3"):
```
	if err := wb.SetDefinedName(&excelize.DefinedName{
		Name:     s_def,
		RefersTo: "$A1:$C3",
		Comment:  "Data area",
	}); err != nil {
		log.Fatal("Can't set defined name: ", s_def, "Error: ", err)
	}
```
This resulted in a corrupted Excel file, which gave the following error message when I tried to open it in Excel:
**"We found a problem with some content in 'test.xlsx'. Do you want us to try to recover as much as we can? ..."**
However, the whole sheet is missing.

**The issue is in master branch: v2.4.1-0.20210711160239-f62c45fe0c1**

Here is the full test code:
```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

const s_file = "test.xlsx"
const s_sh = "test"
const s_def = "data"

func main() {

	fileDelete(s_file)
	wb := excelize.NewFile()

	// add new sheet and data to it
	wb.NewSheet(s_sh)
	sl_cells := []string{"A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3"}
	for _, s_cell := range sl_cells {
		wb.SetCellStr(s_sh, s_cell, s_cell)
	}

	// set definition for data areas
	if err := wb.SetDefinedName(&excelize.DefinedName{
		Name:     s_def,
		RefersTo: "$A1:$C3",
		Comment:  "Data area",
	}); err != nil {
		log.Fatal("Can't set defined name: ", s_def, "Error: ", err)
	}

	if err := wb.SaveAs(s_file); err != nil {
		log.Fatal("Could not save new Excel file `", s_file, "`: ", err)
	}
	fmt.Println("Done")
}

func fileExists(s_file string) bool {
	info, err := os.Stat(s_file)
	if os.IsNotExist(err) {
		return false
	}
	if info.IsDir() {
		log.Fatal("Error: ", s_file, " is a directory")
	}
	return true
}

func fileDelete(s_file string) {
	if fileExists(s_file) {
		err := os.Remove(s_file)
		if err != nil {
			log.Fatal("Problem removing file `", s_file, "`: ", err)
		}
	}
}
```

**Comment by xuri** [comment]
Hi @Orionsg, please use ``RefersTo: `"$A1:$C3"`,`` instead of `RefersTo: "$A1:$C3",`.

**Comment by Orionsg** [comment]
Hi xuri, 

It seems strange to me that adding backticks (`) around the range reference would make a difference. It is not mentioned as something one has to do in the documentation for the SetDefinedName function, but strangely you are right :-). The Excel file is no longer corrupted when the backticks are added as you describe. However, when giving the sheet name together with the range reference, the backticks are not needed. It seems inconsistent.

Furthermore:

1. While the Excel file is not corrupted, the defined name is not created in my example code above, when specifying only the range with backticks but no sheet reference for RefersTo. This seems like a hidden error.

2. Would not the full reference to the sheet be needed? Otherwise, how do we know to which sheet the defined name pertains. Perhaps it is the active sheet. But still, it would be better to enforce a full reference to avoid mistakes.

3. If anything not conforming to the full, right format is given as a value for "RefersTo", I would rather have a hard fail right away, i.e. an error being generated.
