### ISSUE TITLE
how to set row height with streamWriter?

### ISSUE THREAD

**Issue by xieping5555** [360EntSecGroup-Skylar/excelize#882]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
The stream writer doesn't support set row's height currently, I have added this feature request to the [Roadmap](https://github.com/xuri/excelize/wiki#feature-todo).

**Comment by xuri** [comment]
I have added support for set rows height and hidden row by stream writer, please try to upgrade the master branch code, and this feature will be released in the next version.
