### ISSUE TITLE
Corrupted Excel file with conditional formatting inside pivot table

### ISSUE THREAD

**Issue by postulha** [360EntSecGroup-Skylar/excelize#883]
**Description**

Corrupted Excel file is created after opening a file with conditional formatting inside pivot table, calling `UpdateLinkedValue()`, and saving it.

**Steps to reproduce the issue:**
Run the following code (copy [input.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/6815998/input.xlsx) to the same dir):
```
package main

import (
	"log"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {
	f, err := excelize.OpenFile("./input.xlsx")
	if err != nil {
		log.Fatalf("open Excel file: %v", err)
	}

	if err := f.UpdateLinkedValue(); err != nil {
		log.Fatalf("update Excel linked values: %v", err)
	}

	if err = f.SaveAs("./output.xlsx"); err != nil {
		log.Fatalf("save Excel file: %v", err)
	}
}
```

**Describe the results you received:**
After opening the result file `output.xlsx` I see the message `WORKBOOK REPAIRED We temporarily repaired this workbook so that you can open it in Reading View.`.
 
![image](https://user-images.githubusercontent.com/53427228/125623201-a24fc18d-5e48-4c43-9226-373884920ab6.png)

**Describe the results you expected:**
The result file is successfully opened without any warnings or errors.

**Output of `go version`:**

```text
go version go1.16.3 linux/amd64
```

**Excelize version or commit ID:**

```text
2.4.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
`go env` output:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alex/.cache/go-build"
GOENV="/home/alex/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/alex/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alex/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1758173493=/tmp/go-build -gno-record-gcc-switches"
```

Microsoft Excel version: Office 365 online on https://www.office.com

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
