### ISSUE TITLE
github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0 undefined: strconv.ParseComplex

### ISSUE THREAD

**Issue by YJiWei** [360EntSecGroup-Skylar/excelize#884]
**My code is as follows**
package main

import (
	"fmt"
	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func createNewExcel() {
	f := excelize.NewFile()
	index := f.NewSheet("Sheet2")
	f.SetCellValue("Sheet2", "A2", "Hello world.")
	f.SetCellValue("Sheet1", "B2", 100)
	f.SetActiveSheet(index)
	err := f.SaveAs("Book1.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}

func main() {
	createNewExcel()
}

**After running, the output is as follows**

# github.com/360EntSecGroup-Skylar/excelize/v2
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1740:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1756:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1772:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1788:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1804:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1820:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1836:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1852:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1872:18: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1892:19: undefined: strconv.ParseComplex
C:\Users\Administrator\go\pkg\mod\github.com\360!ent!sec!group-!skylar\excelize\v2@v2.4.0\calc.go:1892:19: too many errors

**Comment by xuri** [comment]
This issue duplicate with #815, #816, #820 and #836, since [v2.4.0](https://github.com/xuri/excelize/releases/tag/v2.4.0) (commit [`f8f699`](https://github.com/xuri/excelize/commit/f8f699a172bd0219a8736b19091dd3eaa9eb3b25)), for complex number support required, the requirements Go language version is 1.15 or later.
