### ISSUE TITLE
wong in read in sheets

### ISSUE THREAD

**Issue by snailQH** [360EntSecGroup-Skylar/excelize#89]
Hello,I am using your lib in read in some xlsx files. But I fount that "excelize" cannot read in the content for every xlsx files.
I attached an example file which I tried out by "tealeg/xlsx".
Can you help me finding out the problem(s)? There are 3 sheets in the example xlsx file,But only two can be read out by  "excelize". 
[errorin360EntSecGroup-Skylar.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1182209/errorin360EntSecGroup-Skylar.xlsx)

**Comment by xuri** [comment]
I have tested with your attached file with following code and it works well:

```
package main

import (
	"fmt"
	"os"
	"strconv"

	"github.com/xuri/excelize"
)

func main() {
	xlsx, err := excelize.OpenFile("./errorin360EntSecGroup-Skylar.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	// Get sheet index.
	index := xlsx.GetSheetIndex("cannot")
	// Get all the rows in a sheet.
	rows := xlsx.GetRows("sheet" + strconv.Itoa(index))
	for _, row := range rows {
		for _, colCell := range row {
			fmt.Print(colCell, "\t")
		}
		fmt.Println()
	}
}
```

**Comment by snailQH** [comment]
Thanks. It works by your code.
I wrote the following code. And it didn't work in some unsure case. Did I use it in a wrong way?
<pre><code>
	sheets := xlsx.GetSheetMap()
	for i := range sheets {
		fmt.Println(i, sheets[i])
		rows := xlsx.GetRows(sheets[i])
		for _, row := range rows {
			for _, colCell := range row {
				fmt.Print(colCell, "\t")
			}
			fmt.Println()
		}
	}
</code></pre>

**Comment by xuri** [comment]
Use `rows := xlsx.GetRows(fmt.Sprintf("Sheet%d", i))` instead of `rows := xlsx.GetRows(sheets[i])`, relate issue #25, #43, #47 and #51.

**Comment by snailQH** [comment]
Thanks @xuri  . It works well.
