### ISSUE TITLE
Failed to set cell background color in linux

### ISSUE THREAD

**Issue by sytan** [360EntSecGroup-Skylar/excelize#93]
Failed to set cell background color with LibreOffice Calc in linux .
after look at the styles.xml of xlsx file ,it's found that "xfId" was missing in cellXfs .
So the issued was solved by just set XfID in  func setCellXf of file styles.go :
        i := 0
	xf.XfID = &i                                                         //set a value to XfID instead of default nil
	style.CellXfs.Xf = append(style.CellXfs.Xf, xf)   //line  2126

And it in func setFills of file styles.go,  pattern.FgColor.RG was not set .  is it good?

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. The element `pattern.FgColor.RGB` will be set when create style with pattern fill.
