### ISSUE TITLE
Performance Figures in wiki are lying about memory usage

### ISSUE THREAD

**Issue by pztrn** [360EntSecGroup-Skylar/excelize#95]
Just tried example from README to get rows and print them out. On 6M file with 50k rows and 23 columns memory usage was 708036 kilobytes. For 1M file with 10.8k rows and 23 columns it eat 153835 kilobytes of memory. The code was:

```
    xlsx, err := excelize.OpenFile(filename)
    if err != nil {
        panic(err)
    }

    rows := xlsx.GetRows("sheet1")
    log.Println("Found", len(rows), "rows")
    for _, row := range rows {
        log.Println(row)
    }
```

I doubt that you can get 27 kilobytes (even megabytes) of memory usage for 12800x50 file.

Checked on macOS 10.12.6 with golang 1.8.3 and latest git revision.

**Comment by xuri** [comment]
Thanks for you issue. The memory usage figures in the wiki are result that test by set cell value case. I will update it and indicate the test method.

**Comment by xuri** [comment]
Memory usage figures in the [wiki](https://github.com/360EntSecGroup-Skylar/excelize/wiki) has been updated.

**Comment by pztrn** [comment]
Great, thanks!
