### ISSUE TITLE
Write whole line at once

### ISSUE THREAD

**Issue by pztrn** [360EntSecGroup-Skylar/excelize#96]
I have a bunch of ``[][]string``, how do I pass ``[]string`` while looping to write it?

Feature request: something like ``AppendLine(line []string)`` or ``WriteLine(idx int, line []string`` for ease of writing. Right now I have to iterate thru letters to write it with ``SetCellValue()`` which increases complexity.

**Comment by pztrn** [comment]
To be clear, what have I done now: https://lab.pztrn.name/pztrn/excelator/src/master/excelator.go#L76

What I want to do:

```
line := []string{"First", "Second", "Third"}
xlsx.AppendLine(line)
```

Without dealing with columns names.

**Comment by cemremengu** [comment]
This is also available [here](https://godoc.org/github.com/tealeg/xlsx#Row.WriteSlice)

In addition to the functionality here, I think an `offset` parameter would be great in case you want to start writing from a specific cell of the column.

I can submit a PR, once we agree on the function (API) signature.

**Comment by xuri** [comment]
@pztrn @cemremengu Thank you for your issue. I have added function [`SetSheetRow()`](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.SetSheetRow) to support write the whole line at once.
