### ISSUE TITLE
Help read line by line xlsx

### ISSUE THREAD

**Issue by Juniornewxt** [360EntSecGroup-Skylar/excelize#963]
Hello friend, I need some help, an example of how to do it.
I have an xlsx file, but I don't know how many lines it has, only that I will have records from A to F.
I need to read this file and get the value of each cell and add it to a command line.
I have to do this for each line in xlsx.
Do you have any examples of this?

Tks.

**Comment by xuri** [comment]
Please reference the [go.dev](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc) or [docs](https://xuri.me/excelize/), you can fetch the rows of the worksheet by [`GetRows`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.GetRows), and read the cell value of each row.
