### ISSUE TITLE
这个库的write不支持循环分片的方式写入到前端

### ISSUE THREAD

**Issue by liangweijiang** [360EntSecGroup-Skylar/excelize#964]
前端需要把数据库的数据以excel表的形式下载下来,但是数据库数据的量级非常的大,需要通过limit不断的分片去查询,这里耗时会有点久,但是不可能让用户长时间的等待,这个库的write方法只能是等文件完全写完了才能写入到前端,不能通过循环分片的方式不断的写入,希望您们这边能给出我解决的思路或者方法,谢谢了

**Comment by xuri** [comment]
A zip format-based spreadsheet file doesn't support writing streamingly, so you must wait for the file has been saved after all data has been written, this limit is not in the scope of this lib. Please consider splitting to multi-file or asynchrony to download the spreadsheet.

**Comment by duke-git** [comment]
使用write方法写入gin返回给前端，非常慢，截图是70M，用了41s. 请问有什么优化方法吗？
_ = fileResp.File.Write(c.Writer) // c -> *gin.Context
<img width="564" alt="image" src="https://user-images.githubusercontent.com/5037603/156536560-02dc22a9-eb8a-49e0-8a79-6b1214087846.png">
