### ISSUE TITLE
如何将自己创建的表放置在第一位啊？或者说直接修改sheet1的名称，因为我创建的表总是在sheet1后面

### ISSUE THREAD

**Issue by boteman0206** [360EntSecGroup-Skylar/excelize#965]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Please reference the [go.dev](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc) or [docs](https://xuri.me/excelize/), you can rename the default worksheet by [`SetSheetName`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2#File.SetSheetName).

**Comment by boteman0206** [comment]
ok，thinks
