### ISSUE TITLE
SetCellRichText cannot set Chinese

### ISSUE THREAD

**Issue by yushanapp** [360EntSecGroup-Skylar/excelize#966]
```
err := f.SetCellRichText(sheetName,cellName, []excelize.RichTextRun{
			{
				Text: "我",
				Font: &excelize.Font{
					Bold:   true,
					Color:  "2354e8",
					Family: "Calibri",
				},
			}})
		if err != nil {
			log.Print(err)
		}
```

**Describe the results you received:**
If the text is English characters, the display is correct, but when the text is Chinese, it cannot be displayed

**Describe the results you expected:**
When the text is Chinese, it can be displayed normally

**Output of `go version`:**
```text
go version go1.16.1 windows/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.4.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10

**Comment by xuri** [comment]
Thanks for your feedback, I have tested and it works well, could you provide more details, such as the Microsoft Excel&trade; version and complete reproduce code?

**Comment by yushanapp** [comment]
`func readExcel(file string) {
	f, err := excelize.OpenFile(file)
	if err != nil {
		fmt.Println(err)
	}

	sheetName := f.GetSheetName(0)
	rows,_ := f.Rows(sheetName)
	rows.Next()
	titles,_:= rows.Columns()

	var keyIndex int
	var searchIndex int
	for i,title := range titles{
		if title == "关键词"{
			keyIndex = i
		}else if title == "搜索词"{
			searchIndex = i
		}
	}

	percentColumnIndex := len(titles) + 1
	newSearchColumnIndex := percentColumnIndex + 1

	currentRow := 1

	newSearchCellTitle,_:= excelize.CoordinatesToCellName(newSearchColumnIndex, currentRow)
	f.SetCellStr(sheetName,newSearchCellTitle,"关键词富文本")
	percentCellTitle,_ := excelize.CoordinatesToCellName(percentColumnIndex, currentRow)
	f.SetCellStr(sheetName,percentCellTitle,"匹配率")

	currentRow++
	for rows.Next() {
		row, err := rows.Columns()
		if err != nil {
			fmt.Println(err)
		}
		if len(row) <= keyIndex || len(row) <= searchIndex{
			break
		}
		keyWord := row[keyIndex]
		searchWord := row[searchIndex]
		log.Print(keyWord)

		var matchIndexs []int

		for i,sword := range searchWord{
			for _,word := range keyWord{
				if sword == word {
					matchIndexs = append(matchIndexs, i)
					break
				}
			}
		}

		searchWords := strings.Split(searchWord,"")

		var richTexts []excelize.RichTextRun

		for i,word := range searchWords {
			isMatch  := false
			for _,index := range matchIndexs{
				if i == index{
					isMatch = true
					break
				}
			}
			if isMatch{
				richTexts = append(richTexts,excelize.RichTextRun{
					Text: word,
					Font: &excelize.Font{
						Bold:   false,
						Color:  "e83723",
						Italic: true,
					},
				})
			}else{
				richTexts = append(richTexts,excelize.RichTextRun{
					Text: word,
					Font: &excelize.Font{
						Bold:   true,
						Color:  "2354e8",
					},
				})
			}
		}

		newSearchCell,_:= excelize.CoordinatesToCellName(newSearchColumnIndex, currentRow)
		err = f.SetCellRichText(sheetName,newSearchCell, []excelize.RichTextRun{
			{
				Text: "错",
				Font: &excelize.Font{
					Bold:   true,
					Color:  "2354e8",
				},
			}})
		if err != nil {
			log.Print(err)
		}
		matchPercent := float64(len(matchIndexs))/ float64(utf8.RuneCountInString(searchWord))
		percentCell,_ := excelize.CoordinatesToCellName(percentColumnIndex, currentRow)
		f.SetCellFloat(sheetName,percentCell,matchPercent,2,64)
		currentRow++
	}

	f.Save()

}`

**Comment by yushanapp** [comment]
[test.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/6853487/test.xlsx)

**Comment by yushanapp** [comment]
The above is all my code and the xlsx file used for testing

**Comment by xuri** [comment]
I have tested your code and attachment and it works well, which version Microsoft Excel&trade; are you using? Kind notice: please create an issue with the issue template as possible, and using the simple minimum code to reproduce the issue. as possible.

**Comment by yushanapp** [comment]
I use wps to open xlsx files, are wps and excel incompatible in terms of rich text?

**Comment by yushanapp** [comment]
I re-tested, and now it works normally even when using wps to open it, I haven’t modified anything, and I don’t understand what the problem was before.

**Comment by xuri** [comment]
Okay, I'll close this issue, if you have any questions, please let me know.
