### ISSUE TITLE
color data in style struct without theme

### ISSUE THREAD

**Issue by wangzheng1234** [360EntSecGroup-Skylar/excelize#967]
where copy sheet with cell style use new style,  Fill struct just have color string , without theme define in  xlsxColor struct ， seem miss some data ?

how can i set cell style with system theme data?

**Comment by xuri** [comment]
Thanks for your issue, could you create the issue by an issue template and provide more details?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
