### ISSUE TITLE
A document must contain exactly one root element. Line 2, column 0.

### ISSUE THREAD

**Issue by afalkov** [360EntSecGroup-Skylar/excelize#97]
Windows: basic usage example generates xlsx file that opens by Excel with error: _Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  A document must contain exactly one root element. Line 2, column 0._

xlsx := excelize.NewFile()
xlsx.SetCellValue("Sheet1", "B2", 100)
err := xlsx.SaveAs("./Workbook.xlsx")

**Comment by xuri** [comment]
Check the Go version you are using. This library needs Go version 1.8 or later after fixed issue #32 for collecting XML all attributes. Relate issue #35, #39, #42 and  #84.

**Comment by afalkov** [comment]
Thank you!
