### ISSUE TITLE
is it possible to check if cell has hyperlink?

### ISSUE THREAD

**Issue by plandem** [360EntSecGroup-Skylar/excelize#98]
Can't get a way to check if cell has any hyperlink

**Comment by xuri** [comment]
Thanks for your issue. I have added a function `GetCellHyperLink()`.

**Comment by plandem** [comment]
thanks! will check later and write feedback

**Comment by plandem** [comment]
Hmm, I'm getting nil :( Document has hyperlinks that must be "fixed" - i.e. to external non-existing file, I can see them at Excel, but I can't get it via library :( Any ideas?

P.S.: I need to check my file and write at log, that there some external links.

**Comment by xuri** [comment]
The function `GetCellHyperLink()` just support get two types of hyperlink `External` for web site or `Location`.

**Comment by plandem** [comment]
ok, "external" can point to file also, I mean at Excel I see next link:
```
='/Debian/public/xxxx/yyy/xxxx/[FILE_NAME.xls]SHEET_NAME'!H25
```

**Comment by xuri** [comment]
Please provide file attachments If you can.
